### PR TITLE
move download mirror from  Kerbalstuff

### PR DESCRIPTION
**Pull request by Sigma88**
@plague006  this should be more or less the same as #2287

### CODE REVIEW

**Comment by techman83** [comment]
Testing failed due being reliant on #2287 being merged. Normally recommend individual PRs for changes, exception being when they depend on each other.

**Comment by Sigma88** [comment]
so the problem was I put the link there? whoops :)

thanks @techman83

**Comment by techman83** [comment]
@Sigma88 more that it's using the meta data in the repo that is no longer correct for the dependency and failing it. Where as the build script injects all the metadata contained inside the PR for when the mods depend on each other :)

I don't know that you can rebase a PR made with the GitHub interface, I primarily use git on the cli.

**Comment by Sigma88** [comment]
I'm going to start over, I'm still getting a hang of this.

sorry for the problems

**Comment by techman83** [comment]
No issue at all @Sigma88 - appreciate the effort :-)

**Pull request closed without merging**
