### PR TITLE
RN fix for new ksp version

### PR DESCRIPTION
**Pull request by raidernick**
-Update files for new ksp version

### CODE REVIEW

**Comment by raidernick** [comment]
it seems to be stalled because of firespitter, which seems to work in 1.1.3 just fine, it can probably be marked as compatible.

**Comment by politas** [comment]
@BobPalmer is maintaining the metadata for FirespitterCore. He would need to update that.

Bob?

**Comment by raidernick** [comment]
@politas since I don't see any issues with FS can I simply update the metadata for 1.1.3 so I can finish this pr?

**Comment by politas** [comment]
Sorry, I've been somewhat busy. If these are new releases targeted only at 1.1.3, then this should be fine to merge. As long as there will still be working releases for anyone using 1.1.2. If you're saying the existing 1.1.2 releases are also fine for 1.1.3, then it would be better to switch to Min /Max KSP versions. (As I believe one of these already is)  Sorry, commenting on my phone, so I have limited abilities.

**Comment by raidernick** [comment]
there now they are min/max versions. Yes they still work with 1.1.3 I made no changes so even with FS metadata not fixed I want this merged.

**Comment by politas** [comment]
Of no one else gets to it, I'll merge it this evening

**Comment by BobPalmer** [comment]
FYI - new Firespitter is up

**Pull request merged**
