### PR TITLE
Move Endurance Space Exploration System to Spacedock

### PR DESCRIPTION
**Pull request by politas**
Builds on and closes #3411, with many thanks to @ILM126

### CODE REVIEW

**Comment by politas** [comment]
Depends on KSP-CKAN/CKAN-meta#1014

**Comment by politas** [comment]
I can't see a MiniAVC at all in the download I have for this

**Comment by Dazpoet** [comment]
Hm I see this

```
- GameData/Endurance/Flags/NASA (Interstellar).png
- GameData/Endurance/LICENSE-SOURCE.txt
- GameData/Endurance/MiniAVC Licence.txt
- GameData/Endurance/MiniAVC.dll
- GameData/Endurance/MiniAVC.xml
- GameData/Endurance/Parts
- GameData/Endurance/Parts/CLSConfigs.cfg
- GameData/Endurance/Parts/COLONY
```

in the Jenkins output and grabbing the .zip from spacedock there's also miniavc things in it. From what I gather from the other PR #3387 the .xml file should be filtered?

**Comment by politas** [comment]
Ah, it's been added in v0.92. Ok.

**Pull request merged**
