### PR TITLE
Add Kerbin-Side Complete from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of AlphaAsh, to add [Kerbin-Side Complete](https://spacedock.info/mod/150/Kerbin-Side%20Complete) to CKAN.

Please direct questions about this pull request to [AlphaAsh](https://spacedock.info/profile/AlphaAsh).

### CODE REVIEW

**Comment by plague006** [comment]
ref https://github.com/KSP-CKAN/NetKAN/issues/2179

**Comment by politas** [comment]
Ref #3155

**Comment by politas** [comment]
I think that rather than leaving an out of date KerbinSide as the only available version, we should just make all the KerbinSide* mods conflict with all other KerbinSide mods, and we can remove the conflicts when we have the overwriting stuff worked out (if ever!)

**Comment by Dazpoet** [comment]
I agree to that solution and will merge this since it seems like the least bad solution for now. Seeing as KerbinSide isn't as widespread I hope this won't lead to a `PlanetPack` level clusterfuck down the line.

**Pull request merged**
