### PR TITLE
Update StockVisualEnhancements.netkan

### PR DESCRIPTION
**Pull request by politas**
Add epoch, mod author has changed version system

### CODE REVIEW

**Comment by Olympic1** [comment]
Merge after a new update comes out.

**Comment by Dazpoet** [comment]
Just adding to this that a new update has yet to appear at the time of writing this.

**Comment by politas** [comment]
Yeah, it's still waiting on an EVE release. This mod is also now up on Spacedock, where again, it includes a pre-release EVE install.

**Comment by politas** [comment]
Putting up a Spacedock version, instead

**Pull request closed without merging**
