### PR TITLE
Add recommended addons; installation location

### PR DESCRIPTION
**Pull request by DMagic1**

### CODE REVIEW

**Comment by pjf** [comment]
Looks like we're missing a comma after the license. :)

**Comment by DMagic1** [comment]
that's what I get for copying and pasting too much...

**Comment by pjf** [comment]
Oh hell yes! I've wanted something like this forever! Merging with great enthusiasm and thanks!

**Comment by pjf** [comment]
Also, I *really* love our [testing bots](http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/710/console).

**Comment by DMagic1** [comment]
Thanks. Someday soon I'll complete my contract trifecta mod pack with a Mission Control on the go window.

Yeah, I was watching the bot, it's nice that it tells me there's probably a comma missing.

**Pull request merged**
