### PR TITLE
Add Kerbodyne Plus (fixed KerbalStuff submission)

### PR DESCRIPTION
**Pull request by politas**
replaces #2972, with suggestions from mod author in #2982

### CODE REVIEW

**Comment by politas** [comment]
closes #2982

**Comment by politas** [comment]
mono ckan.exe show KerbodynePlus
Kerbodyne Plus: End-game parts pack.

Module info:
- version:	1.0
- authors:	BonusEventus
- status:	stable
- license:	CC-BY-NC-SA-3.0

Provides:
- KerbodynePlus

Resources:
- homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/130809-105-kerbodyne-plus-v10/
- kerbalstuff: https://kerbalstuff.com/mod/1437/Kerbodyne%20Plus

Filename: B245072D-KerbodynePlus-1.0.zip

Showing 65 installed files:
- GameData/kerbodynePlus
- GameData/kerbodynePlus/license.txt
- GameData/kerbodynePlus/Parts
- GameData/kerbodynePlus/Parts/Command
- GameData/kerbodynePlus/Parts/Command/crew_module.cfg
- GameData/kerbodynePlus/Parts/Engine
- GameData/kerbodynePlus/Parts/Engine/large_booster.cfg
- GameData/kerbodynePlus/Parts/Engine/large_booster.dds
- GameData/kerbodynePlus/Parts/Engine/large_booster.mu
- GameData/kerbodynePlus/Parts/Engine/large_booster_emissive.dds
- GameData/kerbodynePlus/Parts/Fuel
- GameData/kerbodynePlus/Parts/Fuel/k303_16_375.cfg
- GameData/kerbodynePlus/Parts/Fuel/xl_tank.dds
- GameData/kerbodynePlus/Parts/Fuel/xl_tank.mu
- GameData/kerbodynePlus/Parts/Structural
- GameData/kerbodynePlus/Parts/Structural/crew_module_ext.mu
- GameData/kerbodynePlus/Parts/Structural/endcaps.dds
- GameData/kerbodynePlus/Parts/Structural/t404_375_adapter.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_375_adapter.dds
- GameData/kerbodynePlus/Parts/Structural/t404_375_adapter.mu
- GameData/kerbodynePlus/Parts/Structural/t404_a.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_a.mu
- GameData/kerbodynePlus/Parts/Structural/t404_a_2.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_a_2.mu
- GameData/kerbodynePlus/Parts/Structural/t404_a_3.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_a_3.mu
- GameData/kerbodynePlus/Parts/Structural/t404_b.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_b.mu
- GameData/kerbodynePlus/Parts/Structural/t404_b_2.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_b_2.mu
- GameData/kerbodynePlus/Parts/Structural/t404_b_3.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_b_3.mu
- GameData/kerbodynePlus/Parts/Structural/t404_crew_module_ext.dds
- GameData/kerbodynePlus/Parts/Structural/t404_crew_module_ext_em.dds
- GameData/kerbodynePlus/Parts/Structural/t404_panel.cfg
- GameData/kerbodynePlus/Parts/Structural/t404_panel.mu
- GameData/kerbodynePlus/Parts/Structural/t404_wall_strut.dds
- GameData/kerbodynePlus/Parts/Structural/t404_wall_strut_emissive.dds
- GameData/kerbodynePlus/Parts/Utility
- GameData/kerbodynePlus/Parts/Utility/extremeDockingPort.cfg
- GameData/kerbodynePlus/Parts/Utility/extremeDockingPort2_diff.dds
- GameData/kerbodynePlus/Parts/Utility/extremeDockingPort_1m.mu
- GameData/kerbodynePlus/Parts/Utility/extremeDockingPort_2m.cfg
- GameData/kerbodynePlus/Parts/Utility/extremeDockingPort_3m.cfg
- GameData/kerbodynePlus/Parts/Utility/solarWing.cfg
- GameData/kerbodynePlus/Parts/Utility/solarWing.mu
- GameData/kerbodynePlus/Parts/Utility/solarWings.dds
- GameData/kerbodynePlus/Parts/Utility/sPanels.dds
- GameData/kerbodynePlus/Parts/Utility/truss.dds
- GameData/kerbodynePlus/Parts/Utility/xl_landing_leg.cfg
- GameData/kerbodynePlus/Parts/Utility/xl_landing_leg.dds
- GameData/kerbodynePlus/Parts/Utility/xl_landing_leg.mu
- GameData/kerbodynePlus/Parts/Utility/xl_landing_leg_emissive.dds
- GameData/kerbodynePlus/releaseNotes.txt
- GameData/kerbodynePlus/Sounds
- GameData/kerbodynePlus/Sounds/sound_large_blast.wav
- GameData/kerbodynePlus/Sounds/sound_large_booster.wav
- GameData/kerbodynePlus/Spaces
- GameData/kerbodynePlus/Spaces/crew_module_int
- GameData/kerbodynePlus/Spaces/crew_module_int/crew_module_int.mu
- GameData/kerbodynePlus/Spaces/crew_module_int/crew_module_int_diffuse.dds
- GameData/kerbodynePlus/Spaces/crew_module_int/crew_module_int_emissive.dds
- GameData/kerbodynePlus/Spaces/crew_module_int/glass.dds
- GameData/kerbodynePlus/Spaces/crew_module_int/internal.cfg
- GameData/kerbodynePlus/README.md

**Comment by plague006** [comment]
Only "close" messages in the original comment actually close linked PRs. (You can edit them in later if you forget initially).

**Comment by politas** [comment]
Thanks for the advice!

**Pull request merged**
