### PR TITLE
Fix install on MethaneRockets

### PR DESCRIPTION
**Pull request by politas**
Discovered this was failing on http://status.ksp-ckan.org/

### CODE REVIEW

**Comment by DinCahill** [comment]
I couldn't install this, because RealPlume needs another package for its config:

```
CKAN.TooManyModsProvideKraken: Too many mods provide RealPlumeConfigs:
RealPlume-StockConfigs v0.10.9
* RealismOverhaul v11.3.1
```

Here's the relevant output from Jenkins:

```
2675 [1] ERROR CKAN.RegistryManager (null) - Loaded registry with inconsistencies:

The following inconsistencies were found:
RealPlume requires RealPlumeConfigs but nothing provides it
- EngineLighting 1.4.5
- MethaneRockets 0.6
- ModuleManager 2.6.25
- RealPlume 2:v10.5.1
- SmokeScreen 2.6.17.0
2640 [1] ERROR CKAN.RegistryManager (null) - Loaded registry with inconsistencies:

The following inconsistencies were found:
RealPlume requires RealPlumeConfigs but nothing provides it
```

How should we deal with this?

**Comment by politas** [comment]
Strictly, that's a problem with RealPlume, not with this mod. We'll have to look into that separately.

**Comment by DinCahill** [comment]
It works if I install RealPlume first and select the the stock config. So we're good to merge this, and then fix RealPlume? I don't know how to do that one :smile:

**Comment by politas** [comment]
RealPlume is fine, nothing needs to be done there as far as I can see.

**Pull request merged**
