### PR TITLE
Freeze stale mods

### PR DESCRIPTION
**Pull request by HebaruSan**
## Motivation

See KSP-CKAN/NetKAN-Infra#96, we currently crawl a lot of mods that are vanishingly unlikely to ever update again. Now that KSP-CKAN/NetKAN-Infra#97 is merged and has run, we have a timestamp for every mod, and we can use this to freeze the stale ones.

## Changes

Now any mod with a `last_indexed` date earlier than 2017-01-01 is renamed to .frozen. This will take these mods out of the bot's rotation, saving assorted system resources.

Command used to generate the list:

`wget -q -O - http://status.ksp-ckan.space/status/netkan.json | jq -rS '("2017-01-01T00:00:00Z"|fromdate) as $cutoff | to_entries | map(select(.value.last_indexed and (.value.last_indexed[0:19]+"Z"|fromdate)<$cutoff) | .key) | sort_by(ascii_downcase) | .[]'`

Command used to generate the PR (from the NetKAN/NetKAN folder):

`for X in $(wget -q -O - http://status.ksp-ckan.space/status/netkan.json | jq -rS '("2017-01-01T00:00:00Z"|fromdate) as $cutoff | to_entries | map(select(.value.last_indexed and (.value.last_indexed[0:19]+"Z"|fromdate)<$cutoff) | .key) | sort_by(ascii_downcase) | .[]') ; do git mv $X.netkan $X.frozen ; done`

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by techman83** [comment]
Did this leave some mods available for the new autofreezer to munch on as a test run the first time around?

**Comment by HebaruSan** [comment]
Yes, today minus one thousand days is 22 Feb 2017, so the script should freeze any that expired between 1 Jan and 22 Feb:

`$ wget -q -O - http://status.ksp-ckan.space/status/netkan.json | jq -rS '("2017-01-01T00:00:00Z"|fromdate) as $min | ("2017-02-22T00:00:00Z"|fromdate) as $max | to_entries | map(select(.value.last_indexed and (.value.last_indexed[0:19]+"Z"|fromdate)>$min and (.value.last_indexed[0:19]+"Z"|fromdate)<$max) | .key) | sort_by(ascii_downcase) | .[]' `
```
AnimatedStationScreens
AntennaRangePatches
BallastNukSub
BDynamicsMk22Cockpits
CepheusSunflare
ContractConfigurator-InterplanetaryMountaineer
DSDMobileProcessingLabs
EdenSunflare
EstesParachutePack
FlyingWingCargo
GameofKerbals
GrandPrix
GrindyScience
GTIndustries
HeatShieldfortheMk1CommandPod
HermesInterplanetarySpacecraft
HexTruss
HospitalShip
K2CommandPod
KerbalOlympics
KerbalStockLauncherOverhaul
KirovAirShip
LandingHeight
LessGrindyScience
LowExpectations
MilitarySuitTextures
Mk3MiniExpansionPack
MTPTank
PartCommander
PhoenixIndustriesAgencies
PhoenixIndustriesBoosters
PhoenixIndustriesFlags
PoliticalMap4kTexture
PoliticalMap8kTexture
PoliticalMapMilitaryTexture
ProceduralProbes
Radialstackdecoupler
StockFairingTweaker
Taerobee
TrackingStationAmbientlight
VesselSwitcher
WernherChecker
Zenit3SLBReduzx
```

**Comment by techman83** [comment]
Alright, that's great! I don't see a reason not to merge this in.

**Comment by HebaruSan** [comment]
Hmm, this should have prevented this module from being frozen:

https://github.com/KSP-CKAN/CKAN-meta/commits/master/EnduranceSpaceExplorationSystem/EnduranceSpaceExplorationSystem-V1.10.ckan

Maybe `last_indexed` was missing or wrong due to problems in the early stages of the implementation of the new Infra.

**Pull request merged**
