### PR TITLE
Update BWA-X-ROMBUS.netkan

### PR DESCRIPTION
**Pull request by Lupinarius**
Please merge tho changes if they will have the desired effect. This should Add the source code repository information, and widen the range of KSP releases that can use the mod, since it has now been tested on older versions.

### CODE REVIEW

**Comment by politas** [comment]
Repository only needs to be `https://github.com/Lupinarius/BWA-X/`

**Comment by Lupinarius** [comment]
Correction made so ready to merge AFAIK then.

**Comment by politas** [comment]
Ditch the comma on the end of the repository line. The last element of any structure cannot have a comma trailing it before the closing } or ].

**Comment by Lupinarius** [comment]
Thanks, I'll check for those errors more in the future.

**Comment by Lupinarius** [comment]
comma smashed.

**Comment by politas** [comment]
Looks good. Merging with thanks!

**Pull request merged**
