### PR TITLE
Create Waterfall.netkan

### PR DESCRIPTION
**Pull request by DuoDex**
Adds CKAN support for Waterfall. First time writing a netkan from scratch, so we'll see how this goes.

### CODE REVIEW

**Comment by DuoDex** [comment]
Forgot a space, oopsie.

**Comment by HebaruSan** [comment]
Hi @DuoDex, thanks for the contribution, but most of Nertea's mods use metanetkans hosted on his own repositories, so I imagine he'll want to do that for this one as well. E.g.: 
- https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/CommunityTechTree.netkan

We'll also want to make sure he's OK with having this added. It's a new mod and he may or may not consider it ready at this point.

**Comment by HebaruSan** [comment]
FYI @DuoDex, the metanetkan request just came through in #8274. Enjoy!

**Comment by DuoDex** [comment]
Thanks!

**Pull request closed without merging**
