### PR TITLE
Add SuperSwifty2004's Water Powered Engines Mod from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of SuperSwifty2004, to add [SuperSwifty2004's Water Powered Engines Mod](https://kerbalstuff.com/mod/489/SuperSwifty2004%27s%20Water%20Powered%20Engines%20Mod) to CKAN.

Please direct questions about this pull request to [SuperSwifty2004](https://kerbalstuff.com/profile/SuperSwifty2004).

### CODE REVIEW

**Comment by hakan42** [comment]
Mod is mispacked, contacting original author about it.

**Comment by AlexanderDzhoganov** [comment]
How is it mispacked, I got the zip but didn't see any issues?

**Comment by TwistedMexi** [comment]
Mod is expected in such a format that when you open the zip, you see this structure:
Modname > [Plugin Subfolders and files]

This oackage has too many directory levels and lacks a Modname folder. The top directory should not be included, and the "GameData" directory should be renamed to the mod name .

**Comment by Ippo343** [comment]
This mod is still improperly packaged. Closing untile the author corrects the packaging.

**Pull request closed without merging**
