### PR TITLE
Add Kerbal Mission Patch Template from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of SayburStuff, to add [Kerbal Mission Patch Template](https://kerbalstuff.com/mod/820/Kerbal%20Mission%20Patch%20Template) to CKAN.

Please direct questions about this pull request to [SayburStuff](https://kerbalstuff.com/profile/SayburStuff).

### CODE REVIEW

**Comment by Dazpoet** [comment]
Added red label since I honestly don't even understand how this mod is supposed to be installed. It seems the GameData folder included is a single flag and outside of it there are some .svg files.

**Comment by Dazpoet** [comment]
So it would appear this is a tool rather than a mod, considering http://forum.kerbalspaceprogram.com/threads/122052-Kerbal-Mission-Patch-Template-v1-0

My knee-jerk response is to close this since it feels outside the scope of CKAN, but then again we do index [PartMapper](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PartMapper.netkan) which is also a tool.

**Comment by sumghai** [comment]
This isn't even a tool - just a bunch of image templates or "shareables" in the manner of flags.

Since this isn't supposed to be installed in the game at all, there's no point indexing it on CKAN in the first place. I recommend closing this pull request.

**Comment by Dazpoet** [comment]
Good enough for me, closing this.

**Pull request closed without merging**
