### PR TITLE
Kerbalism: remove conflict with DynamicBatteryStorage

### PR DESCRIPTION
**Pull request by SirMortimer**
does what it says on the tin.

### CODE REVIEW

**Comment by DasSkelett** [comment]
This is for 3.2 and up, right?

**Comment by SirMortimer** [comment]
yes, and yes. can't announce on forums because it's down, but GitHub has the latest.

forgot to update space dock, will do that now....

**Comment by DasSkelett** [comment]
Okay. Is this working together with the 3.1 config?

Because our bot is currently down, and if I merge this, Kerbalism 3.2 will be indexed by the merge webhook, but the newest config will be missing, and the CKAN client will choose the 3.1 config to satisfy the dependencies.
If they aren't compatible, I would wait until the bot is back up again and the config is indexed.

**Comment by SirMortimer** [comment]
The configs are compatible, but I'd rather have people use the 3.2 version when they update. There are new parts that are part of the configs, as well as some issues fixed in there.

**Comment by DasSkelett** [comment]
The bot is working again and the config is indexed :tada:
I'm using this now to test whether the webhooks are online again too :P

**Comment by DasSkelett** [comment]
Worked like a charm: https://github.com/KSP-CKAN/CKAN-meta/commit/fb892dcc98265500801a632efef11b5b73063511. Thanks for the update @SirMortimer!

**Pull request merged**
