### PR TITLE
Create thebubble.netkan

### PR DESCRIPTION
**Pull request by JustinKerbice**

### CODE REVIEW

**Comment by Dazpoet** [comment]
Seems to be in the wrong place. This file is in the root directory rather than the NetKAN folder, the latter one being where it should be.

**Comment by JustinKerbice** [comment]
Oups, my bad, I guess. Doesn't seems I can move file myself.

**Comment by Dazpoet** [comment]
Just move it in your local branch and push the change, that should resolve the situation :)

**Comment by JustinKerbice** [comment]
done

**Comment by Dazpoet** [comment]
Have you added / commited the change? There is nothing new in this PR right now. If you have done the change in your local branch you'll have to sync and commit the file in GUI or do 
```
git add -A
git commit -am "<comment>"
```
in commandline.

Then you push your branch and this PR will be updated.

While changing things would you mind it very much to change the filename to kribubble.netkan so it's easier for maintainers to find the file based on the identifier? This will not have any effect at all on the name of the mod shown in CKAN nor any other place than the NetKAN repo.

**Comment by JustinKerbice** [comment]
... the web UI sucks, there is no way to do such thing, quite ridiculous.

**Comment by Dazpoet** [comment]
I'll merge this and fix it post-merge

**Comment by JustinKerbice** [comment]
Thanks Dazpoet.

**Pull request merged**
