### PR TITLE
Create HooliganLabsAirships.netkan

### PR DESCRIPTION
**Pull request by politas**
Ref Issue #1275

### CODE REVIEW

**Comment by mgsdk** [comment]
I think you need commas at the end of line 8 and 15, and the semicolon at the end of line 7 should be unnecessary.

**Comment by politas** [comment]
Thanks!

**Comment by mgsdk** [comment]
One small detail remains. We try to avoid distributing unnecessary files such as "Thumbs.db" and the source code. After install, you need to add a filter for these:
```
"file" : "HooliganLabs",
"install_to" : "GameData",
"filter" : [ "Thumbs.db", "Source" ]
```
This also requires that the spec gets increased, so
```
"spec_version" : "v1.4",
```

**Comment by mgsdk** [comment]
Looks good now, thank you for your patience with the process and helping us keep the DB up to date.

**Pull request merged**
