### PR TITLE
Updated layout to accomodate manual installs

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Added github to all

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
!pull

**Comment by linuxgurugamer** [comment]
Help.
For some reason, even though version 0.3.7 is on kerbalstuff, this is failing because it is downloading 0.3.4 of the unmanned contracts

**Comment by linuxgurugamer** [comment]
My problem was a lowercase D in Gamedata.
It might make sense to add a check for the proper case for the gamedata, and alert the user if it is wrong

**Comment by Dazpoet** [comment]
You could cut the adresses for KS and KSP forums down to not include the flavourtext after the modnumber and threadnumber. They'll still work and won't look weird in the future if the name of the mod on KS or the name of the thread on forums change. Seeing as you're changing stuff around that change might make sense to do now rather than later :)

**Comment by linuxgurugamer** [comment]
Understood, I'll do that the next time I change things.

Thanks

**Comment by Dazpoet** [comment]
Seeing as you closed this, am I to understand that you don't want these changes merged?

**Comment by linuxgurugamer** [comment]
oops. Ummm, I just pulled everything and checked, I don't see the flavourtext there anymore.  Did you make those changes?

**Comment by linuxgurugamer** [comment]
For some reason, it is pulling the wrong version of spacetux:
Downloading "https://github.com/jrossignol/ContractConfigurator/releases/download/0.7.11/ContractConfigurator_0.7.11.zip" (libcurl)
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/lastSuccessfulBuild/artifact/ModuleManager-2.6.0.zip" (libcurl)
Downloading "https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.3.2" (libcurl)


When version 0.3.3 is available for the Spacetux Shared Assets

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
I haven't done anything to this PR other than commenting on it. What flavourtext are you refering to?

**Comment by linuxgurugamer** [comment]
Umm, I think we are crossing messages.  I was referring to your earlier message, and then got confused (I think) by your comment.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by Dazpoet** [comment]
Either way, the reason it's downloading 0.3.2 is because it seems 0.3.3 hasn't been pushed to CKAN-meta by the bot yet. Someone will probably give it a swift kick again in the future and it'll fix itself.

**Comment by linuxgurugamer** [comment]
Ok, so I'll wait until this evening.
Thanks

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
For some reason, it is pulling the wrong version of spacetux:
Downloading "https://github.com/jrossignol/ContractConfigurator/releases/download/0.7.11/ContractConfigurator_0.7.11.zip" (libcurl)
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/lastSuccessfulBuild/artifact/ModuleManager-2.6.0.zip" (libcurl)
Downloading "https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.3.2" (libcurl)

When version 0.3.3 is available for the Spacetux Shared Assets

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by Dazpoet** [comment]
Will ModuleManager be added back or was it removed due to not Being required anymore?

**Comment by linuxgurugamer** [comment]
It wasn't required, i assume you are referring to the grandtour?

**Comment by Dazpoet** [comment]
I was indeed, everything looks fine so I merge this now :)

**Comment by linuxgurugamer** [comment]
Thank you

**Pull request merged**
