### PR TITLE
Update SETI.netkan

### PR DESCRIPTION
**Pull request by Y3mo**
Fixed the old SETI-BalanceMod for KSP 0.90 to the version 0.9.0, since it will not be developed anymore.

The kerbalstuff download will be taken over by a similar mod with different structure, therefore I made a pull request for a new netkan identifier/file named "SETI-BalanceMod".

Thank you very much!
Yemo

### CODE REVIEW

**Comment by Y3mo** [comment]
Lesson learned, should be ok now.

**Comment by Olympic1** [comment]
Not really required for a merge, but add the following line so that people can see who the author is:
`"author" : "Yemo",`

**Comment by Y3mo** [comment]
Added author line, thank you!

Just starting to appreciate the kerbalstuff referencing, so easy, so much stuff not to worry about as soon as the license is accepted. ;-)

**Comment by Olympic1** [comment]
Merging with my thanks

**Pull request merged**
