### PR TITLE
Moved install to Github, added version file

### PR DESCRIPTION
**Pull request by Gameslinx**
Added sigmareplacements: Skybox. Moved download to github in accordance to a version file.

### CODE REVIEW

**Comment by Gameslinx** [comment]
Darn. Thought my JSON was formatted properly...

**Comment by HebaruSan** [comment]
The formatting is OK, but that's an invalid value for `spec_version`:
https://ci.ksp-ckan.org/job/NetKAN/6922/console

**Comment by HebaruSan** [comment]
(Clicked wrong button by accident.)

**Comment by HebaruSan** [comment]
@Gameslinx , don't change spec_version. It isn't supposed to reflect your mod's version.

https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#spec_version

**Comment by Gameslinx** [comment]
Right, got it. Cheers. I'm not able to understand what the error logs are saying above, unfortunately, otherwise i'd have another go at submitting a pull req

**Pull request merged**
