### PR TITLE
Add Unmanned before Manned from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Yemo, to add [Unmanned before Manned](https://kerbalstuff.com/mod/1198/Unmanned%20before%20Manned) to CKAN.

Please direct questions about this pull request to [Yemo](https://kerbalstuff.com/profile/Yemo).

### CODE REVIEW

**Comment by Y3mo** [comment]
Requesting change of file name and identifier to UnmannedBeforeManned (captial B) for easier readability.
This should be the right content of the netkan file (copy paste and adjust from my other SETI mods).

{
    "$kref": "#/ckan/kerbalstuff/1198",
    "spec_version": "v1.4",
    "identifier": "UnmannedBeforeManned",
    "license": "restricted",
	"depends"	: [ { "name" : "ModuleManager" } ],
	"install" : [ { "file" : "UnmannedBeforeManned",
				"install_to" : "GameData" } ]
}

**Comment by plague006** [comment]
File name/identifier aren't seen by end user, so readability isn't really an issue. End users do see `title` though, which is taken directly from the KerbalStuff page. If you want, we can hardcode the `title` to have the capitalization you want, or you can change the title on KerbalStuff: your choice.

**Comment by Y3mo** [comment]
No problem, the kerbalstuff title is fine for end users.
It was just about back end consistency (install folder=MM identifier=netKAN identifier).

Thank you for all your hard work on ckan!

**Comment by plague006** [comment]
Closed by https://github.com/KSP-CKAN/NetKAN/pull/2454

**Pull request closed without merging**
