### PR TITLE
Fix much metadata

### PR DESCRIPTION
**Pull request by pjf**
I've no idea why travis is being so grumpy, but running `prove` in the
NetKAN repo revealed a number of metadata errors. This commit doesn't
fix all of them, but it fixes the easy-to-fix ones. In particular:

* A number of documents have been given a spec `v1.2` or `v1.4` header, as they use newer features.
* A number of files have been renamed to match their identifier.

This doesn't fix hard errors, like missing licenses (which might be okay
if the remote data is fine), or identifiers which don't match the CKAN
spec (which maybe we should just update to allow).

### CODE REVIEW

**Comment by Ippo343** [comment]
#rebuild

**Comment by Dazpoet** [comment]
#rebuild

**Comment by pjf** [comment]
#rebuild

Srsly, `build.sh`, you should not be trying to `jsonlint` yourself.

**Comment by pjf** [comment]
#rebuild now that I've fixed `netkan.exe`

**Comment by pjf** [comment]
OMFG. KerbalStuff is down. I've shaved so many yaks, and now this!!? o_O

**Comment by pjf** [comment]
It's back. Quick, #rebuild!

**Comment by pjf** [comment]
Um.. #rebuild again? C'mon, I'm pretty sure this should reach completion if everything is up.

**Comment by pjf** [comment]
So it looks like the test script is installing mods, but then not clearing away the installs afterwards, meaning mods which conflict with each other can be attempted to be installed.

At this point, I'm declaring my changes to be good even though jenkins is failing them, because they're working on my local system, and if I have to shave the yak in the test script I will go insane and I wants to sleep please and thank you.

**Pull request merged**
