### PR TITLE
Minor change to Contract Configurator netkan

### PR DESCRIPTION
**Pull request by jrossignol**

### CODE REVIEW

**Comment by plague006** [comment]
Hey nightingale. Love your work / what Contract Config has brought to the scene.

I noticed in your ksp thread OP you have WaypointManagerand CoherentContracts as recommendations. Did you want to reflect that in the CKAN entry?

**Comment by jrossignol** [comment]
Good point, why didn't I think of that?  PR updated. :wink:

**Comment by plague006** [comment]
There's actually a `recommends` field if you want to use that for some of them. `recommends` are "ticked" by default whereas `suggests` are on a later screen and unticked by default.

**Comment by jrossignol** [comment]
Hmmm...  for these I think I prefer `suggests`, although I wasn't aware of the `recommends` functionality - thanks for enlightening me!

**Comment by plague006** [comment]
Sounds good.

Passes local, passes Jenkins, merging with my thanks.

**Pull request merged**
