### PR TITLE
Add Kerbal Launch Failure, Add Antares & Cygnus, Update Zero-Point Inline Fairings

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Didn't realize I closed this (I suck at git)

**Comment by Dazpoet** [comment]
Based on how 0point fairings distinctly doesn't work in Stock aero I think we should probably list it as a depends rather than a recommends. what does @NecroBones think about it?

**Comment by NecroBones** [comment]
Yes, that would be fine with me. We're trying to come up with a solution for stock aero, but we can always remove the dependency later if that ever happens.

**Comment by Dazpoet** [comment]
Took another look and it might be worth hardcoding the author field for AntaresCygnus since there are 2 authors rather than the one we scrape from KerbalStuff. The other author is Kartoffelkuchen according to the forum thread :)

**Comment by Dazpoet** [comment]
#rebuild

**Comment by plague006** [comment]
Damn it, didn't mean to push to that branch. Need to figure out how to fix/revert that.

**Comment by Dazpoet** [comment]
Is https://github.com/plague006/NetKAN/commit/0ba3ea0b8b3522c003ca084f041d1276bd7457a7 identical to #1483 ? In that case I guess we can merge this and it wouldn't be a problem?

**Comment by plague006** [comment]
Yes, I accidentally pushed that commit to this branch (when it was meant for #1485). I then reverted 1 commit too far back (which recreated the lack of quotes) and then added the quotes back.

So in the end this *isn't* touching epicsuits, #1485 did that, this is for Launch Fails, Antares, and Fairings.

**Pull request merged**
