### PR TITLE
Add Infernal RO-Robotics from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of whale_2, to add [Infernal RO-Robotics](https://spacedock.info/mod/2329/Infernal%20RO-Robotics) to CKAN.

Please direct questions about this pull request to [whale_2](https://spacedock.info/profile/whale_2).

Mod details:
    name = /mod/2329/Infernal%20RO-Robotics
    author = whale_2
    abstract = Infernal Robotics fork for Realism Overhaul
    license = GPLv3
    Homepage = https://github.com/whale2/InfernalRobotics/tree/master
    description =
This is special fork of **Infernal Robotics** targeted at **Realism Overhaul**, though it should work just fine in usual KSP too.
Features autostrut-like mechanism for moving parts if needed.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Hey @whale2, this is marked as compatible with KSP 1.8 but RealismOverhaul is still on KSP 1.7. Is that OK?

Also what about this is particular to RO? It kind of sounds like this is an adoption/continuation of InfernalRobotics just using RO as branding...?

**Comment by whale2** [comment]
Hi HebaruSan,

It's quite a complicated story with many parties involved. As you
probably know, Infernal Robotics was picked up by Rudolf Meier and
completely rewritten along with some other mods like KJR on which IR Next
is kind of depends. At this point there already was KJR Continued by
pap1723, which was a part of RO set of mods. Currently, RO folks refuse to
provide any support if KJR Next is used, don't ask me why, but this
rendered IR Next less viable option for RO. I was eager to add IR to my RO
gameplay, so I picked up old IR, added some features to it as well as RO
rebalancing. This move was discussed with sirkut and ZodiusInfuser, (I also
messaged Ziw but got no answer) and I said I won't advertise it much on
forums so not to add to confusion with different IR forks.
So technically, my IR fork works as well in non-RO game as in RO, but from
"product placement" POV, it is intended for RO where IR Next is harder to
use. Hope it explains the matter.

As of 1.8 - RO gradually moves to this version after Kopernicus got
released for 1.8.1 - you can see it in so called Golden Spreadsheet (
https://docs.google.com/spreadsheets/d/1Ldf_nCZw0MiCP-Y5YFuvQioEKihY1SNgD-5yS983itE/edit?usp=sharing)

Also, preferred method of installing RO is CKAN, so I wanted to add this
RO-branded IR to it.

**Comment by whale2** [comment]
Hmm, would it make sense to add IR Next as a conflicting mod? I believe it uses the same directory under GameData.

**Comment by HebaruSan** [comment]
Yes, I think several new relationships are probably necessary here.
Can this mod be used with KJRNext?

**Comment by whale2** [comment]
> Can this mod be used with KJRNext?

Frankly - I didn't test it.

**Comment by HebaruSan** [comment]
OK, if any users complain about problems, let us know and we can add a conflict.

**Pull request merged**
