### PR TITLE
Create SETI-ModPack-Basic.netkan

### PR DESCRIPTION
**Pull request by Y3mo**
This is my first time attempting to transfer a meta-package to netkan, I ll try to work on it until it does not fail checks.

It is the ModPack-1-Basic distributed as a ckan file in the SETI thread, with extensions.
In the referenced github file, I temporarily set the KSP version to 1.0.4, so I can test it before people with with the current version 1.0.5 can see it.

I just read on the CKAN forum thread that such a metapackage can work, but I m not aware of any so far (even RealismOverhaul has some download content in it). If anyone has an example of a netkan metapackage, I would really appreciate learning from it.

Thank you very much,
Yemo

### CODE REVIEW

**Comment by Y3mo** [comment]
Hm,
I m not sure what to make of the error:
NetKAN metadata/NetKAN/dummy_ksp is not a vaild install

Does it not like the "kind": "metapackage", within the external, referenced netkan file
or does it need something to install? Or something else?

Any help appreciated!

**Comment by Olympic1** [comment]
`NetKAN metadata/NetKAN/dummy_ksp is not a vaild install` is harmless, this occurs at every build. It is used to create a temp ksp folder to test if a `.netkan` file can install the correct files of a mod.

As for a metapackage, I know it is possible to create a metapackage but I never tried ot out. So I can't help you with that, but I'll have a look at it.

**Comment by Olympic1** [comment]
Change the file extension to `.ckan`

**Comment by plague006** [comment]
@Olympic1 is right. There's nothing wrong with `SETI-ModPack-Basic.netkan` per se, but the `$kref` (https://raw.githubusercontent.com/Y3mo/SETI-ModPacks/master/SETI-ModPack-Basic.netkan) isn't a .netkan it's a .ckan. A .ckan can be a metapackage but a .netkan cannot.

With that said, if you were to merge https://raw.githubusercontent.com/Y3mo/SETI-ModPacks/master/SETI-ModPack-Basic.netkan into https://github.com/KSP-CKAN/CKAN-meta it would be listed and function as expected. I was actually curious so I tested in my fork and it worked just fine: http://puu.sh/liUwj/66d87cb526.png

That's all the theoretical though, in reality I *think* we've decided that modpacks aren't going to be listed in CKAN proper. *BUT* as demonstrated by working on my own fork, if you (or anyone) was to set up a metadata repository for modpacks, users could easily add the repository to their CKAN install and the modpacks would be seamlessly integrated in the regular modlist. If you, or anyone else, wants to take on the task I'd happily help set things up and pass on any info needed. Tagging @pjf to see if he has any further insight on the issue of modpacks.

With all that said, I have to close this PR as it isn't a .netkan but I hope you, someone else, or a collective of people start up a modpack repository.

**Comment by Y3mo** [comment]
Thank you both for the help/explanation.
Unfortunately I barely have time to support/dev my mods, maintaining a repository is therefor out of my league (both in terms of time as well as understanding of ckan).
Since the whole SETI package is something like RealismOverhaul, I wanted to separate the "total conversion" aspect (thus ModPack) from the install files (SETIrebalance), thus making it easier to use the latter without the former.
But that would only work if users see the mod pack in the list, without them needing to add a repository first.

I guess I ll just follow the RealismOverhaul route then without separation of the "total conversion" and "file installation" aspects.

Thank you very much for your help with ckan, it makes conversions really possible,
Yemo

**Comment by politas** [comment]
I might be interested in maintaining a modpack repository, but I haven't had time to work out what is needed. I'm going to have fairly patchy availability over the next few months, as I'm renovating a house in my spare time, but once that's done, I should have the required time.

**Comment by plague006** [comment]
@politas I'll be around when/if you have questions.

**Pull request closed without merging**
