### PR TITLE
Add VensStockPartRevamp-CTTPatch

### PR DESCRIPTION
**Pull request by plague006**
Before this is merged...

@NathanKell would you like to get in touch with the author about integrating this into VSPR itself?

### CODE REVIEW

**Comment by NathanKell** [comment]
Alas I don't have any special means of contact, I just post on the repo like anyone else. :]

**Comment by plague006** [comment]
Oh.. I pinged you because you're listed as the author in our metadata.. but that might be an error in the way we scrape github for authors, it seems to only grab the user who issued the release.

**Comment by NathanKell** [comment]
I do have collab rights on the repo, so I can push MM fixes and in extremis make releases.

**Comment by politas** [comment]
LGTM, Merging now

**Pull request merged**
