### PR TITLE
Add OldSchoolTurrets.netkan

### PR DESCRIPTION
**Pull request by plague006**
Closes #1930

### CODE REVIEW

**Comment by dbent** [comment]
Character classes `\s` is "whitespace" and `\S` is "non-whitespace" so `[\s\S]` is equivalent to "any character", or simply `.`.

Or in other words: `(^|/).*\\.meta$`

But looking at the download, I don't see any `.meta` files?

**Comment by dbent** [comment]
Nevermind, they have a hidden attribute, curious.

**Comment by plague006** [comment]
My mistake with the regex. I use a large body of text to make sure I'm only filtering what I mean to. I use \s because the body of text has linebreaks, and I failed to switch it back.

**Comment by plague006** [comment]
Passes local, jenkins fail is because it's testing unrelated mods.

**Comment by techman83** [comment]
@plague006 the build script compares the checked out commit to origin master. It will test all files that differ. I don't know if there is a way around that, but it's certainly not optimal.

**Comment by plague006** [comment]
@techman83 Not that it gets us there, but the old jenkins was able to isolate the commits without taking the chain.

**Comment by techman83** [comment]
@plague006 I'm not sure how, it's the same build script. Jenkins doesn't decide anything at all, it sets up some environment variables, launches the container and runs the script.

**Comment by mgsdk** [comment]
@techman83 @plague006 I think there are some issues with the current script. I am in the process of doing a second pass of it, but it will most likely be a few days before I have a PR ready for a merge (I am away most of today and tomorrow).

**Comment by plague006** [comment]
Tested locally again, merging.

**Pull request merged**
