### PR TITLE
Spacetuxlib

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
4615 [1] FATAL CKAN.NetKAN.Program (null) - Too many .version files located: GameData/SpaceTuxLibrary/KSP_ColorPicker.version, GameData/SpaceTuxLibrary/KSP_Log.version, GameData/SpaceTuxLibrary/KSP_PartHighlighter.version, GameData/SpaceTuxLibrary/SpaceTuxLibrary.version

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Pull request merged**
