### PR TITLE
First release

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by dbent** [comment]
FYI, `author`, `name`, `abstract`, `homepage`, and `kerbalstuff` will all be populated and updated automatically by the bot. No need to specify them explicitly when using a Kerbal Stuff `$kref`. Also a `release_status` of `stable` is assumed if one is not specified.

You also install a `GameData/Better Science Labs Continued/Resources/snackexperiment.cfg~` file which probably shouldn't be in the distribution.

**Comment by linuxgurugamer** [comment]
I just uploaded a new version 0.1.3.0 which removed that file and fixes some problems

**Comment by linuxgurugamer** [comment]
I assume it doesn't hurt to specify those fields?  I essentially copied 
one of my earlier files and updated it.

thanks for the heads-up on the old file, I just uploaded a new release 
which fixes that and other problems.

When can I expect to see it in CKAN?

Thanks


JBB

**Comment by dbent** [comment]
No, specifying the fields doesn't hurt, but you lose the ability to just edit the fields on KS and have them flow through automatically. It'll appear within 3 hours, the bot needs to index it.

**Comment by linuxgurugamer** [comment]
Ok, thanks

**Comment by linuxgurugamer** [comment]
Hi Dwayne,

I was wondering if you could do me a favor.

I just released a new mod: 
https://kerbalstuff.com/mod/929/EVA%20Handrails%20Pack%20Continued

http://forum.kerbalspaceprogram.com/threads/100531-0-25-NEBULA-space-engineering-EVA-handrails-pack?p=2029039#post2029039

but I just got out of the hospital and don't have the wherewithal to do 
the NetKAN stuff.

I was wondering if you would set up the netkan file for me?

Thanks


Jonathan Bayer

**Pull request merged**
