### PR TITLE
Kiwi Tech Tree

### PR DESCRIPTION
**Pull request by hemeac**
Kiwi Tech Tree Overhaul
A "Probes/Planes Before Crew" overhaul of the Tech Tree that builds on the those concepts by adding part upgrades through the B9PS system and gameplay elements from certain mods for mods which are currently supported.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Here's the relevant part of [the log](https://ci.ksp-ckan.space/job/NetKAN/10228/console):

```
Running jsonlint on the changed files
If you get an error below you should look for syntax errors in the metadata
Validating NetKAN/KiwiTechTree.netkan...
NetKAN/KiwiTechTree.netkan:8:1: Warning: Object contains duplicate key: u'ksp_version_min'
   |  At line 8, column 1, offset 328
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/KiwiTechTree.netkan:26:4: Error: Strict JSON does not allow a final comma in an array (list) literal
   |  At line 26, column 4, offset 816
   |  Array started at line 20, column 18, offset 632
NetKAN/KiwiTechTree.netkan:89:4: Error: Strict JSON does not allow a final comma in an object (dictionary) literal
   |  At line 89, column 4, offset 3341
   |  Object started at line 86, column 17, offset 3257
NetKAN/KiwiTechTree.netkan: has errors
Build step 'Execute shell' marked build as failure
```

**Comment by hemeac** [comment]
Thanks, think I've fixed the three failed checks

**Comment by HebaruSan** [comment]
One note, it's usually a bit tedious to maintain `ksp_version_*` in the netkan. For easier control, you can put a version file in the download so each release's versions could be indicated as needed without having to submit further pull requests to NetKAN.

- http://ksp.cybutek.net/kspavc/Documents/README.htm

If you want to go that way, let us know, otherwise it looks like the current file will work fine.

**Comment by hemeac** [comment]
I've added a Version file in the download and added that Spacedock.  Did a quick test with netkan.exe using "$vref": 			"#/ckan/ksp-avc", and that seems to work ok, will edit the file to reflect that.

**Comment by HebaruSan** [comment]
Nice! All looks good to me. Thanks for the submission! Merging...

**Pull request merged**
