### PR TITLE
Walkabout

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Unfortunately, #rebuild doesn't do anything anymore since we switched from Travis to GitHub Actions.
Try the "Re-run jobs" dropdown in the upper right of the Checks tab of the pull request.

**Comment by HebaruSan** [comment]
SpaceTuxLibrary just needed to be marked as working on 1.11.2 on SpaceDock. I did that, may take a few minutes to flow through to the metdata, then a re-run should work.

**Comment by linuxgurugamer** [comment]
> SpaceTuxLibrary just needed to be marked as working on 1.11.2 on SpaceDock. I did that, may take a few minutes to flow through to the metdata, then a re-run should work.

Thank you

**Comment by linuxgurugamer** [comment]
I already updated ToolbarController on Spacedock, as well as the ClickThroughBlocker, but it's still failing on the ToolbarController.  I'll try again in 1/2 hour or so, otherwise I suppose I can push an update on both of them

**Comment by HebaruSan** [comment]
ZeroMiniAVC was the last hold-out, give it another few minutes to update.

**Pull request merged**
