### PR TITLE
Add AmbientLightAdjustment's dependency on Toolbar

### LINKED ISSUE #2279: AmbientLightAdjustment depends on Toolbar Plugin
As per the forum thread:
> This plugin requires the Toolbar Plugin version >=1.7.0 (no longer bundled with the download - don't forget to grab it separately or this plugin can't do its thing!)

NetKAN metadata doesn't specify this.

### PR DESCRIPTION
**Pull request by plague006**
Closes #2279

### CODE REVIEW

**Comment by plague006** [comment]
GJ Jenks.

jsonchk is happy with the .netkan

Generated .ckan:
````
AmbientLightAdjustment-1.4.4.2.ckan  
{
    "spec_version": 1,
    "identifier": "AmbientLightAdjustment",
    "name": "Ambient Light Adjustment",
    "abstract": "Allows to adjust the ambient lighting on the fly in the flight scene",
    "author": "timmers_uk",
    "license": "GPL-3.0",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/71536",
        "kerbalstuff": "https://kerbalstuff.com/mod/421/Ambient%20Light%20Adjustment",
        "repository": "https://github.com/timmersuk/ksp_ambient_light",
        "x_screenshot": "https://kerbalstuff.com/content/timmers_uk_1564/Ambient_Light_Adjustment/Ambient_Light_Adjustment.png"
    },
    "version": "1.4.4.2",
    "ksp_version": "1.0.4",
    "depends": [
        {
            "name": "Toolbar"
        }
    ],
    "download": "https://kerbalstuff.com/mod/421/Ambient%20Light%20Adjustment/download/1.4.4.2",
    "download_size": 36891,
    "x_generated_by": "netkan"
}
````

Installed files:

````
D:\testsuite>type tree.md 
Folder PATH listing for volume WD
Volume serial number is 8C08-377A
D:\TESTSUITE\DUMMY_KSP\GAMEDATA
+---000_Toolbar
|       CHANGES.txt
|       folder.png
|       LICENSE.txt
|       move-cursor.png
|       new-button-available.png
|       resize-cursor.png
|       toolbar-dropdown.png
|       Toolbar.dll
|       update-available.png
|       version.txt
|       
\---AmbientLightAdjustment
        AmbientLightAdjustment.dll
        AmbientLightAdjustment.version
        CHANGES.txt
        contrast.tga
        LICENSE.txt
        MiniAVC.dll
````

**Comment by techman83** [comment]
The latest NetKAN artifact didn't like it for some reason.

**Comment by techman83** [comment]
Sorry, I need to have my morning coffee. You might have to rebase, it's picking up 'LVNNuclearEngineClusters.netkan' which is failing. I saw that last night.

One day I'll dig into jenkins and see if we can get the commit compare rather than comparing against latest.

**Comment by plague006** [comment]
I suck at rebasing.

**Comment by plague006** [comment]
Well I guess with history rewritten I can claim to not suck at rebasing.. lol

**Comment by techman83** [comment]
:+1:

**Pull request merged**
