### PR TITLE
fix homepage url

### PR DESCRIPTION
**Pull request by miki-g**
bad and ugly forum - changed thread URL ( after change of title )

### CODE REVIEW

**Comment by politas** [comment]
You've added a comment= bit at the end that will opena  specific comment rather than the main thread. If you want a link that will remain unchanging, the forums currently ignore everything after the first "-", (but sometimes you need to have _a_ character there, whatever it may be.) So for example, this should work:

    "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/139827-*"

**Comment by politas** [comment]
Oh, and it looks like Jenkins is saying your .version file is not strict JSON.

**Comment by miki-g** [comment]
.version file I fixed yesterday immediately after the jenkins test
but I do not know how to run jenkins again without changing the file .netkan

thanx for sugestion with * in url :) ... #comment is "ok" ... for better focus on first post (scrolling away forum banner, menu, ... ) ... or it is bad idea? :)

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
Merged with thanks! Always good to learn a new trick!

**Pull request merged**
