### PR TITLE
SVE "CKAN friendly" redevelopment

### PR DESCRIPTION
**Pull request by politas**
Same name collapses all three releases into a single entry

### CODE REVIEW

**Comment by Olympic1** [comment]
Zip folder completely changes. EVE and scatterer folders got removed and now depends on them.

sunflare config now is a separate download.

The problem is all sort of conflicts. Dependency on EVE but conflicts with the configs while EVE depends on those. Same for scatterer.

More info:
http://forum.kerbalspaceprogram.com/index.php?/topic/143288-12-113-stock-visual-enhancements-114-1083/&page=54#comment-2817688 and in the readme in the zip.

**Comment by politas** [comment]
Please employ some "extreme vetting" on this one.

**Comment by Olympic1** [comment]
Tested and works. If you just could put some `vref` in the SVE files this is good for merging

**Comment by Olympic1** [comment]
Thanks, merging

**Pull request merged**
