### PR TITLE
Add Kerbol 4X from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
# Needs ability to overwrite
This pull request was automatically generated by Kerbal Stuff on behalf of Angorek, to add [Kerbol 4X](https://kerbalstuff.com/mod/970/Kerbol%204X) to CKAN.

Please direct questions about this pull request to [Angorek](https://kerbalstuff.com/profile/Angorek).

### CODE REVIEW

**Comment by plague006** [comment]
This mod's archive contains
- KerbolPlus
- Kopernicus
- Texture Replacer
- Environmental Visual Enhancements with Pingopete`s RVE textures
- KSC Switcher
and instructions include overwriting some files.

Need to figure out which of those can be added as depencencies, or if they have to be conflicts (with Kerbol 4X supplying the mod itself).

**Comment by Angorek** [comment]
Hi ! 
I`m finishing next update and it will need KerbinSide and Kerbol Plus installed separately. My mod will overwrite their cfg files. Is it possible to do it with CKAN ? 
Everything else is in the archive and I want it to stay that way, because these mods have many different versions, EVE especially and I want to upload only files I`m 100% sure will work.

**Comment by plague006** [comment]
CKAN cannot overwrite files from another mod. What we'll have to end up doing is splitting yours and some other mods. Would ModuleManager patches be an option for you? It doesn't have to be every file, but the less files that have to be split out, the better.

**Comment by Angorek** [comment]
So I think CKAN won't work in this case :( I need to overwrite files, because MM will not work for KerbinSide, and I can`t include it into package because of it`s licence.
With KerbolPlus there should be no problem, because Kopernicus supports MM.

**Comment by plague006** [comment]
>So I think CKAN won't work in this case
CKAN can still handle it, we just have to break packages apart.

**Comment by Angorek** [comment]
But what do you mean by saying " break the packages" ?

**Comment by plague006** [comment]
It's entirely CKAN-side, but your mod will have some parts (specifically the conflicting parts) separated into a different package so that everything can coexist when installed via CKAN.

For example: PlanetShine has its default config, but Astronomer's Pack wants to overwrite it. So PlanetShine has its config put into a separate package. Users have to choose one config or the other, which prevent people accidentally playing without one.

Your mod will go through the same general thing.

**Comment by Angorek** [comment]
Well sorry, but I have to resign from CKAN. The reason is very simple.. no time. I`m studying to be a pilot, and working so I have a lot on my head right now..

**Comment by plague006** [comment]
Thoughts on how to tackle this (basically my notepad)

4x has to replace all (26) the .cfg files in `KerbolPlus`'s `DwarfPlanets` `KeelonSystem` `ModConfigs`, and `SarvinSystem` folders without affecting their .png files. 4x does not package the entirety of `KerbolPlus` (so no way around this with a `conflicts`, K+ would have to be split). Cannot use a filter_regex for all the .cfg files in K+ because it includes 2 part cfgs. (Manually adding the 2 cfgs makes it very easy to break K+ if another part or planet is added).

4x `depends` `Kopernicus` with no conflicts.

4x `depends` `TextureReplacer-2.4.6`. For some reason 4x has a modified `TextureReplacer.version` set to version `1.8` and ksp_ver `0.25.0`. I'm unclear on why, but believe it can be discarded in favor of a plain `depends`.

There's an `EnvironmentalVisualEnhancements` folder which doesn't match up to `7.4` or `7.3` of the same-named mod. Nor does it match up to https://github.com/Pingopete/RVE-KSP-1.0.4. I think this could be resolved by a `conflicts` with `EnvironmentalVisualEnhancements`.

----

The biggest issue is the conflict with `KerbolPlus`. Pulling out 26 individual files to split it up is unreasonable. If the mod author were to include the whole mod then a `conflicts` would likely solve the situation.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN/issues/1311 would benefit this mod

**Comment by plague006** [comment]
Closing in favour of https://github.com/KSP-CKAN/NetKAN/issues/2179

**Pull request closed without merging**
