### PR TITLE
Add Engineer Level Fixer from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of civilwargeeky, to add [Engineer Level Fixer](https://kerbalstuff.com/mod/1155/Engineer%20Level%20Fixer) to CKAN.

Please direct questions about this pull request to [civilwargeeky](https://kerbalstuff.com/profile/civilwargeeky).

### CODE REVIEW

**Comment by civilwargeeky** [comment]
Hi! To whom it may concern, does it usually take several days to merge a new mod if the checks passed? This is my first foray into Kerbal modding and I was hoping to see my mod in CKAN quickly.

If there is anything I can do to speed along the process, please let me know! Thanks.

**Comment by techman83** [comment]
@civilwargeeky - I think the usual volunteer metadata herders have been away. It looks pretty straight forward and the build did pass! Great thing is that new releases will be picked up automatically by the bot :-)

**Comment by plague006** [comment]
This mod `depends` `ModuleManager`. On mobile so I can't write the fix myself.

**Comment by civilwargeeky** [comment]
Okay thanks!
I forked the project, and changed my file to be this:
```
{
    "spec_version": "v1.4",
    "x_via": "Automated KerbalStuff CKAN submission",
    "identifier": "EngineerLevelFixer",
    "license": "MIT",
    "$kref": "#/ckan/kerbalstuff/1155",
    "$vref": "#/ckan/ksp-avc",
    "depends" : [
      { "name" : "ModuleManager" }
    ]
}
```
Before I submit a pull request, should this be the proper way to format my file to include the things you said?

**Comment by plague006** [comment]
Looks good. If there are any technical errors Jenkins will catch them.

**Pull request merged**
