### PR TITLE
Adds missing author line for USI-(MKS/OSI)

### PR DESCRIPTION
**Pull request by SkyMarshal**
Also cleaned up the formatting.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Hm while you're updating we might want to change the suggestion for TAC-LS to USI-LS? Seems like a reasonable change?

**Comment by SkyMarshal** [comment]
I guess.  I am unsure how complete USI-LS is, however.  I have been using TAC-LS lately.

**Comment by Dazpoet** [comment]
My thought was that I assumed TACLS is in there because the author wants to promote an LS mod style of play and seeing as there is now an USI variety of LS it would be better to add that one.

We have USI-LS indexed (manually, over att CKAN-meta) so it's stable enough to be around here atleast :)

**Comment by SkyMarshal** [comment]
Looking at it, USI-LS should be functional, but is... kinda sparse.  I'm not opposed to changing the recommendation setting, but RoverDude still has the [forum thread](http://forum.kerbalspaceprogram.com/threads/116790-1-0-USI-Life-Support-ALPHA-0-1-0-2015-04-27) marked as alpha.

**Comment by Dazpoet** [comment]
Best is probably to just ask him, any thoughts @BobPalmer ?

**Comment by SkyMarshal** [comment]
Good point.  I forgot github had a thing for that.

**Comment by BobPalmer** [comment]
USI-LS is complete enough.  Remove the suggestion for TAC-LS

**Comment by SkyMarshal** [comment]
Suggestion adjusted.  No idea if I did that right or not.

**Comment by Dazpoet** [comment]
Seems the bot hates us... But seeing as you only changed 2 lines after the mod ok'd it all should be fine. Thanks for the update!

**Pull request merged**
