### PR TITLE
KerbalAircraftExpanstion update for 1.2.2 with authors permission

### LINKED ISSUE #5139: KAX needs updating
KAX is available for 1.2.2
I've contact the author asking permission to update the netkan

This is more of a placeholder, so that no one else raises the issue

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #5139

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Author confirmed 1.2.1 compatibility

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
LGTM

**Pull request merged**
