### PR TITLE
Add B9-Pwings-Fork.netkan

### PR DESCRIPTION
**Pull request by politas**
Adding compatibility fork of B9AerospaceProceduralParts. Tested locally

### CODE REVIEW

**Comment by Olympic1** [comment]
Because the download includes a `.version` file, you can use `"$vref": "#/ckan/ksp-avc",` and drop the `ksp_version`. I'll also make a PR to use the new id instead.

**Comment by politas** [comment]
The .version file has not been updated for the fork. It'll all be wrong

**Comment by Olympic1** [comment]
Oh, I overlooked it :disappointed:

**Comment by Olympic1** [comment]
Passes local. Merging with my thanks.

**Comment by politas** [comment]
Good catch on the Recommends, Olympic1, by the way.

**Pull request merged**
