### PR TITLE
Add F-18A Super Hornet from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of LuizChacon, to add [F-18A Super Hornet](https://kerbalstuff.com/mod/840/F-18A%20Super%20Hornet) to CKAN.

Please direct questions about this pull request to [LuizChacon](https://kerbalstuff.com/profile/LuizChacon).

### CODE REVIEW

**Comment by mgsdk** [comment]
KS says GPL-3.0, one of the license files says CC-BY-NC-4.0. Will need to be tested on a 0.90 builder.

**Comment by Dazpoet** [comment]
There are acctually 2 licenses in the .zip. One CC-BY-NC-4.0 and one WTFPL... afaik GPL-3.0 is the most restrictive of the 3?

**Comment by politas** [comment]
Actually, the NC part of CC-BY-NC is more restrictive than the GPL. Does this mod include code and artwork? It is likely that different parts have different licences, in that case. GPL for code, CC for artwork. Squad's licence discussion almost recommends such an approach.

**Comment by politas** [comment]
Hang on, doesn't the CKAN spec allow for multiple licences? Why aren't we doing that? From a legal standpoint, that's a better idea.

**Comment by Dazpoet** [comment]
Good point! I did not consider that aspect of it. What a mess though, should this perhaps then be marked as one of the more general ones listed [here](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#license) ? I think they would all fall into the `unrestricted` category?

As for multiple licenses I don't think the clients can show more than one and tbh I'm not totally sure the `"licenses"` field does what it is supposed too but I can update #1419 and see what happens :)

**Comment by Dazpoet** [comment]
Alas it seems I was unfortunatly right and #1419 fails due to no set license field, I tried locally to run it through netkan.exe and it scrapes for a license from KS there and returns an error since the scraped `GPLv3` isn't a valid license as per the CKAN.schema.

It would appear we require a set `license` field and then `licenses` can add more but only to the metadata file and not for being displayed to the user.

**Comment by politas** [comment]
I've raised #1424 do discuss this. We should handle multiple licences properly.

**Pull request closed without merging**
