### PR TITLE
Add Science Roles - Final Frontier Ribbon Pack from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of SmarterThanMe, to add [Science Roles - Final Frontier Ribbon Pack](https://spacedock.info/mod/582/Science%20Roles%20-%20Final%20Frontier%20Ribbon%20Pack) to CKAN.

Mod details:
    name = /mod/582/Science%20Roles%20-%20Final%20Frontier%20Ribbon%20Pack
    author = SmarterThanMe
    abstract = This is a collection of ribbons that you can assign to your Scientists to differentiate their qualifications and expertise for Role-Playing purposes. PLEASE NOTE: Final Frontier is required for this ribbon pack.
    license = CC BY-NC-SA 4.0
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/129465-110-stms-final-frontier-expeditionrank-ribbon-packs-updated-180416-2xexpedition-ribbons/
    description = This is a collection of ribbons that you can assign to your Scientists to differentiate their qualifications and expertise for Role-Playing purposes. PLEASE NOTE: Final Frontier is required for this ribbon pack.

Please direct questions about this pull request to [SmarterThanMe](https://spacedock.info/profile/SmarterThanMe).

### CODE REVIEW

**Comment by plague006** [comment]
@politas mind if I leave this to you? I suspect you know more about these ribbon packs than anyone else.

**Comment by SmarterThanMe** [comment]
Should be more or less the same as the others?

**Comment by politas** [comment]
That should work.

**Comment by plague006** [comment]
`FinalFrontier` will be available via https://github.com/KSP-CKAN/NetKAN/pull/3734

**Comment by plague006** [comment]
Rebuilding

**Comment by plague006** [comment]
@SmarterThanMe presently your mods are inconsistently named. If you're cool with that so are we, but if you'd like a specific naming scheme for them just let us know. http://puu.sh/owjOG/fa4969e8ca.png

**Comment by SmarterThanMe** [comment]
@plague006 Yeah, that's intentional. :) There's another two people who are working on or have released rank packs of their own, so I wanted to keep my work distinct from their's. Also expeditions, because I can imagine that someone else will jump in on that at some point.

**Pull request merged**
