### PR TITLE
Move Rusty Star Rockets to SpaceDock

### PR DESCRIPTION
**Pull request by politas**
Closes #3221

### CODE REVIEW

**Comment by politas** [comment]
#rebuild, maybe?

**Comment by politas** [comment]
Tested fine locally.

**Comment by Olympic1** [comment]
Merging with my thanks

**Comment by techman83** [comment]
Looks like we're getting a lot of corrupted downloads lately.

**Comment by politas** [comment]
Spacedock had a faulty disk, which has now been replaced.

**Pull request merged**
