### PR TITLE
Added Urgent Contracts

### PR DESCRIPTION
**Pull request by GarwelGarwel**

### CODE REVIEW

**Comment by GarwelGarwel** [comment]
Not sure why it says the checks have failed.

**Comment by DasSkelett** [comment]
```
Warning: JSON document was prefixed by a BOM (Byte Order Mark): '\xef\xbb\xbf'
   |  At line 1, column 0, offset 0 (AT-START)
```

**Comment by DasSkelett** [comment]
Your Timekeeper netkan also had a BOM in it. What software (text editor) do you use to create these files?

**Comment by GarwelGarwel** [comment]
I use Notepad++.

**Comment by GarwelGarwel** [comment]
Ok, I see the problem is in the encoding I use. I'll resubmit the PR now.

**Pull request closed without merging**
