### PR TITLE
Update SDHI-ServiceModuleSystem.netkan

### PR DESCRIPTION
**Pull request by plague006**
1.0.4 bump

### CODE REVIEW

**Comment by sumghai** [comment]
Yep, this looks good  to me :)

**Comment by techman83** [comment]
Is there a problem with some of the metadata, because in theory 1.0 means all of 1.0.x, this would lock it to 1.0.4.

I think we can override per version now.

**Comment by sumghai** [comment]
This new update is intended for KSP 1.0.4 only. Not sure what value overriding would have.

**Comment by techman83** [comment]
Fair point, looks like your using GitHub, so no version information can be gathered automatically. So this makes sense.

**Comment by sumghai** [comment]
Excellent, thanks guys :)

Yeah, I'm just using Github.

**Pull request merged**
