### PR TITLE
Overrides for 1.0.4 compatible mods

### PR DESCRIPTION
**Pull request by plague006**
Chatterer
CollisionFX
DMagicOrbitalScience
InfernalRobotics-Sequencer
IR-Model-Rework-Core
IR-Model-Rework-Expansion
MissionController2
PlanetShine-Config-Default
PlanetShine
PortableScienceContainer
RCSBuildAid
RoutineMissionManager
SAVE

### CODE REVIEW

**Comment by plague006** [comment]
Reverted RCSBuildAid.netkan to its original state (forgot it doesn't work with m4v's github)

**Comment by dbent** [comment]
`Chatterer` has been marked as 1.0.4 compatible on KS. I did the `PlanetShine` changes in another PR which makes this one fail to merge.

**Comment by plague006** [comment]
I didn't see PlanetShine was updated because you merged yours after I submitted my PR. My predictive skills have failed me.

**Comment by plague006** [comment]
I'd rather just not deal with this, I have no idea how to undo the specific PlanetShine changes to have this not fail.

**Comment by dbent** [comment]
You can just replace them with the current version of the files.

**Comment by plague006** [comment]
I'd rather just not deal with this. Thanks for the info though.

**Pull request closed without merging**
