### PR TITLE
Add UKCLSSM (fixed KerbalStuffBot submission)

### PR DESCRIPTION
**Pull request by politas**
Closes #2976

### CODE REVIEW

**Comment by politas** [comment]
14319 [1] FATAL CKAN.NetKAN.Program (null) - Unexpected character encountered while parsing value: <. Path '', line 2, position 1.

Can anyone work out what NetKAN is complaining about?

**Comment by plague006** [comment]
KerbalStuff is presently having issues, likely resulting in this failure. In spite of multiple attempts I can't download the .zip to review the metadata. Will try again another day.

**Comment by politas** [comment]
#rebuiild

**Comment by politas** [comment]
Nope. This was failing well before KerbalStuff started having issues, and it still is.

**Comment by Olympic1** [comment]
I think the problem is caused by that there is no `KSP Version` on the KS page which means that our bot can't extract the compatible version for the mod. It doesn't extract the version from the changelog page iirc.

**Comment by plague006** [comment]
@politas if you have an alternate source for this, feel free to reopen.

**Pull request closed without merging**
