### PR TITLE
SETI metadata relocation - UbM

### PR DESCRIPTION
**Pull request by Y3mo**
no other changes

### CODE REVIEW

**Comment by politas** [comment]
#rebuild

**Comment by Y3mo** [comment]
Hey,
with the exception of the new SETI mini mod, the external metadata files are exactly the same as before (which all worked fine), just at a different location.
But I guess since some mods are not officially updated to 1.1.3, it tries to find the appropriate dependency for 1.1.2 or even 1.0.5 for checking, which is pretty much irrelevant to the validity of the metadata itself.

Best regards,
Y3mo

**Comment by Y3mo** [comment]
6

**Comment by politas** [comment]
Merging with thanks

**Comment by politas** [comment]
Or not, just at the moment. Mobile github is not allowing me to merge this.

**Pull request merged**
