### PR TITLE
Release for KWRocketryRedux

### PR DESCRIPTION
**Pull request by linuxgurugamer**
These three netkan files are for the KWRocketryRedux

### CODE REVIEW

**Comment by plague006** [comment]
Please change the `provides` virtual module to `KWRocketryRedux-power`. Then have both `KWRocketryRedux-GraduatedPwr` and `KWRocketryRedux-InstantPwr` `conflicts` `KWRocketryRedux-power`. You'll also need to updated the `depends` in `KWRocketryRedux`.

**Comment by plague006** [comment]
Also, this isn't installing to the directory you want `GameData/KWRocketry/GameData/KWRocketry/Soundbank/sound_liq11.wav`

**Comment by linuxgurugamer** [comment]
done

**Comment by linuxgurugamer** [comment]
Done and passed checks

**Comment by plague006** [comment]
To give users an easier time finding the appropriate modules can you `name` `KWRocketryRedux-GraduatedPwr` to `KW Rocketry Redux - Graduated Power Response Configs` (or something similar as long as the base mod name is in the `name`. Similarly `KWRocketryRedux-InstantPwr` with a `name` of `KW Rocketry Redux - Instant Power Response Configs`. Lastly the `name` for `KWRocketryRedux` seems overly complicated. Would `KW Rocketry Redux` still remain accurate? The `abstract` already specifies that this is full KW with community fixes.

**Comment by linuxgurugamer** [comment]
Done

**Comment by plague006** [comment]
Looks good, merging with my thanks.

**Pull request merged**
