### PR TITLE
Move KerboKatz' Mods to self-hosted Netkans

### PR DESCRIPTION
**Pull request by politas**

### CODE REVIEW

**Comment by plague006** [comment]
Looks good, merging with my thanks.

**Comment by plague006** [comment]
If you wouldn't mind double-checking that the following were intended:

Author changed in:
https://github.com/KSP-CKAN/CKAN-meta/commit/6c777e940484a71203ecd6db3b8ecfd4e4b97679  
https://github.com/KSP-CKAN/CKAN-meta/commit/b73d0764504dbd9786b64b13dd69138ecc247315  
https://github.com/KSP-CKAN/CKAN-meta/commit/7f3d939f523f453ee9fe2ecd08f01e148d7d4b2d  
https://github.com/KSP-CKAN/CKAN-meta/commit/ad7cc928f8fef548390ea6a81f59823fd0351f9d  
https://github.com/KSP-CKAN/CKAN-meta/commit/ba530ac79a83b4dd0af62d80ef3094368ca7ff0c

Dependency on `KerboKatzUtilities` removed in:
https://github.com/KSP-CKAN/CKAN-meta/commit/b73d0764504dbd9786b64b13dd69138ecc247315

**Comment by politas** [comment]
Ah, yes. They should probably all stay as SpaceTiger. I'll fix that. Xarun is their Github handle, rather than their Forum name.

**Comment by plague006** [comment]
Awesome, appreciate you having a look.

**Pull request merged**
