### PR TITLE
Skillz

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #4531

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
The author has advised this is on GitHub with a .version file, now. That's probably a preferable source. Not sure what the Github address is, though.

**Comment by linuxgurugamer** [comment]
he may have said so, but it's not true (yet).  There is an entry on the ksp-avc site, but the file isn't included in the download and isn't on Github either.  I've asked him to fix that

**Comment by politas** [comment]
Might leave this one a couple of days pending updates from the author.

**Comment by politas** [comment]
Enough waiting. Merging with thanks!

**Pull request merged**
