### PR TITLE
Add Syncrio to CKAN

### PR DESCRIPTION
**Pull request by Caylis1397**

### CODE REVIEW

**Comment by Olympic1** [comment]
The `identifier` and `.netkan` name has to be the same. You forgot the `i` in the file name.

**Comment by Olympic1** [comment]
Change `spec_version` from 1 to  `"v1.2"`

**Comment by politas** [comment]
Will have to wait for Spacedock to be working again.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
Looks good to me. Merging with thanks!

**Pull request merged**
