### PR TITLE
Add SimpleNuclear NFT Balanced, closes #3344

### PR DESCRIPTION
**Pull request by Olympic1**
Add SimpleNuclear-NFT-Balanced and conflict with SimpleNuclear-NFT

### CODE REVIEW

**Comment by politas** [comment]
Only issue I have is that this prevents users installing only one of NearFutureElectrical or NearFuturePropulsion with the SimpleNuclear configs.

I don't think making the NFT mods "recommends" would cause any problems?

**Comment by Olympic1** [comment]
@politas Done

**Comment by politas** [comment]
Merging with my thanks

**Comment by plague006** [comment]
This module fails to install unless a user realizes the 2 `recommends` (which are opt out) conflict with one another.

FWIW if it was misleading, me adding a commit to a PR isn't an endorsement of any kind, I was just fixing a technical error that was blocking Jenkins.

Cleaned up in https://github.com/KSP-CKAN/NetKAN/pull/3374 and https://github.com/KSP-CKAN/CKAN-meta/pull/999.

**Pull request merged**
