### PR TITLE
Add EasyVesselSwitch v1.0.0

### PR DESCRIPTION
**Pull request by ihsoft**

### CODE REVIEW

**Comment by ihsoft** [comment]
Please, let me know if any info is required but missing.

**Comment by plague006** [comment]
Looks good to me, when CKAN 1.18 is released I'll change the license to `Unlicense` for specificity, merging with my thanks.

**Comment by ihsoft** [comment]
> I'll change the license to Unlicense for specificity

Should I change it in my repository as well or it will work without the change?

**Comment by plague006** [comment]
It'll work without any change on your end.

**Pull request merged**
