### PR TITLE
EvaFuel to spacedock

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Sent the mod author a message asking for a new .zip to be uploaded since Jenkins complains it's corrupt both in this PR and in #3815.

**Comment by AliceTheGorgon** [comment]
I've uploaded a new zip to Spacedock. Hopefully this one doesn't give the bot issues.

**Comment by plague006** [comment]
`CKAN.FileNotFoundKraken: Trying to install EvaFuel 1.1.1, but it's not downloaded or download is corrupted` both from the bot and with my local test suite.

I tried extensively to get this to work. I downloaded the .zip and reuploaded it to another site myself and couldn't install. I even tried downloading it, unzipping it, re-compressing it myself, and it still failed. I'm really not sure where to go from here.

**Comment by AliceTheGorgon** [comment]
At a guess, it might be related to compression options.
I've uploaded some test zips with different settings, here:
https://drive.google.com/folderview?id=0B4ps98pMWaZnOFIxblI0MDk2YkU

There's also a .7z file, in case CKAN supports those.

If none of those work, I can create some more test files from my Windows partition and upload them too.

**Comment by plague006** [comment]
I tried `Default-7zip-Windows.zip` `Default-builtin-Windows.zip` `Store-7zip-Windows.zip` `Store-zip-Linux.zip` and `Ultra-zip-Linux.zip` and.... *drumroll* each one worked.

**Comment by AliceTheGorgon** [comment]
I guess there's something weird going on with the right-click -> compress -> "to zip file" option on my computer then, since the ones made from the command line worked fine here, but the original gui ones didn't.
Unless spacedock is breaking them, but it seems like the issue would be more widespread if that where the case.

Anyway, sorry for the trouble. In the future I'll make sure to make the zips from the command line.

**Comment by plague006** [comment]
`EvaFuel-v1.zip` didn't pass testing.

**Comment by AliceTheGorgon** [comment]
Thanks for double-checking. That's really weird.

Is there a way I can download the test suite to check my zips before uploading them, so this doesn't happen again?

**Comment by politas** [comment]
You can make a .ckan file that points to a staging location, and test the installation works with CKAN. That's ultimately where it's failing.

**Comment by AliceTheGorgon** [comment]
Okay, I've got a testing .ckan file setup, and it also hangs on the same files the bot had issues with, and works with the ones that worked here. Thanks for all your help everyone, and sorry for the bother.

**Comment by AliceTheGorgon** [comment]
Sorry for another post so quickly. The mod was updated, and the new zip is in spacedock. I tested it with my local copy of CKAN, and this one should finally work with the bot.

**Comment by plague006** [comment]
Passes Jenkins.

**Comment by politas** [comment]
LGTM, merging

**Pull request merged**
