### PR TITLE
Split PlanetShine into core and default config

### PR DESCRIPTION
**Pull request by SpaceTeph**
Preparatory work for other mods that tweak the PlanetShine config - Astronomer's Pack is one of them.

### CODE REVIEW

**Comment by hakan42** [comment]
#rebuild

**Comment by hakan42** [comment]
Could you provide the pull requests for those splitting jobs as two separate PRs? Then, Jenkins would have a chance to show that the Config part is working, and after merging that, we could re-build the other part...

**Comment by SpaceTeph** [comment]
Well, the issue is, this mod pair can't be automatically checked because it has a circular dependency. Those are apparently common in NetKAN, and they're useful: the config depends on the mod, the mod depends on the config... It means that the config cannot be independently installed without the mod and the other way around. Doesn't that mean that Jenkins will always fail the automated test? If yes, the only way for Jenkins to succeed would be to check the installation of both the mod and its config at the same time with something like

    ckan install -c built/PlanetShine-0.2.2.1.ckan built/PlanetShine-Config-Default-0.2.2.1.ckan

I get your point about using two separate PRs, but if I start by submitting the Config first, it will pass dependency checks but will fail when installing because it contains files that are part of the not-yet-changed PlanetShine mod in the repository...

**Comment by hakan42** [comment]
Yes, I get you... So, if you are confident with this PR, gimme a ping and I'll merge it. Any errors can be repaired in upcoming PRs :smiling_imp:

**Comment by SpaceTeph** [comment]
Then ping @hakan42, because I have tested this with the newly-changed, multiple-files -c option. My only ugly feeling is with the existing installations of the mod - do the clients get a heads-up and the possibility to update the mod when the NetKAN/CKAN data changed, but the mod version itself didn't?

**Comment by AlexanderDzhoganov** [comment]
[*wink* *wink*](https://github.com/KSP-CKAN/CKAN-core/pull/41)

**Comment by SpaceTeph** [comment]
You guys are good XD

**Comment by SpaceTeph** [comment]
Ah, one issue pops up: since the mod name is generated by NetKAN, they have different IDs (PlanetShine vs PlanetShine-Config-Default) but the same display name in the CKAN GUI (PlanetShine). Whoops, didn't think of that.

**Comment by hakan42** [comment]
Yes, just update the "name"  attribute in the netkans. I had the same issue with the BoxSat addon, and seldomly using the GUI, did not discover it until after people started complaining in the forums :blush:

**Pull request merged**
