### PR TITLE
Update DepthMask netkan file in preparation for next patch

### PR DESCRIPTION
**Pull request by drewcassidy**
I'm about to push a new version of DepthMask with a more standard distribution layout, so this is to update the NetKAN to match

- https://forum.kerbalspaceprogram.com/index.php?/topic/185353-111-112-moduledepthmask-portable-holes-for-your-parts/
- https://github.com/drewcassidy/KSP-DepthMask
- https://spacedock.info/mod/2943/ModuleDepthMask

### CODE REVIEW

**Comment by drewcassidy** [comment]
Its possible I misunderstood how the netkan works, its only "read" when a new update is pushed, right?

**Comment by HebaruSan** [comment]
The netkan is read at updates for mods on SpaceDock, yes, but it is also read periodically in between updates in case anything has changed. So after we merge this pull request, it will be applied to whatever the current version is at that time. What we would usually do is wait until the new version is released, then merge.

**Comment by drewcassidy** [comment]
Understood. will let you know

**Comment by drewcassidy** [comment]
Update pushed

**Comment by HebaruSan** [comment]
Thanks for the update!

**Pull request merged**
