### PR TITLE
Add MalemuteRover

### PR DESCRIPTION
**Pull request by Olympic1**
Requested by @ArnePeirs for https://github.com/BobPalmer/CKAN/pull/6

### CODE REVIEW

**Comment by ArnePeirs** [comment]
Thx

**Comment by plague006** [comment]
Needs a rebuild after ref'ed PR is merged.

**Comment by plague006** [comment]
I don't get it.. @Olympic1 aka Arne Peirs writing a PR requested by @ArnePeirs aka TheOlympicOne...?

Needs a rebuild after ref'ed PR is merged.

**Comment by politas** [comment]
This will need to be rebased when the source is merged.

**Pull request merged**
