### PR TITLE
Update and rename BritishRockets.kerbalstuff to BritishRockets.netkan

### PR DESCRIPTION
**Pull request by TheWire**
Changed BritishRockets from KerbalStuff to GitHub, updated to 1.0.1.

### CODE REVIEW

**Comment by Dazpoet** [comment]
spec_version must be at least v1.4 for usage of the `find` keyword in the install stanza. Could you please bump the spec_version? :)

**Comment by TheWire** [comment]
OK fixed hopefully.

**Comment by politas** [comment]
Can you also remove the "version" line and the "download" line? Netkan will collect that information from Github automatically as you release new versions.

**Comment by politas** [comment]
Just have to trim off that last comma and all will be fine.

**Comment by pjf** [comment]
This is working for me! :)

```
$ ckan.exe show BritishRockets
British Rockets: Collection of British launch vehicles

Module info:
- version:	1.0.1
- authors:	TheWire
- status:	stable
- license:	CC-BY-NC-SA-4.0

Depends:
- KlockheedMartian-Gimbal

Provides:
- BritishRockets

Resources:
- homepage: http://www.curse.com/ksp-mods/kerbal/233347-british-rockets
- repository: https://github.com/TheWire/British_Rockets

Filename: B2296E8C-BritishRockets-1.0.1.zip

Showing 68 installed files:
- GameData/British Rockets
- GameData/British Rockets/Parts
- GameData/British Rockets/Parts/Black Arrow
- GameData/British Rockets/Parts/Black Arrow/ba_engine_bay
- GameData/British Rockets/Parts/Black Arrow/ba_engine_bay/ba_engine_bay_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_engine_bay/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_engine_bay/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_explosive_bolt
- GameData/British Rockets/Parts/Black Arrow/ba_explosive_bolt/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_explosive_bolt/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_explosive_bolt/test_tex2.dds
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_1
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_1/ba_fairing_1_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_1/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_1/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_2
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_2/ba_fairing_ 2_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_2/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_fairing_2/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_imp
- GameData/British Rockets/Parts/Black Arrow/ba_imp/imp_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_imp/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_imp/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_main_fuel
- GameData/British Rockets/Parts/Black Arrow/ba_main_fuel/ba_fuel_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_main_fuel/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_main_fuel/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_payload_decoupler
- GameData/British Rockets/Parts/Black Arrow/ba_payload_decoupler/ba_payload_decoupler_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_payload_decoupler/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_payload_decoupler/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_second_stage
- GameData/British Rockets/Parts/Black Arrow/ba_second_stage/ba_second_stage_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_second_stage/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_second_stage/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_separation_bay
- GameData/British Rockets/Parts/Black Arrow/ba_separation_bay/ba_separation_bay_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_separation_bay/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_separation_bay/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_siskin
- GameData/British Rockets/Parts/Black Arrow/ba_siskin/ba_sep_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_siskin/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_siskin/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_spin_table
- GameData/British Rockets/Parts/Black Arrow/ba_spin_table/ba_payload_sep_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_spin_table/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_spin_table/part.cfg
- GameData/British Rockets/Parts/Black Arrow/ba_waxwing
- GameData/British Rockets/Parts/Black Arrow/ba_waxwing/ba_waxwing_tex.dds
- GameData/British Rockets/Parts/Black Arrow/ba_waxwing/model.mu
- GameData/British Rockets/Parts/Black Arrow/ba_waxwing/part.cfg
- GameData/British Rockets/Parts/Engines
- GameData/British Rockets/Parts/Engines/Gamma
- GameData/British Rockets/Parts/Engines/Gamma/gamma_8_tex.dds
- GameData/British Rockets/Parts/Engines/Gamma/model.mu
- GameData/British Rockets/Parts/Engines/Gamma/part.cfg
- GameData/British Rockets/Parts/Engines/Gamma_2
- GameData/British Rockets/Parts/Engines/Gamma_2/ba_gamma_2_tex.dds
- GameData/British Rockets/Parts/Engines/Gamma_2/model.mu
- GameData/British Rockets/Parts/Engines/Gamma_2/part.cfg
- GameData/British Rockets/Readme.txt
- GameData/British Rockets/Real_Plume_British_Rockets.cfg
- GameData/British Rockets/RF_British_Rockets.cfg
- GameData/British Rockets/RO_BR_Black_Arrow.cfg
- GameData/British Rockets/RO_BR_Engines.cfg
- Ships/VAB
- Ships/VAB/Black Arrow  (Realism Overhaul).craft
- Ships/VAB/Black Arrow.craft
```

**Comment by pjf** [comment]
And eyeballing the original file, this all looks correct to me, so I'm merging with great thanks!

**Pull request merged**
