### PR TITLE
Add RemoteTech from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of tomekpiotrowski, to add [RemoteTech](https://spacedock.info/mod/520/RemoteTech) to CKAN.

Mod details:
    name = /mod/520/RemoteTech
    author = tomekpiotrowski
    description = **RemoteTech**

Community developed continuation of Kerbal Space Program's RemoteTech mod.

RemoteTech allows you to construct vast relay networks of communication satellites and remotely controlled unmanned vehicles. Your unmanned vessels require an uplink to a command station to be controlled. This adds a new layer of difficulty that compensates for the lack of live crew members.

[A detailed manual is available on-line](http://remotetechnologiesgroup.github.io/RemoteTech/).

Questions? Try the [KSP forum thread](http://forum.kerbalspaceprogram.com/threads/83305/).
    abstract = Community developed continuation of Kerbal Space Program's RemoteTech mod.
    license = GPLv2
    Homepage = http://remotetechnologiesgroup.github.io/RemoteTech/

Please direct questions about this pull request to [tomekpiotrowski](https://spacedock.info/profile/tomekpiotrowski).

### CODE REVIEW

**Comment by tomekpiotrowski** [comment]
RemoteTech is maintained by a new team now. We've created a new account for RT on spacedock and spacedock has submitted this PR for us. There already is an old RT netkan, that should probably be removed.

**Comment by politas** [comment]
Thanks, @tomekpiotrowski for the update. It's great to see RemoteTech available for KSP 1.1! It looks like the old Kerbalstuff entry we had was already referring to the new team, so I've copied over some of the details.

**Comment by tomekpiotrowski** [comment]
Thanks!

**Comment by Dazpoet** [comment]
It's been a long time since I last had RT installed but I seem to recall there being less .dlls back then, are all of these native to RT or are some fetched from elsewhere?

```
- GameData/RemoteTech/Plugins
- GameData/RemoteTech/Plugins/Assembly-CSharp-firstpass.dll
- GameData/RemoteTech/Plugins/Assembly-CSharp.dll
- GameData/RemoteTech/Plugins/KSPUtil.dll
- GameData/RemoteTech/Plugins/RemoteTech.dll
- GameData/RemoteTech/Plugins/UnityEngine.dll
- GameData/RemoteTech/Plugins/UnityEngine.UI.dll
```

**Comment by tomekpiotrowski** [comment]
Thank you for noticing.

They were mistakenly added to version 1.6.10. 1.6.11 that was released today does not contain them.

**Comment by Dazpoet** [comment]
New version does not show an overabundance of .dll files so I'm merging this now :+1:

**Pull request merged**
