### PR TITLE
Add GregroxMun's JupiteryJoolRecolor versions

### PR DESCRIPTION
**Pull request by politas**
The Homepage for this mod shows a couple of alternate recolor schemes, thus the choice for the provides/conflicts
Closes #4268

### CODE REVIEW

**Comment by politas** [comment]
Sent message to mod author to check for any unexpected issues.

**Comment by politas** [comment]
No reply, lets go with assumed consent due to Spacedock selection.

**Comment by Olympic1** [comment]
ping @GregroxMun

**Comment by Olympic1** [comment]
Still no reply so merging

**Pull request merged**
