### PR TITLE
RSS: Update netkan for next RSS

### PR DESCRIPTION
**Pull request by NathanKell**
Next RSS will have its cache files in its own folder, no need to deal with that.

**DO NOT MERGE UNTIL NEXT RSS**

### CODE REVIEW

**Comment by dbent** [comment]
You can use an override and just commit it now (staging changes is one of the main reasons it was created). Just replace `EXPECTED_VERSION_WITH_CHANGE` with, well, the version number you expect will have the change. Don't forget the leading `v` which it seems RSS has in its version number.

```json

{
  "x_netkan_override": [
    {
      "version": "<EXPECTED_VERSION_WITH_CHANGE",
      "override": {
        "install": [
          {
            "find"      : "RealSolarSystem",
            "install_to": "GameData"
          },
          {
            "find"      : "Cache",
            "install_to": "GameData/Kopernicus"
          }
        ]
      }
    },
    {
      "version": ">=EXPECTED_VERSION_WITH_CHANGE",
      "override": {
        "install": [
          {
            "find"      : "RealSolarSystem",
            "install_to": "GameData"
          }
        ]
      }
    }
  ]
}
```

**Comment by NathanKell** [comment]
@dbent Ah, I see! I'd prefer to avoid further overrides if possible--we'll have to add one for 1.1 anyway probably. But good to know!

**Comment by politas** [comment]
Once you have a new release, any old overrides can be removed - Netkan will only re-examine the latest release.

**Comment by NathanKell** [comment]
Ohh! Right. Thanks!

**Pull request merged**
