### PR TITLE
Revert "Add B9PartSwitch to Kerbalism deps"

### PR DESCRIPTION
**Pull request by steamp0rt**
Reverts KSP-CKAN/NetKAN#7109

### CODE REVIEW

**Comment by DasSkelett** [comment]
Context: https://github.com/KSP-CKAN/CKAN-meta/pull/1435 and 

As soon as I merge this, the bot reruns and generates the 2.2.0 .ckan.
If I delete it afterwards, it will generate it in 4 hours again.

Can you delete the version from spacedock? This prevents the bot from pulling it.

**Comment by steamp0rt** [comment]
Is there even a delete button on spacedock?

**Comment by DasSkelett** [comment]
I think another option is to freeze the 2.2.0.ckan. Not sure if this works though.

**Comment by DasSkelett** [comment]
Huh, no idea.

**Comment by DasSkelett** [comment]
I'll try to freeze it.

**Comment by DasSkelett** [comment]
image
Worked!
So what about the dependency? For what version(s) do you want it added or removed?

**Comment by steamp0rt** [comment]
all of em. I added em too early -- SirMortimer thought it'd be needed due to a bug in the Configure module, but he found a different way to do things

**Pull request merged**
