### PR TITLE
Add Extraplanetary Launchpads - No More Production from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of theRagingIrishman, to add [Extraplanetary Launchpads - No More Production](https://spacedock.info/mod/1085/Extraplanetary%20Launchpads%20-%20No%20More%20Production) to CKAN.

Mod details:
    name = /mod/1085/Extraplanetary%20Launchpads%20-%20No%20More%20Production
    author = theRagingIrishman
    abstract = This gets rid of some useless stuff in Extraplanetary Launchpads
    license = Released to the public domain
    Homepage = 
    description = This mod will remove all Extraplanetary Launchpad parts related to the production chain of RocketParts ie tanks, drills, refineries but will keep all parts related to the actual building of Rockets.

WARNING: If you don't have MKS or Kerbidan Dynamics or some other mod that replaces the production line, this mod will potato EL and make it useless.

Please direct questions about this pull request to [theRagingIrishman](https://spacedock.info/profile/theRagingIrishman).

### CODE REVIEW

**Comment by Dazpoet** [comment]
That should do it :)

Put UKS as a suggest since it's one of many options but I couldn't find whatever Kerbidan Dynamics is so I didn't add that.

**Comment by politas** [comment]
I think KeridianDynamicsVesselAssembly is what they mean. Max KSP 1.1.3

**Comment by Dazpoet** [comment]
Added it in the case of it becoming updated

**Comment by politas** [comment]
A lot of effort for one config file! Merged with thanks!

**Pull request merged**
