### PR TITLE
Update Quick... Mods

### PR DESCRIPTION
**Pull request by Olympic1**
Updated every Quick... mod except for `QuickStart` because @malahx didn't publish his mod on SpaceDock because it isn't updated for 1.0.5 yet.

`QuickHide` will install as `v3.03` but has the same zipfile as `v3.03a`, so added an epoch for it.

### CODE REVIEW

**Comment by politas** [comment]
These all build and install fine, but they all contain .version files we could be using.

**Comment by plague006** [comment]
Scratching my head as I look at the `spec_ver` from `QuickBrake.kerbalstuff`.

`QuickGoTo` should `suggests` `toolbar`.

**Comment by plague006** [comment]
`QuickIVA` should probably `suggests` `toolbar` based on `GameData/QuickIVA/Textures/BlizzyToolBar.dds`

**Comment by plague006** [comment]
Same for `QuickRevert` and `QuickScroll` (both install Blizzytoolbar textures)

**Comment by plague006** [comment]
Looks good to me, merge if you're cool with my commits.

**Comment by malahx** [comment]
Huge thanks for this, I've tried to do it some days ago, but with too many errors ... again thanks.

**Pull request merged**
