### PR TITLE
Add Surface Experiment Pack

### PR DESCRIPTION
**Pull request by politas**
Closes #2991
Use of BSD Simplified licence advised via PM on KSP forums. I have asked for that to be added to the OP on the forums.

### CODE REVIEW

**Comment by politas** [comment]
KerbalStuff down again?

**Comment by Olympic1** [comment]
Yep, for 14 hours already

**Comment by plague006** [comment]
@politas if/when you can, ping the author or check the thread or whatever for another download location?

**Comment by politas** [comment]
Github release is expected: http://forum.kerbalspaceprogram.com/index.php?/topic/77858-105surface-experiment-pack-full-release/&do=findComment&comment=2410627

**Comment by Olympic1** [comment]
@politas there is a SpaceDock release now: http://spacedock.info/mod/318/Surface%20Experiment%20Pack

**Comment by politas** [comment]
Let's see if that works, then.

**Pull request merged**
