### PR TITLE
Update KSPInterstellarExtended.netkan

### PR DESCRIPTION
**Pull request by sswelm**
4th try

### CODE REVIEW

**Comment by politas** [comment]
Unhandled Exception:
CKAN.FileNotFoundKraken: Trying to install InterstellarFuelSwitch 1.18, but it's not downloaded or download is corrupted

**Comment by Olympic1** [comment]
I just merged a fix for IFS

**Comment by Olympic1** [comment]
Works locally

**Comment by sswelm** [comment]
great work

**Pull request merged**
