### PR TITLE
Move to self-hosted for last NF mods

### PR DESCRIPTION
**Pull request by ChrisAdderley**
Changes the last 3 NF CKAN packages to self-hosted versions.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Just making sure, did you mean to remove NearFutureSolar's ModuleManager dependency? The forum thread still says,

> Dependencies (Required and Bundled)
> Module Manager

**Comment by ChrisAdderley** [comment]
It's not actually required anymore so it could be removed from the forum post/distribution. I've re-added it though, just as it's more work to go and get all those out than it is to update the CKAN file ;).

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Looks good, thanks for the updates.
One side note, you might want to update the licenses on SpaceDock, since these mods are still listed under the more permissive licenses there.

**Comment by ChrisAdderley** [comment]
I'll do that... sometime. I would hope that people understand that generally the forum thread and the zips themselves are the most authoritative.

**Pull request merged**
