### PR TITLE
Add Vaporo's Blue Galaxy Skybox from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Vaporo, to add [Vaporo's Blue Galaxy Skybox](https://kerbalstuff.com/mod/1413/Vaporo%27s%20Blue%20Galaxy%20Skybox) to CKAN.

Please direct questions about this pull request to [Vaporo](https://kerbalstuff.com/profile/Vaporo).

### CODE REVIEW

**Comment by politas** [comment]
This mod's installation instructions involve deleting files that don't belong to it. CKAN won't do that.

**Comment by plague006** [comment]
> Delete any other skyboxes you have installed.

To us, that's just a conflict with other skybox mods.

>Delete the files in the Texture Replacer/EnvMap folder (If you want the reflections on Kerbals' helmets.).

Users won't have the reflections on Kerbals' helmets. We can note that in the abstract if anyone thinks it'll be an issue.

**Comment by politas** [comment]
>To us, that's just a conflict with other skybox mods.
Do we have a "skybox" metamod set up, yet?

**Comment by plague006** [comment]
We do not.

**Pull request closed without merging**
