### PR TITLE
FASTCORPAutogarage

### PR DESCRIPTION
**Pull request by linuxgurugamer**
closes #4260

### CODE REVIEW

**Comment by politas** [comment]
Needs a dependency on RasterPropMonitor for full functionality, so we would normally include that.

Also, given the need for changes to the settings ffile, can we override the abstract to include a request to check the homepage for proper configuration?

**Comment by politas** [comment]
Do those "/n"s work in the client?

**Comment by linuxgurugamer** [comment]
Not sure.  I think so, but will be checking once it gets accepted.  If not, i'll redo it

**Comment by politas** [comment]
Just tested, and it does indeed work beautifully!
Merging with thanks!

**Pull request merged**
