### PR TITLE
StarshipExpansionProject: filter Spaces in case they move it

### PR DESCRIPTION
**Pull request by JonnyOThan**
SEP might consider moving the Spaces folder inside the normal location in GameData.  the StarshipExpansionProjectIVA.netkan already can handle this, but we need to exclude it from this one.

### CODE REVIEW

**Comment by SofieBrink** [comment]
Can confirm we might do this

**Review by HebaruSan — APPROVED** [review]
@JonnyOThan feel free to just merge stuff like this when you're happy with it.

**Comment by JonnyOThan** [comment]
> feel free to just merge stuff like this when you're happy with it.
I always wait to make sure I'm not doing something stupid :)

**Comment by JonnyOThan** [comment]
Uhhh I have no idea how or why I reverted this. Might have been a misclick.

**Comment by HebaruSan** [comment]
I think you just made a branch, no PR, not merged to master.

https://github.com/KSP-CKAN/NetKAN/tree/revert-10287-update/StarshipExpansionProject

GitHub has a button to do that somewhere, so a misclick sounds likely.

**Pull request merged**
