### PR TITLE
Update Kronkus.netkan

### PR DESCRIPTION
**Pull request by MrChumley**
Kronkus has been updated to work with latest Kopernicus.

### CODE REVIEW

**Comment by pjf** [comment]
@MrChumley : Hooray! Just one quick question:

- It looks like Kronkus is CC-0 licensed; this commit would change it to a CC-BY-NC-ND-4.0, is that intentional?

**Comment by MrChumley** [comment]
I would rather it be released under CC-0.

**Comment by MrChumley** [comment]
Will that work?

**Comment by pjf** [comment]
Yes it does! Merging with thanks!

```
Kronkus: Kronkus - A Kopernicus planet pack

Module info:
- version:	v1.0
- authors:	MrChumley
- status:	stable
- license:	CC0

Depends:
- Kopernicus
- ModuleManager

Provides:
- Kronkus

Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/132379
- kerbalstuff: https://kerbalstuff.com/mod/1152/Kronkus
- repository: http://github.com/MrChumley/Kronkus

Filename: A718222E-Kronkus-v1.0.zip

Showing 36 installed files:
- GameData/Kronkus
- GameData/Kronkus/Cache
- GameData/Kronkus/Eahpeh.cfg
- GameData/Kronkus/Kersex.cfg
- GameData/Kronkus/KronkNHPatch.cfg
- GameData/Kronkus/Kronkus.cfg
- GameData/Kronkus/Kronkus_Resources.cfg
- GameData/Kronkus/Kronkus_ScienceDefs.cfg
- GameData/Kronkus/LICENSE
- GameData/Kronkus/Meelo.cfg
- GameData/Kronkus/PluginData
- GameData/Kronkus/PluginData/Eahpeh.dds
- GameData/Kronkus/PluginData/Eahpeh_Biome.png
- GameData/Kronkus/PluginData/Kersex_Biome.png
- GameData/Kronkus/PluginData/Kersex_Height.dds
- GameData/Kronkus/PluginData/Meelo_Biome.png
- GameData/Kronkus/PluginData/Meelo_Height.dds
- GameData/Kronkus/PluginData/Sket_Biome.png
- GameData/Kronkus/PluginData/Sket_high.dds
- GameData/Kronkus/README.txt
- GameData/Kronkus/Rings
- GameData/Kronkus/Rings/Kronkus_ring.png
- GameData/Kronkus/Sketti.cfg
- GameData/Kronkus/Textures
- GameData/Kronkus/Textures/Eahpeh_Color.dds
- GameData/Kronkus/Textures/Eahpeh_Normal.dds
- GameData/Kronkus/Textures/Kersex_Color.dds
- GameData/Kronkus/Textures/Kersex_Normal.dds
- GameData/Kronkus/Textures/Kronkus.dds
- GameData/Kronkus/Textures/Meelo_Color.dds
- GameData/Kronkus/Textures/Meelo_Normal.dds
- GameData/Kronkus/Textures/Sketti.dds
- GameData/Kronkus/Textures/Sketti_Normal.dds
- GameData/Kronkus/Textures/ramp_blue.png
- GameData/Kronkus/celesbod.cfg
- GameData/Kronkus/license.txt
```

**Pull request merged**
