### PR TITLE
Fix compatibility with newest version of FirespitterCore

### PR DESCRIPTION
**Pull request by Dazpoet**

### CODE REVIEW

**Comment by techman83** [comment]
Hmm - why is it doing that
```
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
```

**Comment by Dazpoet** [comment]
Argh it's because I've changed how firespitterCore looks and forgot to remove a file.

**Comment by techman83** [comment]
That looks better!

**Comment by Dazpoet** [comment]
That should do it, to bad we can't use the .version file but I don't really want to stuck mucking about with the firespittercore package right now since it was _just_ finally fixed.

We should probably set up a .netkan indexing these things from github instead since it seems there's a newer version of firespitter there now. Let's give it a few days and see if it shows up on KS aswell first though.

**Pull request merged**
