### PR TITLE
Freeze all kerbalstuff mods - Closes #3106

### LINKED ISSUE #3106: Indexer Timing out Due to KerbalStuff mods
It's worth Freezing (or maybe changing extension to .kerbalstuff for easier migration) all the KerbalStuff mods.

### PR DESCRIPTION
**Pull request by techman83**
This will alleviate the immediate problem of Netkan trying to index KerbalStuff mods.

### CODE REVIEW

**Comment by techman83** [comment]
I cancelled the build, it'll fail trying to feed Netkan a bunch of files that don't have the Netkan extension.

**Comment by plague006** [comment]
My concern is a purely selfish one.. My process for editing netkans makes renaming files a PITA.. but if there's a technical reason to change the extension I'll merge this in a second.

**Comment by plague006** [comment]
Just saw https://github.com/KSP-CKAN/NetKAN/issues/3106, that changes things. =)

**Comment by techman83** [comment]
Haha :-)

**Pull request merged**
