### PR TITLE
Create JNSQ.netkan

### PR DESCRIPTION
**Pull request by Galileo88**
https://raw.githubusercontent.com/Galileo88/JNSQ/master/CKAN/JNSQ.netkan

ckan compat add 1.6

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by DasSkelett** [comment]
@Galileo88 little typo in the abstract, double 'a':
`"A a 1/4 real scale, reimagined stock planet pack"`

**Comment by HebaruSan** [comment]
The validator bot doesn't have enough disk space to download this module.

> 259920 [1] FATAL CKAN.NetKAN.Program (null) - Disk full. Path 

RationalResources should be indexed independently.

**Comment by Galileo88** [comment]
> RationalResources should be indexed independently.

That's fine. We can do that

**Comment by HebaruSan** [comment]
@techman83, how much disk capacity does the NetKAN-bot have? This mod is 1.8 GB with five releases in the past month, and I want to make sure we're not going to gum up the works even further here.

@Galileo88, the current `asset_match` value would match either one of these:
image
This would be safer, assuming you keep the filenames the same:

```json
   "$kref":"#/ckan/github/Galileo88/JNSQ/asset_match/JNSQ\\..*.zip",
```

**Comment by HebaruSan** [comment]
This is invalid syntax. JSON only allows one instance of a given property per object (that's why this is an array!):

```json
   "provides":[  
      "EnvironmentalVisualEnhancements-Config"
   ],
   "provides":[  
      "Scatterer-sunflare"
   ],
   "provides":[  
      "DistantObject-config"
   ],
   "provides":[  
      "PlanetShine-Config"
   ],
```

Fix:

```json
   "provides":[
      "EnvironmentalVisualEnhancements-Config",
      "Scatterer-sunflare",
      "DistantObject-config",
      "PlanetShine-Config"
   ],
```

**Comment by Galileo88** [comment]
Oh see I I had it set like that initially, but It was failing so I bliondly changed it thinking it would fix the issue. 
Ill get it right eventually

**Comment by Galileo88** [comment]
Alright, I made those recommended changes.

**Comment by DasSkelett** [comment]
There's a wild mix of tabs and spaces in the netkan file (in the `conflicts` and the `suggests` nodes), not critical, but you might want to have it consistent.

**Comment by HebaruSan** [comment]
Be careful with versions like this.
image

0.6.5 is between 0.6 and 0.7, but 0.65 is later than both, because 65 > 7.

**Comment by Galileo88** [comment]
> 0.6.5 is between 0.6 and 0.7, but 0.65 is later than both, because 65 > 7.

Fair enough. Do you suggest I remove those?

**Comment by HebaruSan** [comment]
> Fair enough. Do you suggest I remove those?

No, it won't be a problem unless you want us to index that version. That was just an FYI for future releases.

**Comment by Galileo88** [comment]
> > Fair enough. Do you suggest I remove those?
> 
> No, it won't be a problem unless you want us to index that version. That was just an FYI for future releases.

gotcha. thanks for letting me know

**Comment by Galileo88** [comment]
Regarding indexing Rational Resources separately, I will just keep it as it is for now and change it once Jadeifmaar gets it indexed

**Comment by HebaruSan** [comment]
I ran this locally to get around the bot's storage limit. Result shared below for inspection and in case anyone else wants to try a test install.

<details><summary>Generated metadata</summary>

```json
{
    "spec_version": "v1.4",
    "identifier": "JNSQ",
    "name": "JNSQ",
    "abstract": "A a 1/4 real scale, reimagined stock planet pack",
    "author": "Team Galileo",
    "license": "CC-BY-NC-ND-3.0",
    "release_status": "stable",
    "resources": {
        "homepage": "https://forum.kerbalspaceprogram.com/index.php?/topic/184880-*",
        "repository": "https://github.com/Galileo88/JNSQ"
    },
    "version": "0.7",
    "ksp_version_min": "1.7.0",
    "ksp_version_max": "1.7.2",
    "localizations": [
        "en-us",
        "es-us",
        "es-mx",
        "ja",
        "ru",
        "zh-cn"
    ],
    "provides": [
        "EnvironmentalVisualEnhancements-Config",
        "Scatterer-sunflare",
        "DistantObject-config",
        "PlanetShine-Config"
    ],
    "depends": [
        {
            "name": "ModuleManager"
        },
        {
            "name": "Kopernicus"
        }
    ],
    "suggests": [
        {
            "name": "Scatterer"
        },
        {
            "name": "EnvironmentalVisualEnhancements"
        },
        {
            "name": "DistantObject"
        },
        {
            "name": "PlanetShine"
        },
        {
            "name": "Strategia"
        },
        {
            "name": "FinalFrontier"
        },
        {
            "name": "TextureReplacer"
        }
    ],
    "conflicts": [
        {
            "name": "EnvironmentalVisualEnhancements-Config"
        },
        {
            "name": "StockVisualEnhancements"
        },
        {
            "name": "Spectra"
        },
        {
            "name": "AstronomersVisualPack"
        },
        {
            "name": "SciFiVisualEnhancements"
        },
        {
            "name": "DistantObject-RealSolarSystem"
        },
        {
            "name": "PlanetShine-Config"
        },
        {
            "name": "CustomBarnKit-RO"
        }
    ],
    "install": [
        {
            "find": "GameData/JNSQ",
            "install_to": "GameData",
            "comment": "This correctly installs JNSQ"
        },
        {
            "find": "GameData/RationalResources",
            "install_to": "GameData",
            "comment": "This correctly installs Rational Resources for JNSQ"
        }
    ],
    "download": "https://github.com/Galileo88/JNSQ/releases/download/0.7/JNSQ.0.7.zip",
    "download_size": 1917357925,
    "download_hash": {
        "sha1": "8B29450EE7E7C2686CEC19D1809CB8BAEAE3BFE7",
        "sha256": "5F7B506DB7FA582E4F7A1615A0E7A38331C69210602659BCBE5A71B1C2CCBD44"
    },
    "download_content_type": "application/zip",
    "x_generated_by": "netkan"
}

```
</details>

**Comment by HebaruSan** [comment]
Is "es-us" (Spanish in the USA) the intended locale, or is that meant to be "es-es" (Spanish in Spain)? I guess it's not impossible but I'm more used to seeing "es-es".

**Comment by Galileo88** [comment]
Dang it, I thought I pushed the change to fix the double “a” lol

**Comment by HebaruSan** [comment]
> Dang it, I thought I pushed the change to fix the double “a” lol

Hmm, you did, and I confirmed it. Assume that problem is on our side for now, I'll see if I can figure out what's happening...

**Comment by HebaruSan** [comment]
Test install with all suggestions went smoothly:

image

**Comment by HebaruSan** [comment]
Looks good overall. Still need confirmation that indexing this won't break the bot, and proper handling of RationalResources dependency.

**Comment by techman83** [comment]
The system cleans itself up over time, but there were some old images hanging around. So I have purged some old stuff and run it again:

```
JNSQ 0.7 requires Kopernicus but it is not listed in the index, or not available for your version of KSP.
```

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Oh right. ModularFlightIntegrator still only supports up to KSP 1.6 (but other modders are happily bundling it for 1.7). One moment...

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
@Galileo88, RationalResources is indexed now. You can replace the install stanza with a proper `depends`.

**Comment by steamp0rt** [comment]
Nice

**Comment by Galileo88** [comment]
Let me know if there is anything else I need to do for this.

**Comment by HebaruSan** [comment]
@Galileo88, yes: RationalResources is indexed now. You can replace the install stanza with a proper depends.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Looks good now!

**Comment by yalov** [comment]
@Galileo88 Does it also provide Kronometer.dll, and  more CKAN-way is to filter it and add as depends?
Does Sigma88LoadingScreens conflict with LGG Loading Screen mod?
Also forum page has many recommends for the JNSQ

**Comment by HebaruSan** [comment]
Good point, the `JNSQ_Plugins` folder should probably be filtered out.

**Comment by Galileo88** [comment]
myrocksarebiggerthanyourrocks.dll needs to stay. I don't care what else is added or changed. I'm not in a position to make those changes at the moment. It will have to be don't later tonight

**Comment by Galileo88** [comment]
> @Galileo88 Does it also provide Kronometer.dll, and more CKAN-way is to filter it and add as depends?
> Does Sigma88LoadingScreens conflict with LGG Loading Screen mod?
> Also forum page has many recommends for the JNSQ

I think i have addressed all of this in the latest push to the netkan. 

* Kronometer is provided 
* Sigma Loading Screens disables itself when LGG Loading screens is installed
* And I have added as many of the suggested mods as I could

**Pull request merged**
