### PR TITLE
Add KSRSS

### LINKED ISSUE #10158: [Mod] KSRSS
image

- <https://gitlab.com/ksrss/KSRSS/-/releases>
- <https://gitlab.com/ksrss/KSRSS/-/tree/reborn>
- <https://github.com/KerbalFrench/KSRSS-Textures/releases>
- <https://forum.kerbalspaceprogram.com/topic/192818-beta-ksrss-07-kerbin-or-x25-sized-rss/>

### PR DESCRIPTION
**Pull request by DeltaDizzy**
- <https://gitlab.com/ksrss/KSRSS/-/releases>
- <https://gitlab.com/ksrss/KSRSS/-/tree/reborn>
- <https://github.com/KerbalFrench/KSRSS-Textures/releases>
- <https://forum.kerbalspaceprogram.com/topic/192818-beta-ksrss-07-kerbin-or-x25-sized-rss/>
- Should I add suggestions? If so, how many/which ones?
- Much review wanted!

Fixes #10158.

### CODE REVIEW

**Comment by DeltaDizzy** [comment]
It seems that `x_netkan_gitlab.use_source_archive: true` doesn't actually work or I don't understand how it is supposed to be used?

**Comment by HebaruSan** [comment]
> It seems that `x_netkan_gitlab.use_source_archive: true` doesn't actually work or I don't understand how it is supposed to be used?

Yeah, `x_netkan_gitlab` is an object. I pushed a commit showing the correct usage.
 
Please don't merge this yet. It's not ready; the latest changes are on a separate branch which hasn't had a release made yet.

**Comment by JonnyOThan** [comment]
The reborn version does not depend on external textures.

**Comment by HebaruSan** [comment]
Let's re-open this if a usable release actually happens.

**Pull request closed without merging**
