### PR TITLE
Add Simple Realism from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Krakenfour, to add [Simple Realism](https://kerbalstuff.com/mod/1205/Simple%20Realism) to CKAN.

Please direct questions about this pull request to [Krakenfour](https://kerbalstuff.com/profile/Krakenfour).

### CODE REVIEW

**Comment by vosechu** [comment]
@plague006 i'd like to help with these. How do you annotate when you've contacted the person on kerbalstuff? Do you add the inprogress tag?

**Comment by plague006** [comment]
I usually just leave it in these PR comments. Ex. a link to a post I made in a mod's KSP forum thread and a description of what information I need(ed).

**Comment by vosechu** [comment]
Perfect. Thanks @plague006

**Comment by plague006** [comment]
Closed by https://github.com/KSP-CKAN/NetKAN/pull/2465

**Pull request closed without merging**
