### PR TITLE
Added RaceKerbol

### PR DESCRIPTION
**Pull request by pjf**
# Waiting on 1.14 release

Depends upon KSP-CKAN/CKAN#1360 .

Attn @Lyneira.

### CODE REVIEW

**Comment by pjf** [comment]
Obviously v1.14 isn't out yet, but here's what we get on my branch:

```
{
    "spec_version": "v1.14",
    "identifier": "RaceKerbol",
    "name": "Race Kerbol",
    "abstract": "Race Kerbol (the sun) in a series of scenarios from start to finish while trying to keep as close to the ground as possible to get a higher score! Your craft is solar powered, so make sure to keep your panels exposed to the sun as much as possible.",
    "license": "CC-BY-NC-SA",
    "comment": "Contains both GPL and CC-BY-NC-SA sections",
    "ksp_version": "1.0.4",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/131060",
        "repository": "https://github.com/Lyneira/RaceKerbol"
    },
    "depends": [
        {
            "name": "ModuleManager"
        },
        {
            "name": "KerbalFoundries"
        }
    ],
    "install": [
        {
            "file": "saves/scenarios",
            "install_to": "Scenarios"
        },
        {
            "file": "GameData/RaceKerbol",
            "install_to": "GameData"
        }
    ],
    "version": "v1.0",
    "author": "Lyneira",
    "download": "https://github.com/Lyneira/RaceKerbol/releases/download/v1.0/RaceKerbol-1.0.zip",
    "download_size": 50974,
    "x_generated_by": "netkan"
}
```

**Comment by pjf** [comment]
This should be unblocked, since the feature is now in release. :)

**Comment by pjf** [comment]
Here's what I get with the current `netkan.exe` build:

```
$ ckan.exe show RaceKerbol
Race Kerbol: Race Kerbol (the sun) in a series of scenarios from start to finish while trying to keep as close to the ground as possible to get a higher score! Your craft is solar powered, so make sure to keep your panels exposed to the sun as much as possible.

Module info:
- version:	v1.2.2
- authors:	Lyneira
- status:	stable
- license:	CC-BY-NC-SA

Depends:
- ModuleManager
- KerbalFoundries

Provides:
- RaceKerbol

Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/131060
- repository: https://github.com/Lyneira/RaceKerbol

Filename: 27C8FFB6-RaceKerbol-v1.2.2.zip

Showing 15 installed files:
- saves/scenarios/scenarios
- saves/scenarios/scenarios/Race Kerbol 01 - Westbound.sfs
- saves/scenarios/scenarios/Race Kerbol 02 - Desert Pass.sfs
- saves/scenarios/scenarios/Race Kerbol 03 - Island Hop.sfs
- GameData/RaceKerbol
- GameData/RaceKerbol/Parts
- GameData/RaceKerbol/Parts/atmoPlasmaEngine.cfg
- GameData/RaceKerbol/Parts/radialFlatSolarPanelx16.cfg
- GameData/RaceKerbol/Parts/radialFlatSolarPanelx4.cfg
- GameData/RaceKerbol/Parts/Repulsor.cfg
- GameData/RaceKerbol/PluginData
- GameData/RaceKerbol/PluginData/RaceKerbol
- GameData/RaceKerbol/PluginData/RaceKerbol/config.xml
- GameData/RaceKerbol/RaceKerbol.dll
- GameData/RaceKerbol/RK.png
```

**Comment by Dazpoet** [comment]
Some discussion on irc about this but the problem is that Jenkins does not seem to have access to ckan 1.14 and as such cannot validate this file.

**Comment by techman83** [comment]
Jenkins is happy now :D - LGTM

**Pull request merged**
