### PR TITLE
Update DeadlyReentry

### PR DESCRIPTION
**Pull request by dbent**
- Use vref
- Add dependency on ModularFlightIntegrator
- Add install stanza

### CODE REVIEW

**Comment by Blu3wolf** [comment]
Seems you beat me to it by a minute... XD

**Comment by Blu3wolf** [comment]
Also, you are missing a dependency.

**Comment by Blu3wolf** [comment]
and it seems I was missing an install stanza. Guess we both missed stuff!

**Comment by dbent** [comment]
Thanks, added `ModuleManager` as a dependency.

**Comment by Blu3wolf** [comment]
Which I believe makes this and #1237 pretty much identical.

**Comment by Dazpoet** [comment]
Did Jenkins stop working again? -.-

**Comment by mgsdk** [comment]
Looking at the build queue, I think it went belly up yes.

**Comment by Dazpoet** [comment]
Can someone confirm this working under linux so we won't kill a bot by mistake by merging it? :)

**Comment by mgsdk** [comment]
My custom build netkan will generate a ckan file, which CKAN will happily install for a clean KSP 1.0.2 install. I have not tested it inside KSP.

**Comment by mgsdk** [comment]
ckan file for reference:
```
{
    "spec_version": 1,
    "identifier": "DeadlyReentry",
    "name": "Deadly Reentry Continued",
    "abstract": "Makes re-entry much more dangerous",
    "license": "CC-BY-SA",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/54954",
        "repository": "https://github.com/Starwaster/DeadlyReentry"
    },
    "depends": [
        {
            "name": "ModuleManager"
        },
        {
            "name": "ModularFlightIntegrator"
        }
    ],
    "install": [
        {
            "file": "DeadlyReentry",
            "install_to": "GameData"
        }
    ],
    "author": "Starwaster",
    "version": "v7.0.1",
    "download": "https://github.com/Starwaster/DeadlyReentry/releases/download/v7.0.1/DeadlyReentry_7.0.1_The_Melificent_Edition.zip",
    "x_generated_by": "netkan",
    "download_size": 1420950,
    "ksp_version_min": "1.0.0",
    "ksp_version_max": "1.0.2"
}
```

**Pull request merged**
