### PR TITLE
Add 77 Racing Wheels (fixed KerbalStuffBot submission)

### PR DESCRIPTION
**Pull request by politas**
Replaces #2881. Tests ok on my Netkan

### CODE REVIEW

**Comment by politas** [comment]
This is working fine for me locally, so I don't know why it's failing here. any ideas?

**Comment by politas** [comment]
mono ckan.exe show 77RacingWheels
77 Racing Wheels: Adjusted wheels with a powerful racing sound for getting somewhere in a hurry.

Module info:
- version:	1.0
- authors:	Azimech
- status:	stable
- license:	LGPL-3.0

Depends:
- RoverWheelSounds
- ModuleManager

Provides:
- 77RacingWheels

Resources:
- kerbalstuff: https://kerbalstuff.com/mod/1369/77%20Racing%20Wheels

Filename: FE0C5B77-77RacingWheels-1.0.zip

Showing 8 installed files:
- GameData/77Industries
- GameData/77Industries/77Racing
- GameData/77Industries/77Racing/type1.wav
- GameData/77Industries/77Racing/type2.wav
- GameData/77Industries/77Racing/wheels.cfg
- GameData/77Industries/77Racing/wheelsound.cfg
- GameData/77Industries/Flags
- GameData/77Industries/Flags/77Indus.png

**Comment by pjf** [comment]
From [the test output](http://ci.ksp-ckan.org/job/NetKAN/1615/console) (Details -> console under "all checks have failed" below):

```
#   Failed test '77RacingWheels: CKAN identifers must consist only of letters, numbers, and dashes, and must start with a letter.'
#   at t/metadata.t line 26.
#                   '77RacingWheels'
#     doesn't match '(?^:^[A-Za-z][A-Z-a-z0-9-]*$)'
```

It looks like our spec says that  identifiers can't start with numbers. Obviously our code *can* handle that, because we can inflate and install just fine, but the spec has been written in a pretty conservative way. (We can change the mod identifier, or change the spec, although changing the identifier is easier.)

**Comment by politas** [comment]
I think we should change the spec, unless there's a good argument against it.

**Comment by plague006** [comment]
`Seven7...` as an identifier is a bit misleading/misrepresentative of the mod. It's supposed to be 77 as in the numeral seventy-seven. I would put `RacingWheels` forward. If that change is made this can be merged at will.

**Comment by politas** [comment]
Do we know why the test doesn't match the spec?

**Pull request merged**
