### PR TITLE
Add vref and update authors for NRAP

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Unclear on why `1.1.99` is being replaced with `1.1.0` when `build.sh` says `KSP_VERSION_DEFAULT="1.1.2"`.

**Comment by techman83** [comment]
We should remove those testing files from NetKAN/CKAN-meta, all the build scripts live [here](https://github.com/KSP-CKAN/xKAN-meta_testing) now.

**Comment by techman83** [comment]
LGTM, merging with thanks!

**Comment by plague006** [comment]
That explains that.

**Pull request merged**
