### PR TITLE
RN dependency update anim dec fix

### PR DESCRIPTION
**Pull request by raidernick**
-Fix animated deocuplers to mark as compatible with 1.1.3 which it is.
-Remove x86 and x64 versions as he got rid of these once 1.1 dropped,
there is only 1 updated version for x64 and x86

### CODE REVIEW

**Comment by politas** [comment]
Can you add new AnimatedDecouplers-x64.frozen and AnimatedDecouplers-x86.frozen files?

**Comment by raidernick** [comment]
@politas did i do that correctly?

**Comment by politas** [comment]
That looks fine to me, but Jenkins doesn't seem to be finding the new netkan. I'll test it when I get home.

**Comment by politas** [comment]
Looks good to me. Merging with thanks!

**Pull request merged**
