### PR TITLE
TACLS - New Maintainer

### LINKED ISSUE #3960: TACLS maintainer change
KSP-RO group ( @danfarnsy in particular) has taken over maintenance of TACLS.
We have released a temporary, 1.1.2 compatible version, and will soon release a fuller version.
Going forward the kref should point to https://github.com/KSP-RO/TacLifeSupport ( in particular the new KSP1.1.2 release is https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.11.3 ) but all old releases should point to their old locations.

Can that be done?

### PR DESCRIPTION
**Pull request by politas**
TAC Life Support has been taken over by the KSP-RO group
Closes #3960 
Closes #3962

### CODE REVIEW

**Comment by NathanKell** [comment]
Thank you for this. I evidently operated under the faulty assumption that the text of the .frozen netkan was still correct, and further that the 'author' field described the current maintainer, rather than the history of prior authors.

**Comment by politas** [comment]
That would only be the case if this were a fork of the original, rather than a takeover. (Though it would still be better to maintain the previous author details)

**Comment by NathanKell** [comment]
Ah, I see.

**Comment by NathanKell** [comment]
Ah, the above comment was supposed to be @plague006 . Sorry to you both!

**Comment by plague006** [comment]
No apologies needed, thanks for helping us keep the metadata up to date.

**Comment by plague006** [comment]
Still has no `name`.

**Pull request merged**
