### PR TITLE
Split EVE core mod and default configuration

### PR DESCRIPTION
**Pull request by SpaceTeph**

### CODE REVIEW

**Comment by hakan42** [comment]
Ah, that failure might be because the EVE-LR and EVE-HR netkan files did not run successfully through the netkan-bot yet.

I'll check what their issue is.

**Comment by hakan42** [comment]
o.k., now we have them, but they are marked 0.25 (hardcoded in the netkan, do you know what the current state of the addon is? 0.90 compatible yet?)

**Comment by SpaceTeph** [comment]
AFAIK the mod is compatible for all versions from 0.24 up, so it works under 0.90 (tested it myself too). That is why I have changed the ksp_version field to ksp_version_min in the files of the pull request, BTW.

**Comment by hakan42** [comment]
By the way, @SpaceTeph , thousand thanks to you for making my .90 installation beautiful again :smile:

**Comment by SpaceTeph** [comment]
@hakan42 That is the whole goal! I was tired of having to manage that stuff outside of CKAN. :smiley:
Now that the mods that are required are split, I'm working on Astronomer's Pack. Looking good.

**Comment by TeddyDD** [comment]
Somethig is wrong
```
Module "Environmental Visual Enhancements" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/EnvironmentalVisualEnhancements/Plugins/CityLights.dll
Installing Mod : EnvironmentalVisualEnhancements-Config-Default 7-4
Owning Mod     : EnvironmentalVisualEnhancements
CKAN Version   : v1.5.6-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!
```

**Comment by SpaceTeph** [comment]
@TeddyDD: I had to make EnvironmentalVisualEnhancements and EnvironmentalVisualEnhancements-HR/-LR swap roles and install directories. You will need to uninstall both (and EnvironmentalVisualEnhancements-Config-Default if you still have it) and reinstall them for everything to work, sadly. It's a breaking change. Sorry about that.

**Comment by TeddyDD** [comment]
Strange. I don't have this mods installed so I have nothing to uninstall

**Comment by SpaceTeph** [comment]
I assume CKAN has some kind of issue where mods that are removed from the repository can't do a clean uninstall. EnvironmentalVisualEnhancements-Config-Default was removed in this way, and in its first buggy version it did install stuff under GameData/EnvironmentalVisualEnhancements, so maybe that's what happened to you.

Please try a
  ckan remove EnvironmentalVisualEnhancements-Config-Default
in the console. If this doesn't work, just remove GameData/EnvironmentalVisualEnhancements and GameData/BoulderCo, if it exists, by hand. EVE should then install.

**Comment by TeddyDD** [comment]
I had neither EnvironmentalVisualEnhancements-Config-Default and BoulderCo installed. Now I installed Astronomer's Clouds and Eve and It seems working

**Pull request merged**
