### PR TITLE
Update NavballDockingIndicator.netkan

### PR DESCRIPTION
**Pull request by politas**
Updated Title to match Forum Thread, set force_v, bumped KSP version max. This has been tested Ok in 1.0.5 by myself and others.

### CODE REVIEW

**Comment by plague006** [comment]
There is no `title`, what you likely mean is `name`. With that said, the `name` scraped from KerbalStuff is `Navball Docking Alignment Indicator ` which is verbatim what you want to hardcode the `name` to. There's no need to hardcode something we scrape dynamically. The other 3 changes get a +1 from me.

**Comment by politas** [comment]
Well, it's showing up as "Simple Docking Indicator by mic_e" in my CKAN. Looks like it must be grabbing that from v5. CKAN's column population is truly weird.

**Comment by plague006** [comment]
Lines 5+6 should be removed (no hardcoded ksp_versions in the main metadata). Line 7: `"x_netkan_override" : [` has an opening square bracket but there's no associated closing bracket on line 15/16.

**Comment by politas** [comment]
Can you do a refresh? That's not what I'm seeing at all. Lines 5+6 are:
5:     
6:     "resources" :
And " x_netkan_override" : is on line 22

**Comment by plague006** [comment]
Totally my mistake, was looking at this and #2794 in side by side tabs and mistook them for the same PR. Merging this with my thanks.

**Pull request merged**
