### PR TITLE
Add Roster Manager from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Papa_Joe, to add [Roster Manager](https://kerbalstuff.com/mod/931/Roster%20Manager) to CKAN.

Please direct questions about this pull request to [Papa_Joe](https://kerbalstuff.com/profile/Papa_Joe).

### CODE REVIEW

**Comment by Dazpoet** [comment]
I'm assuming that the DFInterface.dll is a .dll file for interactions with the DeepFreeze mod? @PapaJoesSoup is that correct or is it from some other mod and should be installed as a dependency?

**Comment by PapaJoesSoup** [comment]
Yes.  The dll is a locally reference-able object that provides for connectivity as well as an interface to DeepFreeze.  This is similar to Ship Manifest and ConnectedLivingSpace where CLSInterface.dll provides a similar object.

**Comment by Dazpoet** [comment]
So DeepFreeze is now in CKAN so I'm returning to this. I noticed that DeepFreeze also installs DFInterface.dll. Is it enough to have it installed by that mod so we can filter it out of this one or does it need to be installed with every mod for some reason? :)

**Comment by PapaJoesSoup** [comment]
It is a locally referenced resource much like CLSInterface.dll in ConnectedLivingSpace.

It contains the code needed to create the soft dependency to the Deepfreeze.dll. and provides interfaces to objects contained in the DeepFreeze.dll.

So it is necessary for every mod that integrates with DeepFreeze.

as an example, in ShipManifest, I have CLSInterface.dll, which is also contained in ConnectedLivingSpace.  However, since it is referenced locally in the build, the namespace is contained in a using directive, so without it, the code will break.

This could have been done like Toolbar where you "embed" the toolbar wrapper into your code under your own namespace, but the author chose this path instead.

I have also created such an interface dll in Ship Manifest for other modders to use, and DeepFreeze uses this dll for their purposes to integrate into my Ship Manifest mod.

**Comment by plague006** [comment]
As the author stated DFInterface.dll must be included, I added this to  #1775 to get resolved.

**Comment by plague006** [comment]
This seems ready to merge as-is. All files in archive are needed, and it passes jenkins.

**Comment by PapaJoesSoup** [comment]
Thanks for staying on top of this.   Indeed, all fires are needed.  They are NOT inclusions of dependent mods.  The inclusion of these files PREVENT dependencies on those mods...

**Comment by dbent** [comment]
Tested manually, merging. Thanks.

**Pull request merged**
