### PR TITLE
Add Odysseus Planet Pack for Kopernicus from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Thomas988, to add [Odysseus Planet Pack for Kopernicus](https://kerbalstuff.com/mod/475/Odysseus%20Planet%20Pack%20for%20Kopernicus) to CKAN.

Please direct questions about this pull request to [Thomas988](https://kerbalstuff.com/profile/Thomas988).

### CODE REVIEW

**Comment by TeddyDD** [comment]
I don't think this gonna work like this :wink:

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by hakan42** [comment]
Kopernicus itself is in pre-alpha state on github with to real releases.

With multiple-repo support, we could set up a prerelease index for Kopernicus and move the .netkan later to the main repository.

**Comment by hakan42** [comment]
o.k., forget the comment above, Kopernicus has not even binary releases yet, so setting up a prerelease index would not make sense.

**Pull request closed without merging**
