### PR TITLE
Create spacebus.netkan

### PR DESCRIPTION
**Pull request by Kunedo83**

### CODE REVIEW

**Comment by HebaruSan** [comment]
There's a validation problem, but we can't see the output due to #6856.

**Comment by Kunedo83** [comment]
the domain incident is by spacedock? if it is by spacedock change the href of spacedock by the one of github or ksp avc

**Comment by DasSkelett** [comment]
No it's CKAN's domain. But we can't view the output log, see https://github.com/KSP-CKAN/NetKAN/issues/6856#issuecomment-442703250. So we need to wait until this is fixed to be able to tell what's the problem.

**Comment by Kunedo83** [comment]
okey thx

**Comment by techman83** [comment]
```
Validating NetKAN/SpaceBus.netkan...
NetKAN/SpaceBus.netkan:2:21: Error: Unknown identifier: u'v1'
   |  At line 2, column 21, offset 23
NetKAN/SpaceBus.netkan:2:23: Error: Bad number, decimal point must be preceded by at least one digit: u'.4'
   |  At line 2, column 23, offset 25
NetKAN/SpaceBus.netkan:2:23: Error: Values must be separated by a comma
   |  At line 2, column 23, offset 25
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:2:23: Error: JSON only permits string literals as object properties (keys)
   |  At line 2, column 23, offset 25
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:2:23: Error: Missing value for object property, expected ":"
   |  At line 2, column 23, offset 25
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:3:19: Error: Can not decode value starting with character u':'
   |  At line 3, column 19, offset 48
NetKAN/SpaceBus.netkan:3:21: Info: Recovering parsing after character u'"'
   |  At line 3, column 21, offset 50
NetKAN/SpaceBus.netkan:3:21: Info: Recovering parsing after character u'"'
   |  At line 3, column 21, offset 50
NetKAN/SpaceBus.netkan:3:21: Error: Values must be separated by a comma
   |  At line 3, column 21, offset 50
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:3:21: Error: Missing value for object property, expected ":"
   |  At line 3, column 21, offset 50
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:4:19: Error: Can not decode value starting with character u':'
   |  At line 4, column 19, offset 81
NetKAN/SpaceBus.netkan:4:21: Info: Recovering parsing after character u'"'
   |  At line 4, column 21, offset 83
NetKAN/SpaceBus.netkan:4:21: Info: Recovering parsing after character u'"'
   |  At line 4, column 21, offset 83
NetKAN/SpaceBus.netkan:4:21: Error: Values must be separated by a comma
   |  At line 4, column 21, offset 83
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:4:21: Error: Missing value for object property, expected ":"
   |  At line 4, column 21, offset 83
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:5:16: Error: Can not decode value starting with character u':'
   |  At line 5, column 16, offset 124
NetKAN/SpaceBus.netkan:5:18: Info: Recovering parsing after character u'"'
   |  At line 5, column 18, offset 126
NetKAN/SpaceBus.netkan:5:18: Info: Recovering parsing after character u'"'
   |  At line 5, column 18, offset 126
NetKAN/SpaceBus.netkan:5:18: Error: Values must be separated by a comma
   |  At line 5, column 18, offset 126
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:5:18: Error: Missing value for object property, expected ":"
   |  At line 5, column 18, offset 126
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:6:13: Error: Can not decode value starting with character u':'
   |  At line 6, column 13, offset 150
NetKAN/SpaceBus.netkan:6:15: Info: Recovering parsing after character u'['
   |  At line 6, column 15, offset 152
NetKAN/SpaceBus.netkan:6:15: Info: Recovering parsing after character u'['
   |  At line 6, column 15, offset 152
NetKAN/SpaceBus.netkan:6:15: Error: Values must be separated by a comma
   |  At line 6, column 15, offset 152
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:6:15: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 6, column 15, offset 152
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:6:15: Error: Missing value for object property, expected ":"
   |  At line 6, column 15, offset 152
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:9:13: Error: Can not decode value starting with character u':'
   |  At line 9, column 13, offset 210
NetKAN/SpaceBus.netkan:9:15: Info: Recovering parsing after character u'['
   |  At line 9, column 15, offset 212
NetKAN/SpaceBus.netkan:9:15: Info: Recovering parsing after character u'['
   |  At line 9, column 15, offset 212
NetKAN/SpaceBus.netkan:9:15: Error: Values must be separated by a comma
   |  At line 9, column 15, offset 212
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:9:15: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 9, column 15, offset 212
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:9:15: Error: Missing value for object property, expected ":"
   |  At line 9, column 15, offset 212
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan:14:0: Error: Unexpected end of input
   |  At line 14, column 0, offset 291 (AT-END)
   |    near text: True
NetKAN/SpaceBus.netkan:14:0: Error: Object literal (dictionary) is not terminated
   |  At line 14, column 0, offset 291 (AT-END)
   |    near text: True
   |  Object started at line 14, column 0, offset 291 (AT-END)
   |    with text: True
NetKAN/SpaceBus.netkan:14:0: Error: Object literal (dictionary) is not terminated
   |  At line 14, column 0, offset 291 (AT-END)
   |    near text: True
   |  Object started at line 1, column 0, offset 0 (AT-START)
NetKAN/SpaceBus.netkan: has errors
```

**Comment by DasSkelett** [comment]
Who needs access to logs if you know someone who has access!

**Comment by HebaruSan** [comment]
Thanks @techman83! "Bad number" made that one pretty obvious. :)
Also it looks like the link is fixed now! I can see that output myself...

**Comment by techman83** [comment]
Yay!

**Pull request merged**
