### PR TITLE
Add netkans based on ckan-meta .ckans.

### PR DESCRIPTION
**Pull request by plague006**
These mod represent the set of ckan-only mods that have had more than 1 release in their history. The contents should represent the most recent .ckan we have. I validated the JSON of all files but did with netkan/ckan. I'll let Jenkins chew through as much of it as I can.

Part of #3890

### CODE REVIEW

**Comment by plague006** [comment]
Fails Jenkins, but we're probably going to want to just modify the testing method. I'll leave that to @techman83 to deal with whenever he deems fit.

**Comment by dbent** [comment]
It's not particularly harmful since they'll be overwritten if necessary anyway, but `download_size` doesn't need to be in any of these. (nor `x_generated_by`, but that's minor).

**Comment by techman83** [comment]
Yeah, the testing expect certain things for NetKANs that don't apply for those. We'll just need to add some logic around when a [v|k] is and isn't needed.

**Comment by plague006** [comment]
Oh yeah there's extra metadata inside because the .netkans here are just verbatim copies of the most recent .ckan we have on file. I don't have the right tool or knowledge set to automatically pull out the un-needed bits. We'll just have to modify them as they're used/as we go.

**Comment by politas** [comment]
I can probably write up a script to strip out all the download_size and x_generated_by lines.

**Comment by politas** [comment]
There we go.

**Comment by plague006** [comment]
I thought about doing it that way too. Problem is I didn't have a way to remove the field while not breaking JSON validity. In your case you changed 36 files and 35 of them are no longer JSON valid. :S

**Comment by techman83** [comment]
The JSON seems valid, it's the metadata tests that expect vref/kref's because they are netkans. We've changed the rules. Just need to change that test a little, if it has "x y + z" kref/vref isn't required. I'll take a closer look when I get back.

**Comment by politas** [comment]
Ok, that does the same thing, but also cleans up the excess commas.

**Comment by politas** [comment]
Ok, that ^^^ is a whole other category of netkans that will need to be sorted - The ones we have an old frozen netkan file pointing to kerbalstuff for.

**Comment by plague006** [comment]
Unless there's a way to automate tracking down those fringe cases I see no issue with simply fixing them as new releases are issued.

**Comment by plague006** [comment]
I was too lax with which mods I turned into .netkans. More will be added as frozen in another PR.

**Comment by plague006** [comment]
Removed astro pack because watching Jenkins download the same (very large) file over and over was torture.

**Comment by plague006** [comment]
Passes all Jenkins metadata tests which is what matters. Fails to install because an old version of `Toolbar` wasn't available to meet a dependency (entirely expected a dependency to be unavailable at some point).

This is ready to rumble.

**Comment by techman83** [comment]
Awesome work @plague006, merging with epic thanks. Any issues we can resolve individually.

**Pull request merged**
