### PR TITLE
HermesInterplanetarySpacecraftDevFilesWithWIPMaVCredittoxxhansonmaxxO…

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #4612

### CODE REVIEW

**Comment by politas** [comment]
That identifier is way to long and unreadable. Can you trim it down?

**Comment by Olympic1** [comment]
ping @linuxgurugamer

**Comment by linuxgurugamer** [comment]
Sorry, thought I had done it

**Comment by linuxgurugamer** [comment]
Is there a maximum length to the mod name?  If so, what is it?

**Comment by politas** [comment]
No hard maximum, it was just an aesthetic call based on the problems of columnar data representation. That looks fine, now. Thanks!

**Pull request merged**
