### PR TITLE
Update CommunityTerrainTexturePack.netkan

### PR DESCRIPTION
**Pull request by Galileo88**

### CODE REVIEW

**Comment by Galileo88** [comment]
Definitely confused by this.

**Comment by Galileo88** [comment]
Can someone explain to me why in the console it still says its downloading OPM in order to get CTTP?

**Comment by Olympic1** [comment]
CTTP is extracted from OPM which is v2.1, while your version is v1.0.

Add `"x_netkan_epoch": "1"`

**Comment by Galileo88** [comment]
That worked thanks!

**Pull request closed without merging**
