### PR TITLE
Fix epic suits

### PR DESCRIPTION
**Pull request by mgsdk**
Closes https://github.com/KSP-CKAN/NetKAN/pull/1214.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Aren't texturereplacer things put inside its own folder as per the installation instructions [here](http://forum.kerbalspaceprogram.com/threads/107471) ?

**Comment by mgsdk** [comment]
It would seem like it. Looks like I need to play around with it myself before we can get it to work.

**Comment by mgsdk** [comment]
I am a little perplexed with regards to installation of this, especially since it would seem that this could easily attempt to overwrite files owned by other mods, as I guess the "EVAtexture.png" goes into the Default folder. Any other texture packs for TextureReplacer could potentially attempt to provide the same feature and clash. Thoughts?

**Comment by Dazpoet** [comment]
Do we index other texturepacks for Texturereplacer? Maybe it'd be worth adding a `"provides" : "TexturePack"` in all of them and also conflict with that? We do this for e.g. PlanetPacks right now even thought I don't think all of them strictly conflicts. If this starts becoming a problem we might have to consider something like conflict stanza which can exlude certain packs, but that sounds like a problem for the far future us.

**Comment by mgsdk** [comment]
From a quick look we list several.
* CustomDesignSpacesuits
* DiverseKerbalHeads
* StarTrekTOSSpaceSuits

There are a few other that install to TextureReplacer, but from the name it doesn't sound like they are replacing any suits texture, though I guess they may touch something in the Default folder.

**Comment by Dazpoet** [comment]
Looked through those 3 mods and they all seem to not conflict with the one in this PR. Acctually CustomDesignSpaceSuits has a dead dl link pointed to @hakan42 website.

**Pull request merged**
