### PR TITLE
BDArmoryContinued

### PR DESCRIPTION
**Pull request by linuxgurugamer**
closes #4467

### CODE REVIEW

**Comment by politas** [comment]
This will need a "provides" and "conflicts" for "BDArmory", or it will be largely useless. There are an awful lot of mods that depend on BDArmory. I'm sure people will be very pleased to see it back!

**Comment by linuxgurugamer** [comment]
Given that this is replacing BDArmory, would it make sense to change the ID to BDArmory and elete the old file?

**Comment by politas** [comment]
BahamutoD could always come back and take up where he left off. This is how we handle functional replacement forks.

**Comment by linuxgurugamer** [comment]
Understood.  Will get to it later this evening

**Comment by linuxgurugamer** [comment]
closes #4467

**Comment by DinCahill** [comment]
Do we need the repository and homepages lines? They should get scraped from SpaceDock.

**Comment by politas** [comment]
Ah, the Spacedock entry has been updated. No, we don't need it, but it won't hurt. This looks like it will do the job, now, and people have been waiting on BDArmory for 1.1.3 a long time. Merging with many thanks!

**Pull request merged**
