### PR TITLE
Add Ludicrous Propulsion Systems

### PR DESCRIPTION
**Pull request by politas**
Author posted on CKAN thread asking for this mod to be added.
Waiting on mod author to publish a full release on GitHub before this will test.

### CODE REVIEW

**Comment by Olympic1** [comment]
#rebuild

**Comment by BenjaminCronin** [comment]
V.0.2.4 has been released several days ago, the AVC file has been fixed

**Comment by politas** [comment]
@BenjaminCronin, The LPS.version file in the v0.2.4 download is still missing the commas. Not sure why.

**Comment by BenjaminCronin** [comment]
Ok, should be good now. Most recent release is 0.2.4.1.

**Comment by Olympic1** [comment]
@BenjaminCronin [Version file](https://github.com/BenjaminCronin/Ludicrous-Propulsion-Systems/blob/master/GameData/LudicrousPropulsionSystems/Versioning/LPS.version#L11) needs a `:` after `"`

**Comment by BenjaminCronin** [comment]
Anything else?

**Comment by Olympic1** [comment]
No, that was the last error

**Comment by BenjaminCronin** [comment]
All right. I'll make a release and your can run the check on that. it will be release v.0.2.4.2

**Comment by BenjaminCronin** [comment]
Alright, done. Thanks for all your help!

**Comment by BenjaminCronin** [comment]
Wait.  Wait wait.

**Comment by BenjaminCronin** [comment]
Ok, we should be good.

**Comment by Olympic1** [comment]
ok then, merging with our thanks

**Pull request merged**
