### PR TITLE
Update Science-Full-Transmit.netkan

### PR DESCRIPTION
**Pull request by Tekaoh**
Update compatibility to 1.6.x and move my repo over to the correct place

### CODE REVIEW

**Comment by Tekaoh** [comment]
Sorry for my noobiness... I can't tell what is making the checks fail... I'm trying to move my repo, does that cause a problem? Do I need to make a version bump or something to allow it?

**Comment by DasSkelett** [comment]
You are missing the abstract, if I get this right.

**Comment by Tekaoh** [comment]
> You are missing the abstract, if I get this right.

I'm not sure what that means...

**Comment by DasSkelett** [comment]
Normally the abstract should be fetched automatically from your GitHub repo (as it happened before this PR).
Now somehow it somehow doesn't happen, at least if I read the error message right:
```
Validating built/Science-Full-Transmit-v1.0.0.ckan.. Failed! See below for error description.
u'abstract' is a required property
```
But I don't know why yet.

**Comment by Tekaoh** [comment]
Hmm, ok. Well, part of this commit is to change the location of the repo for this mod from one account to another. Could that be messing something up? Let me know if there's anything I can do to help fix it up.

**Comment by DasSkelett** [comment]
I think I've got it: Netkan searches for the abstract in your github repository description. On you old repo, it's defined, and on your new one it isn't. So, just take over the description from your old repo.
image

**Comment by Tekaoh** [comment]
Ahh, alright. I didn't know what an abstract was referring to lol. I've set the repo description on the new one. How do I trigger a new check?

**Comment by DasSkelett** [comment]
I think we'll have to wait for a member for that one :/

**Comment by Tekaoh** [comment]
I can close this PR and open a new one. That should do it

**Pull request closed without merging**
