### PR TITLE
Install Brazilian Flags outside Squad folder

### LINKED ISSUE #4305: Brazilian Flags - Bandeira do Brasil e dos Estados
My mod in Spacedock

http://spacedock.info/mod/808/Brazilian%20Flag%20-%20Bandeira%20do%20Brasil

Description
Conteúdo
Adiciona a bandeira do Brasil no KSP.

Planos
- Logo mais estarei adicionando as bandeiras dos estados brasileiro.

V1.0
-Bandeira do Brasil

For All KSP Versions

### PR DESCRIPTION
**Pull request by politas**
We added the functionality to rename folders on installation with v1.18
Closes #4305

### CODE REVIEW

**Comment by politas** [comment]
#rebuild

**Comment by DinCahill** [comment]
LGTM. Thanks. :shipit:

**Comment by politas** [comment]
What's the deal with the hamster/squirrel?

**Comment by DinCahill** [comment]
It's GitHub's "ship it" emote (`:shipit:`).

**Pull request merged**
