### PR TITLE
RN Split Packs, Update Dependencies

### PR DESCRIPTION
**Pull request by raidernick**
-Split Salyut/Soyuz pack into 2 packs
-Sovietcore mod is in the new split pack so I fixed that
-Kosmos is a dependency that is gone now since KS shutdown. I have
permission from author to modify and distribute. I made a new download
available on my github. The mod is updated to 1.0.5

### CODE REVIEW

**Comment by politas** [comment]
Hi Raidernick. You'll need to rename KOSMOS-SSPP.kerbalstuff to KOSMOS-SSPP.netkan, and it will need the following fields, since Github has no such fields:

    "name"         : "User-friendly name for the mod",
    "abstract"     : "A short description of what the mod does",

To RN-SalyutStations (and I am assuming RN-SovietSpacecraft if that is the other half), add the following:

    "conflicts" : [
        { "name: "RN-SalyutStations-SoyuzFerries" }
    ],

To make sure people don't try to leave the old combined mod installed.

**Comment by raidernick** [comment]
@politas there does that look good now?

**Comment by politas** [comment]
Come on Jenkins, #rebuild

**Comment by politas** [comment]
The homepage resource is normally used to point to a thread on the forums for discussion. Are you certain about pointing to the Github repo? That's ok if you are.

**Comment by raidernick** [comment]
@politas It was set to git when I was removed from the forum settings and my threads were locked. Now that I'm back it is a good idea to change them. I changed the ones that actually have forum threads. 

Also I removed the kosmos dependency as since I can modify it anyway, I decided to put the parts I need directly in my mod. I only need 2 parts and I don't want to make users download a >100mb mod just for 2 parts.

I'll still host the fixed kosmos though.

**Comment by politas** [comment]
Might be an idea to make those 2 parts be not part of your mod if someone has Kosmos installed, via ModuleManager, then.

**Comment by politas** [comment]
Actually, checking the licence on KOSMOS, it's a "No Derivatives" CC licence, so unless you have explicit permission, you can't separate out parts of it. That would make your mod a derivative of KOSMOS (partially).

In RN-SalyutStations, you've missed a " in the "conflicts" stanza

    { "name	    : "RN-SalyutStations-SoyuzFerries" }'

And shouldn't RN-SalyutStations depend on SovietPackCore?

**Comment by politas** [comment]
Sorry for the delays in getting this tested. It'd be much quicker for you if Jenkins was working.

**Comment by raidernick** [comment]
I have permission to release do whatever I want with KOSMOS, I noted that in that original message here. He gave permission in his thread when he left to forums for anyone to edit it, but a year before that he gave me his entire unity source project over PM to let me edit it.

I already included his files in my release and I changed the names of them so they won't conflict if someone has the mod installed so don't worry about that.

I fixed the other stuff you mentionned.

**Comment by techman83** [comment]
@politas Jenkins doesn't respond to #rebuild - I never figured out how the previous Jenkins maintainers got that to work. Closing + re-opening will do kick it off though. Which I will do just now.

**Comment by techman83** [comment]
Oh, seems like Jenkins had barfed. The backups are getting larger + filled up the disk. I've sorted that out now.

**Comment by politas** [comment]
Ok, all is good, then. Sorry, I wasn't entirely sure about what you said earlier, so I thought it was worth mentioning, since there were errors that needed fixing anyway. Merging with my thanks.

**Pull request merged**
