### PR TITLE
Create CrowdSourcedFlags.netkan

### PR DESCRIPTION
**Pull request by dmxz**

### CODE REVIEW

**Comment by plague006** [comment]
Test fails because there are no full releases in a .zip (0.1.1.0 is pre-release and 1.15.0 isn't in a .zip)

**Comment by dmxz** [comment]
@plague006 It should be fixed now

**Comment by dmxz** [comment]
@plague006 It _should_ be working now. I just checked with `netkan.exe`

**Comment by plague006** [comment]
Looks good, I'll just ask you to add 2 lines to make it consistent with all other flag-only mods:
````
    "ksp_version"    : "any",
    "comment"        : "flagmod"
````

**Comment by dmxz** [comment]
"ksp_version" and the AVC .version file couldn't coexist so I got rid of .version as I didn't need it anyway. am not good with netkan

**Comment by plague006** [comment]
Looks good, merging with my thanks.

**Pull request merged**
