### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Shjould work :-)
Copied another which does

### CODE REVIEW

**Comment by Dazpoet** [comment]
So this is not supposed to install to `GameData/ContractPacks/Spacetux` like your other contract packs? Just making sure before merging :)

**Comment by linuxgurugamer** [comment]
Ummmm, oops

Yes it is.  I must have make a typo.

Thanks for catching it


JBB

**Comment by linuxgurugamer** [comment]
Fixed, thank you

**Comment by linuxgurugamer** [comment]
This finished this morning, any idea when it will get into CKAN?

**Comment by Dazpoet** [comment]
That something finishes just means that the bot found no errors. To get into CKAN someone has to merge it, something we do manually after making sure it works as it is supposed to. Like in this case I asked about the install stanza just to make sure that it was correct. Then I read the details of the bots build and shortly after writing this post I'll merge it into CKAN.

**Comment by linuxgurugamer** [comment]
Ah, now I understand.

OK, thanks for the explanation.  I'll reduce my noise level :-)

and I did see that it finally got in, I saw it there last night.

Thanks



JBB

**Pull request merged**
