### PR TITLE
Add Sentar Expansion from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of BorisBee, to add [Sentar Expansion](https://spacedock.info/mod/238/Sentar%20Expansion) to CKAN.

Please direct questions about this pull request to [BorisBee](https://spacedock.info/profile/BorisBee).

### CODE REVIEW

**Comment by plague006** [comment]
I'm really not sure what to make of this.. According to the SD page it's version 1.0 for KSP 1.0.5. This isn't the same 1.0 file as http://i.52k.de/kspmods/storage/BorisBee_13147/Sentar_Expansion/Sentar_Expansion-1.0.zip and it's not a repackaging of `http://i.52k.de/kspmods/storage/BorisBee_13147/Sentar_Expansion/Sentar_Expansion-1.2.1.zip`. Further, the ksp forum thread still indicates it's only compatible up to 1.0.4 and there's no changelog or even a post since January.

**Comment by politas** [comment]
There is now an update to the forum thread pointing to Spacedock, so this looks legit.

**Comment by plague006** [comment]
The question isn't its legitimacy. The question is: what version is this? If it's version 1.0 why isn't it the same as the previous 1.0? And why is the author uploading 1.0 instead of 1.2?

**Comment by politas** [comment]
Well, that will make it version 1:1.0, and all should be fine.

**Comment by politas** [comment]
Hmm. It seems following the instructions to fix the merge conflict has effectively merged this change without this PR. bffde920a808338dea3e2a504d91140002062afb is the commit.

**Comment by plague006** [comment]
Looks fine and the bot output was good.

**Comment by politas** [comment]
Thanks for the sanity check.

**Pull request closed without merging**
