### PR TITLE
Resolve file conflicts between KerbinSide and KerbinSideAirRace aka "The Red Pill" (we shall see how deep the rabbit hole goes)

### PR DESCRIPTION
**Pull request by plague006**
Closes KSP-CKAN/CKAN-meta#706

### CODE REVIEW

**Comment by plague006** [comment]
Jenkins passing is erroneous.

**Comment by techman83** [comment]
Does this refer to KSP-CKAN/CKAN#1273

**Comment by plague006** [comment]
KerbinSideAirRace updated, creating new conflicts.

**Comment by dbent** [comment]
:sob: We really ought to create a list of "fragile" installations like this, so at least we're aware they may require double checking on updates.

I assume `KerbinSideAirRace` does not actually distribute a full copy of so a simple `conflicts` wouldn't work?

**Comment by dbent** [comment]
Also, are the files that need filtering not identical? If they are identical we can just filter them from `KerbinSideAirRace` and not bother modifying `KerbinSide`.

**Comment by plague006** [comment]
>I assume `KerbinSideAirRace` does not actually distribute a full copy of so a simple `conflicts` wouldn't work?

Correct.

From the [mod's author](http://forum.kerbalspaceprogram.com/threads/82785-1-0-4-Kerbin-Side-v1-0-3-SideJobs-v1-4-Air-Race-v1-5?p=2083428&viewfull=1#post2083428):
>KerbinSide is not a pre-requisite for Air-Race. Air-Race can stand-alone but if you want to race at Black Krags or Dundard's Edge, you have to get there from KSC. Install KerbinSide All-in-1 and then you can launch from runways at those locations.

We can put this back on hold again though. `KerbinSideAirRace` released 1.5 and I need to look through it.

**Comment by plague006** [comment]
Jenkins continues to test BDarmory and not the mods in this PR. I  :heart: you Jenkins.

**Comment by plague006** [comment]
The conflicting files are all textures.. I could resolve this in a stable way by having `KerbinSideAirRace` install into another folder.. Double-loading textures isn't ideal.. but it means 1 less unneccesary 'core' mod on the list and stability: both things I like.

**Comment by plague006** [comment]
Closes #1936

**Pull request closed without merging**
