### PR TITLE
Add PSA-Greenhouse

### PR DESCRIPTION
**Pull request by Cphoenix**
See [forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/141704-112-psa-greenhouse-for-usi-life-support-v-1123-2016jun13/).

### CODE REVIEW

**Comment by politas** [comment]
#   Failed test 'PSA-Greenhouse - spec_version v1.4+ required for install with 'find''
#   at t/metadata.t line 139.

**Comment by Cphoenix** [comment]
Hope that fixes it.

**Comment by politas** [comment]
To have a spec_version other than 1, it needs to be entered as a version string, eg `"v1.4"`

**Comment by politas** [comment]
Since it has MM configs for USI-UKS (resource consumer) and CLS, it might be best to make USI-LS a "Recommend" rather than a depend, and suggest those two.

**Comment by Cphoenix** [comment]
Actually you were right. There isn't an MM config for CLS. The CLS module is in the part configs themselves, line 92 in Greenhouse1.cfg and line 95 in Greenhouse2.cfg. I'll add USI-UKS-Shared and KeepFit to suggests, and CLS to depends?

**Comment by politas** [comment]
I _think_ that CLS module ref won't cause problems if CLS isn't installed, but maybe ask in the forum thread or a direct message to the author? Make it a recommend at least.

**Comment by Cphoenix** [comment]
Will do. Waiting on response from author then.

**Comment by Cphoenix** [comment]
Alright, fixed-up the spec version correctly this time, and moved around dependencies. The only real hard one is MM.

**Comment by politas** [comment]
Lokos good, passes Jenkins. Merging with thanks!

**Pull request merged**
