### PR TITLE
Add 64k-overhaul

### LINKED ISSUE #5566: 6.4k scale overhaul (request for putting on CKAN
I' am the author of a new mod-6.4k scale overhaul-it adds KScale64 (though you can use any 6.4 scale kerbin sized body) configs to the game
forum threadhttp://forum.kerbalspaceprogram.com/index.php?/topic/161381-122-64k-overhaul/
Currently for version 1.2.2
requires: Module manager so it should work in 1.3 currently but when i add mod configs the version will be tied to the mod with the lowest KSP version more info on the forum thread 
Download: https://github.com/Kerbinorbiter/64k-overhaul/releases/tag/p0.01
thanks in advance
-KerbinOrbiter

### PR DESCRIPTION
**Pull request by politas**
@Kerbinorbiter, does this look ok?
Closes #5566

### CODE REVIEW

**Comment by Kerbinorbiter** [comment]
could you add recomend Dragon01's Soyuz other than that go ahead

**Comment by politas** [comment]
You mean [Above the Sky - Soyuz TMA and R7](https://spacedock.info/mod/1297/Above%20the%20Sky%20-%20Soyuz%20TMA%20and%20R7)?

**Comment by Kerbinorbiter** [comment]
Yes

**Comment by politas** [comment]
#rebuild

**Comment by Kerbinorbiter** [comment]
Ok will do tonight also adding a resource (doesn't require CRP) I'm trying to keep dependancys low

**Comment by politas** [comment]
#rebuild

**Comment by Kerbinorbiter** [comment]
done.

**Comment by politas** [comment]
#rebuild

**Comment by Kerbinorbiter** [comment]
https://github.com/Kerbinorbiter/64k-overhaul/releases/tag/v1.2

**Comment by politas** [comment]
I'm still trying to work out why this is failing, sorry it's taking so long!

**Comment by Kerbinorbiter** [comment]
its fine i know things have issues sometimes usually if i get a problem i cannot seem to think i rewrite the section of code

**Comment by politas** [comment]
There's something about the zip file that Mono doesn't like. Sorry, I've been busy renovating, so haven't had time for CKAN stuff.

**Comment by politas** [comment]
Yep definitely an issue with the zipfile. What software are you using to create it? Perhaps if you moved the "FUTURE GUIDE.md" file into the "64k_overhaul" folder?

**Comment by Kerbinorbiter** [comment]
7zip

**Comment by Kerbinorbiter** [comment]
done same link, edited the download

**Comment by Dazpoet** [comment]
@politas it works now :)

**Comment by Kerbinorbiter** [comment]
wooo!
time to break out the popcorn :D

**Comment by politas** [comment]
#rebuild

**Pull request merged**
