### PR TITLE
Add BD Railgun from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of KSP_Bros, to add [BD Railgun](https://spacedock.info/mod/427/BD%20Railgun) to CKAN.

Mod details:
    name = /mod/427/BD%20Railgun
    author = KSP_Bros
    abstract = 2 railguns for BD. It is VERY powerful. #railgunz #big guns #weapons
    license = Creative Commons - you may edit bot must give credit
    Homepage = 
    description = Two guns:
1.  Big Howitzer-"style" railgun
2. Not-so-big machine gun, but very powerful but will add to your power bill
Go to the link below to see what it is in real life. Have fun!
[https://en.wikipedia.org/wiki/Railgun](http://)
	-KSP Bro AE

Please direct questions about this pull request to [KSP_Bros](https://spacedock.info/profile/KSP_Bros).

### CODE REVIEW

**Comment by Cphoenix** [comment]
The license on the SpaceDock page changed and is just as unclear about **which** CC license is to be used. I guess just say "restricted" instead, to be in-line with the spec?

**Comment by politas** [comment]
"restricted" sounds about right, given the vagueness. I think CC-BY-ND is what they really want. Any luck finding a forum thread?

**Comment by Cphoenix** [comment]
>"restricted" sounds about right, given the vagueness. I think CC-BY-ND is what they really want. Any luck finding a forum thread?

[Found it.](http://forum.kerbalspaceprogram.com/index.php?/topic/134499-bd-railgun/)

**Comment by politas** [comment]
Closing in favour of #4490

**Pull request closed without merging**
