### PR TITLE
Add new TestFlight netkans

### PR DESCRIPTION
**Pull request by jwvanderbeck**
I am moving TestFlight to a new distribution model where there is the core TestFlight plugin, and then separate Config Packs.

This adds the core plugin .netkan and .netkans for two config packs, Stock, and Realism Overhaul.

### CODE REVIEW

**Comment by Dazpoet** [comment]
When a mod `provides` something the array is formatted like:

`"provides" : [ "mod1", "mod2" ]`

I also confuse it all the time.

**Comment by jwvanderbeck** [comment]
Ok apparently I still have something wrong but the build output is of no help in determining what.

**Comment by jwvanderbeck** [comment]
sigh .. never underestimate stupidity :)

**Comment by jwvanderbeck** [comment]
Ok your build process is erroring and saying:
> Module TestFlight required, but not listed in index, or not available for your version of KSP

But isn't the whole point of the netkans to provide that in the first place? :)  What am I missing here?

**Comment by Dazpoet** [comment]
Your TestFlight mod is strictly defined as only available for ksp 1.0.0 and as such throws and error when attempting to install it. This is due to your .version file

**Comment by jwvanderbeck** [comment]
sigh..so many moving parts.

I've released a new version of TestFlight with the fixed AVC.

**Comment by Dazpoet** [comment]
Once everything is set up and working though you won't have to think about it anymore :)

**Comment by jwvanderbeck** [comment]
Heh yeah that's why I have as automated a build process as possible, I just forgot to update my script between 1.0 and 1.0.2 :(

**Comment by Dazpoet** [comment]
Now it seems the bot is just being silly because it can't install 2 things at once.

**Comment by Dazpoet** [comment]
Passes jsonlint, looks fine from a visual observation, seems to correctly generate .ckan files and is slowly driving the author insane. I think we just passed all necessary steps for a merge :)

**Pull request merged**
