### PR TITLE
Create MagicSmokeIndustries

### PR DESCRIPTION
**Pull request by LemonzPC**
Magic Smoke Industries Infernal Robotics - Core Beta - Working with KSP 1.2.2

### CODE REVIEW

**Comment by LemonzPC** [comment]
hey all, Hope ive done this all correct im new to github please let me know if theres anything i should of done different. Or if ive done everything wrong... witch would be my luck :D. GL and thank you!

**Comment by politas** [comment]
How does this tie in with https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/InfernalRobotics.netkan https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/InfernalRobotics-LegacyParts.netkan and https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/InfernalRobotics-Sequencer.netkan?

It would be preferable to continue with the InfernalRobotics naming scheme, so all the related mods are grouped together in the repo.

**Comment by LemonzPC** [comment]
Ok cheer mate ill get them update correctly and remove these pull request, update will take a day or 2 xmas time hope yall are having a good holiday !

**Comment by politas** [comment]
Great! Enjoy your holidays!

**Pull request closed without merging**
