### PR TITLE
Mods that provide Custom Asteroids configs should fulfill CustomAsteroids-Pops

### PR DESCRIPTION
**Pull request by Starstrider42**
This PR will prevent false conflicts where players cannot install both Custom Asteroids and a mod that uses it (currently Extrasolar, Other_Worlds, Outer Planets Mod, and Real Solar System), merely because the _stock_ configs are incompatible with something. I've also taken the liberty of updating the Other_Worlds config to point to SpaceDock.

@AndrewDrawsPrettyPictures, @pkmniako, @CaptRobau, and @NathanKell, do these changes meet with your approval?

### CODE REVIEW

**Comment by pkmniako** [comment]
It's good for me

**Comment by AndrewDrawsPrettyPictures** [comment]
Looks okay to me.

**Comment by NathanKell** [comment]
Yup!

**Comment by politas** [comment]
Tangentially related, is CustomAsteroids-Pops-Stock-Stockalike supposed to be a CustomAsteroid-Pops config for StockAlikeSolarSystem? Because currently, it conflicts with it.

**Comment by Starstrider42** [comment]
No. CustomAsteroids-Pops-Stock-Stockalike is a config that reproduces stock KSP asteroid behavior (since the stock asteroid system is disabled by installing Custom Asteroids). The config is incompatible with [Stock-Alike Solar System](http://forum.kerbalspaceprogram.com/index.php?/topic/131405-/) because it refers to the planets Kerbin and Dres, while Stock-Alike Solar System uses the names of real planets.

**Comment by CaptRobau** [comment]
Fine by me.

**Comment by NathanKell** [comment]
Actually we now have Kopernicus asteroid configs so we will be using that rather than Custom Asteroids. After this PR is merged (presuming acceptance) I'll handle the further RSS netkan edits.

**Comment by plague006** [comment]
This fails due to a change in the folder layout in ExtrasolarPlanetsBeyondKerbol-stock's latest release. https://github.com/KSP-CKAN/NetKAN/pull/3913 will address that. This looks fine and all mentioned parties are in agreement so I'm merging with my thanks.

**Pull request merged**
