### PR TITLE
Initial commit USICore, hardcoded license

### PR DESCRIPTION
**Pull request by qm3ster**
closes #2381

### CODE REVIEW

**Comment by qm3ster** [comment]
LET'S SEE NOW. WILL THIS WORK? WILL THIS NOT? WE MAY NEVER KNOW!

**Comment by qm3ster** [comment]
@plague006 I stuck it into both places where it won't work, didn't I?
It should have been in the name of the commit, not a description?

**Comment by qm3ster** [comment]
It works on my local NetKAN.

**Comment by qm3ster** [comment]
@plague006 good to go.

**Comment by pjf** [comment]
@qm3ster: The KS page is a little light on info, so I just want to confirm we're doing the right thing here. Am I correct this is mostly a parts and assets pack (which contains Kontainers and Reactors), which nothing else depends upon?

Glancing at the contents of the .zip I'm guessing it has a dependency on Firespitter-Core, but I can add that before merging if needed.

Is the dependency on USITools a hard one (required) or a soft one (recommended)? The reason I ask is that the .zip itself doesn't have the USITools files at all.

**Comment by qm3ster** [comment]
Haven't been around much, so not sure where it's headed. USI tools is not required right now, but will probbably be a hard dependency once more content is added. (It's not something that has user-facing functionality, so no way it could be a suggestion/recommendation, it's either needed or not.)
In the future, this will be suggested/recommended/depended by MKS, FTT. (Most likely the rare 'recommended' because while nothing stops you from running those mods without reactors and kontainers, but using them is a different issue, and would require other mods.

The idea behind this release is not having duplicate parts in eg MKS and FTT, so they are being taken out into their own package.

**Comment by plague006** [comment]
Auto-closing works in the top comment and/or in any of the commits or commit messages/descriptions.

**Comment by plague006** [comment]
This core mod will conflict with/cause issues for https://github.com/KSP-CKAN/NetKAN/pull/2343

**Comment by qm3ster** [comment]
With USI Core still not merged, currently already not possible to install Karbonite and MKS together. They both install UmbraSpaceIndustries folder, not Kolonization and Karbonite, clashing a lot.

**Comment by plague006** [comment]
The entire suite of RoverDude's mods need all their metadata overhauled at once. Merging/creating USI Core alone will only server to create more issues.

**Comment by qm3ster** [comment]
Agreed, thanks for Karbonite delay.

**Pull request closed without merging**
