### PR TITLE
SeaDragon: remove "quicksearch" recommendation.

### PR DESCRIPTION
**Pull request by NecroBones**
The other PR was closed for being a duplicate, but it was for a different mod's Netkan. Same change, but to a different file.

### CODE REVIEW

**Comment by NecroBones** [comment]
Replacement for #3504, which wasn't actually a duplicate.

**Comment by Dazpoet** [comment]
My mistake, sorry!

**Comment by NecroBones** [comment]
No worries! :)

**Comment by NecroBones** [comment]
Thanks!

**Pull request merged**
