### PR TITLE
Add Fan blade AOA and rotor torque control from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of CarnationRED, to add [Fan blade AOA and rotor torque control](https://spacedock.info/mod/2327/Fan%20blade%20AOA%20and%20rotor%20torque%20control) to CKAN.

Please direct questions about this pull request to [CarnationRED](https://spacedock.info/profile/CarnationRED).

Mod details:
    name = /mod/2327/Fan%20blade%20AOA%20and%20rotor%20torque%20control
    author = CarnationRED
    abstract =   The mod enables you to control AOA(angle of attack) of fan blades in flight, as well as automatically limit rotor's output to save electric charge
    license = MIT
    Homepage = 
    description =
Hi, the mod is "FanAOAnRotorTorque", which enables you to control AOA(angle of attack) of fan blades in flight, as well as automatically limit rotor's output to save electric charge.

NO MORE annoying manual adjusting fan blade deploy angles

BETTER energy efficiency for rotors

**Usage: press "=" to activate, details see video below**

<iframe width="1542" height="807" src="https://www.youtube.com/embed/cRfwq_FndNE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### CODE REVIEW

**Comment by HebaruSan** [comment]
Remaining concerns:

- Is the identifier spelled correctly? Looks like FanAOAAndRotorTorque may have been meant
- Forum thread doesn't specify license
- No link to source code

**Comment by CarnationRED** [comment]
> Remaining concerns:
> 
> * Is the identifier spelled correctly? Looks like FanAOAAndRotorTorque may have been meant
> * Forum thread doesn't specify license
> * No link to source code
Appreciate for your help, I'm kinda new here.
I added a line in forum thread "License: MIT", does that work?
I'm working on uploading codes to github

**Comment by HebaruSan** [comment]
Did the moderators hide your forum thread? The link doesn't work anymore.

https://forum.kerbalspaceprogram.com/index.php?/topic/191535-181breakingground-fan-blade-aoa-and-rotor-torque-control-v02/

**Comment by DasSkelett** [comment]
I think so, you can still find it in the forum search, but clicking on it says permission denied.
https://forum.kerbalspaceprogram.com/index.php?/search/&q=Fan%20blade%20AOA&search_and_or=and&search_in=titles
If I have to take a guess, it's probably because @CarnationRED might be missing the link to the source code in the post?
The forum moderators are quite strict about enforcing that rule.

**Comment by CarnationRED** [comment]
> I think so, you can still find it in the forum search, but clicking on it says permission denied.
> https://forum.kerbalspaceprogram.com/index.php?/search/&q=Fan%20blade%20AOA&search_and_or=and&search_in=titles
> If I have to take a guess, it's probably because @CarnationRED might be missing the link to the source code in the post?
> The forum moderators are quite strict about enforcing that rule.

A moderator sent a PM to me, and I modified the thread OP as asked. Because I'm a new user, the thread is pending approval

**Comment by CarnationRED** [comment]
I'm having problem uploading release files to github on Chrome, is it possible to upload a release via GitHub desktop?
Since my mod repository already contains a mod release directory, can I use that to make a release?
Thanks.

**Comment by HebaruSan** [comment]
Your SpaceDock page will work fine, I have added the forum link and the source link to it.

I don't know how GitHub desktop works, I don't use it.

**Comment by CarnationRED** [comment]
Got it, thanks.

**Comment by HebaruSan** [comment]
Looks like the forum thread is re-instated and everything is in order here. Congrats on your first mod, @CarnationRED!

**Pull request merged**
