### PR TITLE
Add Hospital Ship from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of RobForrest, to add [Hospital Ship](https://spacedock.info/mod/913/Hospital%20Ship) to CKAN.

Mod details:
    name = /mod/913/Hospital%20Ship
    author = RobForrest
    abstract = Hospital Ship
    license = MIT
    Homepage = 
    description = Model by: lavawave2 available here: http://tf3dm.com/3d-model/cargo-ship-2-50101.html
Textures by: Rob Forrest
Config by: Rob Forrest
Unity Import by: Rob Forrest.

Please direct questions about this pull request to [RobForrest](https://spacedock.info/profile/RobForrest).

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
My understanding is that no vessels are allowed on Spacedock, is that correct?

**Comment by politas** [comment]
This looks like a Kerbal Konstructs config?

**Comment by politas** [comment]
Nope, not a KK mod. Just a part.

**Comment by Olympic1** [comment]
Yes, just a part, merging

**Pull request merged**
