### PR TITLE
Added handmade metadata for the Throttle Controlled Avionics instead of the one made by KerbalStuffBot.

### PR DESCRIPTION
**Pull request by allista**
The suffix "Continued" is not a part of the mod's title.

Removed stray commas.

### CODE REVIEW

**Comment by hakan42** [comment]
#rebuild

**Comment by hakan42** [comment]
The build is working now, timeout issues on Jenkins...

**Comment by hakan42** [comment]
@allista This mod contains a .version file. Could I ask you to add the ksp-avc stanza to the netkan?

```
"$vref"        : "#/ckan/ksp-avc",
```

**Comment by allista** [comment]
I tried, but netkan.exe says: `Bad embedded KSP-AVC file`
The file contents are parsed without error with KSP-AVC, through:

	{
		"NAME":"ThrottleControlledAvionics",
		"URL":"https://raw.githubusercontent.com/qfeys/ThrottleControlledAvionics/master/GameData/ThrottleControlledAvionics/ThrottleControlledAvionics.version",
		"DOWNLOAD":"https://github.com/qfeys/ThrottleControlledAvionics/releases",
		"CHANGE_LOG_URL":"https://raw.githubusercontent.com/qfeys/ThrottleControlledAvionics/master/ChanegLog.md",
		"VERSION":
		 {
			 "MAJOR":2
			 "MINOR":0
			 "PATCH":0
			 "BUILD":0
		 }
		"KSP_VERSION_MIN":
		 {
			 "MAJOR":0
			 "MINOR":90
			 "PATCH":0
		 }
		"KSP_VERSION_MAX":
		 {
			 "MAJOR":0
			 "MINOR":90
			 "PATCH":0
		 }
	}

**Comment by hakan42** [comment]
*that* piece of json is invalid, as it is missing all the required commas after the closing braces ( "}" ). Go to http://jsonlint.com/ and give it the URL     https://raw.githubusercontent.com/qfeys/ThrottleControlledAvionics/master/GameData/ThrottleControlledAvionics/ThrottleControlledAvionics.version

I will open up an enhancement request on the TCA repository.

**Comment by allista** [comment]
Thank you for the explanations. I've fixed this in our .version file generator and updated the file in development branch. Will add the `ksp-avc` string and make another pull-request as soon as I publish the new version.

**Pull request merged**
