### PR TITLE
Added dependency

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
!rebuild

**Comment by linuxgurugamer** [comment]
@HebaruSan Since Jenkins isn't working, please review this and merge.  It passes local netkan.exe

**Comment by HebaruSan** [comment]
Jenkins **is** working, it just isn't properly linking itself up to commits anymore:

- https://ci.ksp-ckan.space/job/NetKAN/10252/console

**Comment by HebaruSan** [comment]
Changes look fine, merging.

**Pull request merged**
