### PR TITLE
Add Sigma RemoteTech Expansion from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Sigma88, to add [Sigma RemoteTech Expansion](https://kerbalstuff.com/mod/914/Sigma%20RemoteTech%20Expansion) to CKAN.

Please direct questions about this pull request to [Sigma88](https://kerbalstuff.com/profile/Sigma88).

### CODE REVIEW

**Comment by Sigma88** [comment]
I think the integration of this in CKAN should be already possible, if there are any problems feel free to contact me

**Comment by Sigma88** [comment]
As far as I know the current release should work fine with CKAN

let me know if there are any problems

**Comment by Sigma88** [comment]
I thought this might help

this mod is fully compatible with Stock KSP and this is how it works

without RemoteTech:
- most of the antennas will be loaded to work in Stock KSP
- antennas are compatible with AntennaRange only if RemoteTech is not installed
- the RemoteTech Specific antennas this mod adds won't show up


this is fully compatible with #1605

if someone has this mod with at the same time #1309, that mod should be installed and this mod (#1609) should be ignored

**Comment by dbent** [comment]
Replaced by #1679

**Pull request closed without merging**
