### PR TITLE
Update VSR netkan to mark next version for KSP1.1

### PR DESCRIPTION
**Pull request by NathanKell**

### CODE REVIEW

**Comment by plague006** [comment]
Please expand the existing `x_netkan_override`. Multiples overwrite one another (iirc).

**Comment by NathanKell** [comment]
@plague006 how does one do that exactly? And I fear that may affect more than this, I think I added another override recently...

**Comment by NathanKell** [comment]
Ah, no, I think I only did that here after all.

**Comment by NathanKell** [comment]
Thanks!

**Comment by plague006** [comment]
Picture worth a thousand words. =)

**Comment by NathanKell** [comment]
Indeed!

**Pull request merged**
