### PR TITLE
[In progess, do not merge!] Removed netkan file, download source no longer available.

### PR DESCRIPTION
**Pull request by mgsdk**
Going to https://ksp.marce.at/ results in a page saying "Mods have been permanently taken down due to inappropriate behavior of a community member."

Unable to download mod.

### CODE REVIEW

**Comment by mgsdk** [comment]
See https://github.com/KSP-CKAN/NetKAN/issues/932

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://snuepfsunantes.org/during.php?v>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hey, I think I've found the thing you were looking for, just take a look here <http://choltushyxe.greenswampsoup.com/commonly.php?v5x92>

Good wishes, blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hi, I just read an article that you might be interested in, you won't regret, please read it here <http://ngogytrapu.remanufacturedammo.com/aedcpxkf>

Typos courtesy of my iPhone, blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hey,
You won't believe what I've just read, this is so amazing, read more at  <http://sadivyga.warmingamerica.com/aettozl>

Pardon my monkey thumbs, blue@blu3wolf.com

**Pull request closed without merging**
