### PR TITLE
Git2

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Updated all netkans beginning with A for LGG's mods to use github as the source, this to work around the issue with CKAN and Spacedock not properly honoring the .version file

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
AntennaRangePatch4Antennas has no releases on GitHub.

**Comment by linuxgurugamer** [comment]
I know, thanks.  There was another error with AFBW, I'm working around it.  Appreciate all help and comments, but please do not commit without my knowing.  I'm rebuilding all the netkans for my mods to use github instead of spacedock, and will be doing a bunch at a time.

**Comment by HebaruSan** [comment]
The error with AFBW was fixed by the previous commit I added, it needed to select the Windows asset.

**Pull request closed without merging**
