### PR TITLE
Force-allow KSPWheel on 1.12 while AVC is down

### PR DESCRIPTION
**Pull request by NathanKell**
This works around the issue where the remote version file (which gives this compatibility) is hosted on the AVC server, which is down (as it sometimes is).

### CODE REVIEW

**Comment by NathanKell** [comment]
@HebaruSan I assume this is the better approach than editing the .ckan file?

**Review by HebaruSan — APPROVED** [review]
Yeah, if you changed the .ckan in CKAN-meta, the bot would just overwrite it. This should be fine.

**Comment by NathanKell** [comment]
Thanks! :)

**Comment by HebaruSan** [comment]
The change made it to CKAN-meta, should be available to users in 2 minutes or so.

https://github.com/KSP-CKAN/CKAN-meta/commit/8c6e37a563d507aa04f69dc1735166364fac8f61

**Pull request merged**
