### PR TITLE
Add Nehemiah's mods

### LINKED ISSUE #5557: NEOS / OMS in CKAN
Now that [Nehemiah has given me the go-ahead](http://forum.kerbalspaceprogram.com/index.php?/topic/73723-090-orbital-material-science-version-06/&do=findComment&comment=2868282) to be the official maintainer until his (hopefully soon) return, I'd like to investigate how best to get his excellent mod-collection into CKAN.

Basically it consists of a number of very closely-linked mods which all share a plugin and some common configuration/models (names below correspond to the current directory paths):

1. Kemini - early science using just the Mk1 capsule
   * Requires: Module Manager
1. KEES - mid-level science, using KAS to attach various exposure experiments to the outside of a craft
   * Requires Kerbal Attachment System
   * Recommends: K2 Command Pod
1. KerbalLifeScience/OMS - end-level station science requiring building a station and using various supply missions to stock it with equipment and experiments
   * Recommends: Connected Living Spaces
1. MultiPurposeParts- Common parts (not released as a separate mod at present, but included in KLS and OMS)
1. NE_Science_Common - Plugin and common configuration (not released as separate mod at present, but included in Kemini/KEES/KLS/OMS)

The first 4 are released as separate downloads, as well as in a single "Science Pack" download. Each of the components has an AVC-compatible version file, and all are released via GitHub at present:
https://github.com/mwerle/OrbitalMaterialScience/releases

All mods are installed under GameData/NehemiahInc

Part of the reason for splitting the mods up originally was due to the relatively large download-sizes of some of them (affected some users), as well as some users only wanting a subset (usually Kemini). By far the biggest number of downloads is for the "Science Pack" though.

How would you recommend the mods be structured in future to be both good for CKAN as well as continuing to be good for standalone distribution?  I don't really want standalone users to have to download A + B + C separately before they have a usable install.

For CKAN I'm guessing having a "lite" version of each download which only includes its own data, with links to the dependent mods, then for standalone distribution have the current "full" versions which include the dependencies inside the ZIP.

Alternatively could just link the "Science Pack" for CKAN, which means CKAN users would always have to do the full download (14MiB) on any update.

### PR DESCRIPTION
**Pull request by Olympic1**
Nehemiah's mods are continued and the new author (@mwerle) wanted them to be available on CKAN again.

The version files are not valid json's but a [PR](https://github.com/mwerle/OrbitalMaterialScience/pull/12) is made for this. For now I added them but they need to be fixed.

### Waiting on new release

Closes #5557

### CODE REVIEW

**Comment by Olympic1** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Any reason why this can't be fixed at this time?

**Comment by Olympic1** [comment]
#rebuild

**Comment by Olympic1** [comment]
@linuxgurugamer feel free to merge

**Pull request merged**
