### PR TITLE
Add Tweakscale Configs for Making History from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of JedTech, to add [Tweakscale Configs for Making History](https://spacedock.info/mod/1806/Tweakscale%20Configs%20for%20Making%20History) to CKAN.

Mod details:
    name = /mod/1806/Tweakscale%20Configs%20for%20Making%20History
    author = JedTech
    abstract = Configs to add Tweakscale functionality to Making History Expansion. Requires Tweakscale Mod.
    license = WTFPL http://www.wtfpl.net/
    Homepage = https://forum.kerbalspaceprogram.com/index.php?/topic/101540-14x-tweakscale-v239mar-09/&page=52
    description = Requires [TweakScale](https://spacedock.info/mod/127/TweakScale)

This is simply additional configs to add TweakScale functionality to parts included in the Making History Expansion.

These configs will probably be included with the next TweakScale release. So Please uninstall this mod when TweakScale is updated to 1.4.2+

Please direct questions about this pull request to [JedTech](https://spacedock.info/profile/JedTech).

### CODE REVIEW

**Comment by HebaruSan** [comment]
@dbent, would this be the right syntax for depending on the DLC?

```json
    "depends": [ { "name": "MakingHistory-DLC" } ]
```

And is it safe to do that before everyone upgrades to 1.25?

**Comment by dbent** [comment]
> @dbent, would this be the right syntax for depending on the DLC?

Yes.

> And is it safe to do that before everyone upgrades to 1.25?

Yes, you just won't be able to install the mod (without ignoring dependencies).

**Comment by HebaruSan** [comment]
Hmm, the pull request validation scripts might need a little updating...

> TweakscaleMakingHistoryConfigs 1.0e requires MakingHistory-DLC but it is not listed in the index, or not available for your version of KSP.

I'm assuming we could simulate the DLC in our dummy installs without too much difficulty.

**Comment by HebaruSan** [comment]
#rebuild

**Pull request merged**
