### PR TITLE
Add Contract Pack: The K-Files

### PR DESCRIPTION
**Pull request by severedsolo**

### CODE REVIEW

**Comment by plague006** [comment]
line 14 needs your closed square bracket `]` and a comma

**Comment by severedsolo** [comment]
Can't see anything obviously wrong - may be the AVC file though, I'll look at that later.

**Comment by severedsolo** [comment]
Huh. I presume this is the problem:

2251 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on ContractConfigurator found, but nothing provides it.

ContractConfigurator is definitely listed (and my other contract packs are indexed fine)

**Comment by plague006** [comment]
Closing and re-opening to force a new Jenkins build.

**Comment by plague006** [comment]
It took me a long while to figure out what was up, lol.

You've specified a minimum `ContractConfigurator` version of `1.8.0`. `1.8.0` of CC is only compatible with ksp_version `1.0.5`. Meanwhile, the `ksp_version` compatibility in your .version file indicates your mod is only compatible up to `1.0.4`.

2 potential fixes are 1) drop the version requirement for CC 2) create a new release of your mod with your up-to-date .version file

**Comment by severedsolo** [comment]
I'll do both, as I'll have to make a new release for CKAN anyway for 1.0.5

**Comment by plague006** [comment]
This passes and works for 1.0.4. I'll note that the compatibility for 0.90.0 can't be fulfilled (because of the min_version of CC set) but that's not a significant issue. Merging this with my thanks.

**Comment by severedsolo** [comment]
Oh yeah, that's just a leftover as I copied KSS's netkan file. Cheers for your help!

**Pull request merged**
