### PR TITLE
Add BearLandingLegLTB (fixed KerbalStuffBot submission)

### PR DESCRIPTION
**Pull request by politas**
closes #2887

### CODE REVIEW

**Comment by politas** [comment]
5478 [1] FATAL CKAN.NetKAN.Program (null) - Error converting value "http:\\www.samuelesnow.com" to type 'System.Uri'. Path 'website', line 1, position 605.

This makes no sense to me. BearPod-MK1 has the exact same homepage, and that's fine. Maybe there's been a change to netkan?

**Comment by plague006** [comment]
BearPod-MK1 has the same homepage yes, but it isn't fine. On http://status.ksp-ckan.org/ you can see it's now failing. In the past it merged with a different address (though still not a valid one as it had the @ symbol in it).

Pinging @dbent and/or @techman83 to have a look into this. In https://github.com/KSP-CKAN/NetKAN/pull/2995 I tried hardcoding the homepage but it seems to fail regardless as soon as it tries converting the website.

**Comment by dbent** [comment]
I'll see if I can make a fix for this today.

**Comment by plague006** [comment]
Following the link, there's a curse download (yay.. manual indexing..)

**Pull request closed without merging**
