### PR TITLE
Add Sigma OPM Expansion from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Sigma88, to add [Sigma OPM Expansion](https://kerbalstuff.com/mod/912/Sigma%20OPM%20Expansion) to CKAN.

Please direct questions about this pull request to [Sigma88](https://kerbalstuff.com/profile/Sigma88).

### CODE REVIEW

**Comment by dbent** [comment]
As noted in #1533, we should wait until OPM uses custom PQS cache file locations that this can then overwrite with a MM patch.

**Comment by Sigma88** [comment]
I'm going to release a compatible patch in the next few days
thanks to anyone involved :)

**Comment by Sigma88** [comment]
The current release should work fine with CKAN

let me know if there are any problems

**Comment by Sigma88** [comment]
I thought this might help

technically this mod does not require OPM to be installed

without OPM:
- you won't get any changes to OPM planets (duh!)
- you will get Pluron-Khato in an orbit more suitable for Stock

without kopernicus:
- the planet pack won't load so this is a requirement

this is fully compatible with #1609

if someone has this mod with at the same time #1309, that mod should be installed and this mod (#1605) should be ignored

**Comment by dbent** [comment]
Replaced by #1678

**Pull request closed without merging**
