### PR TITLE
Increase Atomic Age KSP Compatibility

### PR DESCRIPTION
**Pull request by politas**
Forum users report this mod is working (mostly) fine in KSP 1.1

### CODE REVIEW

**Comment by DinCahill** [comment]
The zip file contains an "AtomicAge v3.1" directory (which is confusing since the zip is Atomic_Age-3.2.zip), which contains GameData and Ships directories. The mod in GameData is installed, but not the Ships. Should we be installing the ships?

**Comment by politas** [comment]
We often don't

**Comment by politas** [comment]
But now we will

**Comment by DinCahill** [comment]
LGTM. Thanks :rocket: :shipit:

**Pull request merged**
