### PR TITLE
RoadToKosmos-core Support

### PR DESCRIPTION
**Pull request by Niemand303**
Added manually a  NetKAN for my RtK core files mod

### CODE REVIEW

**Comment by Dazpoet** [comment]
You have an extra comma on the comment line in the install stanza.

**Comment by Niemand303** [comment]
Why did you closed? The automatic version is bad and doesn't have all the requirements. Fixed the typo.

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
#rebuild

**Pull request merged**
