### PR TITLE
KerbalCitiesPack

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #4385
using new netkan.sh generation script

### CODE REVIEW

**Comment by politas** [comment]
Ok, there's an existing kerbalCitiesPack.frozen that you should delete (assuming this is a new source for the same mod)

**Comment by linuxgurugamer** [comment]
I also saw that this file had the issue of a dir with only a subdir inside, so I changed the "find" to a "file"

**Comment by politas** [comment]
This does not look like the same Kerbal Cities Pack that Amankduffers made.

**Comment by politas** [comment]
Could use a homepage resource declaration:

    "resources": {
       "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/144012-kerbal-cities-pack"
   },

**Comment by politas** [comment]
Great stuff! Merging with thanks!

**Pull request merged**
