### PR TITLE
Tags for NodeSplitter

### PR DESCRIPTION
**Pull request by HebaruSan**
#7980 added this mod without tags.
Now it has them.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
thanks.  I need t update my shell script for this
Whats the link to the suggested tags?

**Comment by HebaruSan** [comment]
The tags wiki is here:

- https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags

**Comment by linuxgurugamer** [comment]
thank you

**Comment by HebaruSan** [comment]
netkan.exe will actually warn about this now (with the URL!), in addition to a few other things. It can be worth checking the pull request validation output even if it succeeds, just in case.

**Pull request merged**
