### PR TITLE
Create CrewQueue.netkan

### PR DESCRIPTION
**Pull request by Blu3wolf**

### CODE REVIEW

**Comment by politas** [comment]
I think you need to remove lines 9 and 13, and wait for FingerboxesCore to be added, and then this should pass.

**Comment by mgsdk** [comment]
Removing lines 9 and 13 would make the file look more tidy, but I don't believe the build bot will fail you for that. The current issue is with the install stanza. Requesting installation into a _specific_ folder in GameData requires spec "v1.2" or higher as far as I can tell.

**Comment by Blu3wolf** [comment]
there are plenty of other netkan files already with blank lines for spacing. I can remove them if its a proble, but I assumed it wasnt an issue

**Comment by Blu3wolf** [comment]
It does mgsdk you are correct. I will fix that.

**Comment by mgsdk** [comment]
The remote source does not match a known import method. Where is this mod scraped from? KS? GitHub?

**Comment by Blu3wolf** [comment]
Github. Looks like I goofed that up as well...

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
dependency does not match the name given to the core package. Should be `FingerboxesCore`

**Pull request merged**
