### PR TITLE
Sound track Editor Forked

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
@HebaruSan Could you look at this, please.  Seems that the build environment doesn't include the mono directories which this needs

**Comment by DasSkelett** [comment]
Yeah, we don't create `KSP_x64_Data` in our fake instances.
But are you sure this folder exists in real instances? Because I can't spot it in my KSP install. There's only `KSP_Data`:

grafik

(It's a Steam install on Linux)

**Comment by linuxgurugamer** [comment]
Absolutely positive.  I just looked at the zip file for KSP 1.8.1.

I see, it's there on the Windows install, not Linux or OSX

Can you mark this as a Windows-only install?

**Comment by DasSkelett** [comment]
No, we don't have a way to mark mods exclusive for one OS, there have been some discussions in https://github.com/KSP-CKAN/CKAN/issues/489 and https://github.com/KSP-CKAN/CKAN/issues/1739.

Without knowing anything about KSP's interaction with Mono and the folder structure philosophy, is there something that speaks against putting the DLL in `KSP_Data`? Or does KSP get confused with the architecture then?

**Comment by linuxgurugamer** [comment]
> No, we don't have a way to mark mods exclusive for one OS, there have been some discussions in [KSP-CKAN/CKAN#489](https://github.com/KSP-CKAN/CKAN/issues/489) and [KSP-CKAN/CKAN#1739](https://github.com/KSP-CKAN/CKAN/issues/1739).
> 
> Without knowing anything about KSP's interaction with Mono and the folder structure philosophy, is there something that speaks against putting the DLL in `KSP_Data`? Or does KSP get confused with the architecture then?

There are different types of DLLs.  The ones in the GameData are c# DLLs, and are read by the Mono interpreter.  The other DLLs are Windows DLLs, and are needed by the OS

**Comment by DasSkelett** [comment]
Oh yeah, the old "Who at Microsoft though it was a good idea to assign two entirely different file types with completely different environment requirements the same file extension".

Your best bet for now is to include something like "Windows only" in the mod name, like `Advanced Fly-By-Wire` does.

**Comment by HebaruSan** [comment]
This was attempted and failed before with the original mod:

- https://github.com/KSP-CKAN/NetKAN/issues/5953
- https://github.com/KSP-CKAN/NetKAN/pull/5984
- https://github.com/KSP-CKAN/CKAN-meta/pull/1300

**Comment by linuxgurugamer** [comment]
Well, I'm hoping to get it working on Linux.  It may only need testing, for now I'd like to keep it this way since I'm going to be supporting both 1.7.3 version and 1.8.x version.
I do see that the original had the libmpg123 in the Mono directory, I'll be adding that in the next release, which hopefully will take care of the linux/osx issue
I will need to add one stanza to this to take care of that

**Comment by linuxgurugamer** [comment]
Stanza is added, could you just verify everything is ok?  Once it's in, I'll be testing the install on Linux & OSX later today

**Comment by HebaruSan** [comment]
https://ci.ksp-ckan.space/job/NetKAN/9191/console

```
9843 [1] FATAL CKAN.NetKAN.Program (null) - Could not find KSP_Data entry in zipfile to install
```

**Comment by HebaruSan** [comment]
Please add tags.
https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags

**Comment by linuxgurugamer** [comment]
I'll remove the audio and music in a minute, just doing a new build to add in the new directory

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Ok, current failure is expected, I'll let you merge it if you think it's ok.
Please let me know, since once the first file is indexed, I'll have to update it to get the other version indexed

**Comment by HebaruSan** [comment]
Why is it expected or OK that the install fails? Won't that mean that people won't be able to install it?

```
Installing mod "SoundTrackEditorForked 4.6.1.2"
Could not find a part of the path "/home/jenkins/workspace/NetKAN/dummy_ksp/KSP_Data/Mono/libmpg123-0.dll".
Build step 'Execute shell' marked build as failure
```

**Comment by linuxgurugamer** [comment]
No, it's failing because the test environment isn't making the KSP_Data and KSP_x64_Data directories

**Comment by HebaruSan** [comment]
OK, I will try it locally to make sure...

**Comment by HebaruSan** [comment]
Unfortunately it still fails on a real game install:

```
Installing mod "SoundTrackEditorForked 4.6.1.2"
Could not find a part of the path "/home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/KSP_Data/Mono/libmpg123-0.dll".
```

**Comment by linuxgurugamer** [comment]
oh.  Nuts.  I'll have to make two copies, one for windows and one for linux/mac

**Comment by linuxgurugamer** [comment]
Ok, I've made it into two, both are still using the same file on Spacedock

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
How can I test this locally?  use netkan.exe and then ckan to use the generated ckan file?

**Comment by linuxgurugamer** [comment]
so testing locally, it isn't creating the directories, how can Imake it do that?

**Comment by HebaruSan** [comment]
I don't think you can, that's why #5953 resulted in this module being frozen.

**Comment by linuxgurugamer** [comment]
oh, yuck
Ok, leave this for now, I have a couple of ideas I'll try locally.  Will Ping you if I figure something out

**Pull request closed without merging**
