### PR TITLE
AdditionalProgressionContracts

### PR DESCRIPTION
**Pull request by linuxgurugamer**
created by new automated script
hand verified
Closes #4437

### CODE REVIEW

**Comment by politas** [comment]
Ah. Thanks to KSP-CKAN/CKAN#1477, that find doesn't work. Try this instead:

    {
        "find": "additionalprogressioncontracts",
        "install_to": "GameData/ContractPacks"
    }

**Comment by linuxgurugamer** [comment]
So, if I understand this problem correctly, if there is no GameData directory (as in this case), and then there is a directory (such as ContractPacks) with only another directory in it, it will fail?

What would happen if there are two directories below the top dir?  or a directory and a file?

Thanks

**Comment by linuxgurugamer** [comment]
Also, what would happen if there WAS a GameData, such that the file contained:
GameData/ContractPacks/packname/(allfiles)

**Comment by politas** [comment]
The existence of GameData is irrelevant. We can't find a directory that only contains subdirectories, not files. (For now; it's a bug I'm planning to try to fix soon. :)

**Comment by politas** [comment]
Looks good to me. Merging with thanks!

**Pull request merged**
