### PR TITLE
Airports for Real Solar System / KSC Switcher

### PR DESCRIPTION
**Pull request by miki-g**
some real airports locations as new additional KSC

### CODE REVIEW

**Comment by plague006** [comment]
You didn't correctly attach the .zip to the release and so netkan can't detect the download. You can hit the edit button next to a release to open the screen shown [here](http://puu.sh/oSLgC/5db7064b05.png) and then click "selecting them" to select the .zip file to upload and attach to the release.

**Comment by miki-g** [comment]
thanks, tests re-run again automatically?

**Comment by politas** [comment]
#rebuild

**Comment by plague006** [comment]
As you have a `$vref` set, `ksp_version_min` and `ksp_version_max` are redundant. After that change this looks ready to go.

**Comment by miki-g** [comment]
pff ... f.off licenses :)))
thanks for reply, i am not software developer and dont have too many time to study bunch of licenses ... my choice is simple ... if CC0 is good for ckan, then is good for me :D

**Comment by plague006** [comment]
CKAN actually uses MIT. CC0 is only for metadata.

**Comment by miki-g** [comment]
thankx, CC0 is ok for now? we dont need more and more test on jenkins :)

i dont have fluent english, but wtfpl looks good :) (maybe i change to this in future addon updates, for now ok)

?

**Comment by plague006** [comment]
Sounds good, thanks for the contribution.

**Comment by miki-g** [comment]
thanks for help with first steps in ckan/netkan and github project releasing

good luck & have a nice day ;)

:+1:

**Pull request merged**
