### PR TITLE
Add support for Semi-Saturable Reaction Wheels

### PR DESCRIPTION
**Pull request by pap1723**

### CODE REVIEW

**Comment by HebaruSan** [comment]
We should update the current listing unless both forks are planned to be maintained in parallel:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/SemiSaturatableRW.netkan

**Comment by HebaruSan** [comment]
Also "GNU" isn't in the list of licenses. If you just delete that line, we'll get the proper license directly from the repo automatically.

**Comment by HebaruSan** [comment]
FYI you can easily search for indexed mods on the status page:

http://status.ksp-ckan.space/

**Comment by pap1723** [comment]
I never knew that page existed. Thank you! I will resubmit. Sorry all of
the recent ones have required more work on your end.

**Comment by PhineasFreak** [comment]
The new SSRW version is only valid for KSP 1.4+. Older KSP versions should be served by the original SSRW distribution.

**Comment by HebaruSan** [comment]
I took the liberty of migrating your changes to the existing netkan.
@PhineasFreak, don't worry, the old versions won't be affected. They'll still be there.

**Comment by HebaruSan** [comment]
#rebuild

**Pull request merged**
