### PR TITLE
Add KerbalGalaxy2 Remaster from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of XxLedvin25xX, to add [KerbalGalaxy2 Remaster](https://spacedock.info/mod/2146/KerbalGalaxy2%20Remaster) to CKAN.

Please direct questions about this pull request to [XxLedvin25xX](https://spacedock.info/profile/XxLedvin25xX).

Mod details:
    name = /mod/2146/KerbalGalaxy2%20Remaster
    author = XxLedvin25xX
    abstract = Thi﻿s mod adds a galaxy, with solar systems orbiting a black hole, and wormhole near Jool that leads to the Gargantua system.
    license = CC-BY-NC-SA﻿
    Homepage = https://forum.kerbalspaceprogram.com/index.php?/topic/184275-beta17x-kerbalgalaxy2-remaster/
    description =
[BETA][1.7.x]KerbalGalaxy REMASTER

 

------------------------------------------------------------------------------------

 

This mod is a BETA, can contain many errors, I recommend waiting for version 1.0, the BETA can damage your SAVE, be careful, YOU HAVE BEEN WARNED!

 

------------------------------------------------------------------------------------

 

The Original Mod Made By Artyomka15.

Link To Orginal Mod "KerbalGalaxy2"

Remastered By: XxLedvin25xX and Olympic1

License: CC-BY-NC-SA

------------------------------------------------------------------------------------

You Need Kopernicus, Module Manager and TextureReplacer

**Download the Textures From [HERE](https://mega.nz/#!eHplXKzT!2PhEZFAI0B7TDbRUv3jXQ_VITX-W6A4vMouYVb8krmY)**

------------------------------------------------------------------------------------ 

1- Download Kopernicus, ModuleManager and TextureReplacer for your game version.

2- Download The "[BETA] (1.7.x) V0.8 KerbalGalaxyRemaster".

3- Download the "KGRemaster Textures".

4- Drop "GameData" in your folder "KerbalSpaceProgram" and replace all.

5- Enjoy!

------------------------------------------------------------------------------------ 

This mod is only an update for the new versions I do not intend to earn credit, or money, or anything, only that the community enjoys.

------------------------------------------------------------------------------------

 

This mod adds a galaxy, with solar systems orbiting a black hole, and wormhole near Jool that leads to the Gargantua system, this mod adds the following stars with their planets:

------------------------------------------------------------------------------------

WhormHole in Jool to Gargantua 

------------------------------------------------------------------------------------

POLARIS

- Green ocean planet PANDORA

- Yellow gas giant RYLA

- Icy moon HOTH 

- Moon CITE 

------------------------------------------------------------------------------------

Brown Dwarf NIM

------------------------------------------------------------------------------------

Red dwarf ERAVATE

- Planet SEHERA 

- Planet EDEN 

------------------------------------------------------------------------------------

Blue supergiant Oblok

- Gas giant AELION

- Dwarf planet PHOENIX  

- Dwarf planet SUNFLOWER 

------------------------------------------------------------------------------------

Neutron star Osiris

- Planet Ida 

- Gas planet Isus 

- Moon Rocko 

- Moon Volco 

------------------------------------------------------------------------------------

Yellow-White star Abbadon

- Planet Violetta

- Planet Nix

- Moon Icy

- Planet Aphrodite

------------------------------------------------------------------------------------

Gargantua system

- Miller's planet 

- Mann's planet  

------------------------------------------------------------------------------------

Bugs and Reports

- The KSC is misplaced on the first screen, but the rockets are still working the same and the takeoff zone is the same, the map inside the ship is not affected by this, but in the research center if it is affected.

ckan compat add 1.6

### CODE REVIEW

**Comment by HebaruSan** [comment]
Install instructions:

```
3- Download the "KGRemaster Textures". Link http://bit.ly/KGRTex (This link is only a shortener and does not contain ads)
```

That link:

image

@Olympic1, you're listed as co-author. What's going on with this texture download?

**Comment by HebaruSan** [comment]
#rebuild

**Comment by Olympic1** [comment]
Don't use the shortened link as that needs a key for some reason, use the link on SD or the thread. I don't know if we can let CKAN download from mega.nz though.

**Comment by HebaruSan** [comment]
> I don't know if we can let CKAN download from mega.nz though.

Yeah, doesn't look like it, at least not from that URL. I keep getting a rich page instead of a download, and ` wget 'https://mega.nz/#!eHplXKzT!2PhEZFAI0B7TDbRUv3jXQ_VITX-W6A4vMouYVb8krmY'` saves an index.html file instead of the zip file.

Is there any other way to access this file? (For example, put it in the same download on SpaceDock?)

**Comment by HebaruSan** [comment]
Deleted from SpaceDock.

**Pull request closed without merging**
