### PR TITLE
Add Distant Object Enhancement Continued from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of TheDarkBadger, to add [Distant Object Enhancement Continued](https://spacedock.info/mod/2274/Distant%20Object%20Enhancement%20Continued) to CKAN.

Please direct questions about this pull request to [TheDarkBadger](https://spacedock.info/profile/TheDarkBadger).

Mod details:
    name = /mod/2274/Distant%20Object%20Enhancement%20Continued
    author = TheDarkBadger
    abstract = Distant Object Enhancement Continued is a visual enhancement mod that makes objects realistically visible over large distances.Click and dra
    license = CC Attribution 4.0 International (CC BY 4.0)
    Homepage = 
    description =
Distant Object Enhancement Continued is a visual enhancement mod that makes objects realistically visible over large distances. It is an update of MOARdv's Distant Object Enhancement bis v1.9.1.1, which is a update of Rubber Ducky's Distant Object Enhancement.

I have adopted the mod with permission of MOARdv

This version keeps Ducktopia's CC Attribution 4.0 International license.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Since it's an adoption of an existing mod with permission, we should probably update the existing modules rather than creating a new one:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DistantObject.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DistantObject-default.netkan

@TheDarkBadger, I see that you have this on both GitHub and SpaceDock. Do you have a preference which one we use? GitHub would probably be smoother for CKAN.

**Comment by TheDarkBadger** [comment]
Either is fine

**Comment by HebaruSan** [comment]
@TheDarkBadger, the release on GitHub currently has the file as a link embedded in the description. Can you please move it to a separate asset? This is done by editing the release and clicking on this section:

image

**Comment by TheDarkBadger** [comment]
Thanks, done

**Comment by DasSkelett** [comment]
Should we update the name property @HebaruSan ? It looks like @TheDarkBadger wants to go with `Distant Object Enhancement Continued`.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Sure, why not. Also we can add all the authors...

**Comment by HebaruSan** [comment]
#rebuild

**Pull request merged**
