### PR TITLE
Modular Segmented SRBs

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by HebaruSan** [comment]
Please don't forget tags.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
@linuxgurugamer  can you please add tags when indexing new mods? 

https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags

**Comment by linuxgurugamer** [comment]
Done

**Comment by HebaruSan** [comment]
Thanks!

**Pull request merged**
