### PR TITLE
HullcamVDSContinued

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by DinCahill** [comment]
Are we supposed to also `provide` HullcamVDS when making a Continued version? Not that we have anything which depends on HullcamVDS. Just asking.

**Comment by politas** [comment]
If it's providing a DLL and directory with the same name as the original, then we should use a "provides".

**Comment by politas** [comment]
Actually, KerbalTubes depends on HullCamVDS, though admittedly, the last version of that is for KSP 1.0.5 so far.

**Comment by linuxgurugamer** [comment]
I'm out of town, will update this tomorrow

**Pull request closed without merging**
