### PR TITLE
Update RCS Build Aid to use AVC for NetKAN version

### PR DESCRIPTION
**Pull request by Blu3wolf**

### CODE REVIEW

**Comment by Dazpoet** [comment]
Hm seems there are no releases in the github repository. Unsure why since we seem to have indexed from there before.

**Comment by Blu3wolf** [comment]
No Idea... could be deliberate? A mess up on the mod authors part?

**Comment by Dazpoet** [comment]
Seems author is fixing 0.7 himself since it is available on curse https://github.com/KSP-CKAN/CKAN-meta/pull/498

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://esportskart.com/cousin.php?1rvla>

 

blue@blu3wolf.com

**Pull request closed without merging**
