### PR TITLE
Fixed for SpaceDock

### PR DESCRIPTION
**Pull request by Magion**

### CODE REVIEW

**Comment by dbent** [comment]
Hi @Magion, you'll also want to change the filename from `WernherChecker.frozen` to `WernherChecker.netkan` so the index will actually read it.

**Comment by Magion** [comment]
Why it was renamed to .frozen before?

**Comment by dbent** [comment]
Because when KerbalStuff fell off the face of the earth we didn't want to spend time making requests we knew were going to fail.

LGTM, merging, thanks.

**Comment by Magion** [comment]
Aaah, sure! That makes sense.

**Pull request merged**
