### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by linuxgurugamer**
This is for the Spacetux Agency recently added to kerbalstuff.com

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
This passes netkan.exe on Windows, is this failure related to the changes at kerbalstuff.com (he disabled RC4)

**Comment by Dazpoet** [comment]
By clicking "Details" to the right of the "Failed - Merged build finished" and then choosing Console Output at the top you can see what failed the build. Right now all PRs based on a $kref pointing to KS fail due to https://github.com/KSP-CKAN/CKAN-support/issues/107

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Pull request merged**
