### PR TITLE
Create kunedo.netkan

### PR DESCRIPTION
**Pull request by Kunedo83**

### CODE REVIEW

**Comment by HebaruSan** [comment]
The identifier should probably be FanRadiator rather than your user name, in case you decide to make another mod at some point, and to match the `name` property. Any objections?

**Comment by Kunedo83** [comment]
> The identifier should probably be FanRadiator rather than your user name, in case you decide to make another mod at some point, and to match the `name` property. Any objections?

ok changing indentifier to fanradiator , thx for warning :)

**Comment by Kunedo83** [comment]
Is it possible to install it in gamedata/kunedo/fanradiator? for next mods install in same folder.

**Comment by HebaruSan** [comment]
If you structure the ZIP file that way, yes. Currently you would have GameData/Kunedo/Parts/fanradiator as it is in the ZIP.

**Comment by Kunedo83** [comment]
okey, 5 minutes im changing

**Pull request merged**
