### PR TITLE
Freeze StockVisualEnhancements

### PR DESCRIPTION
**Pull request by politas**
Author has requested removal, and installation is wrong

### CODE REVIEW

**Comment by TeddyDD** [comment]
Here is fixed netkan for medium resolution variant of this mod (If anyone interested) https://gist.github.com/TeddyDD/8d32965e71bae7dd7d4a0ba11a0aab82

**Comment by politas** [comment]
The Scatterer config files in SVE have been modified,so you need to take them into account. This is part of why I froze the mod. CKAN installation was broken.

**Comment by TeddyDD** [comment]
Yeah, you right. That means Scatterer would have to be spitted into scatterer, scatterer-confing and scatterer-sunflare. I can do this later, but I have to compare all three editions of SVE with Meld to avoid any surprises.

**Comment by politas** [comment]
I was actually thinking of just doing the same thing with Scatterer as we do for EVE in SVE

**Comment by politas** [comment]
I'm checking with the new mod maintainer about any changes in the other bundled mods.

**Pull request merged**
