### PR TITLE
Add ColorfulFuelLines.netkan

### PR DESCRIPTION
**Pull request by plague006**
Closes  #1867

Pinging @NecroBones just to let you know this is being added.

### CODE REVIEW

**Comment by NecroBones** [comment]
Awesome, thanks. I may have to add some required dependencies if I can get the new functionality working. Will open another issue when the time comes.

**Comment by NecroBones** [comment]
Should I open a new issue? The mod now has dependencies. It requires ModuleManager and FirespitterCore.

**Comment by plague006** [comment]
Nope, thanks for the heads up. =)

**Comment by NecroBones** [comment]
Awesome, thanks :)

**Comment by dbent** [comment]
CI looks good and manual test looks fine, merging.

**Pull request merged**
