### PR TITLE
Create RealScaleBoosters.netkan

### PR DESCRIPTION
**Pull request by NecroBones**

### CODE REVIEW

**Comment by NecroBones** [comment]
Supersedes #2965

**Comment by pjf** [comment]
This looks fantastic, and especially thanks for adding the relations with other mods.

Thank you so much for your patience and kind words on the forums, too!

~ Paul

```
$ ckan.exe show RealScaleBoosters
Real Scale Boosters: Realistically sized rocket parts, with realistic stats and performance, heavily based on real world rockets. 

Module info:
- version:	0.2.1
- authors:	NecroBones
- status:	stable
- license:	CC-BY-NC-SA

Depends:
- ModuleManager

Recommends:
- HangarExtender
- KerbalJointReinforcement

Suggests:
- RealSolarSystem
- CommunityTechTree

Provides:
- RealScaleBoosters

Resources:
- homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/129134-RSB
- kerbalstuff: https://kerbalstuff.com/mod/1435/Real%20Scale%20Boosters

Filename: 2C116FCE-RealScaleBoosters-0.2.1.zip

Showing 158 installed files:
- GameData/RealScaleBoosters/FX/RSBemitterF1.mu
- GameData/RealScaleBoosters/FX/RSBemitterH1.mu
- GameData/RealScaleBoosters/FX/RSBemitterJ2.mu
- GameData/RealScaleBoosters/FX/RSBemitterJ2X.mu
- GameData/RealScaleBoosters/FX/RSBemitterRS68.mu
- GameData/RealScaleBoosters/FX/RSBemitterSTSSRB.mu
- GameData/RealScaleBoosters/FX/RSBemitterUllage.mu
- GameData/RealScaleBoosters/FX/SYflameParticle01.dds
- GameData/RealScaleBoosters/Parts/Ares/RSBares-Specular.dds
- GameData/RealScaleBoosters/Parts/Ares/RSBdecouplerAresI3m.cfg
- GameData/RealScaleBoosters/Parts/Ares/RSBdecouplerAresI3m.mu
- GameData/RealScaleBoosters/Parts/Ares/RSBdecouplerAresI5m.cfg
- GameData/RealScaleBoosters/Parts/Ares/RSBdecouplerAresI5m.mu
- GameData/RealScaleBoosters/Parts/Ares/RSBtankAresIstage2.cfg
- GameData/RealScaleBoosters/Parts/Ares/RSBtankAresIstage2.mu
- GameData/RealScaleBoosters/Parts/Atlas/RSBatlas-Specular.dds
- GameData/RealScaleBoosters/Parts/Atlas/RSBdecouplerAtlas500Payload.cfg
- GameData/RealScaleBoosters/Parts/Atlas/RSBdecouplerAtlas500Payload.mu
- GameData/RealScaleBoosters/Parts/Atlas/RSBengineAtlasSRB.cfg
- GameData/RealScaleBoosters/Parts/Atlas/RSBengineAtlasSRB.mu
- GameData/RealScaleBoosters/Parts/Atlas/RSBinterstageAtlasCentaur400.cfg
- GameData/RealScaleBoosters/Parts/Atlas/RSBinterstageAtlasCentaur400.mu
- GameData/RealScaleBoosters/Parts/Atlas/RSBinterstageAtlasCentaur500.cfg
- GameData/RealScaleBoosters/Parts/Atlas/RSBinterstageAtlasCentaur500.mu
- GameData/RealScaleBoosters/Parts/Atlas/RSBtankAtlasCentaur.cfg
- GameData/RealScaleBoosters/Parts/Atlas/RSBtankAtlasCentaur.mu
- GameData/RealScaleBoosters/Parts/Atlas/RSBtankAtlasVcore.cfg
- GameData/RealScaleBoosters/Parts/Atlas/RSBtankAtlasVcore.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBadapterDeltaIV5m3m.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBadapterDeltaIV5m3m.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBdecouplerDeltaIV4m.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBdecouplerDeltaIV4m.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBdecouplerDeltaIV5m.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBdecouplerDeltaIV5m.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBdeltaIV-Specular.dds
- GameData/RealScaleBoosters/Parts/Delta/RSBdeltaIVsrm.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBdeltaIVsrm.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVcore.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVcore.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss4m.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss4mL.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss4mT.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss4mU.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss5m.cfg
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss5mL.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss5mT.mu
- GameData/RealScaleBoosters/Parts/Delta/RSBtankDeltaIVdcss5mU.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineAresSRB.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineAresSRB.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineBase-Specular.dds
- GameData/RealScaleBoosters/Parts/Engines/RSBengineBell-Emissive.dds
- GameData/RealScaleBoosters/Parts/Engines/RSBengineBell-Specular.dds
- GameData/RealScaleBoosters/Parts/Engines/RSBengineF1.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineF1.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineH1.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineH1.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineJ2.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineJ2.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineJ2X.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineJ2X.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRD180.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRD180.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRD180-Specular.dds
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRL10A42.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRL10A42.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRL10B2.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRL10B2.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRS25.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRS68.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineRS68.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBengineSTSSRB.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBengineSTSSRB.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBnoseconeSTSSRB.cfg
- GameData/RealScaleBoosters/Parts/Engines/RSBnoseconeSTSSRB.mu
- GameData/RealScaleBoosters/Parts/Engines/RSBSTS-SRB-Specular.dds
- GameData/RealScaleBoosters/Parts/Etc/RSBdecouplerRadial01.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBdecouplerRadial01.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBetc-Specular.dds
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingAresI5m.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingAresI5m.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingAtlasCentaur305.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingAtlasCentaur305.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingAtlasCentaur381.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingAtlasCentaur381.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingDeltaIV4m.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingDeltaIV4m.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingDeltaIV5m.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBfairingDeltaIV5m.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone10m.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone10m.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone305.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone305.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone381.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone381.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone5m.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone5m.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone6m.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBnosecone6m.mu
- GameData/RealScaleBoosters/Parts/Etc/RSBstrutXL.cfg
- GameData/RealScaleBoosters/Parts/Etc/RSBstrutXL.dds
- GameData/RealScaleBoosters/Parts/Saturn/RSBdecouplerSaturnSII.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBdecouplerSaturnSII.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBdecouplerSaturnSIVB.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBdecouplerSaturnSIVB.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBdecouplerSaturnSIVB2.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBdecouplerSaturnSIVB2.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBfairingSaturn10m.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBfairingSaturn10m.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBfairingSaturn6m.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBfairingSaturn6m.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBfinSaturnSIB-black.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBfinSaturnSIB-black.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBfinSaturnSIB-white.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBfinSaturnSIB-white.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBfinSaturnSIC.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBfinSaturnSIC.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBprobeSaturn.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBprobeSaturn.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBsaturnAPS.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBsaturnAPS.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBsaturn-Specular.dds
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturn10m6m.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturn10m6m.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturn10m7m.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturn10m7m.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturn6m5m.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturn6m5m.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSIB.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSIB.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSIC.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSIC.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSII.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSII.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSIVB.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBtankSaturnSIVB.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBullageSaturnSII.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBullageSaturnSII.mu
- GameData/RealScaleBoosters/Parts/Saturn/RSBullageSaturnSIVB.cfg
- GameData/RealScaleBoosters/Parts/Saturn/RSBullageSaturnSIVB.mu
- GameData/RealScaleBoosters/Patches/0_TechTree.cfg
- GameData/RealScaleBoosters/Patches/Misc.txt
- GameData/RealScaleBoosters/Patches/RealScaleBoosters_TweakScale.cfg
- GameData/RealScaleBoosters/RealScaleBoosters.version
- GameData/RealScaleBoosters/RealScaleBoosters-CHANGELOG.txt
- GameData/RealScaleBoosters/RealScaleBoosters-README.txt
- GameData/RealScaleBoosters/SharedTextures/RSBfairing.dds
- GameData/RealScaleBoosters/Ships/VAB/RSB Ares I.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V 401.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V 431.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V 502.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V 532.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V 552.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V HLV.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Delta IV Heavy.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Delta IV M+ (4,4).craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Delta IV M+ (5,4).craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Saturn IB.craft
- GameData/RealScaleBoosters/Ships/VAB/RSB Saturn V.craft
```

**Comment by NecroBones** [comment]
Thanks, and you're welcome.

**Comment by plague006** [comment]
Had a glance at the installed files and noticed `GameData/RealScaleBoosters/Ships/VAB/RSB Atlas V HLV.craft`.

In some cases (mostly contract packs) .craft files are intentionally installed into `GameData` but from the look of things, they should be installed to `Ships`, correct?

**Comment by NecroBones** [comment]
I'm good with that. For now I've been assuming it would be up to the player to copy them out if they wanted to use them, but if this takes that load off of the player then that's good.

**Pull request merged**
