### PR TITLE
Add Pathfinder-USILS-CommunityPatch.netkan

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #2349

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I'm not sure what is going on.

It says no files found in Pathfinder, but Pathfinder is available in CKAN already.


109 [1] WARN CKAN.KSPManager (null) - 7f34b7dadea974cc5375c68adcf188057d88bd32 at /home/jenkins/workspace/PR builder - NetKAN metadata/NetKAN/dummy_ksp is not a vaild install
372 [1] WARN CKAN.Curl (null) - Curl environment not pre-initialised, performing non-threadsafe init.
1631 [1] FATAL CKAN.NetKAN.Program (null) - No files found in Pathfinder to install!
Build step 'Execute shell' marked build as failure

**Comment by linuxgurugamer** [comment]
Please note that the problem I had was apparently due to a change in the netkan.exe program.  
It used to be (and you can see in older .netkan files), that the "File:" line didn't need the complete path to the directory.  So I had in there:
"File:" "Pathfinder"
  To make this work, I had to change this to:
"File:" "GameData/Pathfinder"

**Comment by Olympic1** [comment]
The old `file` element didn't require a filepath, but this was changed in v1.5.0 to `find`. So using the `find` element only requires the folder name you want to install into `GameData`.

**Comment by plague006** [comment]
Will merge once `"file"       : "GameData/Pathfinder",` is changed to `"find"       : "Pathfinder",` (which will allow netkan to better adapt to any archive structure changes)

**Comment by plague006** [comment]
Ready for merge once `"file"       : "GameData/Pathfinder",` is changed to `"find"       : "Pathfinder",`

**Pull request closed without merging**
