### PR TITLE
SearchAndRescue

### PR DESCRIPTION
**Pull request by linuxgurugamer**
netkan created by new automated script
hand verified

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
close #4443

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
I saw that the rebuild was issued by @techman83  8 times, is there a problem with this?

**Comment by politas** [comment]
There's a problem with the build environment thanks to a change in Jenkins. We need to hand-verify mod installation metadata while that gets fixed.

**Comment by politas** [comment]
This one isn't going to work - there's no Spacedock ModID.

**Comment by linuxgurugamer** [comment]
oops.  I'll get this fixed, it was an earlier version of the script

**Comment by politas** [comment]
Tested locally, works fine. Merging with thanks!

**Pull request merged**
