### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by maj-mal-funqt10n**
added custombarnkit, removed contract configurator & persistent rotation

___

ckan compat add 1.10 1.11

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks for the updates!

**Comment by DasSkelett** [comment]
Hey @maj-mal-funqt10n, it looks like you deleted your mod from SpaceDock. Are you planning to reupload it? Or should we freeze the netkan?

**Comment by maj-mal-funqt10n** [comment]
hi yes i plan to reupload as soon as i can, it broke the forum rules and had to be deleted

**Comment by maj-mal-funqt10n** [comment]
here is the new version https://spacedock.info/mod/2803/CARP

**Pull request merged**
