### PR TITLE
Create DMTanks-SphericalTanks.netkan

### PR DESCRIPTION
**Pull request by Bezzier**
newly released

### CODE REVIEW

**Comment by Bezzier** [comment]
[SphericalTanks_v1_0_0.zip](https://github.com/KSP-CKAN/NetKAN/files/280729/SphericalTanks_v1_0_0.zip)
I don't understand the error? Zip File Attached... appears to have the folder that's supposedly missing.

**Comment by plague006** [comment]
Seems like another case of https://github.com/KSP-CKAN/NetKAN/pull/3824.

I extracted the contents and created a new .zip and had no issues. By chance did you use the right-click -> compress -> "to zip file" option in windows explorer to create the .zip?

**Comment by Bezzier** [comment]
I did, I think.

**Comment by Bezzier** [comment]
This time I created a new .zip file from the file menu in file explorer, then copied the contents into it.... does this one work?

[SphericalTanks_v1_0_0.zip](https://github.com/KSP-CKAN/NetKAN/files/281843/SphericalTanks_v1_0_0.zip)

**Comment by Bezzier** [comment]
seems to work fine now. Hoping for a swift merge.

**Comment by politas** [comment]
That's looking fine as far as I can see. Merging with many thanks!

**Pull request merged**
