### PR TITLE
RealisticRemodel1x fix install

### PR DESCRIPTION
**Pull request by plague006**
The dashes are gone for now but they may be back, and in greater numbers.

### CODE REVIEW

**Comment by politas** [comment]
If they may be back in greater numbers, then a .* would be called for!

**Comment by plague006** [comment]
Well if you're playing joke killer I can play that game, I never said the dashes would be consecutive. Right --p-o-l-i-t-a-s--? :D

**Comment by politas** [comment]
Interestingly, did you know that full stops (aka periods) in gmail addresses are ignored? So First.Last@gmail.com is the same as FirstLast@gmail.com, or indeed F.i.r.s.t.L.a.s.t@gmail.com

**Comment by plague006** [comment]
I did know that, earlier this year either I gave out the wrong address or someone miswrote my address but I got an email at one point to firstnamelastname@gmail.com when what I signed up for was firstname.lastname@gmail.com. Needless to say it was a "wtf" moment before a google search put me at ease.

**Pull request merged**
