### PR TITLE
Index SystemHeat packages

### PR DESCRIPTION
**Pull request by ChrisAdderley**
___

ckan compat add 1.10

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
If I'm understanding this right, this is not working as ModuleManager is not marked for 1.11?

**Comment by HebaruSan** [comment]
Yeah basically. There's a workaround for that, I'll apply it...

**Comment by HebaruSan** [comment]
@sarbian would it be OK to mark the current MM as compatible wtih KSP 1.11? We are seeing a fair number of 1.11-only mods with an MM dependency.

**Comment by HebaruSan** [comment]
Thanks for the submissions! Looks really solid :100:

**Comment by sarbian** [comment]
@HebaruSan Yes it is ok. I will be able to do it sometime tomorrow but feel free to do it before if you have the time.

**Pull request merged**
