### PR TITLE
Added metadata for AT-Utils library.

### PR DESCRIPTION
**Pull request by allista**
Added ModuleManager and AT-Utils as dependencies to
ThrottleControlledAvionics metadata.

### CODE REVIEW

**Comment by allista** [comment]
Could someone check what's the problem with the build here? Is my metadata at fault or the other patches that got into the same built?

**Comment by politas** [comment]
About Ils is failing because it has no releases on Github, only a pre-release.

**Comment by allista** [comment]
Thanks for the reply. Fixed that.

**Comment by politas** [comment]
The server ModuleManager resides on is having some issues at the moment, which Sarbian is aware of. This will probably pass testing when that's sorted out.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
Looks good to me. Merging with thanks!

**Pull request merged**
