### PR TITLE
Octosat Continued

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Added new dependency

### CODE REVIEW

**Comment by politas** [comment]
Please add an epoch bump to force the new dependency install

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Added, but don't understand why it was needed

**Comment by politas** [comment]
I'd like to try to avoid the ModuleNotFound Kraken bug by making sure that any change in mod dependencies comes with a forced "upgrade"

**Pull request merged**
