### PR TITLE
Add JoolBiomes (fixed KerbalStuffBot submission)

### PR DESCRIPTION
**Pull request by politas**
Closes #2998

### CODE REVIEW

**Comment by plague006** [comment]
Why are we hardcoding a `name` and `abstract` when what's scraped from KS seems fine?

**Comment by politas** [comment]
The name coming from KS is the same as the identifier (no space), and the abstract contains an incomplete sentence, and isn't what shows up in the KS description.

**Comment by plague006** [comment]
> The name coming from KS is the same as the identifier (no space)

That's because it's the proper name of the mod:  JoolBiomes. It's the name listed in KerbalStuff, it's the name of the folder, it's the name on the KSP forum thread, and it's the name listed in Squad's "Modding Monday" (thread)[http://forum.kerbalspaceprogram.com/index.php?/topic/131680-modding-monday-joolbiomes/]. Let's not change the name of the mod.

> the abstract contains an incomplete sentence

The one written by the author/scraped from KS is `Add biomes (with science defs) to Jool.  Includes the Great Green Spot.`. Perhaps not the most eloquently written 2 sentences ever but it's a mod abstract, not prose.

> isn't what shows up in the KS description

Abstract and description are 2 different things on KS entirely. For example abstract is mandatory, that's why even blank KS pages will have an `abstract` when scraped by netkan.

**Comment by politas** [comment]
Ok, I see your point. Will resist the urge to editorialise in future.

**Comment by plague006** [comment]
Per forum thread, author will be setting up a github repo.
http://forum.kerbalspaceprogram.com/index.php?/topic/131274-105-joolbiomes-v10-add-biomes-and-great-green-spot-to-jool/

**Comment by Olympic1** [comment]
@politas the mod got uploaded so spacedock: http://spacedock.info/mod/26/JoolBiomes

You can use the new `$kref` for it

**Pull request merged**
