### PR TITLE
Add Sigma Mod Expansions from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Sigma88, to add [Sigma Mod Expansions](https://kerbalstuff.com/mod/816/Sigma%20Mod%20Expansions) to CKAN.

Please direct questions about this pull request to [Sigma88](https://kerbalstuff.com/profile/Sigma88).

### CODE REVIEW

**Comment by politas** [comment]
Had a look at cleaning up this one, but this is a metamod for several other mods, and I'm not sure whether it should be broken up into different packages, or exactly how to do depends/recommends/suggests for it. If someone else can sort it out and update this, I'd like to see how it's done.

**Comment by Dazpoet** [comment]
Appears to require overwriting of OPM files for some parts of this mod. Should probably be broken into smaller expansions based on the forum thread for this mod. Haven't looked at .zip.

**Comment by Sigma88** [comment]
hi there, I found this page because I saw that github was between the "Top Referrers" on the Kerbalstuff page.
If you need any help with this you can contact me on the ksp forum or here.
I never bothered to split the download in the single expansions but If this could be helpfull I don't have any problems doing that.

**Comment by plague006** [comment]
As an update, this is blocked pending a Kopernicus update and possibly an Outer Planets Mod update as well.

**Comment by Sigma88** [comment]
I have a question about CKAN.
my mod is a bundle of expansions which are all independent one from the other
Lately I did a lot of work to make the various expansions as much modular as possible and in the next release there will be three completely independent blocks.

I still want the main download to contain all the pieces, that said... there are currently 3 features in this xpack. if someone wants 1/3 or 2/3 instead of the whole pack would it be possible to do that from a single KerbalStuff archive? or should I add 3 single_feature_archives alongside the bundle_archive?

thanks for the help

**Comment by Dazpoet** [comment]
It's possible to do from a single KS archive but it will create certain boundaries. Such as the inability to up the version of a single one of the modules since we'll always be scraping the version from the single archive. Also the folderstructure will have to be rigid or the install stanzas will fail to resolve correctly. But apart from that I can't see a reason why we shouldn't be able to index all 4 from a single package, I'd even go as far as to say that it is the prefered method as long as you don't need independent versioning for each module.

We solve it by having 4 .netkan files pointing to the same `$kref` but with different install stanzas and where either the bundle conflicts with all 3 modules or each module conflicts with the bundle. Also the names and abstracts will have to be hardcoded on the modules or they will all generate the same name and abstract which will make the infrastructure and clients unhappy.

**Comment by Sigma88** [comment]
Thank you for your answer.

I'm pretty confident the folder structure won't be a problem since I've already tried deleting one subfolder at a time and everything seems to work out pretty well.

Someone pointed out to me tho that if I divide the mod into different KerbalStuff packets I will be able to see which ones are downloaded the most, and that can help me focus the little time I have to mod towards the improvement of the more requested features.

I will have to check if there are some KS rules against releasing the same content in different "mods" tho...

**Comment by Dazpoet** [comment]
That is indeed a fair point, in the end it's totally up to you how you host things and we'll do our best to index it :)

I'd recommend taking a look at https://kerbalstuff.com/profile/SpaceTiger who seems to be doing exactly what you have in mind.

**Comment by Sigma88** [comment]
Thanks, I didn't know I could make "mod packs" that is exactly what I need!

**Comment by Sigma88** [comment]
the archive should be fine now, when opm releases 1.7.1 I will update my mod too, if there are any problems to get it into CKAN let me know so I can apply the changes in the next release :)

**Comment by Sigma88** [comment]
I thought this may help

this mod is fully compatible with Stock KSP and this is how

without OPM:
- you won't get any changes to OPM planets (duh!)
- you will get Pluron-Khato in an orbit more suitable for Stock

without RemoteTech:
- antennas will be loaded to work in Stock KSP
- antennas are compatible with AntennaRange only if RemoteTech is not installed

without kopernicus:
- the planet pack won't load but the antenna pack will still load



if someone has this mod with at the same time #1605 and/or #1609, this mod should be installed and the other two ignored

**Comment by dbent** [comment]
@Sigma88 since this a collection of #1678 and #1679 how about we just create a metapackage `SigmaExpansions` which `depends` `SigmaRTExpansion` and `SigmaOPMExpansion`?

A user installing `SigmaExpansions` would then automatically install both `SigmaRTExpansion` and `SigmaOPMExpansion` without the need to index another mod.

**Comment by Sigma88** [comment]
this is fine for me
Can it be called "SigmaModExpansions" instead of "SigmaExpansions"?

**Comment by Sigma88** [comment]
@dbent 
wait, just one question:

I've made 3 different KerbalStuff downloads because I can see the stats of the downloads.
I'd like to know how many people download everything and how many download just a part in order to invest more time developing the stuff people download the most.

**Comment by dbent** [comment]
@Sigma88 That should be fine... Anyone installing `SigmaModExpansions` would download `SigmaRTExpansion` once and `SigmaOPMExpansion` once.

**Comment by Sigma88** [comment]
but then I would not be able to distinguish between
1 user downloads only SigmaRT + 1 other user downloads SigmaOPM only
and
1 user downloads SigmaModExpansions

If it wouldn't be much trouble I'd like to avoid using the metapackage. Otherwise, if it is much easier for you to do it that way, I think I'll survive :)

**Comment by dbent** [comment]
Replaced by #1680

**Pull request closed without merging**
