### PR TITLE
Updated depandancies for KSP 1.2

### PR DESCRIPTION
**Pull request by sswelm**

### CODE REVIEW

**Comment by sswelm** [comment]
I don't understand what the problem is ...

**Comment by techman83** [comment]
At a guess, tweakscale not being available for 1.2
```
4931 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on TweakScale found but it is not listed in the index, or not available for your version of KSP.
Module TweakScale required but it is not listed in the index, or not available for your version of KSP.
```

**Comment by sswelm** [comment]
But where can I view this relationship resolver?

**Comment by Olympic1** [comment]
Ignoring tweakscale, it installs fine, merging

**Comment by sswelm** [comment]
Great, but KSPI is still not avialable on CKAN, I guess there is still a dependancy check which prevent is from showing up

**Comment by Olympic1** [comment]
If tweakscale is update it will show up. I see that @pellinor0 is working on it.

**Comment by sswelm** [comment]
true

**Pull request merged**
