### PR TITLE
Iniital release

### PR DESCRIPTION
**Pull request by linuxgurugamer**
I'm trying to do two installs here, one to GameData and one to the GameRoot. It seems to not like this, is this even possible?

### CODE REVIEW

**Comment by plague006** [comment]
CKAN will not install external tools. `RemoteTech` must be a `conflict` as you cannot be assured that users will have AutoPruner.

**Comment by linuxgurugamer** [comment]
ok.  So, can AutoPruner be set up as it's own mod and installed by itself?

**Comment by plague006** [comment]
CKAN will not install external tools.

**Comment by plague006** [comment]
Closed by https://github.com/KSP-CKAN/NetKAN/pull/2460

**Pull request closed without merging**
