### PR TITLE
Move Kerbalism configuration files into GameData/KerbalismConfig

### PR DESCRIPTION
**Pull request by steamp0rt**

### CODE REVIEW

**Comment by steamp0rt** [comment]
Will require 3.0 be pushed to SpaceDock before it compiles, BUT 3.0 will not install properly on ckan without this. HM.

**Comment by HebaruSan** [comment]
Is it going to be two separate files like on GitHub? If so we'll need to make a few additional changes.
https://github.com/Kerbalism/Kerbalism/releases/tag/v3.0-beta-1

**Comment by steamp0rt** [comment]
it's gonna be on spacedock as one file with two folders.

**Comment by HebaruSan** [comment]
OK, good luck!

**Pull request merged**
