### PR TITLE
New Release of AeroRTG

### PR DESCRIPTION
**Pull request by Bezzier**
Even if your submission tested fine locally there are several errors that only the bots will note and reject. This should be expected.
Part newly maintained, being added to CKAN.

### CODE REVIEW

**Comment by politas** [comment]
You've got nothing in that `"resources"` stanza; were you going to put in a `"homepage": "<forum thread url>"` or some such?

**Comment by Bezzier** [comment]
Sorry, yes I was, but I got busy yesterday and didn't have a chance to do the thread..  Let me just point it at the github repository for the homepage for now.

**Comment by plague006** [comment]
Should have an array of authors: `"author": [ "Bezzier", "DaMichel" ]` (with any other authors added too of course)

**Comment by Bezzier** [comment]
You're right, I wasn't thinking. I was hypnotized by the whole "oh, the KREF will automatically fill that in."

Sorry to not be on top of my game.

**Comment by plague006** [comment]
No worries, mistakes are totally normal if you're not looking at this stuff hours daily, lol. Merging with my thanks.

**Pull request merged**
