### PR TITLE
Add FuelEfficientPilots from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of theshepherd, to add [FuelEfficientPilots](https://spacedock.info/mod/1466/FuelEfficientPilots) to CKAN.

Mod details:
    name = /mod/1466/FuelEfficientPilots
    author = theshepherd
    abstract = Give Pilots better fuel efficieny based on experience
    license = public-domain
    Homepage = 
    description = Pilots have the ability to get better fuel efficiency through experience, so now your five-star pilot can give you better bang for your buck!

Please direct questions about this pull request to [theshepherd](https://spacedock.info/profile/theshepherd).

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Needs to have MM added as a dependency

**Comment by packetshepherd** [comment]
This was redone and a pull request was submitted (#5753)

**Comment by packetshepherd** [comment]
Is there anything more I need to do?

**Comment by packetshepherd** [comment]
@Space-Duck, you can remove this request.  Thanks

**Pull request closed without merging**
