### PR TITLE
Consolidating metadata in single repository

### PR DESCRIPTION
**Pull request by Y3mo**
Hey,
I m consolidating all my ckan metadata in a single repository.

Best regards,
Yemo/Y3mo

### CODE REVIEW

**Comment by politas** [comment]
Merging with thanks!

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
No override specified for 1.99.99, so Jenkins gets messed up.

**Comment by Y3mo** [comment]
Thank you!

I intend to shift all my metadata files to the new repository, but nearly all have the 1.99.99 override for maintenance reasons.

How to make the transition with the least amount of extra work necessary?

Best regards,
Y3mo

**Comment by politas** [comment]
Just do the PRs, I'm happy to do local testing!

**Pull request merged**
