### PR TITLE
Add RSSTextures16K

### LINKED ISSUE #7699: I need some help to my texture pack work with ckan!
Hello, I'm the author of this [texturepack](https://forum.kerbalspaceprogram.com/index.php?/topic/191018-vannadins-16k-rss-texture-pack-bugpatch-update210-28-jan-2020/). I want to make it work with ckan so I read manual but it was a bit hard to understand. I'll upload my texture pack to github after check so ckan can download. can you help me?

### PR DESCRIPTION
**Pull request by HebaruSan**
Fixes #7699.

### CODE REVIEW

**Comment by HebaruSan** [comment]
```
Running NetKAN for NetKAN/RSSTextures16K.netkan
106539 [1] FATAL CKAN.NetKAN.Program (null) - https://spacedock.info/mod/1357/VaNnadin's 16K RSS texture pack/download/1.2.1 is not a valid ZIP file: Wrong Central Directory signature
Build step 'Execute shell' marked build as failure
```

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Hmm, same error on GitHub:

```
Running NetKAN for NetKAN/RSSTextures16K.netkan
199781 [1] FATAL CKAN.NetKAN.Program (null) - https://github.com/Vannadin/VaNnadin-s-16K-RSS-texture-pack/releases/download/2.2.1/VaNnadin_16K_RSS_texture_2.2.1.zip is not a valid ZIP file: Wrong Central Directory signature
Build step 'Execute shell' marked build as failure
```

**Comment by HebaruSan** [comment]
As far as I can tell, that error is incorrect and the ZIP is fine. The "Central Directory signature" potentially means one of two things in a ZIP file (probably the first one):

- [Central directory file header signature = 0x02014b50](https://en.wikipedia.org/wiki/Zip_(file_format)#Central_directory_file_header)
- [End of central directory signature = 0x06054b50](https://en.wikipedia.org/wiki/Zip_(file_format)#End_of_central_directory_record_(EOCD))

Both of these are present and correct in this ZIP when inspecting with a [hex editor](https://mh-nexus.de/en/hxd/).

Another team has had this same error for no reason when using ICSharpCode.SharpZipLib:

- https://sourceforge.net/p/ikvm/mailman/message/35481537/

At this point I don't know what our path forward should be.

**Comment by Vannadin** [comment]
how's it going? can you tell me what's the problem exactly?

**Comment by techman83** [comment]
How was the zip created? Adherence to the zip format varies widely between implementations.

**Comment by Vannadin** [comment]
> How was the zip created? Adherence to the zip format varies widely between implementations.
I used a program called "bandizip". 
[https://en.bandisoft.com/](url)
there are several options about compress so you might be able to check it.

**Comment by techman83** [comment]
> there are several options about compress so you might be able to check it.

I don't run windows or mac, so it's been a while since I've used a zip application that wasn't either on the cli or built into the desktop! I haven't ever heard of bandisoft, might be worth trying 7zip (just make sure to set the zip compression type) as it's a pretty popular open source utility - https://www.7-zip.org/

**Comment by Vannadin** [comment]
roger. btw bandizip is a well known tool in Korea. not the most famous but I like it cuz of its speed and many additional functions.
I didn't know that it has this kind of problem. I'll reupload file using 7z

**Comment by techman83** [comment]
> roger. btw bandizip is a well known tool in Korea. not the most famous but I like it cuz of its speed and many additional functions.
> I didn't know that it has this kind of problem. I'll reupload file using 7z

Neat. I figured it was just because I didn't use windows much :smile: 7zip likes to use it's own format, so make your you select 'zip'. The poor zip library has enough troubles with the format it's designed for!

**Comment by HebaruSan** [comment]
#rebuild

**Comment by Vannadin** [comment]
sorry for the late. I had so many things in real life..
https://github.com/Vannadin/VaNnadin-s-16K-RSS-texture-pack/releases/tag/2.2.2
this is 7z compressed version. please check it.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
I think it worked that time!

**Pull request merged**
