### PR TITLE
Update OuterPlanetsMod

### PR DESCRIPTION
**Pull request by dbent**
#### Done

- [x] Remove dependency on `CustomAsteroids`
- [x] Remove dependency on `KopernicusTech`
- [x] Add dependency on `Kopernicus`
- [x] Add `provides` and `conflicts` of `Kopernicus`, since the archive distributes a newer version than what's available from Kopernicus upstream as a release
- [x] Add `provides` and `conflicts` of `PlanetShine-Config` since it distributes its own
- [x] Rejigger relationships with other mods
  - `recommends` mods become `suggests`
  - `suggests` mods become `supports`
  - Updated related mods based on what's currently in the forum post
- [x] Update `install` stanzas for new archive structure
  - Filter `.svn` folders from archive
- [x] Modify PlanetShine upstream so that it can read from multiple configuration files. PR submitted: valerian/ksp-planetshine#1
  - [x] Modifying FinalFrontier so that other mods can replace ribbon textures without overwriting the actual files, then have OuterPlanetsMod use that mechanism. [In Progress](http://forum.kerbalspaceprogram.com/threads/104280?p=1916943#post1916943)
  - [x] Have upstream remove `.svn` folders from archive, so we don't have to filter them, this would benefit manual install users as well. [In Progress](http://forum.kerbalspaceprogram.com/threads/104280?p=1916943#post1916943)

#### To Do

  - [ ] Get Kopernicus upstream to do a 1.0 compatible release and remove the `provides` and `conflicts` from this
    - [Not happening soon](http://forum.kerbalspaceprogram.com/threads/114649?p=1918355#post1918355)

### CODE REVIEW

**Comment by dbent** [comment]
Upon looking at the FinalFrontier source, it seems it already reads ribbon data on celestial bodies from OuterPlanetsMod and can even override them (although its logs a warning in that case, which should probably just be an info); it's just that OuterPlanetsMod does not currently override Eeloo, it simply overwrites the ribbon files.

When I have time, I'll test having OuterPlanetsMod simply specifying a config for Eeloo, but I think that should work.

**Comment by dbent** [comment]
[Post about changes to OuterPlanetsMod](http://forum.kerbalspaceprogram.com/threads/104280?p=1916798#post1916798)

**Comment by dbent** [comment]
[Post about releasing Kopernicus](http://forum.kerbalspaceprogram.com/threads/114649?p=1916842#post1916842)

**Comment by dbent** [comment]
As noted above, I've made a PR for PlanetShine to change its config behavior. I've also made a [post about OuterPlanetsMod using this behaviour](http://forum.kerbalspaceprogram.com/threads/104280?p=1917106#post1917106).

**Comment by Dazpoet** [comment]
Just to make your life oh so much more fun you might also find https://github.com/KSP-CKAN/NetKAN/pull/644 interesting to take a look at if you manage to untangle this project, although I'm not sure if that one is or will be upgraded for OPM 2.0? Having a hard time checking atm.

**Comment by dbent** [comment]
I'll take a look at it if they release a version of KSP 1.0. Waiting on OPM 1.7 Beta 2 to move this guy along, looks like I'll be able to check off all the TODOs except distributing Kopernicus separately.

**Comment by dbent** [comment]
@Dazpoet OPM 1.7 Beta 2 was released which fixes the major issues. The last todo (Kopernicus standalone release) ain't happening any time soon, so I think we should just go with having `OuterPlanetsMods` depend on and provide `Kopernicus`, and conflict with anything else providing `Kopernicus`.

So this is good to merge. :+1:

**Comment by Dazpoet** [comment]
Quickly glancing through the install log and everything seems fine so I'll merge this then :)

**Pull request merged**
