### PR TITLE
PartWizard at authors request

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by politas** [comment]
ksp_version should be 1.1.0

**Comment by linuxgurugamer** [comment]
done

**Comment by politas** [comment]
No, really, ksp_version should be 1.1**_.0_**

**Comment by plague006** [comment]
Ksp_ver 1.1 is fine now. Build.sh was updated

**Comment by plague006** [comment]
Needs a `name` and `abstract`.

**Comment by politas** [comment]
Fine until Squad bring out a KSP 1.1.5 that breaks compatibility.  Do we really want to go through that whole headache again?

**Comment by plague006** [comment]
@politas if a mod author believes their mod won't be affected by patch-level changes, we take them at their word, that's how it's always been.

**Comment by linuxgurugamer** [comment]
Done

**Comment by plague006** [comment]
Merged with my thanks.

**Pull request merged**
