### PR TITLE
Aies Patches

### PR DESCRIPTION
**Pull request by linuxgurugamer**
ckan compat add 1.0.5

### CODE REVIEW

**Comment by HebaruSan** [comment]
Let's tag these before committing, since all other unfrozen netkans currently have tags.

**Comment by linuxgurugamer** [comment]
> Let's tag these before merging, since all other unfrozen netkans currently have tags.
> 
> https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags

I'll add the tags once I get the errors fixed.

**Comment by linuxgurugamer** [comment]
@HebaruSan I'm trying to reach you on IRC:
https://webchat.esper.net/?channels=ckan#chan-2

**Comment by HebaruSan** [comment]
I'm not on IRC. There's a Discord now though:
https://discord.gg/Mb4nXQD

**Pull request merged**
