### PR TITLE
Add tests for spec v1.16

### PR DESCRIPTION
**Pull request by techman83**
I noted we didn't have any tests for spec v1.16. This rectifies that.

### CODE REVIEW

**Comment by techman83** [comment]
Fails because metadata.t found 2 netkans that don't pass the spec validation'

```
#   Failed test 'BackgroundProcessing - spec_version v1.16+ required for 'find_matches_files''
#   at t/metadata.t line 125.
#   Failed test 'kOSBFSMultipleArchiveManager - spec_version v1.16+ required for 'find_matches_files''
```

**Comment by politas** [comment]
#rebuild

**Comment by techman83** [comment]
Re-based and tests fixed. Green tick FTW!

**Comment by politas** [comment]
Looks pretty good to me. I can make sense of all the changes and they seem well-targeted. 
Merging.

**Pull request merged**
