### PR TITLE
Add SSCEP NetKAN metadata to the index

### PR DESCRIPTION
**Pull request by Poodmund**
I think the NetKAN file I have remotely hosted is correct. If not, please let me know here and I'll rectify it before this merge.

https://raw.githubusercontent.com/Poodmund/Stock-Scatter-Collider-Enabler-Patch/master/CKAN/SSCEP.netkan

### CODE REVIEW

**Comment by HebaruSan** [comment]
I usually advocate for meaningful identifiers so I can remember them and tell what they are.
Any chance you could call this EnableScatterColliders?

**Comment by HebaruSan** [comment]
Don't need this for a new mod. Its purpose is to work around versioning hiccups, usually with mods with lots of releases.

```json
    "x_netkan_epoch": "2",
```

**Comment by Poodmund** [comment]
Changed the identifer to 'StockScatterColliderEnablerPatch'. Its important to be explicit in that it ONLY enables the collider meshes for the vanilla instances of ground scatter for the vanilla planets, hence the name.

**Comment by HebaruSan** [comment]
Works now, thanks for the submission! Merging...

**Comment by Poodmund** [comment]
Thanks for the help. :D

**Pull request merged**
