### PR TITLE
Add ShipEffects-Sound-Mod: Dynamic Sound Effects (Maintenance) from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of CoriW, to add [ShipEffects-Sound-Mod: Dynamic Sound Effects (Maintenance)](https://kerbalstuff.com/mod/1102/ShipEffects-Sound-Mod:%20Dynamic%20Sound%20Effects%20%28Maintenance%29) to CKAN.

Please direct questions about this pull request to [CoriW](https://kerbalstuff.com/profile/CoriW).

### CODE REVIEW

**Comment by plague006** [comment]
`Source` folder needs filtering and license needs a correction to our standards.

**Comment by plague006** [comment]
We also need a sane `identifier`. The original mod was indexed as `ShipEffects`.

**Comment by plague006** [comment]
@Dazpoet I'd love your input on how to proceed. This isn't a `ShipEffects-Continued` according to the author but a "Maintenance" fork. Should this be merged into `ShipEffects.netkan` where we simply swap out the kerbalstuff pages and a few other metadata tweaks or should it be spun off completely?

My gut says: Tweak the existing `ShipEffects` to transition into this release stream is the cleaner way to go, and if the original author comes back assess how the 2 authors want to proceed and match their decision on our end. AFAIK there's nothing that will technically restrict us.

**Comment by Dazpoet** [comment]
I'd agree with this directly into the original ShipEffects. It is the sane thing to do and should match what our users expect, e.g. a working continuation with a provided upgrade path from the modversion they might be stuck at prior to this release.

There's some precendence from when I juggled around InfernalRobotics to catch the most current release stream in #971 and #1050. We've also juggled some of the RO things around after they consolidated under KSP-RO, see e.g. #1521.

**Pull request closed without merging**
