### PR TITLE
Create Mk1-1A2Textures4096.netkan

### PR DESCRIPTION
**Pull request by Yarbrough08**

### CODE REVIEW

**Comment by plague006** [comment]
Is there a case where users will want the textures installed but not the command module? If so no change is needed but if the textures are exclusive to the command module, we should add it to `depends`.

**Comment by Yarbrough08** [comment]
No, the textures are for the command module only - and the pod should already have a depends for the textures..

**Comment by plague006** [comment]
Without the dependency of the textures to the module when a user uninstalls the module there's a not-insignificant chance they'll forget to uninstall the textures. With the dependency when the CM is removed the textures have to go with it.

**Comment by Yarbrough08** [comment]
Oh, ok - that makes sense. I've made the changes..

**Comment by plague006** [comment]
Looks good, passes local testing, merging with my thanks.

**Comment by Yarbrough08** [comment]
No problem - thank you as well :)

**Pull request merged**
