### PR TITLE
Add EVA OK! from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of wrcsubers, to add [EVA OK!](https://kerbalstuff.com/mod/1326/EVA%20OK%21) to CKAN.

Please direct questions about this pull request to [wrcsubers](https://kerbalstuff.com/profile/wrcsubers).

### CODE REVIEW

**Comment by Blu3wolf** [comment]
This would be nice to have!

**Comment by Olympic1** [comment]
@plague006 @techman83 @dbent 

The folder is named `EVAOK! v1.0`, I tried to use `EVAOK!.v[\\d+.]{3,5}` but that didn't work. Is the `!` maybe causing this to fail?

@wrcsubers could you maybe remove the `!` in the foldername?

**Comment by plague006** [comment]
`EVAOK.*` will work just fine.

**Comment by wrcsubers** [comment]
Next update (due soon) I will make sure to remove any problem characters in the name and code =) Sorry for the mess!

**Pull request closed without merging**
