### PR TITLE
Add STM's Final Frontier Ribbon packs

### PR DESCRIPTION
**Pull request by politas**
Typical KerbalStuffBot nonsense

### CODE REVIEW

**Comment by politas** [comment]
Replaces KerbalStuffBot PRs #2915, #2916, #2917, #2918, and #2921

**Comment by politas** [comment]
If anyone can see a reason for these to be faulting other than Jenkins stuffing up, I'd be grateful. My local netkan is throwing authentication errors whenever I try to use it for testing.

**Comment by techman83** [comment]
It's having trouble finding the path in one of the zip files
```
2005 [1] FATAL CKAN.NetKAN.Program (null) - Could not find GameData/STMRankRibbons entry in zipfile to install
```
I'm thinking a copy/paste issue, as a couple of those files are looking for the same filepath :)

**Comment by politas** [comment]
Hmpf. The same folder for four of them, then a different one for the other two. The only two I didn't download and check.

**Comment by plague006** [comment]
In at least one case you have netkan searching for `GameData/STMRankRibbons` when you probably mean `GameData/STMRibbons`.

**Comment by politas** [comment]
Yes, I expected that one to not use the "Rank" naming, but it actually does when you look in the zip. That's why I got the other two "Role" packs wrong.

**Comment by SmarterThanMe** [comment]
Anything I can do?

**Comment by politas** [comment]
STM, if you could have a look at the netkans and see if they look right as far as how you expect it should be installed, that would be useful.

**Comment by SmarterThanMe** [comment]
In regards to what people have mentioned above (removing "Rank" from the folder).. I did mean to make that change to all of the packs (being that I did more than just Rank ribbons). Engineering also installs to STMRibbons.
Could it possibly be that I'm using the same Readme in each one (which is in the STMRibbons) folder, and Netkan doesn't like the possibility of overwriting that over and over?
Everything else seems fine (then again, I've been grappling with my 3yo for half the night, and only just got her to sleep, so I have no  idea - will check again in the morning).

**Comment by politas** [comment]
An identical Readme file might well cause problems. Have you changed the folder structure in the EngineeringRoles recently? The copy I downloaded has a STMRankRibbons folder rather than STMRibbons.

**Comment by politas** [comment]
README.txt files filtered out.

**Comment by politas** [comment]
Switched all finds over to STMRibbons

**Comment by SmarterThanMe** [comment]
OK. I moved all the Readme files to their own folders. Should work now?

**Comment by politas** [comment]
README.txt filters removed

**Comment by pjf** [comment]
These all build beautifully and look sensible to me. I'm condensing commits for a cleaner history, but in the process of merging now. Thank you so much!

```
$ ls -lR STMRibbons/
STMRibbons/:
total 0
drwxrwx--- 1 pjf pjf 94 Jan 29 15:06 EngRoles
drwxrwx--- 1 pjf pjf 94 Jan 29 15:06 enlisted
drwxrwx--- 1 pjf pjf 94 Jan 29 15:06 expeditions
drwxrwx--- 1 pjf pjf 94 Jan 29 15:07 navofficers
drwxrwx--- 1 pjf pjf 94 Jan 29 15:07 OpsRoles
drwxrwx--- 1 pjf pjf 94 Jan 29 15:07 wos

STMRibbons/EngRoles:
total 8
-rw-rw---- 1 pjf pjf 1855 Jan 29 15:06 FinalFrontierCustomRibbons.cfg
-rw-rw---- 1 pjf pjf 1000 Jan 29 15:06 README.txt
drwxrwx--- 1 pjf pjf  386 Jan 29 15:06 Ribbons

STMRibbons/EngRoles/Ribbons:
total 44
-rw-rw---- 1 pjf pjf 2980 Jan 29 15:06 Astromining.png
-rw-rw---- 1 pjf pjf 2959 Jan 29 15:06 ElectricPropulsion.png
-rw-rw---- 1 pjf pjf 2868 Jan 29 15:06 FuelSystems.png
-rw-rw---- 1 pjf pjf 2960 Jan 29 15:06 IndustrialProcesses.png
-rw-rw---- 1 pjf pjf 2985 Jan 29 15:06 MaintenanceRepair.png
-rw-rw---- 1 pjf pjf 3162 Jan 29 15:06 MechanicalSystems.png
-rw-rw---- 1 pjf pjf 3018 Jan 29 15:06 NuclearSystems.png
-rw-rw---- 1 pjf pjf 3009 Jan 29 15:06 PowerSystems.png
-rw-rw---- 1 pjf pjf 2867 Jan 29 15:06 Propulsion.png
-rw-rw---- 1 pjf pjf 3024 Jan 29 15:06 Shipyard.png
-rw-rw---- 1 pjf pjf 2979 Jan 29 15:06 SolarSystems.png

STMRibbons/enlisted:
total 8
-rw-rw---- 1 pjf pjf 2237 Jan 29 15:06 FinalFrontierCustomRibbons.cfg
-rw-rw---- 1 pjf pjf 1000 Jan 29 15:06 README.txt
drwxrwx--- 1 pjf pjf  192 Jan 29 15:06 Ribbons

STMRibbons/enlisted/Ribbons:
total 32
-rw-rw---- 1 pjf pjf 1055 Jan 29 15:06 kerb_en1.png
-rw-rw---- 1 pjf pjf 1170 Jan 29 15:06 kerb_en2.png
-rw-rw---- 1 pjf pjf 1153 Jan 29 15:06 kerb_en3.png
-rw-rw---- 1 pjf pjf 1415 Jan 29 15:06 kerb_en4.png
-rw-rw---- 1 pjf pjf 1509 Jan 29 15:06 kerb_en5.png
-rw-rw---- 1 pjf pjf 2001 Jan 29 15:06 kerb_en6.png
-rw-rw---- 1 pjf pjf 1925 Jan 29 15:06 kerb_en7.png
-rw-rw---- 1 pjf pjf 1873 Jan 29 15:06 kerb_en8.png

STMRibbons/expeditions:
total 12
-rw-rw---- 1 pjf pjf 5084 Jan 29 15:06 FinalFrontierCustomRibbons.cfg
-rw-rw---- 1 pjf pjf 1000 Jan 29 15:06 README.txt
drwxrwx--- 1 pjf pjf 1238 Jan 29 15:06 Ribbons

STMRibbons/expeditions/Ribbons:
total 212
-rw-rw---- 1 pjf pjf 2504 Jan 29 15:06 3M-2IC.png
-rw-rw---- 1 pjf pjf 2518 Jan 29 15:06 3M-LDR.png
-rw-rw---- 1 pjf pjf 1961 Jan 29 15:06 3M.png
-rw-rw---- 1 pjf pjf 2217 Jan 29 15:06 7LEAGUE-2IC.png
-rw-rw---- 1 pjf pjf 2245 Jan 29 15:06 7LEAGUE-LDR.png
-rw-rw---- 1 pjf pjf 1596 Jan 29 15:06 7LEAGUE.png
-rw-rw---- 1 pjf pjf 1752 Jan 29 15:06 Argos-2IC.png
-rw-rw---- 1 pjf pjf 1810 Jan 29 15:06 Argos-LDR.png
-rw-rw---- 1 pjf pjf 1413 Jan 29 15:06 Argos.png
-rw-rw---- 1 pjf pjf 1852 Jan 29 15:06 HALLE-2IC.png
-rw-rw---- 1 pjf pjf 1877 Jan 29 15:06 HALLE-LDR.png
-rw-rw---- 1 pjf pjf 1313 Jan 29 15:06 HALLE.png
-rw-rw---- 1 pjf pjf 1947 Jan 29 15:06 InDEX-2IC.png
-rw-rw---- 1 pjf pjf 2004 Jan 29 15:06 InDEX-LDR.png
-rw-rw---- 1 pjf pjf 1433 Jan 29 15:06 InDEX.png
-rw-rw---- 1 pjf pjf 2096 Jan 29 15:06 JOE1-2IC.png
-rw-rw---- 1 pjf pjf 2120 Jan 29 15:06 JOE1-LDR.png
-rw-rw---- 1 pjf pjf 1634 Jan 29 15:06 JOE1.png
-rw-rw---- 1 pjf pjf 2683 Jan 29 15:06 LAMP-2IC.png
-rw-rw---- 1 pjf pjf 2721 Jan 29 15:06 LAMP-LDR.png
-rw-rw---- 1 pjf pjf 2238 Jan 29 15:06 LAMP.png
-rw-rw---- 1 pjf pjf 1662 Jan 29 15:06 Leviathon-2IC.png
-rw-rw---- 1 pjf pjf 1741 Jan 29 15:06 Leviathon-LDR.png
-rw-rw---- 1 pjf pjf 1293 Jan 29 15:06 Leviathon.png
-rw-rw---- 1 pjf pjf 1904 Jan 29 15:06 MEX1-2IC.png
-rw-rw---- 1 pjf pjf 1891 Jan 29 15:06 MEX1-LDR.png
-rw-rw---- 1 pjf pjf 1650 Jan 29 15:06 MEX1.png
-rw-rw---- 1 pjf pjf 2766 Jan 29 15:06 MID-2IC.png
-rw-rw---- 1 pjf pjf 2789 Jan 29 15:06 MID-LDR.png
-rw-rw---- 1 pjf pjf 2290 Jan 29 15:06 MID.png
-rw-rw---- 1 pjf pjf 1981 Jan 29 15:06 MOSA-2IC.png
-rw-rw---- 1 pjf pjf 1880 Jan 29 15:06 MOSA-LDR.png
-rw-rw---- 1 pjf pjf 1785 Jan 29 15:06 MOSA.png
-rw-rw---- 1 pjf pjf 2214 Jan 29 15:06 ORCAST-2IC.png
-rw-rw---- 1 pjf pjf 2240 Jan 29 15:06 ORCAST-LDR.png
-rw-rw---- 1 pjf pjf 1683 Jan 29 15:06 ORCAST.png
-rw-rw---- 1 pjf pjf 1848 Jan 29 15:06 Pegasus-2IC.png
-rw-rw---- 1 pjf pjf 1786 Jan 29 15:06 Pegasus-LDR.png
-rw-rw---- 1 pjf pjf 1697 Jan 29 15:06 Pegasus.png
-rw-rw---- 1 pjf pjf 2210 Jan 29 15:06 Space1-2IC.png
-rw-rw---- 1 pjf pjf 2228 Jan 29 15:06 Space1-LDR.png
-rw-rw---- 1 pjf pjf 1621 Jan 29 15:06 Space1.png
-rw-rw---- 1 pjf pjf 2599 Jan 29 15:06 Spacelab1-2IC.png
-rw-rw---- 1 pjf pjf 2622 Jan 29 15:06 Spacelab1-LDR.png
-rw-rw---- 1 pjf pjf 2046 Jan 29 15:06 Spacelab1.png
-rw-rw---- 1 pjf pjf 4145 Jan 29 15:06 STrIPE2-2IC.png
-rw-rw---- 1 pjf pjf 3971 Jan 29 15:06 STrIPE-2IC.png
-rw-rw---- 1 pjf pjf 4158 Jan 29 15:06 STrIPE2-LDR.png
-rw-rw---- 1 pjf pjf 3758 Jan 29 15:06 STrIPE2.png
-rw-rw---- 1 pjf pjf 3993 Jan 29 15:06 STrIPE-LDR.png
-rw-rw---- 1 pjf pjf 3614 Jan 29 15:06 STrIPE.png

STMRibbons/navofficers:
total 8
-rw-rw---- 1 pjf pjf 2376 Jan 29 15:07 FinalFrontierCustomRibbons.cfg
-rw-rw---- 1 pjf pjf 1000 Jan 29 15:07 README.txt
drwxrwx--- 1 pjf pjf  252 Jan 29 15:07 Ribbons

STMRibbons/navofficers/Ribbons:
total 36
-rw-rw---- 1 pjf pjf 1778 Jan 29 15:07 kerb_navo1.png
-rw-rw---- 1 pjf pjf 1854 Jan 29 15:07 kerb_navo2.png
-rw-rw---- 1 pjf pjf 1800 Jan 29 15:07 kerb_navo3.png
-rw-rw---- 1 pjf pjf 1774 Jan 29 15:07 kerb_navo4.png
-rw-rw---- 1 pjf pjf 1958 Jan 29 15:07 kerb_navo5.png
-rw-rw---- 1 pjf pjf 2250 Jan 29 15:07 kerb_navo6.png
-rw-rw---- 1 pjf pjf 2468 Jan 29 15:07 kerb_navo7.png
-rw-rw---- 1 pjf pjf 2492 Jan 29 15:07 kerb_navo8.png
-rw-rw---- 1 pjf pjf 2474 Jan 29 15:07 kerb_navo9.png

STMRibbons/OpsRoles:
total 8
-rw-rw---- 1 pjf pjf 1665 Jan 29 15:07 FinalFrontierCustomRibbons.cfg
-rw-rw---- 1 pjf pjf 1000 Jan 29 15:07 README.txt
drwxrwx--- 1 pjf pjf  266 Jan 29 15:07 Ribbons

STMRibbons/OpsRoles/Ribbons:
total 36
-rw-rw---- 1 pjf pjf 1570 Jan 29 15:07 Admin.png
-rw-rw---- 1 pjf pjf 1658 Jan 29 15:07 Agriculture.png
-rw-rw---- 1 pjf pjf 1614 Jan 29 15:07 EnvironmentalControl.png
-rw-rw---- 1 pjf pjf 1762 Jan 29 15:07 Helm.png
-rw-rw---- 1 pjf pjf 1722 Jan 29 15:07 LandOps.png
-rw-rw---- 1 pjf pjf 1697 Jan 29 15:07 LifeSupport.png
-rw-rw---- 1 pjf pjf 1714 Jan 29 15:07 Optimisation.png
-rw-rw---- 1 pjf pjf 1686 Jan 29 15:07 Quartermaster.png
-rw-rw---- 1 pjf pjf 1766 Jan 29 15:07 RemotePiloting.png

STMRibbons/wos:
total 8
-rw-rw---- 1 pjf pjf 1300 Jan 29 15:07 FinalFrontierCustomRibbons.cfg
-rw-rw---- 1 pjf pjf 1000 Jan 29 15:07 README.txt
drwxrwx--- 1 pjf pjf   72 Jan 29 15:07 Ribbons

STMRibbons/wos/Ribbons:
total 12
-rw-rw---- 1 pjf pjf 1271 Jan 29 15:07 kerb_wo1.png
-rw-rw---- 1 pjf pjf 1599 Jan 29 15:07 kerb_wo2.png
-rw-rw---- 1 pjf pjf 1795 Jan 29 15:07 kerb_wo3.png
```

**Comment by pjf** [comment]
Merged with great thanks!

**Pull request closed without merging**
