### PR TITLE
Radial Stack Decoupler

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #4782

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I have no idea why this failed, can someone take a look please?

**Comment by techman83** [comment]
I've no idea why it spat out that error.

`2493 [1] FATAL CKAN.NetKAN.Program (null) - Invalid path`

**Comment by politas** [comment]
There's something very odd about that Zipfile. When you open it up, you get a directory entry which has the same name as the zipfile, even if you rename the zipfile. Rename the zipfile and open it again, the directory has the new name.

**Comment by linuxgurugamer** [comment]
I've posted a message in the forum for this

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild #4827

**Comment by politas** [comment]
Looks all fine, now! Merging with thanks!

**Pull request merged**
