### PR TITLE
Add DarkSideTechnologyContinued.netkan

### PR DESCRIPTION
**Pull request by willwill2will54**
The mod is on SpaceDock and Github, but since the author did not use the integrated function in SpaceDock, and apparently does not create 'releases' on GitHub, I decided to create this stopgap until one of those things change.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Hmm, it's already indexed (sort of):
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/DarkSideTechnology.netkan

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
This is for 1.4.2, dependency RetractableLiftingSurface is for 1.4.1.

**Comment by willwill2will54** [comment]
Perhaps it would be best to reevaluate that label.

**Pull request merged**
