### PR TITLE
Adding The Maritime Pack mod

### PR DESCRIPTION
**Pull request by zilti**

### CODE REVIEW

**Comment by benjwgarner** [comment]
According to the console log:

`4718 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on 1869 found but it is not listed in the index, or not available for your version of KSP.`
`Module 1869 required but it is not listed in the index, or not available for your version of KSP.`

@zilti The check failed because 1869 is listed as a dependency for TheMaritimePack, but it is not yet indexed in CKAN. You need to fix the [line splitting problem](https://github.com/KSP-CKAN/NetKAN/pull/5322) in 1869 and wait for it to be indexed by CKAN. Once it has been picked up, TheMaritimePack should (unless there are any other problems) pass the checks.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by zilti** [comment]
So there's still something wrong with the file?

**Comment by politas** [comment]
A Corrupted Download, apparently. Lets try it again.

**Comment by politas** [comment]
My local testing is successful. Merging to see if the bot will handle it properly

**Comment by politas** [comment]
TheMaritimePack-019.ckan is in the repo now!

**Pull request merged**
