### PR TITLE
Update and rename Asclepius.kerbalstuff to Asclepius.netkan

### PR DESCRIPTION
**Pull request by MrChumley**
Changing the existing file. Change the extension to .netkan and update the info.

### CODE REVIEW

**Comment by Olympic1** [comment]
The last indexed version is `Asclepius v1.4.1` on Dec 29th with the changelog: 
```
(12-28-15) Updated Kopernicus to v0.6.3-beta (asteroid declutter)
```
On your GitHub repo it is `Asclepius v1.4` on Dec 12th.
Does the release on GitHub include this update?

**Comment by MrChumley** [comment]
No.  Asclepius came bundled with Kopernicus on kerbalstuff.  v1.4.1 was just a Kopernicus update.   Would it help if I drafted a v1.5 asclepius release?

**Comment by Olympic1** [comment]
Yes, otherwise it could cause ploblems for the users

**Comment by MrChumley** [comment]
ok. Closing this (for now). Thanks for your help (again).

**Comment by Olympic1** [comment]
If you released a new update you can just re-open this issue again, the bot will automatically detect the new release

**Comment by MrChumley** [comment]
Ok I drafted a v1.5 release for Asclepius.

**Comment by Olympic1** [comment]
I just wanted to merge this because it installed fine locally

**Comment by MrChumley** [comment]
if 9446b62 works then thats fine with me.

**Comment by Olympic1** [comment]
Yes, that worked. I'll merge this and add it manually

**Comment by MrChumley** [comment]
Thanks.

**Pull request merged**
