### PR TITLE
ExtraPlanetaryLaunchpads not Compatible with KSP1.1.3

### LINKED ISSUE #4285: Edit EPL Netkan
EPL 5.3.2 is not compatible with KSP 1.1.3, but is marked as compatible for up to version 1.1.99.

### PR DESCRIPTION
**Pull request by politas**
Closes #4285

### CODE REVIEW

**Comment by Blu3wolf** [comment]
Conflicts with #4323 which updates the file to 5.4.0 instead.

**Comment by politas** [comment]
Covered by KSP-CKAN/CKAN-meta#1197 now

**Comment by politas** [comment]
Thanks for your help, @Blu3wolf !

**Comment by Blu3wolf** [comment]
No worries. Glad to be able to.

**Pull request closed without merging**
