### PR TITLE
Add SpaceY Expanded from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of NecroBones, to add [SpaceY Expanded](https://kerbalstuff.com/mod/1137/SpaceY%20Expanded) to CKAN.

Please direct questions about this pull request to [NecroBones](https://kerbalstuff.com/profile/NecroBones).

### CODE REVIEW

**Comment by Dazpoet** [comment]
Relevant https://github.com/KSP-CKAN/NetKAN/issues/2247

**Comment by NecroBones** [comment]
It looks like this failed 10 days ago, and still is not in CKAN. Is there anything I need to do? Thanks.

**Comment by plague006** [comment]
@NecroBones This is an automated PR from a bot and requires a human to create a proper .netkan. I'm typically the one on top of this but I [burnt myself out of late](https://github.com/KSP-CKAN/NetKAN/graphs/contributors?from=2015-06-26&to=2015-09-11&type=c) and I'm taking a break from creating new metadata but I'll happily review the work someone else is willing to do. There's a great [guide on the wiki](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN) if you're willing to DIY.

**Comment by NecroBones** [comment]
I totally understand. I'll look through it and see if I can take over doing my own updates.

**Comment by plague006** [comment]
Closed with #2270

**Comment by NecroBones** [comment]
Excellent, thanks. BTW, I made one small correction, to make the recommendation line refer to Interstellar's Core, rather than the full mod.

**Pull request closed without merging**
