### PR TITLE
Add 6.4x scale 12.8x distance from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Jebediah_Kerman, to add [6.4x scale 12.8x distance](https://spacedock.info/mod/1487/6.4x%20scale%2012.8x%20distance) to CKAN.

Mod details:
    name = /mod/1487/6.4x%20scale%2012.8x%20distance
    author = Jebediah_Kerman
    abstract = Makes the system bigger, and it is a much harder game.
    license = MIT
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/164300-13-64x-size-128x-distances/
    description = This is your mod listing! You can edit it as much as you like before you make it public.

To edit **this** text, you can click on the "**Edit this Mod**" button up there.

By the way, you have a lot of flexibility here. You can embed YouTube videos or screenshots. Be creative.

You can check out the SpaceDock [markdown documentation](/markdown) for tips.

Thanks for hosting your mod on SpaceDock!

Please direct questions about this pull request to [Jebediah_Kerman](https://spacedock.info/profile/Jebediah_Kerman).

### CODE REVIEW

**Comment by politas** [comment]
SigmaDimensions was removed from CKAN at the request of the author. It is required for this mod.

**Comment by Olympic1** [comment]
#rebuild

**Comment by politas** [comment]
Ah. We only have SigmaDimensions for 1.3.1, and this is 1.3.0

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
I was worried about that. This is doing SigmaDimensions wrong, I think

**Comment by politas** [comment]
I've left a note on the forum thread explaining the issue.

**Comment by Olympic1** [comment]
#rebuild

**Pull request merged**
