### PR TITLE
NEOS - make it compatbible with Kerbalism again now that they honour …

### PR DESCRIPTION
**Pull request by mwerle**
…the "dataIsCollectable" flag on experiments.

Issue link: https://github.com/Kerbalism/Kerbalism/issues/249

----

Q: Is it possible (sorry, couldn't find anything in the docs) to mark another mod as being incompatible but only up to some version?

### CODE REVIEW

**Comment by HebaruSan** [comment]
> Q: Is it possible (sorry, couldn't find anything in the docs) to mark another mod as being incompatible but only up to some version?

A: Yes, you can do this:

```json
    "conflicts": [
        { "name": "Kerbalism", "max_version": "2.99" }
    ]
```

**Comment by mwerle** [comment]
Great thanks. Just a moment please.

**Comment by HebaruSan** [comment]
Cool. I gave that a try locally to confirm it works, just in case:

```
$ ckan install Kerbalism=2.1.2
(assorted nonsense)

$ ckan install -c NehemiahEngineeringOrbitalScience-0.8.0.ckan 
The following inconsistencies were found:
* NehemiahEngineeringOrbitalScience 0.8.0 conflicts with Kerbalism 2.1.2
Install canceled. Your files have been returned to their initial state.

$ ckan upgrade Kerbalism

Upgrading modules...


Done!

$ ckan install -c NehemiahEngineeringOrbitalScience-0.8.0.ckan 
About to install...

 * Nehemiah Engineering Orbital Science 0.8.0 (cached)
 * Kerbal Inventory System 1.22 (media.forgecdn.net, 24.0 MiB)
 * Community Category Kit 4.1.0.0 (github.com, 116.1 KiB)
 * Corvus CF v1.3.4 (spacedock.info, 6.5 MiB)
 * K2 Command Pod Continued 1.1.8.6 (spacedock.info, 855.5 KiB)
 * Kerbal Alarm Clock v3.10.0.0 (cached)
 * TriggerAu Flags v2.9.3.0 (cached)

Continue? [Y/n] 
```

**Comment by mwerle** [comment]
Awesome, thank you! And for the super-fast merge. :)

**Pull request merged**
