### PR TITLE
ExtraPlanetaryLaunchpads new release

### PR DESCRIPTION
**Pull request by politas**
Extended KSP version as per forum thread.
KIS is now a dependency rather than a recommend, as per forum thread

### CODE REVIEW

**Comment by Dazpoet** [comment]
Shouldn't this be targetting 1.2.1 as that was the only change to it against the earlier version as per the [EPL forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/54284-12-extraplanetary-launchpads-v553/&page=170#comment-2836162)?

**Comment by politas** [comment]
The main post describes it as being for "1.2", and I don't read that post as being exclusive to 1.2.1, but inclusive of.

>The only change from 5.5.2 is to update the version check for KSP 1.2.1

So there were no changes in code. I am wondering if there might be a .version file we can use in there now, though.

**Comment by politas** [comment]
Awwww, yis! Very cool, let's give more control to Taniwha!

**Comment by politas** [comment]
Whoops, Bash replaced $kref and $vref with the contents of non-existent environment variables.

**Comment by Dazpoet** [comment]
LGTM 👍

**Pull request merged**
