### PR TITLE
Scs

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by HebaruSan** [comment]
```
3654 [1] FATAL CKAN.NetKAN.Program (null) - Schema validation failed: #/resources.homepage: UriExpected
```

Very weird. `homepage` isn't required as far as I know. Going to run this locally with the debug flag.

**Comment by HebaruSan** [comment]
Weirder and weirder.

```json
  "resources": {
    "homepage": "HomePage",
    "repository": "https://github.com/linuxgurugamer/SolarCycleSimulator"
  },
```

**Comment by HebaruSan** [comment]
@linuxgurugamer try removing this invalid link from the repo, presumably in the Settings:

image

**Comment by linuxgurugamer** [comment]
#rebuild

**Pull request merged**
