### PR TITLE
RSSeaDragon: Remove "quicksearch" recommendation, since feature is stock now.

### PR DESCRIPTION
**Pull request by NecroBones**

### CODE REVIEW

**Comment by Dazpoet** [comment]
Closing this since #3505 was merged with the same changes.

**Comment by NecroBones** [comment]
#3505 referenced a different mod, FYI.

**Comment by NecroBones** [comment]
Should I re-do the changes and make a new PR for these changes? Since it was a different netkan file.

**Comment by NecroBones** [comment]
I went ahead and opened #3507

**Pull request closed without merging**
