### PR TITLE
Add LightsOut from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of nodrog6, to add [LightsOut](https://kerbalstuff.com/mod/678/LightsOut) to CKAN.

Please direct questions about this pull request to [nodrog6](https://kerbalstuff.com/profile/nodrog6).

### CODE REVIEW

**Comment by nodrog6** [comment]
Hello!  I'm fairly new to GitHub pull requests and CKAN.  How can I help my mod pass these failed checks?  Thanks for your help.

**Comment by Dazpoet** [comment]
Looks pretty fine from here. I think the problem might be that our buildbot isn't yet updated to 1.0 so it's failing because it (correctly) can't find it for 0.90. Will have to do a manual check.

**Comment by Dazpoet** [comment]
Local testing is somewhat inconclusive. Let's merge and see if it works. @BasharMilesTeg let's see if it installs correctly.

**Comment by Dazpoet** [comment]
@nodrog6 your mod is now indexed and working through CKAN :)

**Comment by nodrog6** [comment]
@Dazpoet thanks so much.  You guys rock.

**Pull request merged**
