### PR TITLE
Create StockLS.netkan

### PR DESCRIPTION
**Pull request by plague006**
Closes #2409
@vosechu I'd like your input on the install. Written as is this will only install `USILifeSupport.cfg` into `GameData/StockLS`. While I'd like to install the other files (.version file, readme, license) that would result in an odd install structure for users:

````
D:\TESTSUITE\DUMMY_KSP\GAMEDATA
|   
\---StockLS
    |   .DS_Store
    |   LICENSE
    |   README.md
    |   StockLS.version
    |   
    +---AutoPruner
    |   \---PRNLs
    |           StockLS.prnl
    |           
    \---GameData
        \---StockLS
                USILifeSupport.cfg
````

Basically the path to `USILifeSupport.cfg` would be `KSP/GameData/StockLS/GameData/StockLS/USILifeSupport.cfg`

Lemme know how you'd like to proceed, if you're happy with just installing `GameData/StockLS/USILifeSupport.cfg` or if you want to restructure the .zip, or whatever.

### CODE REVIEW

**Comment by vosechu** [comment]
@plague006 I've updated the zip on Kerbalstuff. I think the structure is much more sane now. I also deleted all the pesky .DS_Store and used a different zip program that doesn't insert __MACOSXZIP__ or whatever that filename was. :)

I'm not concerned about facilitating the installation of the optional configs just yet; I'm a little divided on whether to even include them because they're a big departure from Malahx's original goal with the Stock* plugins. But they make me happy so I figured I should include them just in case. 

```
.
├── GameData
│   └── StockLS
│       ├── AutoPruner
│       │   └── PRNLs
│       │       └── StockLS.prnl
│       ├── LICENSE
│       ├── README.md
│       ├── StockLS.version
│       └── USILifeSupport.cfg
└── Optional
    └── GameData
        └── StockLS
            ├── README.md
            └── USILifeSupportShim.cfg
```

**Comment by plague006** [comment]
The optional configs can be installed by a seperate module/set of metadata in CKAN easily. For an example see 
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Asclepius.netkan
and
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Asclepius-clouds.netkan.
I'm closing/reopening this PR to force a Jenkins rebuild.

**Comment by vosechu** [comment]
This looks perfect to me!

**Comment by vosechu** [comment]
Thank you so much for the help @plague006! I'll add the optional config later on when I get more of it done.

**Comment by pjf** [comment]
This is looking good to me, so I'm about to merge after I give it one last glance-over.

```
StockLS: Like Malahx's StockPlugins mod, this allows you to have life support without adding a bunch of parts that will break the next time KSP is updated.

Module info:
- version:	1.0.2
- authors:	vosechu
- status:	stable
- license:	MIT

Depends:
- ModuleManager, min: 2.6.0

Recommends:
- USILifeSupport

Suggests:
- StockPlugins
- StockRT
- StockSCANSat

Provides:
- StockLS

Resources:
- homepage: http://github.com/vosechu/StockLS
- kerbalstuff: https://kerbalstuff.com/mod/1210/StockLS
- repository: http://github.com/vosechu/StockLS

Filename: D723222B-StockLS-1.0.2.zip

Showing 8 installed files:
- GameData/StockLS
- GameData/StockLS/AutoPruner
- GameData/StockLS/AutoPruner/PRNLs
- GameData/StockLS/AutoPruner/PRNLs/StockLS.prnl
- GameData/StockLS/LICENSE
- GameData/StockLS/README.md
- GameData/StockLS/StockLS.version
- GameData/StockLS/USILifeSupport.cfg
```

**Comment by pjf** [comment]
This is wonderful! Merging with great joy. :)

**Comment by vosechu** [comment]
Thank you both!

**Pull request merged**
