### PR TITLE
Halloween 🎃 🎃 🎃 

### PR DESCRIPTION
**Pull request by zer0Kerbal**
- https://spacedock.info/mod/2875
- https://github.com/zer0Kerbal/Halloween
- <https://forum.kerbalspaceprogram.com/index.php?/topic/205185-*>

### CODE REVIEW

**Comment by DasSkelett** [comment]
The changes to JackOLantern are already present in #8806, I'm going to force-push to your branch to remove them.

**Comment by DasSkelett** [comment]
A few things:
- The mod isn't published on SpaceDock yet
- The netkan and license file within the zip say CC-BY-NC-SA-4.0, SpaceDock says "CC BY-NC-SA 3.0 unported". I guess SD needs an update?
- Is the name "Halloween! (HWLN)" correct? Especially the "HWLN" part, should that be "HLWN", maybe?

**Comment by zer0Kerbal** [comment]
been pushing hard - to get it out before the holiday. HLWN is what it should be. 🎃 

I should have this out in the next 24-48 hours. 

Was trying to determine the correct license, and it seems that CC BY-NC-SA 4.0 is going to be the license. SD corrected.

**Comment by zer0Kerbal** [comment]
more chainsaw over cuts. 🪚

**Comment by HebaruSan** [comment]
> I should have this out in the next 24-48 hours.

@zer0Kerbal, the holiday is only 11 days away, are you still planning to click Publish on SpaceDock?

**Comment by zer0Kerbal** [comment]
at least the candles are standing up straight and attaching correctly finally.

**Pull request merged**
