### PR TITLE
Move Davon Throttle Control Systems to Spacedock

### PR DESCRIPTION
**Pull request by politas**
filter sources, fix license

### CODE REVIEW

**Comment by Dazpoet** [comment]
As I don't speak regex I'm not sure why the filter isn't working but I can say based on the consoleoutput that it isn't since we're now installing both of them. Don't we need to add brackets around strings or something?

**Comment by politas** [comment]
Brackets are only for where you are doing complex stuff. This is a simple match a string. Don't know why the "." wildcard didn't work.

**Comment by politas** [comment]
That's got it.

**Comment by plague006** [comment]
Can we use `"filter_regexp" : "license and source"` so that we don't accidentally catch any awkwardly named files please.

**Pull request merged**
