### PR TITLE
Initial release for AutomatedScreenshots

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Please delete the HogPlume and ProcedurialFairings-AutoshroudRemover from this, they aren't mine and I don't know why they got included when I did a git clone, git add and git commit

### CODE REVIEW

**Comment by plague006** [comment]
Just delete the 2 extra files from your branch and commit the changes.

**Comment by linuxgurugamer** [comment]
Ok, I just did that.  thanks

**Comment by linuxgurugamer** [comment]
Any idea when this and the KW fix mod will be available via CKAN?


Thanks


JBB

**Comment by plague006** [comment]
Netkan runs every 3 hours, so within 3 hours of a netkan being merged it's available on CKAN.

Should KWFix depend on actually having KW? Does it do anything without it?

**Comment by linuxgurugamer** [comment]
It should depend on KW, but since its just a MM patch, nothing will 
happen without it.

JBB

**Comment by plague006** [comment]
I saw what @TeddyDD is doing in https://github.com/KSP-CKAN/CKAN-meta/pull/724, it's an elegant solution to the issue.

**Comment by plague006** [comment]
Delete `KWCommunityFixes.netkan` and I can merge for `AutomatedScreenshots.netkan`

**Comment by linuxgurugamer** [comment]
Done.

**Comment by linuxgurugamer** [comment]
Any idea when this will be merged?

**Comment by plague006** [comment]
Your latest commit wants to touch `HotPlume.netkan` and `ProceduralFairings-AutoShroudRemover.netkan`. I'm just pulling out `AutomatedScreenshots.netkan` and commiting it in a separate PR.

**Comment by linuxgurugamer** [comment]
That's strange, because I had deleted those two a while ago.

I don't even know how they got in there, because I never touched them.

Anyway, thanks for taking care of it.


JBB

**Comment by linuxgurugamer** [comment]
Again, thanks.

If this happens again, I assume I would see it before submitting the 
pull request.  So I assume that the safest thing would be just to delete 
the repo and clone it again, is that correct?

Thanks

JBB

**Comment by plague006** [comment]
In this specific case, you'd just want to delete the `HotPlume.netkan` and `ProceduralFairings-AutoShroudRemover.netkan` files from your fork of the repo and then commit.

**Pull request closed without merging**
