### PR TITLE
Add min/max version to ancient outdated KCT-RP0 conf

### PR DESCRIPTION
**Pull request by NathanKell**

### CODE REVIEW

**Comment by NathanKell** [comment]
Says RP-0 isn't available for those versions, which is really odd.

**Comment by politas** [comment]
So let me get this straight - This KerbalConstructionTime-RP-0-Config is no longer required, and all the old releases should have KSP version restrictions applied to stop this appearing in people's CKAN client?

We'll need to do that in CKAN-meta direct. There are thirteen .ckan files that all need to be changed.

**Comment by NathanKell** [comment]
Ah, quite right.

**Comment by NathanKell** [comment]
And yes, you understand correctly.

**Comment by politas** [comment]
Ok, sorry to take so long getting back to this. @NathanKell , can you change this PR to rename the file to `KerbalConstructionTime-RP-0-Config.frozen`?

**Comment by NathanKell** [comment]
Done so! No worries.

**Comment by politas** [comment]
Thanks for the super-prompt response!

**Comment by NathanKell** [comment]
:)

**Pull request merged**
