### PR TITLE
Update PreciseEditor.netkan

### PR DESCRIPTION
**Pull request by jfrouleau**
The mod have a new maintainer. The new netkan file points to the new GitHub repository.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks for letting us know, but this won't work until @zolotiyeruki creates a release.

**Comment by jfrouleau** [comment]
Oh my bad, I'll wait till zolotiyeruki make a release.

**Comment by zolotiyeruki** [comment]
I've created a release here: https://github.com/zolotiyeruki/PreciseEditor/releases/tag/v1.4.0.1

Hopefully I did it right.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Yup, looks good. Thanks for the update!

**Pull request merged**
