### PR TITLE
Freeze mods

### PR DESCRIPTION
**Pull request by Olympic1**
Freezing `NFT Decaying RTG's` because since v0.6.0 this feature was removed from the download. This will be brought back in the future.

Deleting the other 5 files because these seperate mods were merged into one (https://kerbalstuff.com/mod/1368).

### CODE REVIEW

**Comment by Olympic1** [comment]
This failed because it still wants to create a release for the mods that we'll freeze

**Comment by politas** [comment]
If we're not expecting them to ever be updated, why are we not just deleting the netkans to clean up the directory?

**Comment by Olympic1** [comment]
Well I can delete the netkans except for the NFT Decaying RTG's one, because Nertea hasn't confirmed to me if he will bring it back or not.

**Comment by Olympic1** [comment]
Nertea said he will bring it back in the future, so freezing the file untill the feature is brought back.
Deleted the other netkans as they were merged into one mod.

This can be merged.

**Pull request merged**
