### PR TITLE
download mirror moved to github

### PR DESCRIPTION
**Pull request by Sigma88**

### CODE REVIEW

**Comment by plague006** [comment]
This requires:
1) @netkan-bot to generate a new .ckan from SigmaBinary-core.netkan (expected within the hour).
2) A manual #rebuild so that Jenkins can download `SigmaBinary-core` (pinging @techman83)

Nothing you need to do yourself @Sigma88.

**Comment by techman83** [comment]
I'll force a rebuild when NetKAN does its thing. I'd love to know the magic whomever configured the last jenkins to make #rebuild work.

**Comment by techman83** [comment]
:dancers:

**Comment by Sigma88** [comment]
I probably am not familiar enough with this system because I am not sure what I should do to make it work.
Is there a tutorial somewhere that I can read to understand how to submit changes?

also, now that I'm not using KerbalStuff anymore, will I need to make a pull request every time I publish an update? or will this check the version automatically?

**Comment by plague006** [comment]
All automatic. As for a tutorial, I'm not sure which system you mean. Probably Git? I looked at http://pcottle.github.io/learnGitBranching/ for the basics and then started using SmartGit to avoid having to learn a full command-line interface.

**Comment by Sigma88** [comment]
what I've done is:

- fork the repository
- edit the file
- pull request

I did the exact same thing for SigmaBinary and it worked. no idea why it shouldn't for dunaike

**Comment by plague006** [comment]
The reason DunaIke didn't initially work is because `SigmaBinary` was broken when Jenkins tested it. The KerbalStuff page was 404 and @netkan-bot hadn't yet generated the new SigmaBinary .ckan with the GitHub info.

**Comment by Sigma88** [comment]
so if I try now it should work right?

**Comment by techman83** [comment]
@Sigma88 Yep!

**Comment by Sigma88** [comment]
ok, thanks everybody :+1:

**Pull request merged**
