### PR TITLE
Add Phoenix Industries Cargo Resupply System from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of MoviesColin, to add [Phoenix Industries Cargo Resupply System](https://kerbalstuff.com/mod/831/Phoenix%20Industries%20Cargo%20Resupply%20System) to CKAN.

Please direct questions about this pull request to [MoviesColin](https://kerbalstuff.com/profile/MoviesColin).

### CODE REVIEW

**Comment by mgsdk** [comment]
Needs to filter Thumbs.db. The zip file contain two sets of parts, do we create two packages and split the flags out into a core package?

**Comment by Dazpoet** [comment]
Surely KSP don't just accept parts having the same names? Partnames are identical for the 2 different versions meaning we'll never install them next to eachother by using a Provides/Conflicts solution. Hence no core package should be needed.

**Comment by mgsdk** [comment]
You're right, so something along the lines of banana for scale then.

**Comment by Dazpoet** [comment]
Sounds about right.

**Pull request closed without merging**
