### PR TITLE
Update AustrianSpaceAgency.netkan

### PR DESCRIPTION
**Pull request by brama0309**
Added Mod recommendation

### CODE REVIEW

**Comment by politas** [comment]
CKAN recommends are intended to refer to mods that have some particular synergy. The recommended mod should have a particular interaction with this mod, which I don't believe is the case here. If you wish to add some TextureReplacer assets to your mod, then setting TextureReplacer as a dependency would be appropriate, but while this is just a flags mod, this isn't really appropriate.

**Comment by brama0309** [comment]
I´ve added some Suit Textures with the ASA Flag on them, and for this TextureReplacer is needed, sry for not mention it in the first comment.

**Comment by politas** [comment]
Those would need to be installed in the GameData/TextureReplacer/Suits directory, in that case, and TextureReplacer would need to be in a `"depends"` block rather than `"recommends"`.

**Comment by brama0309** [comment]
I´ve changed it! Thank you for your help and patience!!

**Comment by politas** [comment]
Now you'll need to add the `"install"` instructions:

    "install": [
        {
            "find":"GameData/AustrianSpaceAgency",
            "install_to": "GameData"
        },
        {
            "find":"Suits/AustrianSpaceAgency",
            "install_to": "GameData/TextureReplacer/Suits"
        }
    ]

**Comment by politas** [comment]
Oh, and could you change the ksp_version and add a comment?

    "ksp_version": "any",
    "comment": "flagmod",

**Comment by politas** [comment]
Looking good, but you've slipped back to recommends instead of depends.

**Comment by politas** [comment]
Ah, sorry, forget to mention this change required up the top:

    "spec_version": "v1.4",

**Comment by politas** [comment]
Thanks for your patience! Merging now

**Comment by brama0309** [comment]
Thank you!

Am 28.08.2016 23:56 schrieb "Myk" <notifications@github.com>:

**Pull request merged**
