### PR TITLE
JackOLantern 🎃 🧙 🎃 

### PR DESCRIPTION
**Pull request by zer0Kerbal**
# JackOLantern (Jack-O'Lantern)
- update 🎃 
- - Happy Early AllHallowedEve!

- https://spacedock.info/mod/2261/Jack-O%27-Lantern
- https://github.com/zer0Kerbal/JackOLantern
- <https://forum.kerbalspaceprogram.com/index.php?/topic/189466-*>

### CODE REVIEW

**Comment by DasSkelett** [comment]
Hey, are you sure about the removal of the ModuleManager dependency? Validation reports that there is a `Tags.cfg` file that uses MM syntax.

The remote version file URL is broken currently: `https://github.com/zer0Kerbal/Jack-O-Lantern/JackOLantern.version`
Try e.g. `https://raw.githubusercontent.com/zer0Kerbal/JackOLantern/master/JackOLantern.version` instead

**Comment by DasSkelett** [comment]
Also is there a chance you could clean up your Git branches / rebase them on upstream master, please? All these stray, unrelated commits are a bit irritating. Thanks!

**Comment by zer0Kerbal** [comment]
*chuckle* the one on SD is from 2019, so I'd say it has some dust on it. ;p It is updated in the new archive.

**Comment by zer0Kerbal** [comment]
@HebaruSan unintentional - was cleaning out the shrubbery per @DasSkelett request and got a little chop happy with the Husqvarna 592 XP... same goes for the Halloween PR

**Comment by HebaruSan** [comment]
Thanks for the updates!

**Comment by zer0Kerbal** [comment]
> Thanks for the updates!

trying to help out. will try to continue to improve and push updates to CKAN as I update / adopt.

**Pull request merged**
