### PR TITLE
Add RealismOverhaulCraftFiles

### LINKED ISSUE #4498: Splitting RO craft files out of RO
https://github.com/KSP-RO/RealismOverhaul/pull/1332 involves splitting our craft files out into a new package which the core RO package then recommends.

Does this look sane to you? If so, what netkan-side changes need be made? Making a new netkan stub to point to our new netkan? What else?

### PR DESCRIPTION
**Pull request by NathanKell**
Closes #4498

### CODE REVIEW

**Comment by NathanKell** [comment]
I stupidly created this PR before I merged the RO-side PR. It may need to be manually checked.

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
Changes in the upstream RealismOverhaul netkan just aren't forcing an update in the latest .ckan file like they should. @techman83, is there a way we can force a rebuild?

**Comment by techman83** [comment]
@politas the indexer will only ever commit the output of netkan. If netkan doesn't produce a different *valid* output, nothing will get committed.

`2016/08/29 03:26:04 INFO Commiting RealismOverhaul-v11.3.1`
|NetKAN ↑|Last Checked|Last Inflated|Last Indexed|
|RealismOverhaul|2 hours ago|2 hours ago|2 hours ago|

Something has happened since though.

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
I thought @raidernick had renamed the craft files to avoid this issue?

**Comment by raidernick** [comment]
@politas I did rename them, so it's not possible that they should conflict

**Comment by politas** [comment]
Ok, with RO 11.3.1 updating, this is now passing. Merging with thanks!

**Pull request merged**
