### PR TITLE
Add New Horizons Visual Enhancements from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Alaygrounds, to add [New Horizons Visual Enhancements](https://spacedock.info/mod/1908/New%20Horizons%20Visual%20Enhancements) to CKAN.

Mod details:
    name = /mod/1908/New%20Horizons%20Visual%20Enhancements
    author = Alaygrounds
    abstract = Adds scatterer effects to all the atmospheric bodies in the New Horizons mod.
    license = Public Domain
    Homepage = https://forum.kerbalspaceprogram.com/index.php?/topic/176745-new-horizons-visual-enhancements/
    description = Requires Scatterer and New Horizons, and their dependancies.

Please direct questions about this pull request to [Alaygrounds](https://spacedock.info/profile/Alaygrounds).

ckan compat add 1.3

### CODE REVIEW

**Comment by HebaruSan** [comment]
This was added in #6686, but as frozen because of dependency issues. Should be re-assessed.

**Comment by HebaruSan** [comment]
Now it's not being validated because the file is being renamed, need KSP-CKAN/xKAN-meta_testing#49.

**Comment by Olympic1** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
What's the dependency, a full release of New Horizons?

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Seems OK now. I think you're right, NewHorizons was the missing dependency, it's only for 1.3.0 but this is for 1.3.1.

**Comment by linuxgurugamer** [comment]
well, I have a working version of NH for 1.7, maybe I'll release that in a curator mode

**Pull request merged**
