### PR TITLE
Add ResearchBodies from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of simon56modder, to add [ResearchBodies](https://kerbalstuff.com/mod/1203/ResearchBodies) to CKAN.

Please direct questions about this pull request to [simon56modder](https://kerbalstuff.com/profile/simon56modder).

### CODE REVIEW

**Comment by Olympic1** [comment]
@Olympic1
Part of KSP-CKAN/CKAN-meta/issues/588

**Comment by Olympic1** [comment]
No conflicts with other planet packs, so merging

**Comment by plague006** [comment]
This needs a MM dependency which I'll PR shortly.

**Comment by plague006** [comment]
The license is also incorrect which I'll address in the same PR.

**Pull request merged**
