### PR TITLE
Added NetKAN/sidosUraniaSystem.netkan per author's request

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by plague006** [comment]
`name`, `ksp_version`, `version`, `release_status` and `author` will all be scraped from the kerbalstuff data and doesn't need to be included in the .netkan. In the specific cases of `ksp_version` and `version` it's actually problematic to have them hardcoded since every new release will all have the same information in CKAN.

`x_netkan_license_ok` should be swapped to a hardcoded `license` because the KerbalStuff page lists the license as `MIT` while the forum thread lists the license as `CC-BY-NC-SA`

**Comment by plague006** [comment]
@Olympic1
Part of KSP-CKAN/CKAN-meta/issues/588

**Comment by linuxgurugamer** [comment]
Do you need me to change it ?

JBB

**Comment by linuxgurugamer** [comment]
Please note that I re-uploaded this .netkan after making changes per a 
previous message from Matthew.

I had to do the re-upload (git add/commit/push) since I no longer had 
the git repo, so had to reclone the repo.

The new merge is: #2407


JBB

**Comment by plague006** [comment]
Closing in favour of #2407

**Pull request closed without merging**
