### PR TITLE
Add BetterEmissives and NinjaTech Enterprises

### PR DESCRIPTION
**Pull request by plague006**
Closes #1393
Closes #1391
When Ninja5tyl3/NinjaTechEnterprises#10 is resolved, AVC support can be added to netkan.

### CODE REVIEW

**Comment by plague006** [comment]
Will my commit messages auto-close issues/PRs or is it only what I write in these posts/comments?

**Comment by Dazpoet** [comment]
NinjaTech has a .version file, if it looks correct I recommend adding a vref to grab info from it. Because .version files are awesome :)

**Comment by mgsdk** [comment]
Output of https://github.com/plague006/NetKAN/commit/16b0578ad64901cae3ded2171166d7bd35e75e16

**BetterEmissives**
```
cat BetterEmissives-v1.0.ckan
{
    "spec_version": 1,
    "identifier": "BetterEmissives",
    "license": "CC-BY-SA-4.0",
    "depends": [
        {
            "name": "ModuleManager"
        }
    ],
    "install": [
        {
            "file": "GameData/BetterEmissive",
            "install_to": "GameData"
        }
    ],
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/122673",
        "kerbalstuff": "https://kerbalstuff.com/mod/833/BetterEmissives"
    },
    "ksp_version": "1.0.2",
    "name": "BetterEmissives",
    "abstract": "Adds pre-1.0-like engine heat effects",
    "author": "mythbusters844",
    "version": "v1.0",
    "download": "https://kerbalstuff.com/mod/833/BetterEmissives/download/v1.0",
    "x_generated_by": "netkan",
    "download_size": 6219
}
```

```
BetterEmissives: Adds pre-1.0-like engine heat effects

Module info:
- version:	v1.0
- authors:	mythbusters844
- status:	stable
- license:	CC-BY-SA-4.0

Depends:
- ModuleManager

Provides:
- BetterEmissives

Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/122673
- kerbalstuff: https://kerbalstuff.com/mod/833/BetterEmissives

Filename: B7A582E7-BetterEmissives-v1.0.zip

Showing 2 installed files:
- GameData/BetterEmissive
- GameData/BetterEmissive/BetterEmissive.cfg
```

**NinjaTech**

```
cat NinjaTechEnterprises-0.0.4.ckan
{
    "spec_version": "v1.4",
    "identifier": "NinjaTechEnterprises",
    "license": "GPL-3.0",
    "depends": [
        {
            "name": "ModuleManager"
        }
    ],
    "install": [
        {
            "find": "Agency",
            "install_to": "GameData/NinjaTechEnterprises"
        },
        {
            "find": "Flags",
            "install_to": "GameData/NinjaTechEnterprises"
        },
        {
            "find": "Parts",
            "install_to": "GameData/NinjaTechEnterprises"
        }
    ],
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/84926-WIP-1-0-2-NinjaTech-Enterprises-Dev-Thread?p=1247397#post1247397",
        "kerbalstuff": "https://kerbalstuff.com/mod/834/NinjaTech%20Enterprises"
    },
    "ksp_version": "1.0.2",
    "name": "NinjaTech Enterprises",
    "abstract": "Adding useful parts for your useful crafts.",
    "author": "Ninja_5tyl3",
    "version": "0.0.4",
    "download": "https://kerbalstuff.com/mod/834/NinjaTech%20Enterprises/download/0.0.4",
    "x_generated_by": "netkan",
    "download_size": 34687
}
```

```
NinjaTech Enterprises: Adding useful parts for your useful crafts.

Module info:
- version:	0.0.4
- authors:	Ninja_5tyl3
- status:	stable
- license:	GPL-3.0

Depends:
- ModuleManager

Provides:
- NinjaTechEnterprises

Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/84926-WIP-1-0-2-NinjaTech-Enterprises-Dev-Thread?p=1247397#post1247397
- kerbalstuff: https://kerbalstuff.com/mod/834/NinjaTech%20Enterprises

Filename: 5EF6F113-NinjaTechEnterprises-0.0.4.zip

Showing 15 installed files:
- GameData/NinjaTechEnterprises/Agency
- GameData/NinjaTechEnterprises/Agency/NinjaTechEnterprises.png
- GameData/NinjaTechEnterprises/Agency/Agency.cfg
- GameData/NinjaTechEnterprises/Agency/NinjaTechEnterprises_sm.png
- GameData/NinjaTechEnterprises/Flags
- GameData/NinjaTechEnterprises/Flags/NinjaTechEnterprises.png
- GameData/NinjaTechEnterprises/Parts
- GameData/NinjaTechEnterprises/Parts/Aero
- GameData/NinjaTechEnterprises/Parts/Aero/heatshieldmm.cfg
- GameData/NinjaTechEnterprises/Parts/Control
- GameData/NinjaTechEnterprises/Parts/Control/rcsmm.cfg
- GameData/NinjaTechEnterprises/Parts/Control/probemm.cfg
- GameData/NinjaTechEnterprises/Parts/Control/asasmm.cfg
- GameData/NinjaTechEnterprises/Parts/Utility
- GameData/NinjaTechEnterprises/Parts/Utility/servicebaymm.cfg
```

**Comment by mgsdk** [comment]
Merged by hand since netkan did not like the zip file for NinjaTech 0.0.4.

**Pull request merged**
