### PR TITLE
Buffalo2 and WildBlueCore NetKAN Additions

### PR DESCRIPTION
**Pull request by Angel-125**
Adds WildBlueCore and Buffalo 2 to CKAN.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Saw this:

image

And realized Sandcastle is already indexed, so we better make sure they won't conflict. The current release doesn't bundle it, but it's in a pre-release, so presumably the next version as well:

image

image

Updated Sandcastle's `install` to only pick out the Sandcastle folder to avoid a future file conflict. We can add the dependency when it's needed.

**Comment by Angel-125** [comment]
> Saw this:
> 
> image
> 
> And realized Sandcastle is already indexed, so we better make sure they won't conflict. The current release doesn't bundle it, but it's in a pre-release, so presumably the next version as well:
> 
> image
> 
> image
> 
> Updated Sandcastle's `install` to only pick out the Sandcastle folder to avoid a future file conflict. We can add the dependency when it's needed.

WildBlueCore is already indexed? I know WildBlueTools is, but I'd forgotten that WBC was already in CKAN. Great spot, thank you :)

**Comment by HebaruSan** [comment]
> WildBlueCore is already indexed? I know WildBlueTools is, but I'd forgotten that WBC was already in CKAN. Great spot, thank you :)

No, **Sandcastle** is already indexed, sorry for the confusion.

**Review by HebaruSan — APPROVED** [review]
Looks good to me, let's give this a try. Thanks for the submission!

**Pull request merged**
