### PR TITLE
New B9PW fork

### PR DESCRIPTION
**Pull request by HebaruSan**
The new B9PW fork is finally ready for prime time.

image

### CODE REVIEW

**Comment by HebaruSan** [comment]
Waiting for @linuxgurugamer to update the remote version file to say 1.12 like the one in the download.

http://ksp.spacetux.net/avc/B9_Aerospace_ProceduralWings.version

**Comment by HebaruSan** [comment]
Asked for a link to image...

**Comment by linuxgurugamer** [comment]
Actually, besides the depenedency on FAR, merging all the codebases with all the various improvements/bug fixes was also important :-)

**Comment by linuxgurugamer** [comment]
Thank you

**Pull request merged**
