### PR TITLE
Create UKS-KerbalismPatch.netkan

### PR DESCRIPTION
**Pull request by Quartz101**
My second mod (sorta)

Edit: Closes https://github.com/KSP-CKAN/NetKAN/pull/4165

### CODE REVIEW

**Comment by Quartz101** [comment]
oops, accidently checked the box that made spacedock or spaceduck or whatever auto send a PR. >_<

**Comment by plague006** [comment]
Would you mind changing the filename and identifier to `UKS-Kerbalism-Patch` to improve readability for us?

**Comment by Quartz101** [comment]
Netkan.exe failed when I tried that, likely because the folder in the Gamedata in the mod zip is called "UKS-KerbalismPatch"

**Comment by plague006** [comment]
Add the following to the file and that'll resolve it:

````
"install": [
        {
            "file": "GameData/UKS-KerbalismPatch",
            "install_to": "GameData"
        }
    ]
````

**Comment by Quartz101** [comment]
Ok

**Comment by politas** [comment]
Add

    "$vref": "#/ckan/ksp-avc",

**Comment by Quartz101** [comment]
Is it good now?

**Comment by politas** [comment]
That's looking fine. Merging with thanks for the persistence!

**Comment by Quartz101** [comment]
Your welcome!

**Pull request merged**
