### PR TITLE
Officially move OPM to proper netkan. attempt 1

### PR DESCRIPTION
**Pull request by Galileo88**

### CODE REVIEW

**Comment by Galileo88** [comment]
If I did this right, I'd be surprised. I'm returning OPM to its original netkan, while keeping OPM_Galileo stuck in 1.3.1. Moving forward OPM, will no longer use it though.

**Comment by Poodmund** [comment]
Just to add a bit of background, Capt. Robau used to manage OPM but since OPM v.2.1.0 he had stepped away from the KSP community somewhat. Galileo and a few of us forked it to maintain the mod and it was listed as OPM_Galileo. Capt. Robau gave us grace to continue OPM officially so it we are looking to deprecate the previous OPM_Galileo netkan and update the metadata on the old OuterPlanetsMod netkan so that it directs to the newer GitHub repo/releases.

**Comment by HebaruSan** [comment]
So do you just want to freeze updates on OPM-Galileo? You can accomplish that by renaming the file from .netkan to .frozen. The bot will then stop looking for new releases.

**Comment by Poodmund** [comment]
Freezing OPM_Galileo sounds like the desired intention. Then we'll just need to adjust the OuterPlanetsMod NetKAN/metadata so that is points to the new release repo and has any updated info.

**Comment by HebaruSan** [comment]
OK, I added a commit to freeze it.

What about the recommends/suggests/conflicts lists? There are a lot more of them in the "before" version. Are all of those confirmed as no longer applicable?

**Comment by Poodmund** [comment]
I also think it would be handy to add the following the the new OuterPlanetsMod NetKan:

"repository" : "https://github.com/Galileo88/Outer-Planets-Mod/"

**Comment by HebaruSan** [comment]
Luckily a $kref on github will add that automatically, so it's there already:

https://ci.ksp-ckan.org/job/NetKAN/7241/console

```json
    "resources": {
        "homepage": "https://forum.kerbalspaceprogram.com/index.php?/topic/165854-ksp-13-opm_galileo-121-17-sept-2017/",
        "repository": "https://github.com/Galileo88/Outer-Planets-Mod"
    },
```

**Comment by Poodmund** [comment]
We're currently in the process of uploading the new release of OPM v2.2.0 so please don't merge this until that's ready to go. 😆 I'll post a message here when its released, should be within the next hour.

**Comment by Galileo88** [comment]
yeah please do. I thought about freezing it, but didnt know if that's what we wanted to do

**Comment by HebaruSan** [comment]
@Poodmund or @Galileo88, can one of you please address my question above about the recommendations and suggestions? As one example among many, SigmaOPMRecolor was recommended previously and is no longer. This can be fine, but I would like to make sure it's intentional before merging.

**Comment by Poodmund** [comment]
@HebaruSan 

"provides": 
[ "CustomAsteroids-Pops" ] - OPM now has a specific Custom Asteroids patch that is modular, no need for this 'provides'.
"recommends": [
{ "name": "OPMClouds" }, - OPMClouds is an old unsupported mod that is no longer compatible.
{ "name": "SigmaOPMRecolor" }, - SigmaOPMRecolor is an old unsupported mod that we haven't looked into whether it still works.
{ "name": "SigmaOPMExpansion" }, - SigmaOPMExpansion is an old unsupported mod that was terminated and split into other mods.
{ "name": "CustomAsteroids" }, - OPM now has its own Kopernicus asteroids implementation included.
{ "name": "SigmaBinary-core"}, - Sigma Binary is still a bit buggy, we will support it in the future when it is more stable.
{ "name": "CustomBarnKit" } - Custom Barn Kit is a dependency and this line needs to be removed.
],
"conflicts": [
{ "name": "BilliardsPlanetPack" }, - I've never heard of this mod.
{ "name": "RealSolarSystem" }, - Probably should keep this one in as a conflict.
{ "name": "ToySolarSystem" } - This is an old mod, not sure it was every properly released.
],
"suggests": [
{ "name": "JDiminishingRTG" }, - Personal suggestion from old metadata, please remove.
{ "name": "AtomicAge" }, - Personal suggestion from old metadata, please remove.
{ "name": "BetterTimeWarp" }, - Please keep but direct to "BetterTimeWarpCont" instead as it is the continued version.
{ "name": "NearFuturePropulsion" }, - Personal suggestion from old metadata, please remove.
{ "name": "NearFutureElectrical" }, - Personal suggestion from old metadata, please remove.
{ "name": "NearFutureSolar" }, - Personal suggestion from old metadata, please remove.
{ "name": "NearFutureConstruction" }, - Personal suggestion from old metadata, please remove.
{ "name": "NearFutureSpacecraft" }, - Personal suggestion from old metadata, please remove.
{ "name": "TransferWindowPlanner"} - Personal suggestion from old metadata, please remove.
],
"supports": [
{ "name": "PlanetShine" }, - Please keep
{ "name": "DistantObjectEnhancement" }, - Please keep
{ "name": "FinalFrontier" }, - Please keep
{ "name": "ResearchBodies" }, - Please keep
{ "name": "AntennaRange" }, - Unsupported mod, please remove.
{ "name": "RemoteTech" }, - Please keep
{ "name": "SCANsat" }, - Please keep
{ "name": "DeadlyReentry" }, - Unsupported mod, please remove
{ "name": "MunarSurfaceExperimentPackage" }, - Unsupported mod, please remove
{ "name": "CommunityResourcePack" }, - Please keep
{ "name": "TextureReplacer" } - Unsupported mod, please remove
],

Does that help explain all the relationships in the previous NetKAN?

**Comment by Poodmund** [comment]
Also, the new OPM v2.2.0 has been published (https://github.com/Galileo88/Outer-Planets-Mod/releases/tag/2.2.0) so once @Galileo88 has given his grace here, feel free to merge as you see fit. Thanks in advance HebaruSan.

**Comment by HebaruSan** [comment]
Yes, that helps, thanks! A few follow-ups...

> Custom Barn Kit is a dependency and this line needs to be removed

Currently the new metadata has it only as a recommendation. I'll move it to depends based on this, let me know if you want that un-done.

**Comment by HebaruSan** [comment]
Hmm, there's a three-way version conflict here between OPM, Kopernicus, and CustomBarnKit. A table probably makes it clearest:

| KSP Version | Kopernicus available? | CustomBarnKit available? |
| --- | --- | --- |
| 1.4.0 | No | Yes |
| 1.4.1 | No | Yes |
| 1.4.2 | Yes | No |

Since both are dependencies, none of the 1.4.x game versions can install this OPM successfully. I assume that users manually installing would just mix and match those releases on whatever game version they wanted. Let me know how you guys want to deal with this.

**Comment by Poodmund** [comment]
Can you move CustomBarnKit to Recommends please?

**Comment by HebaruSan** [comment]
That looks good, merging...

**Pull request merged**
