### PR TITLE
TACLS-RO-config: Updated install stanza to match the new folder structure.

### PR DESCRIPTION
**Pull request by mgsdk**
RO has updated their folder structure on GitHub, this change should reflect that in the netkan file such that the mod can be indexed properly again.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Seeing as RO isn't out for 1.0.2, making Jenkins choke, yet I'll merge this based on visual inspection and being pretty sure you're right.

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://kooking.vn/girls.php?f>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://neox.tmpl.mk.ua/also.php?sml>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://giaophanbuichu.com/new.php?ksnd>

 

blue@blu3wolf.com

**Comment by Olympic1** [comment]
@Blu3wolf I think you need to fix your mail

**Comment by Blu3wolf** [comment]
I really cant. Its spoofed headers being sent by someone else's mail server; there is to the best of my knowledge literally nothing I can do other than make a fresh email address and dissociate myself from this one.


Sent from my Samsung device


-------- Original message --------

**Comment by techman83** [comment]
@Blu3wolf SPF might help. It's pretty straight forward, just identifying what servers send your mail and creating some dns txt/spf records.

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://mesonculturalswing.com/afternoon.php?q>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://thekalyanacentre.com/things.php?cjyj>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
hi,
I think this story is really awesome, you're gonna love it, please read it here <http://quywiltosi.levidamione.com/improve.php?1nr00>

Take care, blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hi,

Just wanted to say hello and wish you a good day! By the way, have you seen that  <http://nkymogygu.indianfusion.net/aeijeeq>

Looking forward, blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hey,
Have you heard the latest news? You're gonna love this, check it out here <http://rakoveslu.harmdogg.com/aekmhuo>
Hope this helps, blue@blu3wolf.com

**Comment by politas** [comment]
Don't know if locking it will prevent those emails from updating it.

**Pull request merged**
