### PR TITLE
PilotAssistant KSP 113

### PR DESCRIPTION
**Pull request by foonix**
Tested various core functions in 1.1.3 - seems to work.  No obvious compatibility reports on forums.

No response from author despite #4052 and Crzyrndm/Pilot-Assistant/issues/25.

### CODE REVIEW

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by politas** [comment]
Looks good to me. Merging with thanks!

**Pull request merged**
