### PR TITLE
Add CobbFX from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of cobbman11, to add [CobbFX](https://spacedock.info/mod/970/CobbFX) to CKAN.

Mod details:
    name = /mod/970/CobbFX
    author = cobbman11
    abstract = CobbFX is a shader preset package built upon the ReShade 2.0 framework, including color enhancements and dynamic depth of field.
    license = MIT
    Homepage = 
    description = WORK IN PROGRESS!

CobbFX is based on crosire's ReShade 2.0 framework.
www.reshade.me

---

_IMPORTANT_

This package has been tested on 64-bit, OpenGL Kerbal Space Program and
the included depth of field effect does not work properly in Direct3D, as the depth buffer cannot be accessed.

To force OpenGL: Through Steam, right click Kerbal Space Program and select "Properties."
Click "Set Launch Options" and enter -force-opengl.

You may also set this launch parameter on your desktop shortcut in the "Target" field of the shortcut preferences.

_INSTALLATION_

-Unzip and copy contents of "ReShade Files" to main KSP directoy.
Keep the .dll that corresponds to your build of KSP and delete the other.

-Rename ReShadeXX.dll (32 or 64) to opengl32.dll.
_Skip this step if you do not wish to use the depth of field effect._ 

-Choose a preset in "CobbFX Presets" and copy "ReShade" folder to main KSP directory.

-Alternative DoF settings have been created to cover a range of needs. 
See readme file in the alternative DoF folder for more info.

-To install a new preset, simply overwrite the "ReShade" folder with a different one.
Note: Occasionally, switching presets in-game will result in a shader load error.
This will require a reinstallation of ReShade into the KSP main directory.

-Main shader effects can be toggled with Scroll Lock and depth of field with Home.
Print Screen will send screenshots directly to your main KSP folder.

-Note: Depth of field may not appear when the KSP UI is enabled.

-Remember, not all effects fit every occasion. Tweak, experiment, and have fun!

_Thanks!_

---

CobbFX by Andrew Cobb, (c) 2016
MIT license

Please direct questions about this pull request to [cobbman11](https://spacedock.info/profile/cobbman11).

### CODE REVIEW

**Comment by politas** [comment]
CKAN can't handle the installation for this mod, currently. We've got no way to rename a file we're installing.

**Comment by Dazpoet** [comment]
I can't say I've used the feature but https://github.com/KSP-CKAN/CKAN/pull/1728 says that we do have the ability to rename a file or directory we're installing :o

**Comment by politas** [comment]
I think we'll have to have multiple netkans for the different presets, anyway. I'll investigate further.

**Comment by politas** [comment]
Ah, it's Windows-only. Screw it.

**Pull request closed without merging**
