### PR TITLE
Fix Nehemiah's mods

### PR DESCRIPTION
**Pull request by AlexanderDzhoganov**

### CODE REVIEW

**Comment by N3h3miah** [comment]
NE_Science_Common is used by 4 mods MultiPurposeParts only by 2. This would add parts to the other 2 mods that are useless for them.

**Comment by AlexanderDzhoganov** [comment]
Ok, I will split up the packages then. Gimme two mins.

**Comment by AlexanderDzhoganov** [comment]
I think it's done, can you take a look?

**Comment by AlexanderDzhoganov** [comment]
The build bot is going to complain but it's a false negative, I think it's all fine.

**Comment by N3h3miah** [comment]
Looks good to me. Thanks.

**Comment by AlexanderDzhoganov** [comment]
I will test it out after the bot pushes the new .ckan's. Thanks for letting me know about this.

**Comment by N3h3miah** [comment]
On the second look I saw something you forgot to update the name in NehemiahMultiPurposeParts.netkan. Sorry.

**Comment by AlexanderDzhoganov** [comment]
Oops, sorry about that. Fixed now :)
Anyway, I tested out the installs on my local CKAN and all checks out:

**Comment by N3h3miah** [comment]
Great and thanks for your support.

**Pull request merged**
