### PR TITLE
Updated author for PlanetShine

### PR DESCRIPTION
**Pull request by prestja**
I've updated PlanetShine for KSP 1.8 and higher. You can find the new forum post containing my reasons for the change in authorship [here](https://forum.kerbalspaceprogram.com/index.php?/topic/189071-18x-planetshine-0262-oct-19-2019/). If I've done anything incorrectly, let me know.

### CODE REVIEW

**Comment by DasSkelett** [comment]
Are you sure you don't want to use a .version file? It can help you keeping the compatibility data up to date if you point to a remote .version file, so you don't need to re-release the mod for new KSP versions.
If you don't, you should remove the included .version file, because it has outdated data in it.

The config is currently split into a [separate CKAN module](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PlanetShine-Config-Default.netkan).
Either it needs an update too, or it should be merged with this mod. I'm not sure what the reasoning was for splitting them up, probably other mods providing different configs for PlanetShine?

**Comment by HebaruSan** [comment]
Submitted prestja/ksp-planetshine#1 to help with the version file.

**Comment by prestja** [comment]
> Are you sure you don't want to use a .version file? It can help you keeping the compatibility data up to date if you point to a remote .version file, so you don't need to re-release the mod for new KSP versions.
For the time being I'll be foregoing a .version until I can get a new entry listed on AVC.
> If you don't, you should remove the included .version file, because it has outdated data in it, which will trigger warnings from KSP-AVC.
Yep. I'll updating that soon.
> The config is currently split into a [separate CKAN module](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/PlanetShine-Config-Default.netkan).
> Either it needs an update too, or it should be merged with this mod. I'm not sure what the reasoning was for splitting them up, probably other mods providing different configs for PlanetShine?
Exactly right. You can get alternate PlanetShine configs from visual packs.

**Comment by prestja** [comment]
@HebaruSan Thanks for the .version update. Everything looks good in my repo.

**Comment by HebaruSan** [comment]
The .version file inside [the download](https://github.com/prestja/ksp-planetshine/releases/download/0.2.6.2/PlanetShine.zip) is still the old one. Can you update it? It's located here:

image

**Comment by prestja** [comment]
> The .version file inside [the download](https://github.com/prestja/ksp-planetshine/releases/download/0.2.6.2/PlanetShine.zip) is still the old one. Can you update it? It's located here:
> 
> image

Alright, I've made a new release 0.2.6.3 with the version bump.

**Comment by HebaruSan** [comment]
Looks good now.

The original author has said he'll start maintaining again, but that was over a month ago now with no further updates:

https://forum.kerbalspaceprogram.com/index.php?/topic/173138-141-planetshine-0261-mar-28-2018/&do=findComment&comment=3687937

I think we should be OK switching back if that happens.

**Comment by prestja** [comment]
> Looks good now.
> 
> The original author has said he'll start maintaining again, but that was over a month ago now with no further updates:
> 
> https://forum.kerbalspaceprogram.com/index.php?/topic/173138-141-planetshine-0261-mar-28-2018/&do=findComment&comment=3687937
> 
> I think we should be OK switching back if that happens.
Thank you very much for all of your help today.

**Pull request merged**
