### PR TITLE
add recommends KKtoSD and Kronometer

### PR DESCRIPTION
**Pull request by Galileo88**

### CODE REVIEW

**Comment by Galileo88** [comment]
This makes no sense to me..

**Comment by HebaruSan** [comment]
Not your fault, I broke the validator. Fix is in KSP-CKAN/CKAN#2203. Please bear with us till that gets merged.

Is it safe to ignore the previous 2 PRs?

**Comment by HebaruSan** [comment]
This PR should be fine once the validator gets fixed; re-opening.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
@Galileo88, the validator is working now, so you can switch it back to recommends now if you think that's more appropriate. Adding a "blocked by" label to make sure you have a chance to consider that before this gets merged.

**Comment by Galileo88** [comment]
Ah ok cool! I was pulled my my hair (or what’s left of it) out trying to figur this out lol

**Comment by Galileo88** [comment]
ok its ready to go!

**Pull request merged**
