### PR TITLE
Add Speed Unit Annex from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of flart, to add [Speed Unit Annex](https://spacedock.info/mod/1662/Speed%20Unit%20Annex) to CKAN.

Mod details:
    name = /mod/1662/Speed%20Unit%20Annex
    author = flart
    abstract = Add (annex) some new speed unit and helpful value to the top line, depending from navball mode and the vesselType.
    license = GPLv3
    Homepage = 
    description = ## SpeedUnitAnnex

Another mod in the family of SpeedUnitChanger and SpeedUnitDisplay.   
It's doesn't change main `xx.x m/s` line, but add (annex) some new speed unit and helpful value to the top line, depending from navball mode and the vesselType. Also it has difficulty setting page.

  
  
  

### Surface mode
   * Rover - it shows km/h or mph (difficulty setting)
   * Boat/Submarine - it shows knots 
   * Plane - it shows Mach number 
   * Kerbal (EVA) - it shows Name
   * all, except Rovers and Boat - it show Above Ground Level (difficulty setting)
  
  
### Orbit mode
   * It shows Apoapsis and Periapsis (difficulty setting)
  
  
### Target mode
   * It shows target vessel
   * It shows a distance to target (difficulty setting)
   
   
   

Please direct questions about this pull request to [flart](https://spacedock.info/profile/flart).

### CODE REVIEW

**Comment by yalov** [comment]
Add please SpeedUnitChanger and SpeedUnitDisplay to conflicts.

Don't know what would happen, but they should not be used together.

**Comment by HebaruSan** [comment]
Thanks for the info, it should be updated now.

**Comment by yalov** [comment]
don't see in the relationships tab, for now.
It should be noted what there are not SpeedUnitDisplay in the ckan (for now) and 
SpeedUnitChanger needs same conflicts.

**Comment by yalov** [comment]
I was needed reinstalling it, now it is ok.

**Pull request merged**
