### PR TITLE
Updated Extraplanetary Launchpads to 1.2.0

### PR DESCRIPTION
**Pull request by bennie98**

### CODE REVIEW

**Comment by Olympic1** [comment]
You need to add a `ksp_version` if you're using `dowload`.

@politas, @ayan4m1, We should also check for `vref`s if no `ksp_version` is given

**Comment by bennie98** [comment]
I did verify this using netkan and it did produce a correct ckan file with the correct ksp version and mod version.

**Comment by Olympic1** [comment]
That is true, but Jenkins is more stubborn then netkan.exe

**Comment by bennie98** [comment]
So what is line should I add? 
ksp_version, version or both?

**Comment by Olympic1** [comment]
"ksp_version": "1.2.0",

**Comment by bennie98** [comment]
This should fix it.

**Comment by Olympic1** [comment]
Yep, merging

**Pull request merged**
