### PR TITLE
Add SpaceAge from Github

### PR DESCRIPTION
**Pull request by GarwelGarwel**
This adds my new mod, Space Age, and updates some metadata for the other mod, Kerbal Health.

### CODE REVIEW

**Comment by GarwelGarwel** [comment]
Huh, I don't see what the problem is.

**Comment by politas** [comment]
From the Console output: 
"NetKAN file found in root of repository, please move it into NetKAN/"
You've got SpaceAge.netkan in the root.

**Comment by GarwelGarwel** [comment]
Thanks! Looks good now.

**Comment by politas** [comment]
Great! Merging with thanks!

**Pull request merged**
