### PR TITLE
Add JD Ballisback from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Jatwaa, to add [JD Ballisback](https://spacedock.info/mod/849/JD%20Ballisback) to CKAN.

Mod details:
    name = /mod/849/JD%20Ballisback
    author = Jatwaa
    abstract = A backpack that offers ballast and buoyancy! With KIS and KAS installed can be strapped on the back of a Kerbal to control his or her buoyancy! 
    license = MIT
    Homepage = 
    description = Ever wanted to sink a Kerbal to the depths or wished they would float? Now you can! Also as a substitute for Ballistanks, this has less ballast storage, but will sink a small craft or Kerbal and will remain nice and hidden. With KAS/KIS can be strapped to the back of a Kerbal for used to control their bouyancy. 

Thanks for hosting your mod on SpaceDock!

Please direct questions about this pull request to [Jatwaa](https://spacedock.info/profile/Jatwaa).

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by techman83** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
Needs install instructions

**Comment by politas** [comment]
Android tablets do not make the best platforms for metadata editing

**Comment by politas** [comment]
OK, this should be good to merge.

**Pull request merged**
