### PR TITLE
Update SupplementaryElectricEngines.netkan

### PR DESCRIPTION
**Pull request by Triplchii**
updated dependencies

___

ckan compat add 1.11 1.12

### CODE REVIEW

**Comment by HebaruSan** [comment]
One moment, I need to turn on some debugging to try to see what's happening here...

**Comment by HebaruSan** [comment]
Yup, that's about what I thought; the validator is currently broken because of some recent changes in KSP-CKAN/CKAN#4010 related to using a `netstandard2.0` dependency. I'll look into this and re-run the validator when it's fixed...

```
  Unhandled Exception:
  System.TypeLoadException: Could not load type of field 'CKAN.SteamLibrary+<>c__DisplayClass0_0:txtParser' (0) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
    at CKAN.GameInstanceManager..ctor (CKAN.IUser user, CKAN.Configuration.IConfiguration configuration) [0x00000] in <3c4f6609dc0c41bcaaa5b1c54f23de44>:0 
    at CKAN.CmdLine.GameInstance+<>c__DisplayClass2_0.<RunSubCommand>b__0 (System.String option, System.Object suboptions) [0x00055] in <3c4f6609dc0c41bcaaa5b1c54f23de44>:0 
    at CommandLine.Parser.ParseArgumentsStrict (System.String[] args, System.Object options, System.Action`2[T1,T2] onVerbCommand, System.Action onFail) [0x00077] in <3c4f6609dc0c41bcaaa5b1c54f23de44>:0 
    at CKAN.CmdLine.GameInstance.RunSubCommand (CKAN.GameInstanceManager manager, CKAN.CmdLine.CommonOptions opts, CKAN.CmdLine.SubCommandOptions unparsed) [0x00062] in <3c4f6609dc0c41bcaaa5b1c54f23de44>:0 
    at CKAN.CmdLine.MainClass.Execute (CKAN.GameInstanceManager manager, CKAN.CmdLine.CommonOptions opts, System.String[] args) [0x00179] in <3c4f6609dc0c41bcaaa5b1c54f23de44>:0 
    at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x000e9] in <3c4f6609dc0c41bcaaa5b1c54f23de44>:0 
```

**Comment by Triplchii** [comment]
I see... so for now should I just leave it be and try again later?

**Comment by HebaruSan** [comment]
I'll make sure the dependency gets added once I've fixed that problem. Thanks for letting us know about this dependnecy.

**Comment by Triplchii** [comment]
Gotcha. Thank you for the help 👍

**Pull request merged**
