### PR TITLE
Update OuterPlanetsMod

### PR DESCRIPTION
**Pull request by dbent**
- Updated minimum ModuleManager version
- Updated minimum Kopernicus version
- Added KopernicusExpansion as a recommended mod

### CODE REVIEW

**Comment by dbent** [comment]
New `recommends` depends on #2236

**Comment by plague006** [comment]
Would you mind moving the `depends` and `recommends` outside of the override? The technical effect should be identical but it makes it a little easier for humans to digest/lowers the required knowledge to read.

**Comment by dbent** [comment]
Done.

**Comment by plague006** [comment]
Looks good, merging with my thanks.

**Pull request merged**
