### PR TITLE
Fix FAR

### PR DESCRIPTION
**Pull request by Olympic1**
Ref: https://github.com/KSP-CKAN/CKAN-meta/pull/1261

### CODE REVIEW

**Comment by dbent** [comment]
D'oh, assumed this would be handled by the remote AVC file since it now contains the correct KSP versions, but the version file in the download is wrong (0.16.0.0) so it doesn't match the remote (0.15.8.0) and NetKAN refuses to use it.

**Comment by dbent** [comment]
Also @techman83, shouldn't FAR have gone to staging instead of being automatically committed?

**Comment by politas** [comment]
Yes, it looks like staging is not working properly. I don't think it ever has.

**Comment by techman83** [comment]
Because @techman83 seemed to miss the convention of an underscore vs dash. So it works, but our metadata conventions are different to how I've coded the metadata parser.

Raised an issue KSP-CKAN/NetKAN-bot#60

Simple one to fix.

**Pull request merged**
