### PR TITLE
Update PRVE compat

### PR DESCRIPTION
**Pull request by HebaruSan**
image

Closes KSP-CKAN/CKAN-meta#2683.

___

ckan compat add 1.12

### CODE REVIEW

**Comment by HebaruSan** [comment]
The Scatterer dependency's compat is out of date:

image

**Comment by SpaceODY** [comment]
Not sure if it's because it hasn't refreshed yet but the new 1.7.1 version is only available for PRVE and not PRVE64k

**Comment by HebaruSan** [comment]
We're getting an error for that one that I don't understand yet:

image

Hopefully our server guy will have a chance to look into it, could just be that we need more disk space.

**Comment by HebaruSan** [comment]
Should be resolved now, sorry for the delay!

https://github.com/KSP-CKAN/CKAN-meta/commit/2fbc92b8aec53af0067ee4531d45ecbee95e70a3

**Pull request merged**
