### PR TITLE
Create ForgottenRealEngines.netkan

### LINKED ISSUE #3517: Add ForgottenRealEngines
Hello! I would like to integrate my mod, [Forgotten Reals Engines](http://spacedock.info/mod/456/Forgotten%20Real%20Engines) in CKAN. For some strange reasons netkan.exe does not work on my computer. Here is a copy of my .netkan file; could anyone check if it works? :)
[FRE-CKAN.zip](https://github.com/KSP-CKAN/NetKAN/files/200989/FRE-CKAN.zip)
Thanks!

### PR DESCRIPTION
**Pull request by Dazpoet**
closes #3517

### CODE REVIEW

**Comment by politas** [comment]
I con't think that's going to work. You'll need a "find" to sort out the "ForgottenRealEngines x.y.z/GameData/ForgottenRealEngines/" folder

**Comment by Zarbizaure** [comment]
So my install instruction in the original .netkan were needed. Could you put them back in as I'm AFK today @Dazpoet ?
Thanks!

**Comment by Zarbizaure** [comment]
Does the zip name "ForgottenRealEngines x.y.z" count as a folder? If so, i can just change that name to "FRE" and do a small patch on spacedock.

**Comment by plague006** [comment]
Looks good, merging with my thanks.

**Pull request merged**
