### PR TITLE
OSE Workshop Reworked

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
!rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
I've sent a message to Roverdude about Firespitter

**Comment by linuxgurugamer** [comment]
This is waiting on Firespitter:

OSEWorkShopReworked 1.2.9 requires FirespitterCore but it is not listed in the index, or not available for your version of KSP.

I've sent messages to Roverdude about it

**Comment by linuxgurugamer** [comment]
#6280

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Pull request merged**
