### PR TITLE
Add Night Shift Mod

### PR DESCRIPTION
**Pull request by coldrifting**
Adds a Day/Night cycle to the Vehicle Editors

https://github.com/coldrifting/NightShift

https://forum.kerbalspaceprogram.com/index.php?/topic/208470-112x-night-shift-auto-daynight-cycle-in-the-vabsph-version-080-initial-release/

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks for the submission! The metadata looks good to me.

Only problem I noticed is on the forum thread, not here; the moderators like to have the license mentioned in the OP, and it isn't yet.

**Comment by coldrifting** [comment]
I've gone ahead and added that, thanks.

**Comment by HebaruSan** [comment]
Hey @coldrifting, the latest release of NightShift is missing the NightShift folder, so it hasn't been added to CKAN.

**Comment by coldrifting** [comment]
My bad, just fixed that. Does it need a new release?

**Comment by HebaruSan** [comment]
Nope, looks like it's all good now! 🎉 

https://github.com/KSP-CKAN/CKAN-meta/commit/4c22e64dac245f2a6acad62e7a7b61fc7d92a9db

**Pull request merged**
