### PR TITLE
Add ProbeSASUpgrades.netkan, closes #2036

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Jenkins passing is aberrant, will manually test after PartUpgrade is added by netkan bot.

@techman83 is there a way to force jenkins to retry a commit? A rebuild option, as it were.

**Comment by plague006** [comment]
Passes local, merging.

**Comment by techman83** [comment]
@plague006 - There is a way to get it to rebuild, I'll go poke the regex.

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
Haha, I'll go try it on something open. INFO: Skip comment on closed PR

**Pull request merged**
