### PR TITLE
StockVisualEnhancements fix

### PR DESCRIPTION
**Pull request by politas**
Use bundled EVE and conflict with the full EVE.

### CODE REVIEW

**Comment by DuoDex** [comment]
See also PR #3784

**Comment by Nhawks1717** [comment]
politas just in case you didn't see my comment on the forums. The current version of SVE has the latest release of EVE bundled in it.

**Comment by politas** [comment]
So, is SVE anything more than an EVE configuration set?

**Comment by DuoDex** [comment]
This most recent config will break SVE. SVE currently provides its own surefire working EVE plugin, as EVE updates break config packs from time to time. Installing EVE _over_ SVE causes some impressive graphical and performance issues, and that's exactly what you seem to be proposing to do.

**Comment by politas** [comment]
The conflict with EnvironmentalVisualEnhancements-Config, shouldn't have allowed any other EVE config to install, but ok, let's go back to using the bundled EVE and conflicting with EVE.

**Comment by pjf** [comment]
Just checking the conversation vs the code. The code changes have this depend upon EVE rather than conflicting with it. Is that correct?

**Comment by politas** [comment]
No, it's installing the bundled EVE and conflicting with EVE

**Comment by plague006** [comment]
@Nhawks1717 should CKAN only be installing the spacedock release or should we make each quality level available via the github releases?

**Comment by politas** [comment]
That would require Github releases.

**Comment by Nhawks1717** [comment]
So is it fixed now or no? I'm a bit confused.

**Comment by DuoDex** [comment]
The current state of the config should work. At the moment SVE provides both configuration and base - and conflicts with anything that provides either configuration _or_ base.

**Comment by Nhawks1717** [comment]
Okay, I'll let the thread peps know this'll be merged soon. Thanks for the hard work guys.

**Comment by plague006** [comment]
Looks good to me, merging with my thanks.

**Pull request merged**
