### PR TITLE
Updated 1.8 compatibility

### PR DESCRIPTION
**Pull request by RCrockford**
Updated version compatibility due to changes in RSS.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Why? The README.txt says:

```
Real Solar System Texture pack (DDS Edition) for KSP 1.3.1+ (RSS-Kopernicus)
```

There's no trace of any suggestion of a minimum of 1.8 compatibility.

**Comment by RCrockford** [comment]
The lower comments in the readme have the info: 
> v18.0 for RSS 18.0

And RSS 18.0 is 1.8 only. There is a breaking change between RSS 18 and earlier versions as some of the textures changed from PNG to DDS.

**Comment by RCrockford** [comment]
Please also see the updated readme.

**Comment by HebaruSan** [comment]
Alright, thanks for the updates!

**Pull request merged**
