### PR TITLE
Fixes missing DLL file issue

### PR DESCRIPTION
**Pull request by sswelm**
Interstellar_Redist.dll should be placed in the GameData folder

### CODE REVIEW

**Comment by sswelm** [comment]
apparently, CKAN is much more stricks now. Making files that would be fine in the past to pass today

**Comment by DasSkelett** [comment]
Thanks for the update! Yeah, since we now also allow netkans to be written in YAML instead of JSON, we had to change the linter, which complains about more syntax "differences". We might be able to tune it a bit.

Regarding the DLL, does this only affect the latest release from a few hours ago (1.12.13)? Or do we need to backport this fix to some older metadata as well?

**Comment by DasSkelett** [comment]
Okay, the DLL seems to have this location since 1.28.12, in 1.28.10 it's inside `GameData/WarpPlugin/Plugins/`.
I see it was also bundled within `GameData/PhotonSail/Plugins/`, but is no more. Does PhotonSailor no longer require this DLL? Or do we need to update it to depend on KSP-IE? Or should we split out the redistributable DLL into its own module, that KSP-IE and PhotonSailor depend on?

**Comment by sswelm** [comment]
For now this only applies to 1.28.12 and up. Both WarpPgin and PhotonSail will have to make use of the same DLL. I guess this is problematic as CKAN cannot both deploy the same file  (but right now only KSPIE deployes theredistributable) . To fixed it better I need to put the redistributable DLL in a seperate downloadable package and make it a requirement for both KSPIE and PhotonSailor

**Comment by DasSkelett** [comment]
Exactly, CKAN doesn't allow two mods to install the same file. If both mods depend on this file but not each other, we need to put it in a separate module. Releasing it as a separate zip somewhere would be very neat, otherwise PhotonSailor-only users need to download the huge KSP-IE zip just to get a single DLL out of it (or the other way around, KSP-IE-only users would need to download the PhotonSailor zip if we extract it from there).

**Comment by sswelm** [comment]
Alright, I uploaded the package to Spacedock and marked it indexable for CKAN 

see https://github.com/KSP-CKAN/NetKAN/pull/8612

it need to put it directly into GamaData folder. Should anything be changed?

**Comment by DasSkelett** [comment]
The license of KSPInterstellarExtended is GPL-3.0, whereas the redistributable is marked as MIT on SpaceDock right now. Is this intended and correct as is, or should the redistributable be GPL-3.0 as well?

**Comment by HebaruSan** [comment]
> apparently, CKAN is much more strict now. Making files that would be fine in the past to no longer pass today

> Thanks for the update! Yeah, since we now also allow netkans to be written in YAML instead of JSON, we had to change the linter, which complains about more syntax "differences". We might be able to tune it a bit.

For what it's worth, the new YAML linter has both errors and warnings, and the "too many spaces" stuff should all be warnings. Your PR can still get the green checkmark even if it has some extra spaces.

**Comment by sswelm** [comment]
> 
> 
> The license of KSPInterstellarExtended is GPL-3.0, whereas the redistributable is marked as MIT on SpaceDock right now. Is this intended and correct as is, or should the redistributable be GPL-3.0 as well?

no MIT, they both should be MIT

**Comment by DasSkelett** [comment]
Hm, looking at the SpaceDock page, it says "Custom MIT", and looking at the text in the zip (or in the [repo}(https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/License.md)), it's not the text of the one I know as "MIT". Are they fully compatible, i.e. does the custom one not have any restrictions that the real MIT/Expat license doesn't have, especially regarding redistributing?
Just want to make sure, because the choice of the license in the metadata decides whether we mirror the mod to archive.org, and we don't want to do that if we are not allowed to.

**Comment by sswelm** [comment]
technically  its a custom License which is very similar to an MIT

for details see https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/License.md

**Comment by DasSkelett** [comment]
> which is very similar to an MIT/GPL-3.0 license

This doesn't make sense, because the MIT and GPL licenses are very very different. At the very least, the first one is permissive, and the second ones are copyleft. It can't really be similar to both of them.

I'm inclined to change it to "unknown" then, because if it's not MIT or GPL-3.0, it's not MIT or GPL-3.0.

**Comment by sswelm** [comment]
ok fine

**Comment by DasSkelett** [comment]
Okay, thanks. I have to ask about PhotonSailor as well, because our metadata says "CC-BY-NC-3.0", SpaceDock says "GPLv3", and the forum thread says "CC-BY-NC". Which one is correct there?

**Comment by sswelm** [comment]
Ok, I fixed the license to CC-BY-NC-3.0

**Comment by DasSkelett** [comment]
I think we're all set now. Thanks again!
Will backport to KSPIE 1.28.12 in a bit.

**Comment by sswelm** [comment]
Alright, people are complaining they cannot install KSPIE  with any other version than 1.12.1 because the InterstellarRedistributal only supports 1.12.1. This is wrong as it is compatible down to KSP 1.8. Could this be fixed somehow?

**Comment by sswelm** [comment]
I|m attemping to fix it with https://github.com/KSP-CKAN/CKAN-meta/pull/2386

**Pull request merged**
