### PR TITLE
Add LunaMultiplayer

### PR DESCRIPTION
**Pull request by DasSkelett**
So I've got a request by the author of DarkMultiplayer to get LunaMultiplayer indexed on CKAN :P
Permission is given by @gavazquez / Dagger as seen in the screenshot below:

image

This needs https://github.com/LunaMultiplayer/LunaMultiplayer/pull/344 to be merged first, and a new release which includes the version file.

https://github.com/LunaMultiplayer/LunaMultiplayer/releases

### CODE REVIEW

**Comment by HebaruSan** [comment]
- The `$kref` should probably use `asset_match` to select the Release asset:
  image
- Should we call it LunaMultiplayer-Client, so users are clear that they're only getting the client piece and will need to set up a server separately?

**Comment by DasSkelett** [comment]
> The `$kref` should probably use `asset_match` to select the Release asset:

Yes, totally wanted to do that, but forgot in the process of writing the netkan. Thanks, will take care of that.

> Should we call it LunaMultiplayer-Client, so users are clear that they're only getting the client piece and will need to set up a server separately?

I went with how `DarkMultiPlayer` did it. But yes, it might be better to add `-Client`. In this case we also need to overwrite the `name`:
` "name": "Luna Multiplayer",`

**Comment by HebaruSan** [comment]
> I went with how `DarkMultiPlayer` did it. But yes, it might be better to add `-Client`. In this case we also need to overwrite the `name`:
> ` "name": "Luna Multiplayer",`

Oh, if we already have `DarkMultiplayer`, then maybe it would be better to leave the identifier consistent and set `"name": "Luna Multiplayer Client"`.

**Comment by DasSkelett** [comment]
> Oh, if we already have `DarkMultiplayer`, then maybe it would be better to leave the identifier consistent and set `"name": "Luna Multiplayer Client"`.

Okay, let's go with this. Keeps the backend consistent, but makes the users aware of what they get.

**Comment by gavazquez** [comment]
Thanks for it guys!! I will do a release tomorrow so it's indexed

**Comment by DasSkelett** [comment]
So, Darklight actually tested installing DMP and LMP installed side by side, and it appears to work fine.
Since some people may want to have them both installed to join different servers (although I'd highly recommend separate instances for this), I'm going to remove that conflict since it's not necessary for any technical reasons.

**Comment by HebaruSan** [comment]
#rebuild

**Pull request merged**
