### PR TITLE
Switch OhScrap to new fork

### PR DESCRIPTION
**Pull request by HebaruSan**
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3755887

ckan compat add 1.8

### CODE REVIEW

**Comment by HebaruSan** [comment]
@zer0Kerbal, is a new ScrapYard release coming for KSP 1.9?

**Comment by zer0Kerbal** [comment]
> 
> 
> @zer0Kerbal, is a new ScrapYard release coming for KSP 1.9?

Yes. in fact it is already on github/release. I just haven't found time to do all the forum/spacedock/curseforge stufff. for 1.9.1

**Comment by zer0Kerbal** [comment]
ScrapYard has now been updated. new thread. new fork. same great taste!
Kanford and Sons - Back in Business!

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
The MagiCore dependency isn't marked as 1.9 compatible yet, so users will need to work around that to install.

**Comment by zer0Kerbal** [comment]
thanks @HebaruSan !
magicore should be updated shortly - its @linuxgurugamer's now. 
Ironic that he just was asking about two of my mods being updated for 1.9.1 :) ;) ;p

**Comment by zer0Kerbal** [comment]
will have a new version of ScrapYard (soon) 2.1.1.0 that removes the dependency.

**Pull request merged**
