### PR TITLE
Update Whirligig World dependencies

### PR DESCRIPTION
**Pull request by HebaruSan**
This mod's dependencies have changed since it was indexed in #7116.

image

image

image

- KopernicusExpansion dependencies are removed (will need historical updates back to 0.12)
- SciRev dependency is added (will need historical updates back to 0.10.0)

I have a PM in progress to see if there are any other known issues.

@StollD, is it OK with you if we index SciRev in CKAN?

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by StollD** [comment]
> @StollD, is it OK with you if we index SciRev in CKAN?

Sure, go ahead

**Comment by HebaruSan** [comment]
> Sure, go ahead

Thanks!

> I have a PM in progress to see if there are any other known issues.

No reply back yet, might as well see whether this and KSP-CKAN/CKAN-meta#2001 help at all.

**Pull request merged**
