### PR TITLE
RN update mods for ksp 1.3

### PR DESCRIPTION
**Pull request by raidernick**
-Update mods for ksp 1.3 compatibility

### CODE REVIEW

**Comment by raidernick** [comment]
Before this is merged @politas or @Olympic1 my mods require texture replacer to have working shaders. Currently this appears to be broken in the 2.6 version. I had changed the author a while ago to this new guy because the original author was AWOL.

Someone else has created a fixed 2.7 version of TR that fixes the reflective shader which is the entire point I need the mod. https://github.com/GER-Space/TextureReplacer/releases/tag/2.7.0

Linked above is the new release. I would just change the netkan file to point there however that guy has a version for 1.2.2 and 1.3 combined into a single release number. I don't know how to tell ckan to just download the zip for 1.3. Can one of you help with this?

**Comment by politas** [comment]
is @GER-Space's 2.7.0 release not actually suitable for KSP 1.2.2?

**Comment by raidernick** [comment]
@politas It has 2 releases look at the page, one for ksp 1.2.2 and one for ksp 1.3. I was asking how to tell ckan to download the 1.3 one.

Forget about that for now though. I will make a separate PR/issue for this. The current ckan for texture replcaer supports 1.3 but starting from here forward it won't. However for now it will work perfectly fine. Can you please merge this it REALLY needs to be done as currently ckan is installing the 1.3 version of my mods on ksp 1.2.2 and breaking the game. PLEASE get this merged ASAP.

**Comment by Theysen** [comment]
I'd appreciate a quick merge as well since many people start to report issues on the Realism Overhaul front as those mods are suggested upon installation and should not be installed actually if CKAN pulls the wrong mod version. 
Looking forward to seeing this fixed, Thanks!

**Comment by raidernick** [comment]
Yes please, I am getting tired of these version mixup complaints and all due to RO installs on ckan. Can someone with merge access please get this done ASAP. Ignore my question about the texture replacer. I can deal with that at a later time in other pr/issue. @linuxgurugamer I know you have merge access here can this please be merged. I only needed the version numbers updated and that's all I've changed.

**Pull request merged**
