### PR TITLE
updated Sqad mods

### PR DESCRIPTION
**Pull request by TeddyDD**
I updated Asteroid Day and added Kerbin Cup (It seems it wasn't indexed)
Tested, they works.

### CODE REVIEW

**Comment by Blu3wolf** [comment]
How thoroughly? I was under the impression that for 1.1.X, Asteroid Day was broken. Ill have to look into that, see if I can find a supporting reference.

**Comment by Blu3wolf** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/114677-go-stock-movement-to-integrate-the-asteroid-day-mod-into-stock/&page=7

Some users claim installing it breaks the game, others that the telescope itself just has no function.

It is also claimed that all the parts aside from the telescope, are part of stock since 1.1 anyway.

**Comment by TeddyDD** [comment]
http://forum.kerbalspaceprogram.com/index.php?/developerarticles.html/asteroid-day-mod-updated-r196/#comment-2043

**Comment by TeddyDD** [comment]
http://forum.kerbalspaceprogram.com/index.php?/developerarticles.html/asteroid-day-mod-updated-r196

**Comment by politas** [comment]
Kerbin Cup is working again? I thought that broke back around 0.24

**Comment by politas** [comment]
Appears to install fine. Merging with thanks!

**Pull request merged**
