### PR TITLE
ALCOR, ASETAvionics, ASETProps,MK12PodIVAReplacementbyASET, Mk1Cockpi…

### PR DESCRIPTION
**Pull request by linuxgurugamer**
…tIVAReplbyASET,  Mk1LanderCanIVAReplbyASET

### CODE REVIEW

**Comment by Dazpoet** [comment]
I notice that ASETAvionics has 2 distinct "parts" within it. The ClassicPack and the ModernPack, should these be split or do they belong together?

**Comment by linuxgurugamer** [comment]
I set it up the way Alex's Tuscany asked, I posted your comment, waiting to
hear back

**Comment by linuxgurugamer** [comment]
I hate spell checkers,  author is alexustas

**Comment by linuxgurugamer** [comment]
From the author:

no. I separate the two packs for my convenience only

So it is good as is

**Pull request merged**
