### PR TITLE
Change kRPC to use Github and update licenses

### PR DESCRIPTION
**Pull request by djungelorm**

### CODE REVIEW

**Comment by plague006** [comment]
This looks good and tests fine manually, but I'll give it a bit of time to see if Jenkins wants to test it.

**Comment by plague006** [comment]
Ah right, I thought we'd resolved it but we actually can't handle more than 1 license. Would you mind just listing the most restrictive license?

**Comment by plague006** [comment]
Merging with my thanks.

**Comment by djungelorm** [comment]
Thanks a bunch! Very quick response :)

**Pull request merged**
