### PR TITLE
Adding "1869 A Steampunk Mod"

### PR DESCRIPTION
**Pull request by zilti**

### CODE REVIEW

**Comment by benjwgarner** [comment]
The check is failing with this error:

`NetKAN/1869.netkan: line terminator characters must be escaped inside string literals: u'\n\nStill in beta,...`

You might be able to escape the new line characters, but it's better to just leave it all on one line. CKAN will wrap the text when it displays it. Since the text display area is resizable and not the same size for everyone, it's better to just keep it all on one line.

**Comment by benjwgarner** [comment]
Since support for the Unlicense was not part of the original spec (see #4131), you need to change the spec_version to 1.18.

`#   Failed test '1869 - spec_version v1.18+ required for license 'Unlicense''`

**Comment by zilti** [comment]
Fixed.

**Comment by linuxgurugamer** [comment]
The format for the spec version is wrong.  it should be as follows:

 "spec_version": "v1.18",

**Comment by zilti** [comment]
Fixed. Maybe stuff like this should be added to the manual.

**Pull request merged**
