### PR TITLE
Update BluedogDB relationships

### LINKED ISSUE #8432: [Mod] Bluedog Design Bureau metadata update request
Hi,

I would like to request some updates to our metadata. If possible we would like it to apply to the next release, v1.7.2 which we plan to release as soon as these metadata updates are live. https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BluedogDB.netkan

1) Add Waterfall to Depends https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Waterfall.netkan

2) Move RealPlume from Supports to Suggests

3) Add Neptune Camera to Suggests https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/NeptuneCamera.netkan

4) Add Space Dust to supports https://raw.githubusercontent.com/post-kerbin-mining-corporation/SpaceDust/master/CKAN/SpaceDust.netkan

Thanks a lot

### PR DESCRIPTION
**Pull request by DasSkelett**
Some metadata updates for a new version that's about to be released.

Closes #8432

### CODE REVIEW

**Comment by zorg2044** [comment]
@DasSkelett sorry 1 question, should I release once this is merged, or is this going to be merged once the new release is out?

**Comment by DasSkelett** [comment]
Haha, was just about to write that to you :)
You need to do the release before this gets merged, otherwise we'd update the metadata of the existing release.
So feel free to go ahead with the release, I'll merge this right after.

**Comment by zorg2044** [comment]
Alright I'll ping you with a heads up in a few hours time. Thanks again.

**Comment by zorg2044** [comment]
Ah you guys are very quick and efficient :) I see its already done. Thanks a bunch once more.

**Pull request merged**
