### PR TITLE
Add Ravenspear Mk.O from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Starloop_Industry, to add [Ravenspear Mk.O](https://kerbalstuff.com/mod/800/Ravenspear%20Mk.O) to CKAN.

Please direct questions about this pull request to [Starloop_Industry](https://kerbalstuff.com/profile/Starloop_Industry).

### CODE REVIEW

**Comment by mgsdk** [comment]
Need to test if the installation instructions on KS are correct. It seems weird it would need to be installed inside the Squad folder.

**Comment by Dazpoet** [comment]
reading part.cfg files it seems to just point to meshes and things within its own folder so installing ravenspear to GameData _should_ work. Haven't tested though.

**Comment by politas** [comment]
That's very non-standard. Shouldn't the parts be in a "Parts" directory?

**Comment by politas** [comment]
KerbalStuff says license "All Rights reserved", but the license.txt file says CC-BY-NC-4.0.

**Comment by Dazpoet** [comment]
What does the forum thread say?

**Comment by politas** [comment]
No forum thread that I can find.

**Comment by Dazpoet** [comment]
In the case of multiple licenses we always go with the stricter one so All rights reserved it is then

**Comment by politas** [comment]
I love that the bot puts in that "Please direct questions about this pull request to Starloop_Industry." and links you to a page that gives no way to send a message.

**Comment by Dazpoet** [comment]
Yep :)

**Comment by politas** [comment]
Well, just spent another fruitless five minutes seeking any mention in the forum. Searches thoroughly poisoned by stock craft with same name.

**Pull request closed without merging**
