### PR TITLE
Update RSS-Adapter.netkan

### PR DESCRIPTION
**Pull request by Globul-Art**
Add resources:
  homepage: https://forum.kerbalspaceprogram.com/topic/224480-181-1122-rss-adapter/

### CODE REVIEW

**Comment by HebaruSan** [comment]
Hi @Globul-Art, you can do this already by setting the Website link for the repo on GitHub; the CKAN bot will pull it into the metadata automatically. This has many benefits, for example you would be able to change it any time without a pull request, and non-CKAN users would have easy access to the link as well.

For example, I have this for Astrogator:

image

image

**Comment by Globul-Art** [comment]
I did it. But I don't see this in the metadata, in my CKAN. 
Should I wait?

**Comment by HebaruSan** [comment]
Yes, the bot has to retrieve the value from GitHub, which may take up to 35 minutes.

**Comment by HebaruSan** [comment]
Replaced by https://github.com/KSP-CKAN/CKAN-meta/commit/a136f1fad861821fa79a61299ff226a723097127.

**Pull request closed without merging**
