### PR TITLE
Creating ESLD Jump Beacons file.

### PR DESCRIPTION
**Pull request by TMarkos**
Submitting this for CKAN support, thanks!  Let me know if I've bollocksed the syntax.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Identifier _must_ match filename :)

**Comment by TMarkos** [comment]
Whoops, sorry.  Can you clarify?  I matched it to the name of my dll file, what filename should I have used?

**Comment by Dazpoet** [comment]
the identifier inside your netkan file must match the name of the netkan file :)

**Comment by TMarkos** [comment]
Changed!

**Comment by TMarkos** [comment]
Whoops, something else seems to have gone wrong.  Do I need to provide an install tag in the markup to prevent that error?

**Comment by mgsdk** [comment]
Yes, you need the install tag as it attempts with the identifier as a filename.

**Pull request merged**
