### PR TITLE
Update SETIBalanceMod.netkan

### PR DESCRIPTION
**Pull request by Y3mo**
Updated the dependencies (StageRecovery to recommendations, BackgroundProcessing in) and recommendations due to the development of the SETI-BalanceMod.

I am the author of the mod.

Best regards,
Yemo

### CODE REVIEW

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
grumble grumble I'll do one more before giving up

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Y3mo** [comment]
Hm, that is strange,

maybe too many recommendations?

Also, when I click on Files changed, the spec_version seems to be missing.

Though I did not delete anything except the SaneStrategies dependency?

PS: Sorry if I m missing something, I do not know all the ins and outs of github.

**Comment by Dazpoet** [comment]
Click the grey arrowthing at the top and it'll expand all rows and you'll see that the spec_version is still there. Might have something to do with the new download code, I've poked a dev (nlight) on irc about it.

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
That's the last one, just looking at different times of day to see if it has an effect

**Comment by Y3mo** [comment]
Hm, really strange.
How about deleting all the recommendations?

So that at least the dependencies are updated.

**Comment by Dazpoet** [comment]
It won't make a change, the problem is discussed further [here](https://github.com/KSP-CKAN/CKAN-support/issues/107#issuecomment-86717190).

**Comment by Dazpoet** [comment]
Setting up a test on a linux machine now and if that passes I'll merge it, tried on OS X and Windows already.

**Pull request merged**
