### PR TITLE
Update KAX

### PR DESCRIPTION
**Pull request by dbent**
Release only on Curse.

### CODE REVIEW

**Comment by plague006** [comment]
For our mirroring, I think we should set this to a `restricted` license.

>Specifically, you may not:
Distribute unmodified versions of KAX, in part or whole, without permission
Use KAX for any commercial purpose

**Comment by dbent** [comment]
Bleh, when did that change. Updated, although due to the GitHub [issues](https://status.github.com/messages) may take a while for the change to appear.

**Comment by dbent** [comment]
Alright, GitHub has finally caught up.

**Comment by plague006** [comment]
Looks good to me, merging with my thanks.

**Comment by techman83** [comment]
> For our mirroring, I think we should set this to a restricted license.
> 
>> Specifically, you may not:
Distribute unmodified versions of KAX, in part or whole, without permission
Use KAX for any commercial purpose

Good catch @plague006 - definitely something we need to vigilant of.

**Pull request merged**
