### PR TITLE
Set DPAI to correct ksp version

### PR DESCRIPTION
**Pull request by Olympic1**
Fixes https://github.com/KSP-CKAN/CKAN-meta/pull/1270

### CODE REVIEW

**Comment by politas** [comment]
What is making it set a min_version of 1.2.0? When I run on the existing netkan, I get a clean 1.3.0 ksp version, as per Spacedock. Was it wrong on Spacedock? I can't see an AVC .version file in the 6.6.0 download I have.

**Comment by bfishman** [comment]
Ah, that explains it.  I uploaded 6.6.0 to spacedock originally with the wrong .version file in it. I noticed this within a minute, so re-uploaded the zip file with a fixed .version file, but the NETKAN scrape must have occurred by that point.

What's the easiest way to rectify this - should I delete 6.6.0 on spacedock and submit a new version?

**Comment by Olympic1** [comment]
I you want to do that, go ahead. I dont have to remind myself to add the vref back in for the next release.

**Comment by bfishman** [comment]
Alright, I'll publish 6.7.0 just to make everyone's life easier!

**Pull request closed without merging**
