### PR TITLE
Change install path to match new download structure

### PR DESCRIPTION
**Pull request by Raptor831**

### CODE REVIEW

**Comment by plague006** [comment]
Installing `GameData` into `GameData` will result in `KSP/GameData/GameData/Modfolder` which is not likely your intent.

**Comment by Raptor831** [comment]
Thanks for the info, changed it to just place the 3 folders explicitly.

**Comment by plague006** [comment]
Change both instances of `file` to `find` and bump the `spec_version` to `v1.4` and that'll have the effect you're looking for.

**Comment by Raptor831** [comment]
That look about right?

**Comment by plague006** [comment]
Looks good to me, merging with my thanks.

**Pull request merged**
