### PR TITLE
Add Leadfoot from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of KerbiceGroup, to add [Leadfoot](https://kerbalstuff.com/mod/606/Leadfoot) to CKAN.

Please direct questions about this pull request to [KerbiceGroup](https://kerbalstuff.com/profile/KerbiceGroup).

### CODE REVIEW

**Comment by JustinKerbice** [comment]
I guess Kerbal Stuff CKAN script needs some improvements, here is license (again), and it looks like ALL KS PR failed ! So... better to rely on this buggy script or do it ourselves ?

**Comment by hakan42** [comment]
"whatever license 1" is not something that CKAN is prepared to accept.

**Comment by JustinKerbice** [comment]
So I have miss a point before... or 1 is ok but not 1.1 ?
Every time I've put something else than restricted, PR was rejected, just for the license (for most of the netkan files).

**Comment by hakan42** [comment]
We should document this better than what we have at https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md , but the list at https://github.com/KSP-CKAN/CKAN-core/blob/master/Types/License.cs is the definite authorative-as-hell source of truth.

If you chose one of the licenses there, and exactly written as there (no spaces or other funky stuff), you are good to go.

**Comment by JustinKerbice** [comment]
1st: I miss the 'not' in your sentence ! That's change the meaning a bit :).
2nd: KS script need to be fixed, it may create "tons" of bad files, need extra work to fix them all one by one.
And I don't have write access on this one, should I create a new one which works or let you fix it ?

**Comment by hakan42** [comment]
Could you please provide a new one? I'll close this in the meantime.

That is how I process KS-provided pull requests most of the time...

**Pull request closed without merging**
