### PR TITLE
Add Stockalike Realism Overhaul Parts Pack from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Hyper_Fun, to add [Stockalike Realism Overhaul Parts Pack](https://spacedock.info/mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack) to CKAN.

Please direct questions about this pull request to [Hyper_Fun](https://spacedock.info/profile/Hyper_Fun).

Mod details:
    name = /mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack
    author = Hyper_Fun
    abstract = Removed all the 'fun' parts from my original mod.
    license = Do whatever you want
    Homepage = https://spacedock.info/mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack
    description =
   Removed all the 'fun' parts from my original mod. Found here:      https://spacedock.info/mod/2239/Stockalike%20Realism%20Overhaul

ckan compat add 1.7

### CODE REVIEW

**Comment by HebaruSan** [comment]
The installation instructions are not CKAN-compatible:

```
2)Make a backup of the 'physics.cfg' file in your KSP installation.

3)Replace the new 'physics.cfg' file in this folder into your KSP installation.
```

**Comment by HyperFunOriginal** [comment]
Again, the mod isn't showing up. For CKAN installations, please remove step 2 & 3 and ignore physics.cfg file. Thanks a lot!

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
@HyperFunOriginal it looks like all of these files are already in StockalikeRealismOverhaul. Why is this being added?

**Comment by HyperFunOriginal** [comment]
It still isn't showing up.

**Comment by HebaruSan** [comment]
@HyperFunOriginal it looks like all of these files are already in StockalikeRealismOverhaul. Why is this being added?

**Comment by HyperFunOriginal** [comment]
Oh wait...

**Comment by HebaruSan** [comment]
Closing because this looks redundant with StockalikeRealismOverhaul. If that is not the case, please reply **and tell us why**.

**Pull request closed without merging**
