### PR TITLE
RoverDude/USI mod metadata overhaul

### PR DESCRIPTION
**Pull request by plague006**
Add USI-Core, USI-MKSLite, USI-NuclearRockets. Change install methods and dependencies of other USI mods as well as make use of their .version files. Epoch bumps to mods that currently conflict with the new `USI-Core` should have users update those mods and avoid issues (hopefully). If that doesn't work then a lot of users will need to be told to remove and re-install UKS and/or Karbonite.

With thanks to @qm3ster and @bobprime for giving me a basis to work from and for pushing me to (finally) get this done.

Closes #2392, closes #2474, closes #2343, closes #2361

### CODE REVIEW

**Comment by plague006** [comment]
I suspect that Jenkins failure is due to KerbalStuff web site issues. Will have it rebuild later.

**Comment by Olympic1** [comment]
Files look alright, but testing is required.

**Comment by plague006** [comment]
>Files look alright, but testing is required.

I'm not sure if you're saying that you're going to test or if you're looking for someone else to do it.

**Comment by pjf** [comment]
@plague006 : You are totally awesome. :)

**Comment by pjf** [comment]
All of these look excellent to me, and definitely better than the old versions given the restructure. Merging with *enormous* thanks. <3

**Comment by plague006** [comment]
@qm3ster and @bobprime just want to re-iterate that the work you guys did was great and appreciated. I only did this myself because it was easier to have the entire USI library overhauled at once with all the small and large changes required.

**Comment by qm3ster** [comment]
@plague006 for president

**Pull request merged**
