### PR TITLE
Add RoverSpeed from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of maculator, to add [RoverSpeed](https://kerbalstuff.com/mod/936/RoverSpeed) to CKAN.

Please direct questions about this pull request to [maculator](https://kerbalstuff.com/profile/maculator).

### CODE REVIEW

**Comment by maculator** [comment]
Crated a .ckan from it, checked it. Everything working.

**Comment by plague006** [comment]
@maculator In #1649 there's a dependency on ModuleManager. You should re-open that PR in lieu of this.

**Comment by maculator** [comment]
okay, thanks. Done.

**Comment by maculator** [comment]
So i can't delete this one because its botmade, but the https://github.com/KSP-CKAN/NetKAN/pull/1649 is the one wich is correct, but doesn't get accepted due to this one .....

**Pull request closed without merging**
