### PR TITLE
Update and rename Asclepius-clouds.kerbalstuff to Asclepius-clouds.ne…

### PR DESCRIPTION
**Pull request by MrChumley**
…tkan

### CODE REVIEW

**Comment by MrChumley** [comment]
I'm not positive that I'm doing this part right.

**Comment by Olympic1** [comment]
Yes you are but it failed because it thinks that Asclepius is still on KS.

Also because these config files will only work if EVE is installed it would be better to move it to `depends`

**Comment by Olympic1** [comment]
Looks good, thanks for updating your mods :+1:

**Comment by MrChumley** [comment]
Thank you.

**Pull request merged**
