### PR TITLE
Add AUC Aeronautic technoloy (fixed KerbalStuffBot submission)

### PR DESCRIPTION
**Pull request by politas**
Closes #2961

### CODE REVIEW

**Comment by Olympic1** [comment]
The `ADF3internal.cfg` requires `RasterPropMonitor`, `ASETAvionics` and `ASETProps`.

As for the craft files, `adf3 starchild bomber.craft` and `adf3 starchild.craft` require `B9-PWings-Fork` and `AdjustableLandingGear`.

Forum thread says:
> Not included in the pack but required for the IVA:
- RasterPropMonitor
- ASET Avionics Pack v 1.0 
- ASET Props Pack

> PS: the craft that are in the zip file, only the starchild stock is purly stock, for the other craft, you will need: B9 procedural wings and BD adjustable landing gear.

**Comment by politas** [comment]
Ok, so if something is required only for the IVA or for individual craft files, do we put them in depends or recommends? I lean towards recommends, since the mod will work ok (with limitations) without them. If you don't have RPM, it won't have the nice IVA, but a lot of people never use IVA, anyway.

**Comment by plague006** [comment]
From the forum thread http://forum.kerbalspaceprogram.com/index.php?/topic/130683-wip-105-auc-aeronautic-mods-001/ it's availble on curse http://kerbal.curseforge.com/projects/auc-aeronautic-technoloy

**Comment by politas** [comment]
Replaced by KSP-CKAN/CKAN-meta#967

**Pull request closed without merging**
