### PR TITLE
UKS isn't supported on CKAN anymore, so remove it as a dependency.

### PR DESCRIPTION
**Pull request by Quartz101**
Title says it all.

### CODE REVIEW

**Comment by politas** [comment]
Fair enough. Merging.

**Comment by politas** [comment]
@Quartz101 , UKS is back on CKAN, are you ok with this being reverted?

**Comment by N70** [comment]
Feel free to revert. P.S - changing github username to N70

**Comment by politas** [comment]
Thanks, N70!

**Comment by N70** [comment]
Your welcome!

**Pull request merged**
