### PR TITLE
HorizonAeronauticsZenit3SLBReduzx

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Closes #4995

### CODE REVIEW

**Comment by Dazpoet** [comment]
It gets stuck on a .version file in the _MACOSX folder. I'm not sure why it's looking there tbh since the CKAN-spec clearly states that [`Only .version files that would be installed for this mod are considered.`](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#vref) and the find directive should only work against the [top-most matching directory](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#install) which shouldn't be in the _MACOSX folder since that makes everything one layer deeper. Not sure how to ping on this but I'm guessing @dbent since it seems NetKAN isn't doing what the spec says it should be doing.

On another note your branch is funny since this PR also contains #5034 but that shouldn't be an issue.

**Comment by Dazpoet** [comment]
Oh and maybe we want to also install the Ships folder?

**Comment by dbent** [comment]
That's weird.

**Comment by linuxgurugamer** [comment]
I'm going to redo this, adding filters to ignore the MAC specific folders

**Pull request closed without merging**
