### PR TITLE
Create WarpShip.netkan

### PR DESCRIPTION
**Pull request by mgsdk**
Fix license, dependencies and install. KSPI may not be possible to resolve at this time.

Closes https://github.com/KerbalStuffBot/NetKAN/blob/add-WarpShip/NetKAN/WarpShip.netkan.

### CODE REVIEW

**Comment by mgsdk** [comment]
#rebuild

**Comment by mgsdk** [comment]
As I sidenote I noticed that it actually doesn't depend on KSPI, but actually may conflict (That's why I added the in progress, perhaps we should add a "do not merge" label?). Should we revert this?

**Comment by Dazpoet** [comment]
OOPS!

**Comment by Dazpoet** [comment]
To continue work we now revert the revert and get back to buisness

**Pull request merged**
