### PR TITLE
Add A7Corsair2.netkan

### PR DESCRIPTION
**Pull request by politas**
Fixed  #1295

### CODE REVIEW

**Comment by politas** [comment]
Can't see why this is failing.

**Comment by Dazpoet** [comment]
See http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/1646/console

The mod is only available for KSP 0.90 and the buildbot is running 1.0.2.

I'm wondering about your install stanza though. The craft file should probably be installed to Ships/SPH but our spec does not allow installation to subfolders of Ships meaning we're stuck between a rock and a hard place on this one :/

**Comment by politas** [comment]
Ah, so anyone hoping to use CKAN for their old 0.90 instance is screwed?

I wondered about the craft file. We can only direct install_to to subdirs on GameData, right?

**Comment by Dazpoet** [comment]
CKAN will work fine on 0.90 installs since we keep all generated .ckan files in CKAN-meta so 0.90 users will get the latest versions we have indexed for their version of KSP. I'm pretty sure we have mods indexed as far back as 0.20 (1 or 2) and a bunch for 0.23.5 and up. However our buildbot is running the latest version since it is the generally most used case.

Yes the .craft file is a problem due to the situation you outline.

**Comment by politas** [comment]
Ah, gotcha. We can't add or update 0.90 mods, though?

**Comment by Dazpoet** [comment]
We can and we do, just they require manual checking rather than automated.

This one passes the json checks but fails on the installation since it's not available for ksp 1.0.2. Remove the install of the .craft file and I'll run it through the works.

**Comment by Dazpoet** [comment]
Works on my local 0.90 install. Merging this.

**Pull request merged**
