### PR TITLE
Octosat Continued

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by Dazpoet** [comment]
I can't check right now but I suspect we might not want to install the shellscript in the partsfolder? Assuming that a.sh is a shellscript?

**Comment by linuxgurugamer** [comment]
It won't hurt, but I'll get it removed
Since this is mine, I'm not going to merge, but if someone could, that would be fine.

**Comment by linuxgurugamer** [comment]
Updated, shell script is out

**Comment by politas** [comment]
LGTM. Merging

**Pull request merged**
