### PR TITLE
Unfreeze StandardPropulsionSystems

### PR DESCRIPTION
**Pull request by HebaruSan**
This mod was frozen in #7513 but just had a new release.

https://spacedock.info/mod/226/Standard%20Propulsion%20Systems
https://forum.kerbalspaceprogram.com/index.php?/topic/119605-1112-standard-propulsion-systems-v106-4202021/&do=findComment&comment=3957888

### CODE REVIEW

**Comment by HebaruSan** [comment]
The forum announcement says there's a version file, but there was no inflation warning suggesting a vref. Hmm...

**Comment by DasSkelett** [comment]
Woah, a mod revived after 5 years of no updates :astonished:

**Comment by HebaruSan** [comment]
Ahh, the NAME field has "smart quotes" instead of actual quotes:

image

Now to see if there's a repo for this or if I have to explain it on the forum...

**Comment by HebaruSan** [comment]
Author notified. We'll get a new inflation error if he fixes it.

**Pull request merged**
