### PR TITLE
Add Master Tech Weapons from SpaceDock

### PR DESCRIPTION
**Pull request by politas**
This is a semi-automated commit on behalf of TMasterson5

### CODE REVIEW

**Comment by politas** [comment]
Waiting for BDArmory release for KSP 1.1

**Comment by politas** [comment]
Waiting for BDArmory release for KSP 1.1

**Comment by plague006** [comment]
`recommends` `NorthKerbinDynamics`

**Comment by politas** [comment]
Added.

**Comment by plague006** [comment]
Nice to have this one off the PR list, merging with my thanks.

**Pull request merged**
