### PR TITLE
CommunityPartsTitlesExtrasNoCCKDup update

### PR DESCRIPTION
**Pull request by yalov**

### CODE REVIEW

**Comment by HebaruSan** [comment]
@yalov, is this change planned for a future release? It looks like the current download does not contain that path.

**Comment by HebaruSan** [comment]
Ahh, GameData is removed. One moment please...

**Comment by yalov** [comment]
patch mane changed in the last version 0.8.0, that is not parced by the SCAN-bot yet.

Also absence of Gamedata is not intended

**Comment by HebaruSan** [comment]
Thanks for the update.

**Comment by HebaruSan** [comment]
> Also absence of Gamedata is not intended

Oh. I was about to merge this. Should I wait till GameData is added to the ZIP?

**Comment by yalov** [comment]
> Oh. I was about to merge this. Should I wait till GameData is added to the ZIP?

yes, I am looking at that

**Comment by yalov** [comment]
I recreated archive manually with the GameData.
GameData disappear some versions ago, because of a changes in my releasing script, but CKAN worked ok.

**Comment by HebaruSan** [comment]
OK, if you want to keep your script as it is, then I can go ahead and merge this. Are you planning ot chnage it?

**Comment by yalov** [comment]
I am looking at it now and planning revert the GameData folder in the root of the archive

**Comment by yalov** [comment]
I fix the problem on my side. You could merge this

**Pull request merged**
