### PR TITLE
Update and rename KerbalFoundries.kerbalstuff to KerbalFoundries.netkan

### PR DESCRIPTION
**Pull request by Dazpoet**
I love this mod <3

### CODE REVIEW

**Comment by Dazpoet** [comment]
Woops I found https://github.com/KSP-CKAN/CKAN-meta/pull/1008 and it seems this should not be done so I'm closing it for now :(

**Comment by politas** [comment]
That was only as a stopgap measure. If it's up on Spacedock now, let's scrape that!

**Comment by Dazpoet** [comment]
I assumed this was the incorrect one mentioned in that PR, but sure this is now re-opened if that isn't the case :)

**Comment by politas** [comment]
Ah, yes, I forgot that detail.
Let me check.

**Comment by politas** [comment]
No, you're right, that is the dodgy one. I'm surprised it hasn't been removed from Spacedock.

**Comment by politas** [comment]
Ok, I've left another comment in the KF forum thread (the real one, rather than the old one improperly linked in that Spacedock entry)

**Pull request closed without merging**
