### PR TITLE
Unfreeze RSSVE

### PR DESCRIPTION
**Pull request by HebaruSan**
See comments on #7259, @Theysen wants to get this re-indexed.

- Converted to YAML format
- Switched to KSP-RO team repo
- Removed Scatterer-config and Scatterer sunflare dependencies because Scatterer depends on those anyway
- Updated compatibility to 1.10 and higher
- Removed TextureReplacerReplaced recommendation

### CODE REVIEW

**Comment by HebaruSan** [comment]
Do not merge until either:

- there's a new release with an up to date version file; OR
- the vref is removed

**Comment by Theysen** [comment]
I just pushed a new version with the updated .version file and packaged the two releases. Anything else you need me to do?

**Comment by HebaruSan** [comment]
Cool! [The validation script picked up the changes](https://github.com/KSP-CKAN/NetKAN/pull/8595/checks?check_run_id=2940835001), and the compatibility now matches what I'd expect from the release announcement:

```json
      "ksp_version_min": "1.10",
```

**Comment by Theysen** [comment]
Awesome, it's working. I says it can't find DOE and I think it's called Distant Object Enhancement Continued these days.

**Pull request merged**
