### PR TITLE
KSPRescuePodFix.netkan

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by politas** [comment]
Hhi, @linuxgurugamer , I assume you've discussed this with the mod author?

**Comment by linuxgurugamer** [comment]
Yes, I did.

**Comment by linuxgurugamer** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/141560-122-ksp-rescue-pod-validator-no-more-kerbals-spawning-in-inflatable-modules/&do=findComment&comment=2918365

**Comment by politas** [comment]
LGTM

**Pull request merged**
