### PR TITLE
Added Interstellar Extended

### PR DESCRIPTION
**Pull request by A2K**
This time everything is updated according to mod author's comments

### CODE REVIEW

**Comment by A2K** [comment]
Updated dependencies

**Comment by Dazpoet** [comment]
Tweakscale should be TweakScale.

Should the ORS folders not be installed at all, I think I saw them installed in an earlier version of this PR?

**Comment by A2K** [comment]
Updated TweakScale dependency name. ORS is now integrated into WarpPlugin.

**Comment by Dazpoet** [comment]
You'll have to filter MiniAVC.xml also, or issues might arise later with upgrading.

I'm itching to press that merge button :D

**Pull request closed without merging**
