### PR TITLE
Add Kerbaltek mods; HyperEdit and Graphotron

### PR DESCRIPTION
**Pull request by Ezriilc**
Please advise if this is correct and complete, and/or how it can be improved.  Thanks!

### CODE REVIEW

**Comment by Ezriilc** [comment]
I think I did this wrong, so I tried to fix it.

**Comment by Dazpoet** [comment]
Are you aware that Graphotron is strictly tied to ksp_version 1.0.0 in your .version file and is this intended?

**Comment by Ezriilc** [comment]
I wasn't aware that was strict.  Can I just remove that?

**Comment by Ezriilc** [comment]
#rebuild

**Comment by Dazpoet** [comment]
#rebuild

**Pull request merged**
