### PR TITLE
Create Historian.netkan

### PR DESCRIPTION
**Pull request by plague006**
resolves #1321

### CODE REVIEW

**Comment by mgsdk** [comment]
I don't know if we want to install it as "KSEA/Historian" or "Historian". Maybe the resident metadata expert @Dazpoet can be of assistance?

**Comment by Dazpoet** [comment]
Seems someone (read: me) used KSEA before so I recommend we keep going with that. See https://github.com/KSP-CKAN/NetKAN/pull/1177/files

**Comment by plague006** [comment]
So the "Historian" identifier will allow auto-detection and prevent manual+CKAN installs from conflicting (tried manually installing the mod via the .ckan and it failed due to detected dll) and the install path "GameData/Historian" avoids the potential "KSEA"  folder name conflict @Dazpoet brought up.

**Comment by Dazpoet** [comment]
Wait what, there would be no conflict but rather a KSEA folder would be created which includes the subfolders `Historian` and `Sentinel` much like how the USI mods work today.

**Comment by plague006** [comment]
Didn't realize Sentinel belonged to Zeenobit, misinterpreted what you had written.

**Comment by Dazpoet** [comment]
Identifier needs to be identical to file name, seems like you changed it by mistake :)

**Pull request merged**
