### PR TITLE
Add Automatic Fuel Cells from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Xyphos, to add [Automatic Fuel Cells](https://spacedock.info/mod/2248/Automatic%20Fuel%20Cells) to CKAN.

Please direct questions about this pull request to [Xyphos](https://spacedock.info/profile/Xyphos).

Mod details:
    name = /mod/2248/Automatic%20Fuel%20Cells
    author = Xyphos
    abstract = This plugin will attempt to conserve fuel consumption by automatically toggling Fuel Cells on or off in accordance with a minimum and maximum threshold setting on the Fuel Cell's context menu.
    license = MIT
    Homepage = https://github.com/Xyphos/KSP_AutomaticFuelCells
    description =
This plugin will attempt to conserve fuel consumption by automatically toggling Fuel Cells on or off in accordance with a minimum and maximum threshold setting on the Fuel Cell's context menu. Requires "Advanced Tweakables" to be enabled in your game settings.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Sounds really similar to ODFC-Refueled from #7373.
@Xyphos and @zer0kerbal, are you aware of each other's mods? Seems like you might be able to save some redundant work by collaborating.

**Comment by Xyphos** [comment]
I'm not sure how his works because I can't find a source code link anywhere, it appears outdated and mine is just a Stock module improvement. I'm almost certain mine behaves differently from his.

**Comment by HebaruSan** [comment]
> I can't find a source code link anywhere

I think this is it: https://github.com/zer0Kerbal/ODFCr

**Comment by zer0Kerbal** [comment]
Thanks @HebaruSan - these mods can co-exist, although if applied to same part ODFC will be primary because it deletes existing ResourceConverters which AFC requires to run.

Yes, will work with AFC - and love their code. Been meaning to /// <summary> the existing ODFC code, which is still in the process of being modernized.

similar - initial impression of summary:
- AFC just installs automation on existing stock module. Requires existing ResourceConverter on part (or can be installed). Needs to be patched in.
- ODFC highly configurable, multi-mode, adaptable replacement for ResourceConverter. Needs to be patched in.

**Pull request merged**
