### PR TITLE
Create KerbalChangelog.netkan

### PR DESCRIPTION
**Pull request by BenjaminCronin**
If possible I'd like this mod to be available for KSP v.1.4.x AND 1.5.x. I take it that `ksp_version` is the max KSP version that the mod is available for, is this the case?

### CODE REVIEW

**Comment by HebaruSan** [comment]
No, `ksp_version` allows an exact match only. `ksp_version_min` and `ksp_version_max` can be used to support a range.

**Comment by HebaruSan** [comment]
And a more flexible approach is to put a KSP-AVC .version file in your download, which can then be read into CKAN metadata with the $vref property.

**Comment by BenjaminCronin** [comment]
@HebaruSan I think that should do the trick, but I'm not sure why the build is failing...

**Comment by HebaruSan** [comment]
Well there was a syntax error, but I would expect it to still fail until the download contains a .version file. I don't see one in the latest ZIP.

**Comment by HebaruSan** [comment]
Looks good now. (The usual validation scripts aren't available due to #6856, but I ran netkan.exe locally and it looks fine.)

Thanks for the submission! Merging...

**Pull request merged**
