### PR TITLE
Add BoringCrewServices to CKAN

### PR DESCRIPTION
**Pull request by SofieBrink**
- <https://github.com/zorg2044/BoringCrewServices>
- <https://spacedock.info/mod/3757/Boring%20Crew%20Services>
- <https://forum.kerbalspaceprogram.com/topic/192972-wip-boring-crew-services-stockalike-starliner-mod/>

BoringCrewServices is expecting to have its official `v1.0.0` release in about 24 hours, 

The spacedock URL in the netkan is already claimed, just private.
The mod contains an internal .ckan file that contains all the dependencies and other fields [here](https://github.com/zorg2044/BoringCrewServices/blob/main/GameData/BoringCrewServices/BoringCrewServices.ckan)

Would love if this got merged when the mod officially releases, we will need a slight change to the netkan after release to update the homepage url, as its currently pointed to the W.I.P. thread and the release thread doesn't yet exist.
But this will probably be available a few hours to a day after release.

### CODE REVIEW

**Comment by HebaruSan** [comment]
> we will need a slight change to the netkan after release to update the homepage url, as its currently pointed to the W.I.P. thread and the release thread doesn't yet exist.

Just deleted it so you'll be able to edit the URL on SpaceDock instead.

**Comment by SofieBrink** [comment]
Slight change of plans @HebaruSan we're releasing now 😄 
If you could re-run the inflation and merge it if its all good that'd be fantastic!

**Comment by HebaruSan** [comment]
SpaceDock still needs you to click this:

image

**Comment by SofieBrink** [comment]
> SpaceDock still needs you to click this:
> 
> image

Might need to refresh, it went live about a minute ago

**Review by HebaruSan — APPROVED** [review]
Thanks for the submission!

**Pull request merged**
