### PR TITLE
Interstellar Fuel Switch depends on Community Resource PAck, otherwise there are errors

### PR DESCRIPTION
**Pull request by Monniasza**
- <https://spacedock.info/mod/175/Interstellar%20Fuel%20Switch>
- <https://forum.kerbalspaceprogram.com/topic/106243-181-1125-interstellar-fuel-switch-ifs-3295/page/47/>

### CODE REVIEW

**Comment by HebaruSan** [comment]
I'm not finding any evidence of this so far.

https://forum.kerbalspaceprogram.com/topic/106243-181-1125-interstellar-fuel-switch-ifs-3295/

image

@Monniasza, what are your reasons for claiming this?

**Comment by Monniasza** [comment]
I've got errors when loading Interstellar Fuel Switch in my development install

**Comment by HebaruSan** [comment]
Lots of people get lots of errors. What are your reasons for claiming that your errors are related to IFS? What are your reasons for claiming the cause is a heretofore unreported dependency on CRP?

**Comment by HebaruSan** [comment]
Found something in support. It's not documented anywhere, but CRP **is** bundled in the ZIP:

image

Confirmed it _was_ removed for a while as stated in #7883:

image

I guess this dependency switches on and off, and we're currently in an "on" state.

Thanks for the report!

**Pull request merged**
