### PR TITLE
More self-hosted NetKans

### PR DESCRIPTION
**Pull request by ChrisAdderley**
Propagate more items to self-hosted versions for better control.

**Modified:**
- CommunityTechTree
- HeatControl
- CryoTanks
- DeployableEngines
- DynamicBatteryStorage
- KerbalAtomics
- KerbalAtomics-NFECompatibility

**New:**
- CryoTanks-Core
- KerbalAtomics-NTRModSupport
- KerbalAtomics-NTRsUseLFO

ckan compat add 1.6

### CODE REVIEW

**Comment by HebaruSan** [comment]
The new CommunityTechTree is missing its $kref.

**Comment by ChrisAdderley** [comment]
I'll look into this when I get home, unfortunately the CI page is blocked at work.

**Comment by HebaruSan** [comment]
The latest error is just reporting that ModuleManager isn't updated for 1.7 yet, which we can work around by adding some magic to the PR text. I'll do that presently...

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Looks good now. Thanks for the updates!

**Comment by ChrisAdderley** [comment]
Thanks for the fix!

**Pull request merged**
