### PR TITLE
Add DraggableMenu

### PR DESCRIPTION
**Pull request by Cphoenix**
It's for 1.0.5 but might as well in case it gets updated.

### CODE REVIEW

**Comment by Cphoenix** [comment]
Actually I'm being silly and this became stock in 1.1 but still, can't hurt for anyone using 1.0.5.

**Comment by politas** [comment]
Needs an install stanza in order to filter Sources:

    "install": [
        {
            "file": "DraggableMenu",
            "install_to": "GameData",
            "filter": "Sources"
        }
    ]

**Comment by Cphoenix** [comment]
Fixed

**Comment by politas** [comment]
My mistake, that needs to be `"file": "GameData/DraggableMenu",`

**Comment by politas** [comment]
Oh, and this also needs this inserted:

    "conflicts": [
        { "name": "MenuStabilizer" }
    ],

**Comment by Cphoenix** [comment]
Added/fixed. And no worries; I'm in class right now. I'm just blindly copy-pasta'ing. Should've caught the GameData bit myself.

**Comment by politas** [comment]
I think that does it. We probably won't see any further versions of this, but I'm sure there are people still using 1.0.5 that may find it useful.

**Pull request merged**
