### PR TITLE
Create LagrangeProjectRSS.netkan

### PR DESCRIPTION
**Pull request by dongk99**
- <https://github.com/dongk99/LagrangeProjectRSS>
- <https://forum.kerbalspaceprogram.com/topic/226357-lagrangeproject-rss/>

### CODE REVIEW

**Comment by dongk99** [comment]
yayyyyyyyyyyyyyyyyyyy......

**Comment by HebaruSan** [comment]
Hi @dongk99, you can set the homepage link by setting the Website link for the repo on GitHub; the CKAN bot will pull it into the metadata automatically. This has many benefits, for example you would be able to change it any time without a pull request, and non-CKAN users would have easy access to the link as well.

For example, I have this for Astrogator:

image

image

**Comment by dongk99** [comment]
Thank you, im gonna do that right now (and for future repos). :D

**Review by HebaruSan — APPROVED** [review]
Thanks for the submission!

**Pull request merged**
