### PR TITLE
Add More Hitchhikers from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of zer0Kerbal, to add [More Hitchhikers](https://spacedock.info/mod/2244/More%20Hitchhikers) to CKAN.

Please direct questions about this pull request to [zer0Kerbal](https://spacedock.info/profile/zer0Kerbal).

Mod details:
    name = /mod/2244/More%20Hitchhikers
    author = zer0Kerbal
    abstract = adds nine more stock sizes of stock Hitchhiker's Storage Containers: from 1.25m (1 crew) to 5m (10 crew).
    license = CC BY-NC-SA 4.0
    Homepage = 
    description =
This is your mod listing! You can edit it as much as you like before you make it public.

To edit **this** text, you can click on the "**Edit this Mod**" button up there.

By the way, you have a lot of flexibility here. You can embed YouTube videos or screenshots. Be creative.

You can check out the SpaceDock [markdown documentation](/markdown) for tips.

Thanks for hosting your mod on SpaceDock!

### CODE REVIEW

**Comment by HebaruSan** [comment]
> 3514 [1] FATAL CKAN.NetKAN.Program (null) - /tmp/CdFileMgr/f8e55025-4ac3-48.tmp is not a valid ZIP file: Error in step EntryHeader for GameData/KGEx/MoreHitchhikers/CC-BY-NC-SA-4.0.txt: Exception during test - 'Compression method not supported'

**Comment by zer0Kerbal** [comment]
should be fixed now. sometimes 7z and I don't get along. :) @HebaruSan

**Comment by HebaruSan** [comment]
#rebuild

**Comment by zer0Kerbal** [comment]
so Deflate64 is the issue? just use Deflate?

**Comment by HebaruSan** [comment]
Yes:  icsharpcode/SharpZipLib#23

**Comment by zer0Kerbal** [comment]
understood. thank you for your patience. 
Should be GTG.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Looks good now, thanks for the submission!

**Comment by zer0Kerbal** [comment]
thank you for your assistance and well, everything. 👍

**Pull request merged**
