### PR TITLE
Add OpenTree from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Oneiros, to add [OpenTree](https://kerbalstuff.com/mod/829/OpenTree) to CKAN.

Please direct questions about this pull request to [Oneiros](https://kerbalstuff.com/profile/Oneiros).

### CODE REVIEW

**Comment by mgsdk** [comment]
I'm unable to locate a webpage for this mod (And it seems rather new). Found a matching user though at http://forum.kerbalspaceprogram.com/members/148004-Oneiros.

**Comment by Dazpoet** [comment]
Requires ModuleManager for sure, is this a CTT mod or something else? I'm very bad at distinguishing the various TechTree mods.

**Comment by mgsdk** [comment]
Considering there is no other info, it would need to be tested manually.

**Comment by mgsdk** [comment]
#rebuild

**Comment by mgsdk** [comment]
An update to this, there is now a forum page at http://forum.kerbalspaceprogram.com/threads/122571, however it is not scraped through KS yet. There also appears to be two versions, of which we would only catch one with the scraper.

**Comment by Dazpoet** [comment]
Hm I'm pretty sure that https://github.com/Dazpoet/CKAN/blob/master/Spec.md#ckangithubuserrepoasset_matchfilter_regexp doesn't work on KS krefs, because that would be to easy.

**Comment by Dazpoet** [comment]
Reading the forum thread for OpenTree I notice that indexing the Standard version will probably be pretty hard for us considering this:

```
Standard Version

Choose this if you have: 
No mods
Mods that do not add new parts to the game (e.g. visual mods)
Mods that only add new parts to the "start" technology (e.g. K.E.R.)
```

I don't think our conflict stanza can handle that without making this the most high maint mod we index since it would require us to add a conflict every time we add a mod which adds part anywhere but the Start tech node.

**Comment by lukeklemens** [comment]
Hey, sorry I'm new to GitHub. The download is at https://kerbalstuff.com/mod/829/OpenTree

I figured the mod requirements would be difficult to integrate into your system. I'll try to figure out some way of combining the two versions without breaking things. Thanks for your awesome project!

**Comment by lukeklemens** [comment]
OK I've updated the mod to a single version that is compatible with everything, so ignore that previous stuff. The only mod required is Module Manager. Thanks

**Comment by lukeklemens** [comment]
Hey guys, just wondering how long this will take to show up in your database? Had a few people requesting it. Thanks

**Comment by techman83** [comment]
@lukeklemens - It looks like it requires a new netkan to be created that covers the relevant MM dependency (and potentially other tweaks). Once the netkan file is in place it will get automatically indexed (including future updates) and be available to clients straight away.

**Pull request closed without merging**
