### PR TITLE
Update Taerobee to GitHub

### LINKED ISSUE #3268: Porting over Taerobee
Taerobee has switched from KS to Github. It is now at https://github.com/Tantares/Taerobee/releases

However, given my last failure (regarding versioning) in doing such a port, I'm hoping someone else might do the PR. :D

### PR DESCRIPTION
**Pull request by Olympic1**
@NathanKell here is your requested PR.

Closes #3268

### CODE REVIEW

**Comment by NathanKell** [comment]
@Olympic1  <3 you are an RP-0 hero! (And a hero for everybody else too obvs, including Beale @Tantares :) )

**Comment by plague006** [comment]
`author`

**Comment by Olympic1** [comment]
@plague006 it extracts the author from the repo

The generated `.ckan`:
```
{
    "spec_version": 1,
    "identifier": "Taerobee",
    "name": "Taerobee - Stockalike X-1 & More",
    "abstract": "Stockalike Historic (Pre-Sputnik) Rocket and Aircraft Parts.",
    "author": "Tantares",
    "license": "CC-BY-NC-SA-4.0",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/119858-/",
        "repository": "https://github.com/Tantares/Taerobee"
    },
    "version": "2.3",
    "ksp_version": "1.0.5",
    "install": [
        {
            "file": "Taerobee",
            "install_to": "GameData"
        }
    ],
    "download": "https://github.com/Tantares/Taerobee/releases/download/v2.3/Taerobee.zip",
    "download_size": 1267997,
    "x_generated_by": "netkan"
}
```

**Comment by plague006** [comment]
I'm too set in established conventions (ex. author, name, and abstract for github netkans)

**Pull request merged**
