### PR TITLE
Mod’s owner changed

### PR DESCRIPTION
**Pull request by formicant**

### CODE REVIEW

**Comment by SirDiazo** [comment]
Confirming transfer of ownership.

**Comment by politas** [comment]
Needs something to tell CKAN which KSP version is supported. Either explicit "ksp_version", a range of  "ksp_version_min" to "ksp_version_max", or a $vref if you include an AVC .version file

**Comment by formicant** [comment]
I added a .version file.

**Comment by politas** [comment]
Excellent! Merging with thanks!

**Pull request merged**
