### PR TITLE
Retro

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
@HebaruSan I need some help.
This is erroring on FirespitterCore not being available.  The .version in the mod specifies a minimum kSP version of 1.5.1
I checked all the CKAN-Meta files, and I see that FirespitterCore-v7.11.0 has a meta file which specifies KSP from 1.5.0 to 1.5.9
Also, the initial commit worked, and now an update is not.  I have no idea what's going on now

**Comment by DasSkelett** [comment]
You might be confuse by [this commit](https://github.com/KSP-CKAN/NetKAN/pull/7199/commits/0cb5e17975af7d97a92e57fc002437706616fe92), which is showing up for this PR. But it changes `KerbalKrashSystem.netkan`, not this one, and has no effect for this PR.

**Comment by linuxgurugamer** [comment]
Thanks, I'll add it

**Comment by linuxgurugamer** [comment]
Grr.  This is what happens when I try to save time by reusing an existing one.
Thanks, added and committed

**Pull request merged**
