### PR TITLE
Add part commander

### PR DESCRIPTION
**Pull request by seanmcdougall**

### CODE REVIEW

**Comment by plague006** [comment]
You can't use `"x_netkan_license_ok": true` because the license in KerbalStuff doesn't match an accepted license. You can just swap that line for `"license" : "GPL-3.0"

**Comment by seanmcdougall** [comment]
Hi Matthew.  I've fixed the license string on KerbalStuff.  Do you still
want me to submit a new netkan file, or is it OK now?

Thanks,

Sean

**Comment by seanmcdougall** [comment]
Ok, I've changed the license line.  Please ignore those other commits - I goofed somewhere creating this pull request.  Still new to this whole GitHub thing.

**Comment by plague006** [comment]
I've goofed worse. =)

**Comment by dbent** [comment]
Checked manually, merging. Thanks.

**Pull request merged**
