### PR TITLE
Added AVC line

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
!pull

**Comment by linuxgurugamer** [comment]
!

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by pjf** [comment]
Just checking which changes should be part of this PR. It's got changes to six files, which is totally fine, but the title of "Added AVC line" implies that some of those files perhaps aren't supposed to be there. :)

**Comment by linuxgurugamer** [comment]
I guess I wasn't clear enough.  I added the AVC line to each of the changed files.

**Comment by plague006** [comment]
EVAHandrailsPackContinued.netkan added in #1645 - 2a64b13 and f731446
Pathfinder.netkan added in  #1747 - 5d8f9a0 and e53dadf

Addings lines for AVC will be added in #1859 - e07609f (and 2a64b13 for the AVC in EVArails...)
That leaves all commits accounted for and this can be closed.

Sorry it took a while @linuxgurugamer

**Comment by linuxgurugamer** [comment]
No problem, thanks for getting to it.

JBB

**Pull request closed without merging**
