### PR TITLE
Update DeadlyReentry netkan to point at currently-active fork

### PR DESCRIPTION
**Pull request by NathanKell**
Well, currently active not-a-fork, since it's actually the head repo. :D

### CODE REVIEW

**Comment by NathanKell** [comment]
Ugh I shoulda branched, you should squash this on merge I guess, sorry!

**Comment by HebaruSan** [comment]
Thanks for the update!

**Comment by HebaruSan** [comment]
Apparently the previous fork wasn't actually abandoned. Lovely.

https://forum.kerbalspaceprogram.com/index.php?/topic/50296-112-deadly-reentry-v782-the-barbie-edition-aug-5th-2021/&do=findComment&comment=4015220

image

**Comment by NathanKell** [comment]
I will be interested to see whether any actual development occurs.

**Comment by HebaruSan** [comment]
Well there's already a new release:

https://github.com/Starwaster/DeadlyReentry/releases/tag/v7.8.2

**Comment by NathanKell** [comment]
Oh dear. This is what I get for working PST hours, I have not been following.

**Pull request merged**
