### PR TITLE
Add BDArmoury DMP Addon from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
# Version scheme is too inconsistent
This pull request was automatically generated by Kerbal Stuff on behalf of jediminer543, to add [BDArmoury DMP Addon](https://kerbalstuff.com/mod/1050/BDArmoury%20DMP%20Addon) to CKAN.

Please direct questions about this pull request to [jediminer543](https://kerbalstuff.com/profile/jediminer543).

### CODE REVIEW

**Comment by plague006** [comment]
Uses a custom version of BDArmory, [waiting on info](http://forum.kerbalspaceprogram.com/threads/130464) from author on if more changes will be made other than `BahaTurret.dll`

**Comment by plague006** [comment]
Only the 1 file should ever be affected. So a BDarmory split seems like the way to proceed.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN/issues/1311 would benefit this mod

**Comment by draeath** [comment]
Mod updated to 0.9.1, but there's also another PR relating to this. See PRs  #2042 and #2065

**Comment by plague006** [comment]
@draeath I think you're in the wrong PR. You're talking about `BDArmory`, this is to add `BDArmoury DMP Addon`.

Unrelated to that, I don't think we can currently index this mod via netkan. The mod author isn't using a version scheme we can follow, he's simply using the git commit hashes as his version numbers.

**Comment by plague006** [comment]
Closing this due to age. If the mod releases/gets a stable versioning scheme this can be re-opened.

**Pull request closed without merging**
