### PR TITLE
Add SM AFVs from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of RecoverMod, to add [SM AFVs](https://spacedock.info/mod/2161/SM%20AFVs) to CKAN.

Please direct questions about this pull request to [RecoverMod](https://spacedock.info/profile/RecoverMod).

Mod details:
    name = /mod/2161/SM%20AFVs
    author = RecoverMod
    abstract = Works for KSP 1.4.3 and upwards
    license = GPLv3
    Homepage = 
    description =
Works for KSP 1.4.3 and upwards

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
"RecoverMod" appears to not be the author, and the forum thread was locked in March.
Closing due to obvious shenanigans.

**Comment by Olympic1** [comment]
The GitHub repo and SpaceDock pages from the original Author were also removed.

**Comment by HebaruSan** [comment]
The author says he's going through some health stuff and that he wants these uploads taken down:

https://forum.kerbalspaceprogram.com/index.php?/profile/50907-spannermonkeysmce/&status=8766&type=status

> Which brings me nicely to the current SpaceDock situation I'm aware that SM Armory and SMAFV's are back up on SpaceDock, this is completely unauthorised, they are not supported . I've not been contacted by the user RecoverMod regarding them, and such publication is in breach of the license. I and others are taking steps to have them removed, something I shouldn't have to do.

**Pull request closed without merging**
