### PR TITLE
Add lorefriendly flag pack .netkan file

### PR DESCRIPTION
**Pull request by Blu3wolf**

### CODE REVIEW

**Comment by Dazpoet** [comment]
No releases so it fails because the bot can't find anything

**Comment by Blu3wolf** [comment]
it has a release now.

**Comment by Dazpoet** [comment]
#rebuild

**Comment by Dazpoet** [comment]
Trying to figure out why it didn't work but the release seems to be source only, even though in this case it's the same thing (ish).

NetKAN needs a release similar to [this](https://github.com/BobPalmer/Karbonite/releases) to work.

**Comment by Blu3wolf** [comment]
@ual002

**Comment by Blu3wolf** [comment]
has a release, has a separate zip containing the mod... should work now?

**Pull request merged**
