### PR TITLE
Preventing the use of github by CKAN due development cycle constraints.

### PR DESCRIPTION
**Pull request by Lisias**
All of these are available on [archive org](https://archive.org/details/kspckanmods) anyway.

Thankyou.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Hi @Lisias, thanks for reaching out.

Can I ask what sort of "development cycle constraints" are of concern here? Maybe we can adjust CKAN and/or the bot to accommodate them, so as to keep the most reliable hosting options available to users.

Thanks!

**Comment by Lisias** [comment]
I had explained it on Forum, and I would prefer not to repeat the same information:

* https://forum.kerbalspaceprogram.com/topic/225966-psa-update-your-ckan-clients-to-134/?do=findComment&comment=4421703
* https://forum.kerbalspaceprogram.com/topic/225966-psa-update-your-ckan-clients-to-134/?do=findComment&comment=4421708

Only what I publish on SpaceDock (and are mirrored on https://archive.org/details/kspckanmods ) are tested and validated to be used by CKAN users.

**Comment by HebaruSan** [comment]
I see. That's why I was asking, because I replied in response to those concerns noting that the bot will handle that pipeline appropriately. I hope that was a relief to find out!

So should we close this?

**Comment by Lisias** [comment]
After merging it, for sure!

**Comment by Lisias** [comment]
Please be adivesed that packages from github will not work on CKAN anymore.

**Comment by HebaruSan** [comment]
> Please be advised that packages from github will not work on CKAN anymore.

This response is unclear to me. Could you please explain what you mean?

**Comment by Lisias** [comment]
> This response is unclear to me. Could you please explain what you mean?

github packages are not meant to be used by CKAN. CKAN users downloading from github will not be able to use it.

Only what's published on SpaceDock and on the Archive mirror will work with CKAN.

**Comment by HebaruSan** [comment]
What do you mean by "they will not be able to use it"? What will happen if they try?

**Comment by Lisias** [comment]
> What do you mean by "they will not be able to use it"? What will happen if they try?

I will send them to CKAN page for support.

**Comment by HebaruSan** [comment]
You skipped ahead a few steps there, I think. Let's go one at a time.

A user installs GitHub release via CKAN and starts the game. So far they are not asking anyone for support. What are you expecting to happen next?

**Comment by Lisias** [comment]
> You skipped ahead a few steps there, I think. Let's go one at a time.
> 
> A user installs GitHub release via CKAN and starts the game. So far they are not asking anyone for support. What are you expecting to happen next?

A pop message telling the user to use SpaceDock, or they will not be able to load their savegames.

**Comment by HebaruSan** [comment]
Ahh, OK. In that case, when you upload that release, instead of the bot adding it to CKAN, it will alert us with some error messages, and we'll merge this then. Cheers! 👍

**Comment by JonnyOThan** [comment]
Hey I'm gonna go ahead and merge this now - it's exactly what I asked for on the forum and I think we should let mod authors control decisions about how their mods are distributed.

Committed (I goofed on the commit message, sorry): https://github.com/KSP-CKAN/NetKAN/commit/146a722e518735c62cf9e7dcb5940ac3e59e2609

**Comment by Lisias** [comment]
Thank you, and I apologize if I sounded harsh on Forum. I spent a good part of the weekend chasing ghosts, and I probably let the frustration leak out before being aware of, well, being frustrated.

**Pull request merged**
