### PR TITLE
Delete SPPCC.frozen

### PR DESCRIPTION
**Pull request by Avera9eJoe**
This file is a now defunct version of Spaceplane Correcetions, SPPCC stands for Space Plane Color Corrections, but I abbreviated the name to Spaceplane Corrections a number of years ago and recreated the page on SpaceDock/CKAN. This file is safe to delete so as to not confuse users.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Users will never see this file, but it makes sense to remove if we're indexing this mod in #7361.

**Comment by HebaruSan** [comment]
BTW @Avera9eJoe, I just caught up on your chat with @allista in the SpaceDock IRC; in case you're curious how CKAN figured out how to install Spectra, it's mostly through manual inspection: #7057

**Comment by Avera9eJoe** [comment]
Hm, HebaruSan the reason I requested this deleted was because users *can* see it, or at the very least I was seeing it when I searched "Spaceplane Color Corrections" on CKAN. I'm fairly certain it is this exact file after doing some searching through files in my local CKAN database. I could be wrong though and it might be something different. I'm not experienced at all when it comes to this sort of thing!

**Comment by HebaruSan** [comment]
Nope, this file has/had no effect on CKAN. It skips files with a .frozen extension.
You may have been seeing this one:
https://github.com/KSP-CKAN/CKAN-meta/tree/master/SPPCC

**Comment by Avera9eJoe** [comment]
Ahhh yes that would be it. The filename was SPPCC. How would I go about requesting that to be deleted? Thank you for all the help!

**Comment by HebaruSan** [comment]
You can click the file, click the pencil icon, change the extension to "frozen", and then use the "commit changes" fields at the bottom to start a pull request.

**Pull request merged**
