### PR TITLE
Remove KSPIE Incompatibilty

### PR DESCRIPTION
**Pull request by hemeac**
Compatibility with KSPIE happened on @sswelm  's side.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Gonna rebse this to un-confuse the validation...

**Comment by HebaruSan** [comment]
Thanks for the update!

**Comment by hemeac** [comment]
Thanks and apologies I had tried rebasing my fork by doing a pull request, but guessing that was not the correct method, still pretty new to Github.

**Comment by HebaruSan** [comment]
Don't worry about it, the tools should be smarter, we just re-did them and there are some kinks left to work out.

**Pull request merged**
