### PR TITLE
Add Wenchang Satellite Launch Center from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of IcecoveryStudio, to add [Wenchang Satellite Launch Center](https://spacedock.info/mod/1091/Wenchang%20Satellite%20Launch%20Center) to CKAN.

Mod details:
    name = /mod/1091/Wenchang%20Satellite%20Launch%20Center
    author = IcecoveryStudio
    abstract = Chinese Wenchang Satellite Launch Center
    license = CC BY-SA 4.0
    Homepage = 
    description = ##A replica of Wenchang Satellite Launch Center, a southern and newly built launch facility in People's Republic of China, which serves flight missions of CZ-5, CZ-7, and future heavy launch vehicles like CZ-9.
##Our members:

###Models: ladeng
###Textures:ladeng
###Import: ladeng
###Configs: ladeng
###Technical Support:

##DEPENDENCIES:

###Kerbal Konstructs

##LICENSE:

###CC BY-SA 4.0

Please direct questions about this pull request to [IcecoveryStudio](https://spacedock.info/profile/IcecoveryStudio).

### CODE REVIEW

**Comment by Dazpoet** [comment]
#4989 must be merged before this since it depends on it

**Comment by politas** [comment]
#rebuild

**Comment by Dazpoet** [comment]
New version with other folderstructure... Let's see if this works then

**Comment by politas** [comment]
LGTM

**Pull request merged**
