### PR TITLE
Suppress recs on CKAN-hosted netkans for RO group mods

### PR DESCRIPTION
**Pull request by NathanKell**
https://github.com/KSP-CKAN/CKAN/pull/3892

### CODE REVIEW

**Comment by NathanKell** [comment]
I left spec version at 1.26 where it was, and upgraded it to 1.26 where it was lower than that, but does suppress recs need a higher spec version? If so I'll make that change here and also all the remote netkans.

**Comment by HebaruSan** [comment]
No; `suppress_recommendations` will be part of the v1.34 spec, but its presence does not break previous client, so no change to `spec_version` is needed.

**Comment by NathanKell** [comment]
Thanks! Ok then I think I hit everything here + remote.

**Review by HebaruSan — APPROVED** [review]
Thanks for the update! 🎆

**Pull request merged**
