### PR TITLE
Add Contract Pack: Unmanned Contracts from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of linuxgurugamer, to add [Contract Pack: Unmanned Contracts](https://kerbalstuff.com/mod/650/Contract%20Pack:%20Unmanned%20Contracts) to CKAN.

Please direct questions about this pull request to [linuxgurugamer](https://kerbalstuff.com/profile/linuxgurugamer).

### CODE REVIEW

**Comment by hakan42** [comment]
@linuxgurugamer , You need a "find" stanza for the contracts.

**Comment by linuxgurugamer** [comment]
I guess I'm dense.  This file was (again) generated by kerbalstuff.  I don't understand what you mean by a "find" stanza

I've made the following:

Netkan file:

{
    "spec_version"    :    1,
    "identifier"    :    "spacetuxUnmannedContracts",
    "$kref"        :    "#/ckan/kerbalstuff/651",
//    "$vref"        :    "#/ckan/ksp-avc",
    "x_netkan_license_ok":     true,

    "depends" : [
        { "name" : "ContractConfigurator" }
    ],
    "install" : [
        {
            "file"       : "GameData/ContractPacks/spacetux",
            "install_to" : "GameData/ContractPacks"
        }
    ]
}


CKAN file (generated from above):

{
  "spec_version": 1,
  "identifier": "spacetuxUnmannedContracts",
  "x_netkan_license_ok": true,
  "depends": [
    {
      "name": "ContractConfigurator"
    }
  ],
  "install": [
    {
      "file": "GameData/ContractPacks/spacetux",
      "install_to": "GameData/ContractPacks"
    }
  ],
  "resources": {
    "homepage": "http://forum.kerbalspaceprogram.com/threads/113400-Spacetux-Contract-Pack-Unmanned-Contracts-0-2-1?p=1792403#post1792403",
    "kerbalstuff": "https://kerbalstuff.com/mod/651/Contract%20Pack:%20Unmanned%20Contracts"
  },
  "ksp_version": "0.90",
  "name": "Contract Pack: Unmanned Contracts",
  "license": "CC-BY-NC-SA-4.0",
  "abstract": "Extensive series of unmanned contracts",
  "author": "linuxgurugamer",
  "version": "0.2.1",
  "download": "https://kerbalstuff.com/mod/651/Contract%20Pack:%20Unmanned%20Contracts/download/0.2.1",
  "x_generated_by": "netkan",
  "download_size": 88717
}

**Comment by linuxgurugamer** [comment]
Please delete this, i've figured out how to upload my own file and just did it.

Thanks

**Comment by Dazpoet** [comment]
Superceded by https://github.com/KSP-CKAN/NetKAN/pull/856 by @hakan42

**Pull request closed without merging**
