### PR TITLE
Repointed CLS to Linuxgurugamer for now

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
What would you say to making author an array with both you and Papa_Joe, and adding the forum thread as the resources.homepage (as the old .ckan file has)?

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
This is temporary, it will totally revert to Papa_Joe when he comes back, so I don't want to make any unnecessary chagnes

**Comment by HebaruSan** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Thanks for merging

**Pull request merged**
