### PR TITLE
Added conflicts due to issues with Kerbalism for KVV & Hullcam

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by politas** [comment]
Can you add n `"x_netkan_epoch"` bump to force reinstallation? Changing dependencies like this always causes grief, otherwise.

**Comment by dbent** [comment]
> Can you add n "x_netkan_epoch" bump to force reinstallation? Changing dependencies like this always causes grief, otherwise.

It shouldn't since v1.20.0 and KSP-CKAN/CKAN#1730.

**Comment by politas** [comment]
>It shouldn't since v1.20.0 and KSP-CKAN/CKAN#1730.

Maybe not, but it still does. We've had many reports.

**Comment by dbent** [comment]
So they should upgrade...

**Comment by politas** [comment]
I don't think KSP-CKAN/CKAN#1730 is working in all cases.

**Comment by dbent** [comment]
> I don't think KSP-CKAN/CKAN#1730 is working in all cases.

I'd need to know what cases to fix it. There shouldn't be any situation that a epoch bump would handle that KSP-CKAN/CKAN#1730 wouldn't.

**Comment by politas** [comment]
Have a look through the various issue reports on Stock Visual Enhancements.

**Pull request merged**
