### PR TITLE
Update AstronomersVisualPack.netkan

### PR DESCRIPTION
**Pull request by themaster402**
Moved dependencies, recommended, and suggested mods to more proper categories. Added conflicts. Ensure staging (possible fix for [versioning issue which prevents indexing on an otherwise compatible install](https://github.com/themaster402/AstronomersVisualPack/issues/2).)

### CODE REVIEW

**Comment by HebaruSan** [comment]
First, I'm sorry that your users had CKAN problems and bothered you with them. Please feel free to refer them to us whenever issues like this come up.

Created WazWaz/EnvironmentalVisualEnhancements#18 to hopefully help with that linked issue. We can add an override to make EVE support up to KSP 1.7, but I'd like to make sure @WazWaz is OK with that first so CKAN users don't go filing a bunch of false bug reports with him.

There doesn't seem to be a problem with the textures being indexed. All three of the packs were indexed within a few hours of their latest releases being created:

- https://github.com/KSP-CKAN/CKAN-meta/commit/d931933b4f246f97258f4c31cd1a6f3ab2ffa211
- https://github.com/KSP-CKAN/CKAN-meta/commit/458d5399ab03ac02077ddc85626333f8380028f4
- https://github.com/KSP-CKAN/CKAN-meta/commit/1545ffc373902e9f2bf25f11e71c4f7313f40a31

Are you sure you want staging enabled? That would create a delay for new releases, but it wouldn't help us fix anything.

**Comment by HebaruSan** [comment]
I think he's OK with supporting the current EVE on 1.7 based on the above PR getting merged, so I made that change in #7226. Users should no longer have problems with AVP showing up as incompatible.

**Comment by HebaruSan** [comment]
TextureReplacer is also now marked as compatible with 1.7 after ducakar/TextureReplacer#14.
The last one left is Scatterer, which only goes up to 1.6.1.

**Comment by HebaruSan** [comment]
Tagging @themaster402 in case you haven't been receiving notifications for the above comments. Your attention is kindly requested for the following part:

> There doesn't seem to be a problem with the textures being indexed. All three of the packs were indexed within a few hours of their latest releases being created:
> 
> - https://github.com/KSP-CKAN/CKAN-meta/commit/d931933b4f246f97258f4c31cd1a6f3ab2ffa211
> - https://github.com/KSP-CKAN/CKAN-meta/commit/458d5399ab03ac02077ddc85626333f8380028f4
> - https://github.com/KSP-CKAN/CKAN-meta/commit/1545ffc373902e9f2bf25f11e71c4f7313f40a31
> 
> Are you sure you want staging enabled? That would create a delay for new releases, but it wouldn't help us fix anything.

**Comment by themaster402** [comment]
If that is the case, I would prefer only the mod relations to be updated. Thank you for the assistance.

**Comment by HebaruSan** [comment]
Cool! Thanks for letting us know about the relationship changes. Merging...

**Pull request merged**
