### PR TITLE
Break InterstellarFuelSwitch.dll into it's own -Core.netkan

### PR DESCRIPTION
**Pull request by Dazpoet**
See reasoning at https://github.com/KSP-CKAN/NetKAN/issues/1126

### CODE REVIEW

**Comment by mgsdk** [comment]
#rebuild

**Comment by mgsdk** [comment]
We need to get the upgrade path sorted out. I created updated .ckan metadata in https://github.com/mgsdk/CKAN-meta/tree/test_interstellar and bumped the versions of all files to test the upgrade path. After upgrading the modules, CKAN will happily allow me to remove InterstellarFuelSwitch, though no InterstellarFuelSwitch-Core is present.

**Comment by mgsdk** [comment]
After some more testing, it seems the issue is that InterstellarFuelSwitch and InterstellarFuelSwitch-Core has the same name. Changing the name tag in InterstellarFuelSwitch-Core makes it show up in the GUI. Also, if all the files get a version bump to allow the client to upgrade them, InterstellarFuelSwitch-Core is installed as expected. The version bump would have to be done manually with the .ckan metadata I guess.

**Comment by Dazpoet** [comment]
updated to include the changes in #1306

**Comment by mgsdk** [comment]
Upgrade path works for CryoEngines and NearFutureConstruction, however I seem to have an issue with InterstellarFuelSwitch not getting the right dependency on the core. Also, I would suggest changing the name of InterstellarFuelSwitch-Core to "Interstellar Fuel Switch Core" to better match the name of InterstellarFuelSwitch.

**Comment by mgsdk** [comment]
All upgrade paths work with manual version bump.

**Pull request merged**
