### PR TITLE
Make `Install` property of RedOnion lower case

### PR DESCRIPTION
**Pull request by DasSkelett**
Thanks @HebaruSan for pointing it out.

### CODE REVIEW

**Comment by HebaruSan** [comment]
I'm trying to figure out whether the bundled ZIP files need to be unzipped, but I don't see any installation instructions. Any idea?

**Comment by DasSkelett** [comment]
No, see [here](https://github.com/evandisoft/RedOnion/issues/28)

**Comment by DasSkelett** [comment]
Out of interest, would there be a way for CKAN to unzip folders (besides the root folder)?

**Comment by HebaruSan** [comment]
Do you mean unzip nested ZIPs? No, that's not implemented as far as I know.

If you mean extract regular folders from the main ZIP, you're already doing that here with Plugins.

**Comment by DasSkelett** [comment]
First one, extract nested zips inside the root zip. Good to know, thank you.

**Pull request merged**
