### PR TITLE
Adding this with Ignobil's permission

### PR DESCRIPTION
**Pull request by linuxgurugamer**
KAL9000

### CODE REVIEW

**Comment by plague006** [comment]
The `$kref` points this mod: https://kerbalstuff.com/mod/900 I don't think that's what you want.

**Comment by plague006** [comment]
The mod also `depends` `KAS` per the OP in the mod's thread.

**Comment by linuxgurugamer** [comment]
@plague006 Thank you, I've fixed it

**Comment by plague006** [comment]
Looks good, passes local. Merging with my thanks.

**Pull request merged**
