### PR TITLE
Add KerbalResearchAndDeveleopment 1.3 for KSP1.0.5

### PR DESCRIPTION
**Pull request by politas**
Based off #4195, this will get the old release supporting KSP 1.0.5 into CKAN

### CODE REVIEW

**Comment by politas** [comment]
I have a change ready for another PR after this is merged that will have the current and future releases working.

**Comment by Cphoenix** [comment]
I know the identifier is supposed to be short, but isn't KRnD a little _too_ short? I know it's not something I would search for if looking to add a new netkan for it, as in the forum thread it's mostly referred to by it's full name. And most netkans it seems have the full or almost full names for most mods.

**Comment by politas** [comment]
KRnD matches the folder name the mod will install. Searching for existing netkans by name is a fundamentally flawed method. Much better to fire up a CKAN client, set the filter to "All" and use the filter by name box to search for unusual name elements.

**Comment by politas** [comment]
It's also the identifier the mod author picked, and the github repository name.

**Comment by Cphoenix** [comment]
Eh, fair enough. It's probably just me having that initial "Ewwwww, why abbreviate when you can be verbose but specific" reaction.

**Comment by plague006** [comment]
`homepage` link is dead

**Comment by politas** [comment]
Done. Have you seen the latest episode of Silicon Valley? I'm interested to know why the hating on tabs.

**Comment by politas** [comment]
Merging, then I will create a new PR to switch to the self-hosted netkan

**Pull request merged**
