### PR TITLE
Add Procedural Fairings Retexture

### PR DESCRIPTION
**Pull request by Cphoenix**
See [forum thread.](http://forum.kerbalspaceprogram.com/index.php?/topic/141636-11x-procedural-fairings-retexture/) Tested and got a valid CKAN out of this.

And after a couple hours doing a disgusting amount of rebasing, reverting, and so on on my fork of NetKAN, I fixed my tomfoolery that caused the mess. Woo. :persevere: 

Replaces #4242

### CODE REVIEW

**Comment by politas** [comment]
"x_netkan_license_ok" is unnecessary. It's purpose is to tell netkan to not enforce checking for a valid "license" so that it can wait for it to added by a later transformation (the $kref expansion, usually). Since you are explicitly entering the license from the start, you should always have a valid one.

**Comment by politas** [comment]
Congrats on cleaning up your fork of the repo! I know how confusing and weird it can be to get that working.

**Comment by Cphoenix** [comment]
There we go. (And yeah, when things get out-of-whack because of a mistake you made, boy howdy can they go off the rails. >.< )

**Comment by politas** [comment]
Looks all good now. Merging with thanks!

**Comment by dbent** [comment]
Think @politas forgot to hit the big fat green button.

**Comment by Cphoenix** [comment]
Lol. Seems so. Thanks. :)

**Comment by politas** [comment]
Hmmph. Must have gone back to notifications before it finished sending the request on the second button press. Sorry about that!

**Pull request merged**
