### PR TITLE
Add ChinesePackContinued

### PR DESCRIPTION
**Pull request by Olympic1**
closes #2519

### CODE REVIEW

**Comment by techman83** [comment]
Something happening with the D/L from KS. Will need to look closer.

**Comment by Olympic1** [comment]
force a rebuild

**Comment by Olympic1** [comment]
Finally

**Comment by plague006** [comment]
Missing the recommends:
````
RSS or 10x Kerbol System (unless you like single-stage-to-Jool rockets)
Ferram Aerospace Research (unless you like the soupy atmosphere in RSS)
Kerbal Joint Reinforcement (unless you like noodle-like rockets)
Kerbal Crew Manifest (Shenzhou's orbital module's hatch doesn't work, this provides a temporary workaround for crew transfering)
Real Fuels (Will be supported in future versions, integration WIP)
RealChute (Provides some help for Shenzhou's chute problems, and it is a good mod afterall)
RealPlume (If you can run RSS at a reasonable FPS, I guess some pretty FX won't hurt anybody)
````

**Comment by Olympic1** [comment]
Added the recommendations, merging

**Pull request merged**
