### PR TITLE
Add RCS Sounds

### PR DESCRIPTION
**Pull request by Olympic1**
Added as requested by FreeThinker (@sswelm) on the [CKAN thread]
(http://forum.kerbalspaceprogram.com/threads/100067?p=2159529#post2159529).

### CODE REVIEW

**Comment by Olympic1** [comment]
Using download via curse because github repo isn't updated

**Comment by sswelm** [comment]
Thanks

**Comment by dbent** [comment]
It's [already in CKAN](https://github.com/KSP-CKAN/CKAN-meta/tree/master/RCSSounds), but I see there's a new `4.3a` version. Can you submit a PR for the new version in CKAN-meta? It doesn't go in Netkan because it's hosted on Curse and can't be updated automatically.

**Comment by Olympic1** [comment]
Made a PR in CKAN-meta
KSP-CKAN/CKAN-meta/pull/748

**Pull request closed without merging**
