### PR TITLE
External NetKAN files for all B9-related mods

### PR DESCRIPTION
**Pull request by blowfishpro**
They're all in their respective Github repositories now

### CODE REVIEW

**Comment by blowfishpro** [comment]
Any idea why CI is failing here?  It seems to be trying to install 5.4.0 from Kerbalstuff, but nothing points to Kerbalstuff anymore.  I ran netkan.exe on all the files locally (both the ones I pushed to git and the ones in this PR which link to them) and they all succeeded.

**Comment by plague006** [comment]
For better or worse (better in this case) ckan.exe even with the -c argument will try to install the newest version of the mod. In this case it's taking `R5.4.0` as < `6.0.0`. The fix is to add an epoch to each of the affected mods.
`"x_netkan_epoch": "1",`

**Comment by plague006** [comment]
Looks good, merging with my thanks.

**Comment by blowfishpro** [comment]
I noticed that the NetKAN bot updated B9AerospaceHX and B9AerospaceLegacy but not B9.  Is there a run log somewhere I could look at to determine the problem?

**Comment by Olympic1** [comment]
@blowfishpro Add an `abstract` to B9 and B9-props.

**Comment by Olympic1** [comment]
@blowfishpro Our bot added your last two mods to CKAN

**Comment by blowfishpro** [comment]
@Olympic1 I added `abstract` this morning, looks like it worked.  Thanks for the help.

**Comment by Olympic1** [comment]
@blowfishpro I'm here to help

**Pull request merged**
