### PR TITLE
Freezing files to stop incorrect metadata coming from author-hosted netkans

### PR DESCRIPTION
**Pull request by plague006**
Per roverdude's request when there's an issue with metadata coming from him I'm freezing the netkans. This can be reverted once a new release is issued which agrees with the metadata set in https://github.com/BobPalmer/CKAN/commit/9f35f7b6a9079e01bd19de9251885e14dbc97eb8 or when the metadata is corrected to agree with the licenses of the current releases of the mods.

Pinging @BobPalmer to let you know your extant netkans are supplying us incorrect metadata. As soon as it's fixed feel free to ping me personally, comment in this PR, or open an issue ticket at your convenience.

### CODE REVIEW

**Comment by BobPalmer** [comment]
The license is now ARR.  Please un-freeze these.

**Comment by Y3mo** [comment]
The license in the download and on the forum pages says CC-BY-NC-SA-4.0.

**Comment by plague006** [comment]
The current releases were already issued under CC and to the best of my understanding licenses can't be changed retroactively. Will the next release(s) be ARR? Absolutely. But that's not the case for the current releases.

If I'm in error I'll happily read any literature provided.

**Comment by politas** [comment]
There are now a set of new releases, so we may as well unfreeze now and let Bob have his way.

**Comment by plague006** [comment]
I wasn't expecting ARR releases so quickly. I'm incredibly impressed by the speed with which @BobPalmer got the consent and/or re-wrote the contributions of all code contributors made in order to change licensing on all the mods he leads. I mean 49 contributors to MKS alone including our own @Olympic1 who I thought was incommunicado.

At any rate, since a new release was issued and all contributions were either released to, or re-written by @BobPalmer there's no "letting him have his way" he followed all steps to legally change the licenses the mods and the netkans he hosts are now accurate.

**Pull request closed without merging**
