### PR TITLE
Add SpaceX Launch Vehicles

### PR DESCRIPTION
**Pull request by Olympic1**
From Kartoffelkuchen

### CODE REVIEW

**Comment by politas** [comment]
Any idea what that Aerohider.dll is and why it's in GameData rather than a subfolder?

**Comment by politas** [comment]
Forum thread says it requires Old School Fairings

**Comment by politas** [comment]
I want to find out how the barge and landing pad are done. I'm surprised there isn't a KerbalKonstructs dependency

**Comment by Olympic1** [comment]
> Any idea what that Aerohider.dll is
It is required for the aerodynamic behaviour of the fairings.

> Old School Fairings has only pre-release versions
I contacted the author for it already

**Comment by Dazpoet** [comment]
Was an answer ever recieved from the author on this @Olympic1 ?

**Comment by Olympic1** [comment]
Nope, hopefully he will make a full release soon.

**Comment by plague006** [comment]
Going to close this as the oldschool fairings author seems very happy not releasing the mod and SpaceXLaunchVehicles no longer bundles the required .dll.

**Pull request closed without merging**
