### PR TITLE
Fixed Contract Configurator Requirement

### PR DESCRIPTION
**Pull request by pap1723**

### CODE REVIEW

**Comment by DinCahill** [comment]
Is the mod broken without this patch, or is it just clean-up?

**Comment by pap1723** [comment]
It won't install with Contract Configurator through CKAN wihtout the update. It shows as conflicting mods.

**Comment by DinCahill** [comment]
I'm out right now, but I'll look at this later tonight if no one else does.

**Comment by politas** [comment]
Yes, indeed. The highest version released of ContractConfigurator is 1.2.5

**Pull request merged**
