### PR TITLE
Add PAWRangeBuff

### LINKED ISSUE #7874: [Mod] PAWRangeBuff
Mod info
--------
* Mod name: PAWRangeBuff
* Author(s): atomontage
* License: MIT
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/193572-180-19x-pawrangebuff-increase-your-eva-right-click-menu-distance/
* Download: https://github.com/atomontage04/PAWRangeBuff/releases

### PR DESCRIPTION
**Pull request by HebaruSan**
Fixes #7874.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Asked about the extremely broad version file compatibility.

https://forum.kerbalspaceprogram.com/index.php?/topic/193572-any-pawrangebuff-increase-your-eva-right-click-menu-distance/&do=findComment&comment=3780007

**Comment by atomontage04** [comment]
> Asked about the extremely broad version file compatibility.
> 
> https://forum.kerbalspaceprogram.com/index.php?/topic/193572-any-pawrangebuff-increase-your-eva-right-click-menu-distance/&do=findComment&comment=3780007

This has been dealt with (and the .version file PR was also merged).
Thank you again.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Yup, looks good. Thanks for contacting us!

**Pull request merged**
