### PR TITLE
Add Oddiseo

### LINKED ISSUE #8172: [Mod] Oddiseo Corp contracts
Mod info
--------
* Mod name: Oddiseo Corp contracts
* Author(s): Tattie Kerbal
* License:  GPL 3.0
* Homepage: https://github.com/oddiseo-ksp/oddiseo
* Download: https://github.com/oddiseo-ksp/oddiseo

Hi CKAN folks, I've been creating a contract mod and would like to get it added to CKAN so that my friends can install it. I tried to create a `netkan` file myself but didn't have much luck. Would you be able to assist me in getting it into the system?

### PR DESCRIPTION
**Pull request by HebaruSan**
Based on the netkan file in the mod's repo. Note, the repo has no releases, so this won't work at first.

Fixes #8172.

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
@oddiseo-ksp, one note, if you plan to have anyone install this without CKAN (like if you make a forum thread and then post a link to your release), it would be good to put the Oddiseo folder inside the ZIP itself so users can just drag it to their GameData. Currently they would have to create that folder themselves.

**Comment by oddiseo-ksp** [comment]
that's a fair point, I'll restructure it for future releases.

**Comment by HebaruSan** [comment]
Looks like it installs correctly, so I'll go ahead and merge this. Thanks for the submission, and good luck with your mod!

**Comment by oddiseo-ksp** [comment]
Thanks! Should be getting a playtest soon, and will slowly add more and weirder contracts.  :grin:

**Pull request merged**
