### PR TITLE
Add ActiveStruts, IR-ConnectionSystem, CameraController-Next, DockingFunctions, and DockingPort-Next

### PR DESCRIPTION
**Pull request by meirumeiru**
IR-ActiveStruts

- <https://github.com/meirumeiru/IR-Active-Struts>

IR-ConnectionSystem

- <https://github.com/meirumeiru/IR-ConnectionSystem>

CameraController-Next

- <https://github.com/meirumeiru/CameraController-Next>

DockingFunctions

- <https://github.com/meirumeiru/DockingFunctions>

DockingPort-Next

- <https://github.com/meirumeiru/DockingPort-Next>

### CODE REVIEW

**Comment by HebaruSan** [comment]
Several of these repos don't exist, and the remaining ones don't have any release.

**Comment by HebaruSan** [comment]
Asked several follow-up questions on Discord.

**Comment by HebaruSan** [comment]
Results of Discord conversation:

 - These mods won't conflict with the other IR fork
 - IR-ActiveStruts is a standalone mod and so might be renamed to ActiveStruts ("we can do this", so still under consideration?)
 - Forum threads may happen for some, others may share existing threads

**Comment by meirumeiru** [comment]
> * IR-ActiveStruts is a standalone mod and so might be renamed to ActiveStruts ("we can do this", so still under consideration?)

you can rename it

**Comment by HebaruSan** [comment]
https://www.githubstatus.com/

image

**Review by HebaruSan — APPROVED** [review]
Thanks for the submissions! ⚽🥅

**Pull request merged**
