### PR TITLE
VehiclePrefabsReadytoGo

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by politas** [comment]
Should this have a BDArmory dependency? It looks like it should from the screenshots.

**Comment by linuxgurugamer** [comment]
I don't think so, but I'll examine the file this evening.  What I remember is that there is about 130 different models

**Comment by linuxgurugamer** [comment]
I looked at the config files of some of the military planes, and unless I'm missing something, they don't need BDArmory.  
Can someone else please take a look?

**Comment by linuxgurugamer** [comment]
I just saw BahaSP in some of the config files, so I'll get it fixed

**Comment by politas** [comment]
The BahaSP references I can find all look like engine FX files, rather than weaponry.

**Comment by Olympic1** [comment]
BahaSP engine effects depend on`BDAnimationModules`

**Comment by politas** [comment]
@linuxgurugamer, can you add that dependency?

**Comment by linuxgurugamer** [comment]
yes

**Comment by politas** [comment]
Looks all good now. Merging with thanks!

**Pull request merged**
