### PR TITLE
Update CrowdSourcedScience.netkan

### PR DESCRIPTION
**Pull request by DuoDex**

### CODE REVIEW

**Comment by DuoDex** [comment]
A fat lot of good the console does now.

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by hakan42** [comment]
Your latest release ( https://github.com/DuoDex/CrowdSourcedScience/releases ) does not contain any zip files, which we really require to install an addon from. Please fix your release and observe that the netkan-bot will index it.

**Pull request closed without merging**
