### PR TITLE
Add ExtrasolarPlanetsBeyondKerbol from spacedock

### PR DESCRIPTION
**Pull request by ChucklesTheBeard**
closes #3215

### CODE REVIEW

**Comment by Unknown601** [comment]
excellent

**Comment by plague006** [comment]
Needs an install stanza. We might also want to index both `Stock Scale` and `RealisticScale` individually.

**Comment by ChucklesTheBeard** [comment]
Yep, saw the install part. :/ dl'ing so I can look at the file structure

**Comment by plague006** [comment]
Per forum thread:

> Recommended Add-Ons
    64K: This mod scales the Kerbol system to 6.4 times its original size. I highly recommend this mod if you are using the "realistic scale" for Extrasolar.
    Extrasolar Clouds: The is a visual enhancements mod made by me for Environmental Visual Enhancements. It adds clouds to all of the terrestrial planets, and makes them look much better (especially Mir).
    KSP Interstellar Extended: Adds tons of advanced propulsion systems and makes the transfer from the Sun to Valentine a bit quicker.
    BetterTimeWarp: Maybe even a necessity. Adds greater time warp options that really help with making your transfers faster and less boring.
    Project Orion Nuclear Pulse Engine: Adds two very interesting nuclear engines into the game based on Project Orion and Project Medusa.

`KSP-64k`, Extrasolar Clouds we don't seem to index yet, `KSPInterstellarExtended`, `BetterTimeWarp`, `USI-NuclearRockets`

**Comment by plague006** [comment]
64k wants to install an old version of Kopernicus.. hmm for now just remove it as a recommendation and if we can modify 64k's dependency we'll re-add it at a later time. Pinging @Felger: is 64k compatible with newer versions of Kopernicus or should it remain locked?

**Comment by plague006** [comment]
The journey is complete. Merging with my thanks. :D

**Pull request merged**
