### PR TITLE
Grounded - Modular Vehicles mod (by blackheart612)

### PR DESCRIPTION
**Pull request by Blaster84x**

### CODE REVIEW

**Comment by HebaruSan** [comment]
Has the author given permission?

**Comment by Blaster84x** [comment]
No but since CKAN is distributing the original files from SpaceDock, the license allows it. But I'll contact him to see if he's OK with it ;)

**Comment by Blaster84x** [comment]
Here you are:

> >@blackheart612 Can I add this mod to the CKAN? I need it for my meta/modpack... 
>(Also, its netkan file links to SpaceDock so no maintenance required.) It's already in the repos but frozen, name is either Grounded.netkan or Grounded.frozen.

>Do you need to change anything in the files? If not, you can just do as you wish no problem. I'm actually not that familiar with CKAN so I don't know what you need to do. 

(Source: [KSP Forums](https://forum.kerbalspaceprogram.com/index.php?/topic/171377-17x-grounded-modular-vehicles-r50-mining-modules-rotor-emergency-light-jun-5-2019/page/11/))

CKAN is not changing anything, so...

**Comment by HebaruSan** [comment]
Thanks!

**Pull request merged**
