### PR TITLE
TACLS-Config-Stock overrides.

### PR DESCRIPTION
**Pull request by pjf**
OMG I forgot these with the other PR.

### CODE REVIEW

**Comment by dbent** [comment]
Needs a comma.

**Comment by pjf** [comment]
Oh noes! Thank you!

**Comment by pjf** [comment]
It's sure great when I test my code locally. PR updated. :)

**Comment by dbent** [comment]
Breaks on missing dependency with TACLS, which should be fine with the other PR. Merging.

**Pull request merged**
