### PR TITLE
Added ContractConfigurator-RemoteTech.netkan

### PR DESCRIPTION
**Pull request by jrossignol**
:smile:

### CODE REVIEW

**Comment by hakan42** [comment]
Cool :smile:

**Comment by jrossignol** [comment]
Fingers crossed on this last one...   No Kraken, no kraken, no kraken....

**Comment by jrossignol** [comment]
Build failed...  with no identified problems. :unamused: 

@hakan42 , any idea?

**Comment by hakan42** [comment]
Unfortunately, I am not at a computer just now... 

The last thing I see in the log is:

jsonlint -s -v NetKAN/ContractConfigurator-RemoteTech.netkan
NetKAN/ContractConfigurator-RemoteTech.netkan: can not decode value: u': {\n        "home...

Could you upload the netkan to an online json validator (google will point you to one)? 

If you are on a Linux system, you can try to run jsonlint yourself, that is often very informative.

**Comment by hakan42** [comment]
By the way, the pull request build is linked right into the github page of your pr (but I am sure you already knew that :smile: )

**Comment by jrossignol** [comment]
Don't be silly @hakan42 , only a stupid person would upload their file without first running a JSON validator....

**Comment by jrossignol** [comment]
(darn, those last two came in out of order). :grin:

**Comment by hakan42** [comment]
If I had a SRB for every time I had one too many or one too less comma somewhere, I'd be on my way to Mars :smile:

**Comment by hakan42** [comment]
Wow, the first PR I follow all the way  from my mobile :smile:

**Pull request merged**
