### PR TITLE
Fix 'Module contains no files to install.'

### PR DESCRIPTION
**Pull request by techman83**
NetKAN currently broken, this should fix it and continue working if the folder reverts to 'RoboBrakes'.

### CODE REVIEW

**Comment by techman83** [comment]
Ok, that didn't quite do what I expected!

```
Showing 7 installed files:
- GameData/RoboBrakes/RoboBrakes v0.3.1
- GameData/RoboBrakes/RoboBrakes v0.3.1/Config
- GameData/RoboBrakes/RoboBrakes v0.3.1/Config/RoboBrakes_ModuleManagerConfig.cfg
- GameData/RoboBrakes/RoboBrakes v0.3.1/RoboBrakes.dll
- GameData/RoboBrakes/RoboBrakes v0.3.1/Textures
- GameData/RoboBrakes/RoboBrakes v0.3.1/Textures/ToolbarButtonArmed.png
- GameData/RoboBrakes/RoboBrakes v0.3.1/Textures/ToolbarButtonIdle.png
```

@Dazpoet / @plague006 - suggestions?

**Comment by pjf** [comment]
In this case, we can just install to `GameData`, and we'll match what a human would do (`GameData/RoboBrakes v0.3.1/RoboBrakes.dll`, etc).  :)

**Comment by techman83** [comment]
@pjf thanks!

**Comment by techman83** [comment]
That looks a little happier :-)

```
Showing 7 installed files:
- GameData/RoboBrakes v0.3.1
- GameData/RoboBrakes v0.3.1/Config
- GameData/RoboBrakes v0.3.1/Config/RoboBrakes_ModuleManagerConfig.cfg
- GameData/RoboBrakes v0.3.1/RoboBrakes.dll
- GameData/RoboBrakes v0.3.1/Textures
- GameData/RoboBrakes v0.3.1/Textures/ToolbarButtonArmed.png
- GameData/RoboBrakes v0.3.1/Textures/ToolbarButtonIdle.png
```

**Comment by plague006** [comment]
:+1:

**Comment by techman83** [comment]
w00! 
```json
"RoboBrakes":{"last_checked":"2015-09-08T12:21:05Z","last_inflated":"2015-09-08T12:21:07Z","failed":false,"last_error":null,"last_indexed":"2015-09-08T12:21:07Z"}
```

**Pull request merged**
