### PR TITLE
Add B9 Aero HL, S2, S3 Space Plane Repack 1.0.X from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of AnitaBlast, to add [B9 Aero HL, S2, S3 Space Plane Repack 1.0.X](https://kerbalstuff.com/mod/783/B9%20Aero%20HL%2C%20S2%2C%20S3%20Space%20Plane%20Repack%201.0.X) to CKAN.

Please direct questions about this pull request to [AnitaBlast](https://kerbalstuff.com/profile/AnitaBlast).

### CODE REVIEW

**Comment by Dazpoet** [comment]
Seems like an unofficial repack? No license and it seems the person adding the mod also don't know what license to add so I'll close this and wait for the real B9 release for now.

**Comment by ANitaBlast** [comment]
Hey that was me. My bad.. I'm a rookie and i just wanted to share that cargo bay tail.. But what if i do the whole mod and leave everything alone except for changing the attachment nodes 
and making the "incompatible mod version" notification go away, and I'll even organize the parts.. Plus I will put the original authors so they can edit it. and we can name it as Un-official [1.0] B9 Aerospace | Release 5.3.0 (updated X.X.15) ? So can we? I'm willing to update the code. Only Because Im Half way  done it

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://drjanefitch.com/dare.php?u65>

 

blue@blu3wolf.com

**Comment by Blu3wolf** [comment]
Hello!

 

New message, please read <http://nentnent.com/rest.php?y>

 

blue@blu3wolf.com

**Comment by politas** [comment]
That sounds like a good idea, @AnitaBlast . Make sure you check the license B9 Aero is released under. If you are allowed to make a derivative package, it is most likely that you will need to release it under the same license, and KSP rules for mods (at least on the forums) is that they must have a clear license. It would be best if you mad a post in the Add-Ons section of the KSP forums and set that as the homepage, so that people can contact you about it, and you can explain why you've forked B9 Aerospace, and whether the fork will continue as it's own entity or is a temporary thing to fill the gap.

bac9 has built up a lot of trust and loyalty, and you'll need to address that if you want users to put their trust in you, instead.

**Comment by Blu3wolf** [comment]
Hey,
Here are some useful links that I've chosen just for you, check it out <http://zybysanti.bflacc.com/tall.php?6ob0t>

Best regards, blue@blu3wolf.com

**Pull request closed without merging**
