### PR TITLE
Add patch for Antennarange mod to Pathfinder

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Initial release

### CODE REVIEW

**Comment by Olympic1** [comment]
Same as I mentioned in #2350

**Comment by plague006** [comment]
Will merge once `"file"       : "GameData/Pathfinder",` is changed to `"find"       : "Pathfinder",` (which will allow netkan to better adapt to any archive structure changes)

**Comment by plague006** [comment]
Ready for merge once `"file"       : "GameData/Pathfinder",` is changed to `"find"       : "Pathfinder",`

**Comment by linuxgurugamer** [comment]
Closes #2351

**Comment by linuxgurugamer** [comment]
When I had it that way, it failed the Jenkins check

JBB

**Comment by linuxgurugamer** [comment]
Per your request, I changed it back, and it is now failing the Jenkins check

**Comment by plague006** [comment]
Merging with my thanks.

**Pull request merged**
