### PR TITLE
Add SSPX IVAs

### PR DESCRIPTION
**Pull request by ChrisAdderley**
Adds a new mod. This shouldn't be merged until the netkan file in the repository dev branch has been merged to master

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
This should be mergeable now assuming the check passes.

**Comment by HebaruSan** [comment]
Do you want StationPartsExpansionRedux to recommend or suggest this? I would think it would be nice to see the option while installing the parts.

**Comment by HebaruSan** [comment]
Thanks for the submission, looks good to me.

**Comment by ChrisAdderley** [comment]
Thanks!

**Pull request merged**
