### PR TITLE
Add B9 Aerospace HX and Legacy

### PR DESCRIPTION
**Pull request by blowfishpro**

### CODE REVIEW

**Comment by Olympic1** [comment]
Remove the `name` and `release_status` as this will be taken from KS, change the `spec_version` to `1`. If you want you can add yourself to the `author` (optional).

For both files

**Comment by blowfishpro** [comment]
Will do (when I get home).  Is there documentation on what the different spec versions mean somewhere?

**Comment by Olympic1** [comment]
I use the [Spec.md](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md) to see which `spec_version` the file needs.

**Comment by blowfishpro** [comment]
Fixed.

**Comment by Olympic1** [comment]
Merging with my thanks

**Pull request merged**
