### PR TITLE
Add kOS-Astrogator.netkan

### PR DESCRIPTION
**Pull request by markjfisher**
A kOS addon to Astrogator

___

ckan compat add 1.11

### CODE REVIEW

**Comment by HebaruSan** [comment]
You can see the output of the validation scripts here:

https://github.com/KSP-CKAN/NetKAN/actions/runs/3153340680/jobs/5129731016

The most useful part is usually the list of installed files, which looks OK to me:

```
  Showing 8 installed files:
    - GameData/kOS-Astrogator
    - GameData/kOS-Astrogator/kOS-Astrogator-Changelog.cfg
    - GameData/kOS-Astrogator/kOS-Astrogator.netkan
    - GameData/kOS-Astrogator/kOS-Astrogator.version
    - GameData/kOS-Astrogator/LICENSE
    - GameData/kOS-Astrogator/Plugins
    - GameData/kOS-Astrogator/Plugins/kOS-Astrogator.dll
    - GameData/kOS-Astrogator/README.md
```

I added a compatibility override to the PR body to enable KSP 1.11, which your users will also have to do to install since kOS hasn't been marked compatible with KSP 1.12 yet:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by HebaruSan** [comment]
I guess technically you don't need to install the .netkan file into GameData. That's purely a CKAN bot infrastructure thing. Astrogator has an "internal" .ckan file to auto-import its values into the metadata, but .netkans don't do that.

**Review by HebaruSan — APPROVED** [review]
Looks good to me, thanks for the submission!

**Comment by markjfisher** [comment]
Wow, thanks for massaging this so it works. I copied a netkan file from another mod and adjusted it, hence the json style rather than yaml. I was driving a bit blind, but I now see the mod in ckan so 🎉

**Pull request merged**
