### PR TITLE
Add SpaceLaunchSystemStockDimension from Spacedock

### PR DESCRIPTION
**Pull request by politas**
Replaces #4085

### CODE REVIEW

**Comment by politas** [comment]
SpaceLaunchSystemPartPack also needs some attention, if my reading of the forum post is correct. I've approached the author.

**Comment by techman83** [comment]
LGTM, merging with thanks!

**Comment by plague006** [comment]
If I'm understanding properly, this is the version to install for stock KSP while `SpaceLaunchSystemPartPack` will be for RO? "Stock dimension" = stock version of the game?

I think we'll want to install the VAB folder, we'll also want to conflict `SpaceLaunchSystemPartPack`, and if I'm correct that this is for the stock version maybe change the ID to `SpaceLaunchSystemPartPack-stock` or something similar.

**Comment by politas** [comment]
I was thinking of maybe overriding the name on the PartPack version, but I've got to work out what the deal is, first. Like I said, I've approached the author. It sounds like the PartPack is for either RealismOverhaul (which may actually mean RSS) _or_ Stock. I have a suspicion that it may be broken as we currently have it.

**Comment by politas** [comment]
To get the RealismOverhaul version, apparently you need to install a bunch of files from a Dropbox folder. I don't think we have any way to set that up.

**Comment by politas** [comment]
Without fully understanding what the author means by "Stock Dimension", I'm leaving it as is. Feel free to hold off on merging while I keep trying to get info from Sobol.

**Comment by plague006** [comment]
If/when you get confirmation that stock dimension = stock aero model and stock Kerbin then this is ready to merge in my book.

**Comment by politas** [comment]
OK, I'm going to merge this, because I'm fairly certain that this one will work fine, and it's PartPack we need to fix up.

**Pull request merged**
