### PR TITLE
Update NoCrewRequirementContinued.netkan, create Overdrive.netkan

### PR DESCRIPTION
**Pull request by Real-Gecko**
- Added Orbinaut to authors array as he is the initial creator
- Made mod KSP version independent as it relies on MM
- Added Module Manager to dependencies
- Added RadioFreeKerbin to recommended

### CODE REVIEW

**Comment by Real-Gecko** [comment]
Also added Overdrive.netkan

**Comment by Dazpoet** [comment]
seeing as both mods are on spacedock you probably want to use kref's instead so we can autoindex them and you won't have to update these files everytime a new version is released

**Comment by Real-Gecko** [comment]
"Spacedock.info -> CKAN" integration is not quite good IMO, it always offers licenses not matching CKAN specification(#4941, #4118), I cannot add additional authors not registered on SD, I cannot add dependencies and recomendations, I cannot set KSP version to 'any' as I did for NoCrewRequirementContinued (it depends on MM mostly, MM works - NCRC works).
So I think I'll manage things manually until SD - CKAN relations are improved :)

**Comment by Real-Gecko** [comment]
By the way: can you, please, clarify [this section](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ckangithubuserrepoasset_matchfilter_regexp) of CKAN spec?
Maybe I can create something that will work automatically from each of my mod repos?

**Comment by Dazpoet** [comment]
That part of the spec is doing pretty much the same thing as the pointer towards SpaceDock but it points towards github instead and require you to input a few more fields manually. I'm pretty sure it'll still only grab one author though and that the author will be the one who made the release.

We also have the option of so-called metanetkans where you point a .netkan file in our repository towards a .netkan file in your own repository. This is e.g. done by [`RealismOverhaul`](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/RealismOverhaul.netkan) which points to [their own .netkan](https://raw.githubusercontent.com/KSP-RO/RealismOverhaul/master/RealismOverhaul.netkan) which just happens to be an example of a .netkan file pointing towards a github repository and it creates a [.ckan file](https://github.com/KSP-CKAN/CKAN-meta/blob/master/RealismOverhaul/RealismOverhaul-v11.3.2.ckan) through our indexer. Some modders even create [their own .netkan repositories](https://github.com/BobPalmer/CKAN) after pointing all their mods towards files outside of our repository.

As for the SpaceDock integration and it filling out fields incorrectly, any field you add manually to a .netkan file pointing towards SpaceDock (or github, or any other source we can index from) will overwrite anything the indexer fetches. Say you e.g. want `"ksp_version" : "any"` for NCRC, you add that to the current .netkan file and it'll overwrite anything it fetches from spacedock. Same with the `author` field.

To get your desired results for NCRC you could basically add this to the end of its current .netkan file and it should generate just the way you want it to.
```
"author": [ "RealGecko", "Orbinaut" ],
"ksp_version" : "any",
"depends": [
         {
             "name": "ModuleManager"
         }
     ],
     "recommends": [
         {
             "name": "RadioFreeKerbin"
         }
    ]
```
Being the author of these mods you're obviously free to do as you like, I'm just trying to bring out an alternative which hopefully will give you less headaches.

**Comment by Real-Gecko** [comment]
So after initial SD commit merged I can provide PR to make resulting .netkan file look like this?
```JSON
{
    "$kref": "#/ckan/spacedock/715",
    "spec_version": "v1.4",
    "identifier": "NoCrewRequirementContinued",
    "x_via": "Automated SpaceDock CKAN submission",
    "license": "GPL-3.0",
    "author": [ "RealGecko", "Orbinaut" ],
    "ksp_version" : "any",
    "depends": [
         {
             "name": "ModuleManager"
         }
     ],
     "recommends": [
         {
             "name": "RadioFreeKerbin"
         }
    ]
}
```
And what happens when I update mod on SD? Won't it overwrite my changes, for example version?

**Comment by Dazpoet** [comment]
I just ran what you posted through NetKAN and it generates this .ckan file
```
{
    "spec_version": "v1.4",
    "identifier": "NoCrewRequirementContinued",
    "name": "No Crew Requirement Continued",
    "abstract": "A simple ModuleManager plugin that eliminates crew requirements for manned vessels and/or the need to attach an unmanned probe to your spacecraft. Useful for automatic launches and docking of space station modules, rescue missions etc. Requires ModuleManager.",
    "author": [
        "RealGecko",
        "Orbinaut"
    ],
    "license": "GPL-3.0",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/140244-no-crew-requirement-continued/",
        "spacedock": "https://spacedock.info/mod/715/No%20Crew%20Requirement%20Continued",
        "repository": "https://github.com/Real-Gecko/NoCrewRequirementContinued",
        "x_screenshot": "https://spacedock.info/content/RealGecko_4471/No_Crew_Requirement_Continued/No_Crew_Requirement_Continued-1476298187.5482783.png"
    },
    "version": "1.0.2",
    "ksp_version": "any",
    "depends": [
        {
            "name": "ModuleManager"
        }
    ],
    "recommends": [
        {
            "name": "RadioFreeKerbin"
        }
    ],
    "download": "https://spacedock.info/mod/715/No%20Crew%20Requirement%20Continued/download/1.0.2",
    "download_size": 1285,
    "download_hash": {
        "sha1": "6082B8972C8AB944391CC2B072FF01948026ABC6",
        "sha256": "24F11B6C68A3885EB67DD944830B3588419AEC573DE9CBB8697764C5BEF4994A"
    },
    "download_content_type": "application/zip",
    "x_via": "Automated SpaceDock CKAN submission",
    "x_generated_by": "netkan"
}
```

I think I understand your confusion now. When you update the mod on SpaceDock we don't change the .netkan file. Rather the .netkan file is the directions for how our indexing bot will handle new releases it finds on spacedock and the .netkan file is always prioritized over whatever it finds on SpaceDock. So when/if you release a new version of NCRC our bot will go like this 

"Yay new version! Better check the .netkan file to see how I'm supposed to handle that. Oh the .netkan file says this works on every version of ksp, I'll just overwrite this information I got from SpaceDock then."

and after that it generates a .ckan file based on the directions and places it in [CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta) which is the place the client looks for mods.

I hope that made it a bit clearer? I'm trying to be comprehensive but I know I sometimes fail miserably :)

**Comment by Real-Gecko** [comment]
OK, now I see. So, I'll make .netkan files look like this:
```JSON
{
    "$kref": "#/ckan/spacedock/715",
    "spec_version": "v1.4",
    "identifier": "NoCrewRequirementContinued",
    "x_via": "Automated SpaceDock CKAN submission",
    "license": "GPL-3.0",
    "author": [ "RealGecko", "Orbinaut" ],
    "ksp_version" : "any",
    "depends": [
         {
             "name": "ModuleManager"
         }
     ],
     "recommends": [
         {
             "name": "RadioFreeKerbin"
         }
    ]
}
```
```JSON
{
    "x_via": "Automated SpaceDock CKAN submission",
    "license": "BSD-3-clause",
    "identifier": "Overdrive",
    "$kref": "#/ckan/spacedock/1063",
    "spec_version": "v1.4"
}
```
This BSD license issue freaked me out :D
SD does not have correct value compatible with CKAN spec:
screenshot_20161116_174925

**Comment by Real-Gecko** [comment]
OK, looks like everything is fine at last :)

**Comment by Dazpoet** [comment]
I will merge this then and if something doesn't work as you want it to we will obviously fix that.

The new netkan file for NCRC will also ensure that our .ckan file for it in CKAN-meta is updated to properly reflect that it works on all ksp versions and not just 1.2.1 the next time the bot is ran.

**Comment by Dazpoet** [comment]
And here they are now, [Overdrive has been added](https://github.com/KSP-CKAN/CKAN-meta/commit/344236f7e838b5693b81eebdd6370e1b423310f8) and [NCRC has been updated to reflect the changes](https://github.com/KSP-CKAN/CKAN-meta/commit/867d9779ea3caef6a878f9d723cb25dc555ce26c)

**Comment by Real-Gecko** [comment]
Oh, man! Thanks a lot! Now everything is cool :)

**Pull request merged**
