### PR TITLE
Standardises tabs, adds KSP-AVC reference.

### PR DESCRIPTION
**Pull request by SkyMarshal**

### CODE REVIEW

**Comment by SkyMarshal** [comment]
Oh, bluh, bad KSP-AVC file.  Let me see about opening a PR there to fix it.

**Comment by SkyMarshal** [comment]
I have a fix pending at severedsolo/KerbinSpaceStation#36

**Comment by Dazpoet** [comment]
Just give this thing another poke when it's done :)

**Comment by SkyMarshal** [comment]
Will do.  Have you set up a means to trigger a rebuild from the github comments?  (If so, is it restricted to repository maintainers/whatnot?)

**Comment by SkyMarshal** [comment]
Fantastic, thanks.

**Comment by SkyMarshal** [comment]
Rebuild.

**Comment by SkyMarshal** [comment]
#rebuild

**Comment by SkyMarshal** [comment]
...It's still seeing the outdated file, for some reason.

**Comment by SkyMarshal** [comment]
Ooooh, damn.  It's grabbing the outdated version from the actual release and not the repository.

**Comment by severedsolo** [comment]
Give me a second - I'll fix it.

**Comment by SkyMarshal** [comment]
Oh, thanks.

**Comment by severedsolo** [comment]
#rebuild

**Comment by severedsolo** [comment]
Tada

**Comment by SkyMarshal** [comment]
I've literally no idea what you did, so I will just assume black magic and start a new religion.  (Thanks!)

**Pull request merged**
