### PR TITLE
Add KerbalPlanetaryExpansion

### PR DESCRIPTION
**Pull request by plague006**
Created as a branch of the repo to allow others to edit if needed and delete once merged.

### CODE REVIEW

**Comment by plague006** [comment]
@Olympic1 would love your input on any conflicts in this pack.

**Comment by Olympic1** [comment]
I didn't knew this pack was released, I'll need to test it first

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN-meta/issues/588

**Comment by Olympic1** [comment]
Removed from KS

**Pull request closed without merging**
