### PR TITLE
Recommendation of DynamicBattery Storage

### PR DESCRIPTION
**Pull request by blackliner**
cleaned up and added DynamicBatteryStorage as a recommended mod, because i did some changes to support it

### CODE REVIEW

**Comment by blackliner** [comment]
what's wrong?

**Comment by Dazpoet** [comment]
I ran it through NetKAN locally with -debug flag set and it seems to get stuck on the parsing of the .version file. A guess would be that it is confused by the lack of a KSP_VERSION_MAX when a KSP_VERSION_MIN exists.

I don't recall exactly how the avc-parsing is done but I'm sure @zengei knows seeing as they wrote it.

**Comment by blackliner** [comment]
I didn't change that part, that's funny...

**Comment by blackliner** [comment]
I think i fixed it, how to run checks again?

**Comment by techman83** [comment]
#rebuild

**Comment by techman83** [comment]
LGTM, merging with thanks!

**Comment by blackliner** [comment]
Awesome, thanks! It seems I forgot the PATCH variable for KSP_VERSION, but that's something the parser could handle IMHO...

**Comment by techman83** [comment]
Patches welcome :slightly_smiling_face:

**Comment by blackliner** [comment]
Okidoki ;-)

**Pull request merged**
