### PR TITLE
Custom Asteroids only works till KSP 0.90

### PR DESCRIPTION
**Pull request by Olympic1**

### CODE REVIEW

**Comment by plague006** [comment]
As users reported having no significant issues with this mod in 1.0.4 I'm not inclined to reduce its compatibility beyond that ksp version.

**Comment by Olympic1** [comment]
Well the author told me it didn't work anymore since 1.0.x, this also is said on the [forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/72785-custom-asteroids-returning-soon/) of the mod:

`UPDATE: I am back, and eager to resume work on Custom Asteroids. The mod is NOT KSP 1.0 compatible at the moment; I'll remove this message when a new version is ready.`

**Comment by plague006** [comment]
Yeah I read what he wrote. I also read what users previously wrote and they report no significant issues up to 1.0.4. Our duty first is to end-users and if they're reporting a mod works we're doing them a disservice to disallow them access to it.

**Comment by Olympic1** [comment]
Ok, I restricted it to 1.0.4. I also saw that @Starstrider42 has made a 1.0.5 pre-release, so expecting a release soon

**Comment by plague006** [comment]
:+1:

**Pull request merged**
