### PR TITLE
Remove quotes for boolean values in VersatileToolboxSystem

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Jenkins probably should have caught that.. @techman83 ref https://github.com/KSP-CKAN/NetKAN/pull/3245

**Comment by Olympic1** [comment]
I could build the files with the quotes succesfully using `netkan.exe`.

**Comment by plague006** [comment]
@Olympic1 yep, netkan doesn't have the issue, ckan.exe does (which is why it failed netkan-bot's indexing with "Schema validation failed")

**Comment by techman83** [comment]
@plague006 Ahh, we're assuming that the netkan is producing valid data during testing, but the indexer doesn't want to auto-commit invalid data, so it does a sanity test.

**Pull request merged**
