### PR TITLE
Git3

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Updated all netkans for LGG's mods to use github as the source, this to work around the issue with CKAN and Spacedock not honoring the .version file as expected

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Error doesn't make sense, it is now erroring on the first when previously it got past it.
I'll wait a bit and try again

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
@HebaruSan any reason #rebuild isn't working?  And any idea why the last build failed?

**Comment by DasSkelett** [comment]
> 1708 [1] FATAL CKAN.NetKAN.Program (null) - libcurl

We tend to get that either when our CI is DOSed because of too many netkans to check in a short time (i.e. AWS credits empty), or when GitHub decides to block us due to too many requests.

**Comment by HebaruSan** [comment]
Noting how to add AFBW for future reference:

https://github.com/KSP-CKAN/NetKAN/pull/7727/commits/4797fdc2fa3b92157a6905beff86ab8d56b88d97

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
I'll have to revert the AIES patch files and submit it later

**Pull request merged**
