### PR TITLE
Add BDArmory DMP Mod from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of jediminer543, to add [BDArmory DMP Mod](https://spacedock.info/mod/253/BDArmory%20DMP%20Mod) to CKAN.

Please direct questions about this pull request to [jediminer543](https://spacedock.info/profile/jediminer543).

### CODE REVIEW

**Comment by plague006** [comment]
Same issue as in https://github.com/KSP-CKAN/NetKAN/pull/2026 -- This mod doesn't follow a versioning scheme that is compatible with CKAN (git commit hashes are being used as version numbers).

**Comment by jediminer543** [comment]
@plague006 Working on 1.0.5 version, will use Change versioning system then, likley to Semantic Versioning, sorry for inconvenience.

**Comment by jediminer543** [comment]
@plague006 Updated to use new versioning, which should be compatiable. Is this reopenable?

**Comment by politas** [comment]
I think this is ready to merge, now.

**Comment by plague006** [comment]
If you're going to have this mod provide `BDArmory` rather than split it, you should list BD's more restrictive license.

**Comment by politas** [comment]
How is CC-BY-SA more restrictive than MIT? MIT requires the copyright notice be retained (BY) and that the licence be retained (SA). Seems functionally equivalent to me.

**Comment by plague006** [comment]
I'm not sure why you're bringing up the MIT license. This mod is under CC0 on both the spacedock page and ksp forum thread.

**Comment by politas** [comment]
Modders changing licenses, grumble, grumble.

**Comment by plague006** [comment]
As much as I wanna be on your side @politas.. it's been CC0 since at least [Aug 2, 2015](https://github.com/KSP-CKAN/NetKAN/pull/2026). -_-

**Comment by politas** [comment]
BDArmory is CC-BY-SA-2.0, though. I can't see now where I got MIT from.

**Comment by politas** [comment]
No, I'm not going crazy, it was MIT on Spacedock originally: https://github.com/KSP-CKAN/NetKAN/commit/fe0253f11d1744da318b77fc7a38d4226d995eb7

**Pull request merged**
