### PR TITLE
Add HotRockets Fireworks pack from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of nazari, to add [HotRockets Fireworks pack](https://kerbalstuff.com/mod/972/HotRockets%20Fireworks%20pack) to CKAN.

Please direct questions about this pull request to [nazari](https://kerbalstuff.com/profile/nazari).

### CODE REVIEW

**Comment by plague006** [comment]
Installs some files to MP_Nazari (ie. HotRockets) and some files to SmokeScreen. Need to check if the mod relies on overwriting files, or if it's just adding files.

**Comment by plague006** [comment]
The smokescreen folder is a standard SmokeScreen-2.6.3.0 install. This adds some files to the MP_Nazari folder and overwrites MP_Nazari/FX/flameparticle1.png

**Comment by Nazari1382** [comment]
use this please https://github.com/KSP-CKAN/NetKAN/pull/1829

**Comment by dbent** [comment]
Closing in favor of #1829

**Pull request closed without merging**
