### PR TITLE
2KASJ0523Planetarysystem.netkan

### PR DESCRIPTION
**Pull request by linuxgurugamer**
closes #4265

### CODE REVIEW

**Comment by politas** [comment]
Hmm. I thought we'd changed that "No starting with a number" test. @techman83?

**Comment by techman83** [comment]
We might have done in the testing library, but the schema regex doesn't allow it.
```
^[A-Za-z][A-Za-z0-9-]*$
```
Changing it to this will allow it to start with anything alpha-numeric:
```
^[A-Za-z0-9-]*$
```

**Comment by politas** [comment]
Ok, the schema is now in sync with the spec. @linuxgurugamer , can you strip the leading "a" from the filename and identifier?

**Comment by politas** [comment]
Looks good to me. Glad the schema change worked! Merging with thanks!

**Pull request merged**
