### PR TITLE
Add Graphics Enhancements Assembly from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of ArtemKerman, to add [Graphics Enhancements Assembly](https://spacedock.info/mod/1461/Graphics%20Enhancements%20Assembly) to CKAN.

Mod details:
    name = /mod/1461/Graphics%20Enhancements%20Assembly
    author = ArtemKerman
    abstract = So, what's parts Included in the GEA? Clouds at all atmospheric bodies (Eve, Kerbin, Duna, Jool, Laythe), the glow of the planets, sandstorms on Duna, modified form of the flame , and much more...
    license = CC-BY-NC-SA-4.0
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/161683-ksp-130-graphics-enhancements-assembly-gea/
    description = **So, what's parts Included in the GEA?** Clouds at all atmospheric bodies (Eve, Kerbin, Duna, Jool, Laythe), the glow of the planets, sandstorms on Duna, modified form of the flame and much more...

Please direct questions about this pull request to [ArtemKerman](https://spacedock.info/profile/ArtemKerman).

### CODE REVIEW

**Comment by HebaruSan** [comment]
A comment two years older than the PR, errors about `find_matching_files` for a netkan that doesn't even have an install stanza... something weird is going on here.

**Comment by Galileo88** [comment]
queue X-files theme music....

**Comment by politas** [comment]
I think the author has re-released in some way and it's reactivated this old PR rather than create a new one. This mod has been plagued with license controversy and apparently bundles specific versions of other mods rather than having clear dependencies. In my head, I'm putting it in the same category as Renaissance Compilation, ie, not really compatible with the CKAN system.

**Comment by HebaruSan** [comment]
> I'm putting it in the same category as Renaissance Compilation, ie, not really compatible with the CKAN system.

Having taken a look in that download, I concur. We could try to install the GEATerrain folder, but with all those bundled folders there are probably more customizations distributed throughout that can't as easily be cherry-picked. And that's ignoring the license issues.

Closing as non-viable. ArtemKerman, if you're reading this and you still want this mod included in CKAN, we can take another look if you create a release can be installed alongside independently downloaded copies of the dependencies. The easiest way to accomplish that is probably ModuleManager patches, take a look at other planet packs or visual packs to see how it's done.

**Comment by Olympic1** [comment]
The uploader name in this PR is incorrect, the uploader has changed ownership to @DavianLin.
[Forum Thread](http://forum.kerbalspaceprogram.com/index.php?/topic/161683-ksp-130-graphics-enhancements-assembly-gea/)

**Comment by HebaruSan** [comment]
It looks like that reflects one person with a changed account name rather than changing ownership:

image

https://forum.kerbalspaceprogram.com/index.php?/topic/161683-171-graphics-enhancements-assembly-gea/&do=findComment&comment=3120870

**Pull request closed without merging**
