### PR TITLE
Epoch ChakaMonkey to make room for fixes

### PR DESCRIPTION
**Pull request by HebaruSan**
With apologies to our Aussie teammates, "That's not a chaotically versioned mod; ***this*** is a chaotically versioned mod":

image

Properly epoching this would make a good college admissions or job interview question. Try it yourself before checking out my answer:

<details><summary>My plan for epoching ChakaMonkey</summary>

- 3:Chaka_Monkey_161_B
- 3:1.4.3.a
- 2:Chaka_143
- 1:Chaka_Monkey_Evolution_1.3.1_X
- 1:1.3_X
- 1:1.3_Collectors_Edition
- Chaka_Monkey_Exploration_Systems_1.2.2.X
- Chaka_Monkey_Exploration_Systems_1.2.2
- Chaka_Monkey_Exploration_Systems_1.1.3
- 1.1_BETA

</details>

ckan compat add 1.4 1.5

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
The validation error already exists without this PR:

```
$ ./ckan.exe install ChakaMonkeyExplorationSystems=Chaka_Monkey_161_B

Unhandled Exception: CKAN.ModuleNotFoundKraken: Module not found: ChakaMonkeyExplorationSystems=Chaka_Monkey_161_B
   at CKAN.Registry.LatestAvailable(String module, KspVersionCriteria ksp_version, RelationshipDescriptor relationship_descriptor)
   at CKAN.CmdLine.Install.<>c__DisplayClass7_0.<RunCommand>b__0(String id)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.CmdLine.Install.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, KSPManager manager)
   at CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by techman83** [comment]
crocodiledundee

**Pull request merged**
