### PR TITLE
Added Pathfinder.netkan at authors request

### PR DESCRIPTION
**Pull request by linuxgurugamer**
This replaces the file from kerbalstuff.com

### CODE REVIEW

**Comment by Dazpoet** [comment]
What is your solution to https://github.com/KSP-CKAN/NetKAN/pull/1637#issuecomment-113871255 ?

**Comment by linuxgurugamer** [comment]
I'm not sure it's my place to say, since I only helped on #1638, but 
here is my suggestion:

Since Netkan itself suggested the following:

#   Failed test 'DeepSpaceExplorationVessels license (CC-BY-NC SA 4.0) should match spec. Set `x_netkan_license_ok` to supress.'
#   at t/metadata.t line 44.
# Looks like you failed 1 test of 3951.

I would take the approach that, if there is a license, even if not 
recognized, to try recompiling it with the x_netkan_license_ok option 
set to see if there are any other errors.  If it does compile the second 
time, send a warning but accept it.

I've essentially given up on kerbalstuff being able to properly create a 
netkan file, since there are too many ways for it to mess up.



LGG

**Comment by Dazpoet** [comment]
I meant the fact that they share files between them so we might need a third Core mod or Shared Assets, or both :)

**Comment by linuxgurugamer** [comment]
Oh.

I didn't realize that.

Ok.  So how about this:

Release the Pathfinder netkan that I wrote for now.  I'll contact the 
author, and will get a new one set up as a dependency of these two.

I'll suggest to him the following, similiar to what I did for Spacetux:

Create a WildBlueIndustriesSA mod, containing the following:
     1.  Agencies
     2.  The WildBlueTools.dll

Once this is done, then:

1.  Write a netkan for the SA mod
2.  Upload both updated mods to kerbalstuff
3.  Modify the Pathfinder netkan to add this as a dependency
4.  Write a netkan file for the Deep Space Exploration Vessels

Sounds good?


JBB

**Comment by pjf** [comment]
We have a WildBlueTools as a separate release now! So our dependencies are straightforward, and hopefully we can integrate them all at the same time. :)

**Comment by dbent** [comment]
Closed in favor of #1747

**Pull request closed without merging**
