### PR TITLE
Closes #5326 TACLS install options

### LINKED ISSUE #5326: TACLS install options
Before the TACLS update for KSP 1.2 the life support settings were not accessible via Module Manager, so CKAN used the "multi-choice" system to allow the user to select between the stock and the RO config. Now, it uses a global config (that can be modified via MM), meaning that this system is not needed now (RO has updated it's own configs for this change).

* TACLS commit: https://github.com/KSP-RO/TacLifeSupport/commit/1b301ea7ff36346fbbed051c748a819ecedb2491
* RO TACLS config: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_RecommendedMods/TACLS/RO_TACLS_TacLifeSupportCfg.cfg
* Original stock TACLS NetKAN: https://github.com/KSP-CKAN/NetKAN/blob/00b0fd7c4e33f3345230ae4e2735673b37b96a15/NetKAN/TACLS-Config-Stock.netkan
* RO TACLS NetKAN: https://github.com/KSP-CKAN/NetKAN/blob/ada4f8324490724f517801fdd0bf2432612cf9bf/NetKAN/TACLS-Config-RealismOverhaul.netkan

### PR DESCRIPTION
**Pull request by benjwgarner**
Currently, MiniAVC is displayed in CKAN with the name "KSP AVC" and is a few patch version numbers behind. KSP-AVC also has the name "KSP AVC" according to the .netkan and .ckan files, but does not appear in the list (or, at least, I can't get it to show up without manually installing from a .ckan file with its identifier. Sometimes mods like to play hide-and-seek in the CKAN listing).

### CODE REVIEW

**Comment by benjwgarner** [comment]
Oops, I forgot to use two separate branches. Commits[ 2446e7a](https://github.com/KSP-CKAN/NetKAN/pull/5330/commits/2446e7a2d810f65e6c2ad5b52c3b3626875cc9ee), [bef39a7](https://github.com/KSP-CKAN/NetKAN/pull/5330/commits/bef39a7820c65d3d72638c55b3c49b5030e746c3), and [7ae0da0](https://github.com/KSP-CKAN/NetKAN/pull/5330/commits/7ae0da0a331b91dd65bc497b986d52ca447c8667) were in regards to https://github.com/KSP-CKAN/NetKAN/issues/5326 and should have been included in a separate pull request.

**Comment by politas** [comment]
I thought MiniAVC was always included in the mod folders?

**Comment by linuxgurugamer** [comment]
I don't understand why this is here

**Comment by politas** [comment]
No, it shouldn't be. The .frozen file is there just to stop people adding it. MniAVC is not a separate mod. I'll delete the bad entry.

**Comment by politas** [comment]
@benjwgarner , can you either pull the MinAVC changes out of this and repurpose the Pull Request for just the TACLS changes, or create a new PR for the TACLS changes?

**Comment by benjwgarner** [comment]
@politas Done, now it's just the TACLS changes.  @linuxgurugamer I'm not sure why MiniAVC was in there, but I was hesitant to delete it since it still had several versions in **CKAN-meta**.

**Comment by politas** [comment]
Thanks, @benjwgarner ! I think I've purged all the MiniAVC releases from CKAN-meta now. If you see any more, please let me know. Merging with thanks!

**Comment by benjwgarner** [comment]
@politas Glad to help, will do.

**Pull request merged**
