### PR TITLE
Warpdrive

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by HebaruSan** [comment]
The server is a bit overloaded from a flood of PRs we had earlier today, I'll see if I can cancel them...

**Comment by HebaruSan** [comment]
... I don't think I have access.
@techman83, the server says "Jenkins is going to shut down. No further builds will be performed." Is it  stuck?

image

**Comment by linuxgurugamer** [comment]
> ... I don't think I have access.
> @techman83, the server says "Jenkins is going to shut down. No further builds will be performed." Is it stuck?
> 
> image

Whoever has access needs to restart Jenkins

**Comment by HebaruSan** [comment]
`abstract` is missing

```
Running NetKAN for NetKAN/WarpDrive.netkan
6095 [1] FATAL CKAN.NetKAN.Program (null) - Schema validation failed: #/abstract: PropertyRequired
Build step 'Execute shell' marked build as failure
```

**Comment by linuxgurugamer** [comment]
> `abstract` is missing
> 
> ```
> Running NetKAN for NetKAN/WarpDrive.netkan
> 6095 [1] FATAL CKAN.NetKAN.Program (null) - Schema validation failed: #/abstract: PropertyRequired
> Build step 'Execute shell' marked build as failure
> ```

I know, but it was too late last night to do anything.
I'm fixing it now

**Pull request merged**
