### PR TITLE
Add BlackRibbon

### LINKED ISSUE #3075: Add mod to CKAN
HI... So I tried making the netkan file myself, but it kept exploding in my face while trying to make the .ckan file with netkan... So if y'all would be so kind as to add my add-on to ckan for me...

Github repo: https://github.com/Shuudoushi/BlackRibbon/tree/master
Name: `BlackRibbon`
Requires: `BDArmory`
Desc: `This is an add-on for BDArmory. It adds new weapons and parts.`

Thanks in advance, and sorry for being a pain...

### PR DESCRIPTION
**Pull request by Olympic1**
Closes #3075

### CODE REVIEW

**Comment by Olympic1** [comment]
Waiting untill KS gets back up

**Comment by Shuudoushi** [comment]
Well then... Speaking of KS... @Olympic1 https://kerbalstuff.com/

**Comment by Olympic1** [comment]
I know, just read it

**Comment by plague006** [comment]
Jenkins test shows the JSON is valid, tested manually with depends removed. Looks good, merging with my thanks.

````
\---BlackRibbon
    |   License.txt
    |   
    +---Agencies
    |       Agents.cfg
    |       BlackRibbon.dds
    |       BlackRibbon_scaled.truecolor
    |       
    +---Flags
    |       BlackRibbon.png
    |       
    \---Parts
        +---clusterBomb
        |       clusterBomb.cfg
        |       model.mu
        |       texture.png
        |       
        +---hiddenM230
        |       hiddenM230.cfg
        |       model.mu
        |       muzzle.png
        |       smoke.png
        |       texture.png
        |       
        \---mk2CargoBay
                BayL.cfg
                BayLarge.mu
                BayS.cfg
                BaySmall.mu
                mk2CargoBay.dds
               
````

**Pull request merged**
