### PR TITLE
Add Whirligig World from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of GregroxMun, to add [Whirligig World](https://spacedock.info/mod/1805/Whirligig%20World) to CKAN.

Mod details:
    name = /mod/1805/Whirligig%20World
    author = GregroxMun
    abstract = You spin me right around, baby! A unique homeworld in an alien solar system, dozens of new bodies to explore.
    license = All Rights Reserved (Whirligig World), GNU General Public License (Kopernicus Expansions Continued)
    Homepage = https://forum.kerbalspaceprogram.com/index.php?/topic/166563-02-nov232017-whirligig-world-a-unique-homeworld-in-an-alien-solar-system/
    description = 

Two centuries ago, explorers from the far off planet Kerbin left their home to colonize other star systems. Preliminary transit data suggested the third planet of Kaywell's star had an oxygen atmosphere and water. It did not.

Unable to correct their course due to piloting error, they crashed into the massive, 70 Kerbin Mass planet Mesbin. Luckily, Mesbin spins. Once every hour and twenty minutes it spins, and the centripedal effect pushes the equator outwards and negates some of the gravity. The 5 gees of gravity at the poles is reduced to a tad over 1 gee at the equator.

The payload of the ship survived, but the engines and fuel tanks were reduced to a lot of metal rubble along the surface. Unable to find somewhere else to go, they buried themselves underground and set up a stable ecosystem and environment down there. Eventually the colony was sufficiently industrialized to start looking up again.

See the Forum Thread for more information.

Please direct questions about this pull request to [GregroxMun](https://spacedock.info/profile/GregroxMun).

ckan compat add 1.6

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Needs https://github.com/StollD/KopernicusExpansion-Continued

@StollD, would it be OK with you if we indexed your KopernicusExpansion continuation in CKAN?

**Comment by StollD** [comment]
Sure. 

But be aware that KEX is multiple independent modules that can be used without each other (and KEX-HeightmapConverter for example isn't even a KSP plugin). So you might have to write 10 netkan files for it. 

On the other hand it probably makes more sense to index them as they are required (so just RegionalPQSMods and EmissiveFX for Whirligig) 

If you need anything feel free to ping me. 

Am 15. Juni 2019 02:26:59 MESZ schrieb HebaruSan <notifications@github.com>:

**Comment by HebaruSan** [comment]
Thanks! And yes, that looks to be the way to do it.
Note to self, this mod appears to be using EmissiveFX and RegionalPQSMods.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Hmm, an ominous pseudocomplaint from the author:

image

I wonder what's behind that...

**Comment by HebaruSan** [comment]
Looks like the dependencies changed in March:

image

**Comment by HebaruSan** [comment]
Also missing https://github.com/StollD/SciRev :

image

**Pull request merged**
