### PR TITLE
Revert B9 PWings back to 'jrodrigv' fork.

### PR DESCRIPTION
**Pull request by Poodmund**
B9 Pwings Fork is currently targeting Rafterman82's fork for 1.7.3 but jrodrigv (the previous dev/maintainer) has updated the upstream fork for 1.8.1

### CODE REVIEW

**Comment by Poodmund** [comment]
Whoops, didn't realise that this was already being discussed on https://github.com/KSP-CKAN/NetKAN/issues/7486

**Comment by DasSkelett** [comment]
See https://github.com/KSP-CKAN/NetKAN/issues/7486#issuecomment-554639985, I think we are okay if we merge it now.
Thanks @Poodmund

**Comment by DasSkelett** [comment]
@jrodrigv, your version tag on GitHub has a 'V' prefix, @Rafterman82's versions don't have one. This will mess up the sorting once the 'V' is removed again.
Can you remove the 'V' prefix from the tag (for this version and in the future)?

**Comment by jrodrigv** [comment]
Sure I will do it asap

**Comment by DasSkelett** [comment]
Thanks! The version without `V` has been indexed, I deleted the other one:
https://github.com/KSP-CKAN/CKAN-meta/commit/ffc1c33dcf8b1446aec86c74af825f20caca3041
https://github.com/KSP-CKAN/CKAN-meta/commit/c194c2c6bc1debc04f25b53ee9d56921b9616eb5

**Comment by Rafterman82** [comment]
Ok just getting online now give me a mo!

Paul Rafter

Sent from my iPhone please excuse any typos.

T: 07802 699 209
E: paulrafter@hotmail.com
S: paul_rafter

Please consider the environment - only print this email if absolutely necessary

On 16 Nov 2019, at 15:53, DasSkelett <notifications@github.com> wrote:

﻿

Thanks! The version without V has been indexed, I deleted the other one:
KSP-CKAN/CKAN-meta@ffc1c33<https://github.com/KSP-CKAN/CKAN-meta/commit/ffc1c33dcf8b1446aec86c74af825f20caca3041>
KSP-CKAN/CKAN-meta@c194c2c<https://github.com/KSP-CKAN/CKAN-meta/commit/c194c2c6bc1debc04f25b53ee9d56921b9616eb5>

**Pull request merged**
