### PR TITLE
Updated Endurance Space Exploration System to SpaceDock

### PR DESCRIPTION
**Pull request by ILM126**
Simple as that... Wow..
So I'm thinking about searching for some mods on SpaceDock and updating it soon~

### CODE REVIEW

**Comment by politas** [comment]
Basically, yes, though while looking at it, there's a few things that could make that mod work better.

The download file has a folder called "Habitat Pack", which is presumably a dependency, but there's nothing in "depends" for it. The modname is "PorkjetHabitats". 

As far as I can tell from the forum thread, KIS and RasterPropMonitor should only be "recommends", and you can add KAS to them, and have TAC-LS and USI-LS in a "suggests" stanza.

**Comment by ILM126** [comment]
Oh, yeah. Thanks ^_^

I'll be sure to check the dependencies, recommends, and suggests of the mods in the future.

**Comment by politas** [comment]
Often, it really is as simple as changing the #kref from kerbalstuff to spacedock. You just happened to hit one that was way more complicated.

**Comment by politas** [comment]
Closed in favour of #3415

**Pull request closed without merging**
