### PR TITLE
Update AsteroidDay

### PR DESCRIPTION
**Pull request by Olympic1**
Use curse `kref` instead of just `download`.

### CODE REVIEW

**Comment by politas** [comment]
I've noticed a problem with the Curse krefs for some mods - the version numbers aren't being handled properly. This seems to be one of them. It looks like Curse doesn't actually have version numbers explicitly, and if the download zip and the mod name are the same, we get what looks like a random number. LanderControl is one example, and KerBalloons does the same thing. It was doing up KerBalloons that I noticed, so I stopped working on that change. This seems to be another example (it's trying to make version 98).

**Comment by Olympic1** [comment]
Added a version number but the dowload is corrupted, works fine locally though

**Comment by politas** [comment]
Won't that force the same version number for every release?

**Comment by Olympic1** [comment]
Yes, used override to fix it.

**Comment by politas** [comment]
98 is just the last three digits of one part of the download URL (098). I think we should stick to manually updating this mod and make the new release version 1.2, to match what we've done previously. Otherwise, we're going to have to put an epoch on it half the time it updates. Ditch the kref.

**Comment by Olympic1** [comment]
Done

**Comment by politas** [comment]
LGTM!

**Pull request merged**
