### PR TITLE
Update NearFutureElectrical-DecayingRTGs for 1.1, primary moved to SpaceDock

### PR DESCRIPTION
**Pull request by lOmicronl**

### CODE REVIEW

**Comment by lOmicronl** [comment]
Not sure why the build failed. JSONLint says the syntax is valid...

**Comment by plague006** [comment]
Same issue as https://github.com/KSP-CKAN/NetKAN/pull/3718

**Comment by plague006** [comment]
Because of how `$vref` works there isn't an elegant solution for this case. You'll need to hardcode `ksp_version`.

**Comment by plague006** [comment]
Tests fine locally, merging with my thanks.

**Pull request merged**
