### PR TITLE
Create Kerbcam-continued.netkan

### PR DESCRIPTION
**Pull request by DuoDex**
Thank you autofill.

### CODE REVIEW

**Comment by plague006** [comment]
Having a `ksp_version` of `1.1.99` means your mod won't be compatible with KSP until that is the current version.
You want `ksp_version` `1.1` which is compatible with all 1.1.X releases.

**Comment by DuoDex** [comment]
Yeah but the console is saying "module contains no files to install" which is a separate error.

**Comment by plague006** [comment]
I wasn't speaking to the error you're getting. You're getting that error because you're not targeting a folder or file inside the zip.

**Comment by plague006** [comment]
`KerbCam`

**Comment by plague006** [comment]
You've listed the license as BSD 3-clause but the license written in `LICENSE.txt` is BSD 2-clause.

**Comment by DuoDex** [comment]
It should be noted the license on the forums is listed as BSD2.

**Comment by politas** [comment]
Can you make the case usage consistent?

    "identifier"   : "KerbCam-Continued",

(and the matching filename. GitHub sorts files according to strict ASCII, so this would not appear in the NetKAN folder until way down after ZPIF-4-Stock, which means currently it wouldn't appear at all)

    "name"   : "KerbCam",

**Comment by politas** [comment]
Brilliant! Merging with thanks!

**Pull request merged**
