### PR TITLE
Update SpaceXLegs.netkan

### PR DESCRIPTION
**Pull request by svendii**

### CODE REVIEW

**Comment by politas** [comment]
If you need to make further changes, you can go to the Files Changed tab and click on the edit pencil icon

**Comment by svendii** [comment]
Okay thanks, sorry for making a mess here..

**Comment by politas** [comment]
No probs. Happy to have your contributions!

**Comment by politas** [comment]
I think there may be an issue with Spacedock at the moment making the build process really slow.

**Comment by svendii** [comment]
Looks like it. Can't even reach the site.

**Comment by svendii** [comment]
Houston, ready for merge.
(That's how this works right?)

**Comment by politas** [comment]
Looks good to me. Merging with thanks! Grid Fins! Super cool!

**Pull request merged**
