### PR TITLE
Update SDHI SMS to v3.2.3

### PR DESCRIPTION
**Pull request by sumghai**
Also added a couple more suggested add-ons.

(Note: I nuked my fork because I was unable to reset it to upstream, and I was pressed for time.)

### CODE REVIEW

**Comment by politas** [comment]
>4668 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on AnimatedDecouplers found but it is not listed in the index, or not available for your version of KSP.
Module AnimatedDecouplers required but it is not listed in the index, or not available for your version of KSP.

**Comment by sumghai** [comment]
@politas - I've tested the latest release of AnimatedDecouplers, and it works fine in KSP 1.2.2.

Although it's not my plugin, should we update its .netkan listing?

**Comment by politas** [comment]
Its .version file is pretty specific, but we could put in an x_netkan_override.
Would be worth trying to contact the author first, though. Maybe do a PR to the mod github updating the .version file, saying that you've tested it?

**Comment by sumghai** [comment]
Yep, I'll let @Starwaster know.

**Comment by sumghai** [comment]
Starwaster has accepted my pull request to update AnimatedDecoupler's .version file.

I assume this means we'll need to retrigger the build for #5051 ?

**Comment by Dazpoet** [comment]
Reran it but it seems we haven't caught the new release of animated decouplers yet. Need to rerun again in a few hours.

**Comment by Dazpoet** [comment]
Working after #5059 Thank you for being patient with us :)

**Pull request merged**
