### PR TITLE
Gpp epocch

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by HebaruSan** [comment]
This isn't the problem, and it's still broken. Please hold off on this.

**Comment by HebaruSan** [comment]
@linuxgurugamer , can you please roll this back? We don't need an epoch on this, and the extra CKAN-meta file is going to mess up the fix that I'm working on.

**Comment by Galileo88** [comment]
would it be easier for me to just create a new release and upgrade the version? I'm certain that a fix for this will type of behavior will happen regardless of if I update again?

**Comment by HebaruSan** [comment]
Yes, incrementing the version would fix the problem and be extremely easy for the CKAN team. It's something we'll need to figure out regardless, but maybe not with a horde of GPP fanboys screaming at us. ;)

**Comment by linuxgurugamer** [comment]
Yes, please do so asap
Thanks

**Comment by Galileo88** [comment]
Yeah that's what I thinking. 

GPP fanboys lol

**Comment by linuxgurugamer** [comment]
It's working now

**Comment by Galileo88** [comment]
We haven’t released anything yet

**Comment by HebaruSan** [comment]
It's working now, _temporarily_, due to KSP-CKAN/CKAN-meta#1326. A new release would fix it permanently.

**Comment by HebaruSan** [comment]
The re-break has happened: https://github.com/KSP-CKAN/CKAN-meta/compare/b2d7b4c1dc...d9f25d54b2

Will re-apply the fix momentarily.

I think we can update NetKAN to use info from the GitHub API to detect and handle same-file updates. Investigation continues...

**Comment by Galileo88** [comment]
I just released a new version

**Pull request merged**
