### PR TITLE
Update WernherChecker.netkan

### PR DESCRIPTION
**Pull request by Magion**
Added range of supported KSP versions, bugtracker link and $vref for fixed .version file

### CODE REVIEW

**Comment by plague006** [comment]
$vref extract version compatibility from the .version file so you don't want to hardcode it into the .netkan unless the .version file is in error.

**Comment by Magion** [comment]
I forgot to include the KSP 1.0.4 compatibility info in the .version file, so I decided to hardcode it here just for this version of the mod. I defined the $vref too, because I wanted to have it there prepared for the next update, since the CKAN Wiki says, that it doesn't conflict with the hardcoded value and is just overridden.

If you say it's not a good idea, I should delete the $vref then, correct?

**Comment by plague006** [comment]
Yes, the vref version compatibility info will be overridden by what's hardcoded. The issue is that hardcoding into the .netkan will apply to the current and all future versions unless the .netkan is manually edited.

The best way to override this specific version while allowing future versions to scrape compatibility data from the vref is overriding the specific version (essentially only hardcoding for this specific version).

````
"x_netkan_override" : [
        {
            "version" : "v0.4",
            "delete" : [ "ksp_version" ],
            "override" : {
                "ksp_version_min" : "1.0.4",
                "ksp_version_max" : "1.0.5"
            }
        }
    ]
````

**Comment by Magion** [comment]
Aaah... I didn't know about this option. I originally intended to delete the hardcoded supported KSP versions after the next update, but this is a better solution.

**Comment by plague006** [comment]
Awesome, merging with my thanks.

**Pull request merged**
