### PR TITLE
Water Launch Sites - recommend MakingHistory-DLC

### PR DESCRIPTION
**Pull request by yalov**
\-\-\-
Edited by @DasSkelett:
See https://github.com/KSP-CKAN/CKAN/pull/2326
\-\-\-

### CODE REVIEW

**Comment by DasSkelett** [comment]
This will need some changes in the client before it works.
Current output if I try to install it via commandline:
```
4246 [1] INFO CKAN.RelationshipResolver (null) - MakingHistory-DLC is recommended/suggested but it is not listed in the index,
or not available for your version of KSP.
```

**Comment by yalov** [comment]
it's ok, you can't buy it via CKAN. It is suppose to be informational

**Comment by DasSkelett** [comment]
Right now you can only see it in the recommendations tab. If that's enough for you, we don't need to change anything.
If you want it to show up in the recommendation screen, as a simple text entry or something, it would need some work.

**Comment by yalov** [comment]
dependency tab is ok

**Comment by HebaruSan** [comment]
Looks OK (with the already noted caveat that it won't do anything), merging...

**Pull request merged**
