### PR TITLE
Add ShadowWorksStockalikeSLSandMore.netkan

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
This netkan is currently broken on the current version of the mod, awaiting new version from author.

**Comment by plague006** [comment]
Passes local, no way (afaik) to force a rebuild from jenkins. Merging.

**Comment by techman83** [comment]
Refer KSP-CKAN/NetKAN-bot#1273

**Comment by plague006** [comment]
In this instance jenkins worked adequately.

When I submitted the PR it should have, and did, pass jenkins. The mod/netkan broke with a mod update after jenkins' tests, and then the 3rd update to the mod fixed it.

**Pull request merged**
