### PR TITLE
Add ChayrolDesignOrg

### LINKED ISSUE #7710: [Mod] Chrayol Design Org.
Mod info
--------
* Mod name: Chrayol Design Org.
* Author(s): DylanSemrau
* License: Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/189111-18-v10-chrayol-design-org-isro-mod/
* Download: https://github.com/DylanSemrau/Chrayol-Design-Org./releases

> {
>   "spec_version"        : "v1.4",
>   "identifier"          : "ChayrolDesignOrg",
>   "$kref"               : "#/ckan/github/DylanSemrau/Chayrol-Design-Org.",
>   "abstract"            : "This mod aims to add a number of different ISRO rockets and spacecraft to the game. Eventually the plan is to add SLV, GSLV MK1-3, RLV, along with a couple of probes (Ex. Chandrayaan, Mangalyaan etc).",
>   "author"              : "DylanSemrau",
>   "license"             : "CC-BY-NC-SA-4.0",
>   "$vref"               : "#/ckan/ksp-avc",
>   "resources": {
>     "homepage": "https://forum.kerbalspaceprogram.com/index.php?/topic/189111-18-v10-chrayol-design-org-isro-mod/",
>     "repository": "https://github.com/DylanSemrau/Chrayol-Design-Org."
>   },
>   "depends": [
>       { "name" : "ModuleManager" }
>   ],
>   "suggests": [
>       { "name" : "JNSQ" },
>       { "name" : "RealPlume-StockConfigs" },
>       { "name" : "BluedogDB" },
>       { "name" : "ModularLaunchPads" }
>   ],
>   "install" : [
>       { 
>       "file" : "GameData/Chrayol_Design_Org",
>        "install_to" : "GameData"
>        }
>   ]
> }

### PR DESCRIPTION
**Pull request by HebaruSan**
Fixes #7710 

ckan compat add 1.5

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
PlumeParty is bundled. Will need to talk to @JadeOfMaar about indexing it.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by JadeOfMaar** [comment]
Plume Party cannot be added as a dependency due to:
* Plume Party itself is currently unreleased (on purpose).
* The portions necessary for, and used by this mod, are nested within this mod.

**Comment by HebaruSan** [comment]
Thanks @JadeOfMaar.

> The portions necessary for, and used by this mod, are nested within this mod.

Is that OK? Will these resources work if multiple mods install them to different paths?

**Comment by JadeOfMaar** [comment]
Yeah they'll work. The mods already using it typically keep a PlumeParty folder within themselves and don't install it into the root level of GameData...except possibly benjee10's Shuttle Orbiter Construction Kit.

**Comment by HebaruSan** [comment]
OK, I guess we have to go along with the bundling in this case. Thanks again!

**Pull request merged**
