### PR TITLE
Kube

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Closes #5911

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
B9PartSwitch appears to be 1.3.0 only so far? This should be fine for 1.3.0 users, but will not appear in the list for 1.3.1 users until B9PartSwitch is updated.

**Comment by linuxgurugamer** [comment]
Oh.  ok, I was waiting for B9 to get fully updated.
thanks

**Pull request merged**
