### PR TITLE
SimpleConstruction Add epoch

### PR DESCRIPTION
**Pull request by politas**
ref #4999

### CODE REVIEW

**Comment by Real-Gecko** [comment]
So, we need to set epoch anyway? Will we need to remove `x_netkan_version_edit`?

**Comment by politas** [comment]
x_netkan_version_edit can stay. Shouldn't make a difference. People are still going to have local metadata saying vVersion<whatever>, and so CKAN will not upgrade until the KSP version forces it.

**Comment by Real-Gecko** [comment]
OK, nice :)

**Comment by Real-Gecko** [comment]
Let's rock!

**Pull request merged**
