### PR TITLE
Add Chaka Monkey Exploration Systems from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of YANFRET, to add [Chaka Monkey Exploration Systems](https://spacedock.info/mod/599/Chaka%20Monkey%20Exploration%20Systems) to CKAN.

Mod details:
    name = /mod/599/Chaka%20Monkey%20Exploration%20Systems
    author = YANFRET
    abstract = A space program based on NASA and Boeing proposals for future missions. Part models from a wide variety of authors have been licensed, and new original models made, then combined with all new textures, sizes and configurations, to create craft files depicting the proposed missions. This project is modeled at 75% real scale.
    license = See forum page for license info:
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/112024-%E2%99%A6-chaka-monkey-exploration-s
    description = 

Please direct questions about this pull request to [YANFRET](https://spacedock.info/profile/YANFRET).

### CODE REVIEW

**Comment by plague006** [comment]
We should consider using this `kref` for `MK12PodIVAReplacementbyASET`.

**Comment by politas** [comment]
Considering how huge this is, we probably shouldn't, unless it's the only source.

**Comment by politas** [comment]
Turns out it is the only source, as far as I can tell.

**Comment by plague006** [comment]
Delete `MK12PodIVAReplacementbyASET.kerbalstuff`

**Comment by politas** [comment]
Ah, I was looking at the Mk's rather than MK. No wonder I couldn't find that.

**Comment by politas** [comment]
Dammit, Jenkins. Do the dependency first!

**Comment by plague006** [comment]
May as well push a temporary commit that omits the dependency

**Comment by plague006** [comment]
`VAB` folder should be installed.
RPM should be a `depends` to ensure IVAs work.

**Comment by politas** [comment]
Mk12PodIVA has a dependency on RPM-Core already.

**Comment by plague006** [comment]
`ChakaMonkeyExplorationSystems` isn't intrisically linked to `Mk12PodIVA`. The dependency could easily be changed to a `recommends` at any point and if that happens you've put whoever PRs and/or reviews that in a position where they've broken our installation of this mod.

We don't rely on second-order depends for mods, we write the metadata to be accurate to the mod we're describing.

**Comment by plague006** [comment]
Just saw that this was updated. Merging with my thanks.

**Pull request merged**
