### PR TITLE
CommNetAntennasConsumptor has own repo

### PR DESCRIPTION
**Pull request by yalov**

### CODE REVIEW

**Comment by yalov** [comment]
because of the repo without releases?

**Comment by DasSkelett** [comment]
> No releases found for yalov/CommNetAntennasConsumptor

**Comment by yalov** [comment]
uploaded the release

**Comment by yalov** [comment]
what the command there for new check?

**Comment by yalov** [comment]
update

**Comment by yalov** [comment]
recheck

**Comment by HebaruSan** [comment]
#rebuild

**Comment by yalov** [comment]
ok, ready to go

**Comment by HebaruSan** [comment]
Thanks for the update!

**Pull request merged**
