### PR TITLE
Add more mods of LuizChacon

### PR DESCRIPTION
**Pull request by Olympic1**
Add 15 more of LuizChacon's craft mods

**Close PR's**
Closes #2528, Closes #2530, Closes #2534, Closes #2579, Closes #2594, Closes #2610, Closes #2611, Closes #2632, Closes #2634, Closes #2636, Closes #2652, Closes #2665, Closes #2669, Closes #2675, Closes #2677

### CODE REVIEW

**Comment by plague006** [comment]
While Jenkins doesn't properly test the actual installations of each mod, installations are basically tested by netkan.exe and Jenkins does test the metadata. Each passed and that's good enough for me. Merging with my thanks.

**Comment by Olympic1** [comment]
I noticed that if you make a PR on CKAN-meta with 5 files, Jenkins test every file. If you would do the same here, it only tests the last file.

**Comment by plague006** [comment]
Yeah I've looked at the build.sh from both and with my limited knowledge I'm really unclear on why it's happening.

**Comment by techman83** [comment]
I just had a long hard stare at it. I think I know what's happening.

**Comment by techman83** [comment]
About to lose internet for a couple hours, will likely have a patch for KSP-CKAN/CKAN#1479

**Pull request merged**
