### PR TITLE
CTTP - Remote hosting of NetKAN metadata

### PR DESCRIPTION
**Pull request by Poodmund**
Update the NetKAN metadata to point to remotely hosted CTTP NetKAN metadata.

### CODE REVIEW

**Comment by HebaruSan** [comment]
It seems to be confused by

```json
    "ksp_version": "any",
```

... but that's explicitly allowed according to the spec, so we may have some code fixing to do here. Please stand by.

**Comment by HebaruSan** [comment]
OK, I've submitted a fix for that. It might take a couple of days for another CKAN dev to review and merge it, so in the meantime if you wish you can workaround this issue by removing that `"ksp_version"` property from your netkan.

**Comment by Poodmund** [comment]
I don't mind waiting. That was pretty much the whole reason for the metadata update as CTTP is just a folder with a bunch of textures in and will work on any version of KSP; we don't want to have to keep updating it going forward. 

Thanks for your work.

**Comment by HebaruSan** [comment]
OK, waiting is fine with me, but just for the record removing that property would not change any behavior because ["any" is the default](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md):

> If no KSP target version is included, a default of "any" is assumed.

The current difficulty is just a weird parsing quirk.

**Comment by Poodmund** [comment]
Oh okay that is good to know. Well I'll leave it as is anyhow as then it documents the edge case nicely.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
New error:

```
Validating built/CommunityTerrainTexturePack-1-1.0.4.ckan.. Failed! See below for error description.
None is not of type u'string'

Failed validating u'type' in schema[u'properties'][u'ksp_version']:
    {u'description': u'A version of KSP',
     u'pattern': u'^(any|[0-9]+\\.[0-9]+(\\.[0-9]+)?)$',
     u'type': u'string'}

On instance[u'ksp_version']:
    None
```

The fix worked fine (since netkan was able to generate the .ckan file), but apparently the bot's extra validation checks don't like the output. Investigating...

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
w00t

**Pull request merged**
