### PR TITLE
Create HarderSolarSystem-generic.netkan

### PR DESCRIPTION
**Pull request by stevehead**
This should be the last of my Harder Solar System config sets, for the foreseeable future at least.

### CODE REVIEW

**Comment by Olympic1** [comment]
Does this work with Kopernicus v0.5.2 ?

**Comment by stevehead** [comment]
Yes, it's been tested with it.

**Comment by Olympic1** [comment]
That was what I wanted to hear :)
Merging

**Comment by stevehead** [comment]
thanks!

**Pull request merged**
