### PR TITLE
Add Kerbal Krash Systems - fixed Kerbalstuffbot submission

### PR DESCRIPTION
**Pull request by politas**
Fixes #2909

### CODE REVIEW

**Comment by EnzoMeertens** [comment]
Thank you! :+1:

**Comment by pjf** [comment]
Oh dear, we're behind on ModuleManger! Let me see if I can find/make an update for that so we can get 2.6.17 into the system.

**Comment by pjf** [comment]
Okay, we're got ModuleManager just fine. Silly me was using an old build that was rightfully ignoring the newer MM documents as they targeted a later spec version. :)

**Comment by pjf** [comment]
You all rock! Merging with great thanks!

```
$ ckan.exe show KerbalKrashSystem
KerbalKrashSystem: Kerbal Krash System rewrites collisions in Kerbal Space Program. KKS crumples your creations and reduces the efficiency of your crafts instead of just exploding on impact.

Module info:
- version:	0.04
- authors:	EnzoMeertens
- status:	stable
- license:	MIT

Depends:
- ModuleManager, min: 2.6.17

Provides:
- KerbalKrashSystem

Resources:
- kerbalstuff: https://kerbalstuff.com/mod/1389/KerbalKrashSystem
- repository: https://github.com/EnzoMeertens/KerbalKrashSystem

Filename: 6DCB7045-KerbalKrashSystem-0.04.zip

Showing 37 installed files:
- GameData/KerbalKrashSystem
- GameData/KerbalKrashSystem/Configs
- GameData/KerbalKrashSystem/Configs/KerbalKrashSystem_Command.cfg
- GameData/KerbalKrashSystem/Configs/KerbalKrashSystem_Container.cfg
- GameData/KerbalKrashSystem/Configs/KerbalKrashSystem_Engine.cfg
- GameData/KerbalKrashSystem/Configs/KerbalKrashSystem_Other.cfg
- GameData/KerbalKrashSystem/License.txt
- GameData/KerbalKrashSystem/Plugins
- GameData/KerbalKrashSystem/Plugins/KerbalKrashSystem.dll
- GameData/KerbalKrashSystem/Plugins/KKS-mods
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_KIS_Repair
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_KIS_Repair/Configs
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_KIS_Repair/Configs/KerbalKrashSystem_KIS_Repair.cfg
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_KIS_Repair/Plugins
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_KIS_Repair/Plugins/KerbalKrashSystem_KIS_Repair.dll
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Configs
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Configs/KerbalKrashSystem_Fuel_Leak.cfg
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/EZPZ
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/EZPZ/Configs
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/EZPZ/Configs/EZ_Particles.cfg
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/EZPZ/Configs/ParticleFX.txt
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/EZPZ/Plugins
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/EZPZ/Plugins/EZ_Particlez.dll
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Plugins/KerbalKrashSystem_Leak.dll
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair/Configs
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair/Configs/KerbalKrashSystem_Repair.cfg
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair/Plugins
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair/Plugins/KerbalKrashSystem_Repair.dll
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science/Configs
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science/Configs/KerbalKrashSystem_Science.cfg
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science/Plugins
- GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science/Plugins/KerbalKrashSystem_Science.dll
- GameData/KerbalKrashSystem/Version.txt
```

**Pull request merged**
