### PR TITLE
RP-0 conflicts with CrowdSourcedScience.

### PR DESCRIPTION
**Pull request by NathanKell**

### CODE REVIEW

**Comment by techman83** [comment]
Hmm looks like we might be getting rate limited by GitHub. Not sure of the best way around that.

**Comment by NathanKell** [comment]
Hmm?

Did you mean to reply to this issue?  Not seeing how that has to do with
RP-0 and CSS conflicting ingame...

Sent by my thumbs, slowly.

**Comment by techman83** [comment]
@NathanKell - I'm talking about Jenkins failing to pass.

**Comment by NathanKell** [comment]
Ah I see.  Sorry,  email only at the moment :]

Sent by my thumbs, slowly.

**Comment by techman83** [comment]
Ok, So I've run the build offline and it works correctly. I'll merge this now, raised an issue to look into it.

**Pull request merged**
