### PR TITLE
Add BlacklegIndustriesMM.netkan

### PR DESCRIPTION
**Pull request by blackleg**

### CODE REVIEW

**Comment by politas** [comment]
So this adds or changes TAC Life Support settings for the parts in Tantares, is that right? It would be good to have that in the mod abstract. I think this is failing due to https://www.blackleg.es not responding, (Looks like that server is not running https?)

**Comment by blackleg** [comment]
@politas I changed the plugin identifier and add info in the abstract

**Comment by politas** [comment]
```
#   Failed test 'BlacklegIndustriesMM_TantaresTACLS: CKAN identifiers must consist only of letters, 
     numbers, and dashes, and must start with a letter or number.'
#   at t/metadata.t line 26.
#                   'BlacklegIndustriesMM_TantaresTACLS'
#     doesn't match '(?^:^[A-Za-z0-9-]+$)'
```
No underscores allowed in identifiers, sorry.

**Comment by politas** [comment]
Thanks, @blackleg. I don't understand why Jenkins is complaining about the spec_version on two other mods, still. This is all fine now as far as I can see. ¡Uniendo con muchas gracias!

**Comment by techman83** [comment]
@politas it'd be a fork of the repo from before those files were fixed. That test runs over all Netkans in the repo.

**Comment by politas** [comment]
@techman83, ah, that explains it. I was baffled.

**Pull request merged**
