### PR TITLE
Add Star Trek: TOS colored Space Suits Pack for TextureReplacer from KerbalStuff

### PR DESCRIPTION
**Pull request by politas**
Added Dependency and Installation details to KerbalStuffBot's #1287

### CODE REVIEW

**Comment by Dazpoet** [comment]
I don't say this often but I think this identifier could use some shortening down.

Lines 5 and 21 are not needed, the comma on line 20 should be removed when line 21 is removed. spec_verison 1.4 is probably not needed, 1.2 should be good enough from what I see.

**Comment by politas** [comment]
Is there a page somewhere that lists the capabilities of the different spec versions?

**Comment by Dazpoet** [comment]
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md

**Comment by politas** [comment]
Are you sure about that license line? I can't see why it's failing now.

**Comment by Dazpoet** [comment]
You're right, re-add license line. I forgot how to NetKAN for a second I think :-1:

**Comment by politas** [comment]
The spec claims that the KerbalStuff $kref should scrape the license.

**Pull request merged**
