### PR TITLE
Update kRPC github and docs links

### PR DESCRIPTION
**Pull request by djungelorm**

### CODE REVIEW

**Comment by plague006** [comment]
Look at you all official now with an org. :D
Merging with my thanks.

**Comment by plague006** [comment]
As an aside I notice kRPC installs `VERSION.txt`, if you want a hand converting it to `kRPC.version` we would be able to scrape KSP version compatibility from it automatically (no more manually editing this file).

**Comment by djungelorm** [comment]
Thanks.

Yeah that would be good. Is there documentation for this?

**Comment by plague006** [comment]
It should be http://ksp.cybutek.net/kspavc/Documents/README.htm for the .version file formatting, for CKAN's use of the file documentation is here: https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#vref

The simplest/easiest version file for your mod would be something like:
````
{
  "NAME": "kRPC",
  "VERSION": {
    "MAJOR": 0,
    "MINOR": 2,
    "PATCH": 1
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 5
  }
}
````

and then `"$vref": "#/ckan/ksp-avc"` added to the .netkan so we can make use of it (when it's in a release).

**Comment by djungelorm** [comment]
OK thanks, will add it to the next version of kRPC

**Pull request merged**
