### PR TITLE
update CommunityPartsTitles 0.4.0

### PR DESCRIPTION
**Pull request by yalov**

### CODE REVIEW

**Comment by yalov** [comment]
waiting confirmation about the KAX/L

**Comment by yalov** [comment]
how to suggest a mod, starting only with some version, so until it's getting there, the mod isn't even suggested?

`{ "name": "Ringworld", "version": ">3.0.0" }`

**Comment by HebaruSan** [comment]
Try what `IR-Model-Rework-Core.netkan` does:

```json
{ "name": "InfernalRobotics", "version_min": "0.19.4" }
```

**Comment by yalov** [comment]
ready to go

**Comment by HebaruSan** [comment]
Sorry, I got that wrong, it's actually `min_version`, and the metadata I quoted needs to be cleaned up:

https://github.com/KSP-CKAN/CKAN/blob/6b4cd143996f029b94162ec89a2e0cb86f9a7c3f/Core/Types/CkanModule.cs#L37-L42

**Pull request merged**
