### PR TITLE
Add dawnguard from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of subdeviant, to add [dawnguard](https://spacedock.info/mod/1704/dawnguard) to CKAN.

Mod details:
    name = /mod/1704/dawnguard
    author = subdeviant
    abstract = solar sail
    license = MIT
    Homepage = https://github.com/subdeviant
    description = **Dawn Guard Solar Sail!**[]
(http://i.imgur.com/enHmhvp.png)

Please direct questions about this pull request to [subdeviant](https://spacedock.info/profile/subdeviant).

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
This isn't a problem for CKAN per se, but the readme.txt file in your download is copied from KSP itself. You should probably replace it with some information about your mod.

**Comment by HebaruSan** [comment]
Also, these parts look like reskins of the stock Gigantor XL Solar Array. I'm not sure that's legal to distribute, because KSP is not distributed under the MIT license.

**Comment by subdeviant** [comment]
yes the parts are absolutely what you say. i just changed the texture to personalise it. this is the first time i have attempted anything like this and wanted to share what i had achieved. the readme was just an attempt to get my version numbers right. i will fix that. will i need to personalise the mesh as well as the texture or will i have to learn blender? i have full respect for squad and do not want to disrespect their work.

**Comment by HebaruSan** [comment]
The contents of a mod download should be either:

1. Owned by you; or
2. Licensed in a way that allows you to distribute it.

SQUAD's parts don't qualify.

If you don't want to learn modeling, you might be able to collaborate with another modder, for example:

https://forum.kerbalspaceprogram.com/index.php?/topic/169473-any-modders-need-any-modelling-done/

**Comment by subdeviant** [comment]
ok. thank you very much for your time. 
would using the database reference as opposed to a personalised copy allow me to continue?

**Comment by HebaruSan** [comment]
Please see what I said earlier; the files in the ZIP should be owned by you or owned by someone who has given you permission to distribute them.

**Comment by subdeviant** [comment]
ok. thank you very much. i know not to spam the pull requests now. i shall not do that again. sorry.
in the meantime i'm off star sailing. it throws a whole new tac on orbital navigation.
thank you bye. :)

**Pull request closed without merging**
