### PR TITLE
Add Kerbal Mods Overhaul (KMO) from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of 534443, to add [Kerbal Mods Overhaul (KMO)](https://spacedock.info/mod/1735/Kerbal%20Mods%20Overhaul%20%28KMO%29) to CKAN.

Mod details:
    name = /mod/1735/Kerbal%20Mods%20Overhaul%20%28KMO%29
    author = 534443
    abstract = "Kerbal Mods Overhaul" (KMO) is nothing more than a set of patches initially made to cope with the personal desire to simplify/modify a number of very popular mods, MKS in primis, in order to bring a slightly different gameplay experience to KSP.
    license = CC BY-SA 4.0
    Homepage = 
    description = ## Kerbal Mods Overhaul (KMO)
<br/>

**Core mods:**

* Modular Kolonization System (MKS) made by RoverDude

* USI Life Support (USI-LS) made by RoverDude

* ExtraplanetaryLaunchpads (EL) made by skykooler and taniwha

<br/>

**Optional mods:**

* OSE Workshop (KIS Addon) made by ObiVanDamme and Aelfhe1m

* KeridianDynamics Vessel Assembly made by EleusisLaArwall

<br/>

Also consider installing Kerbal Attachment System (KAS) and Kerbal Inventory System (KIS), both made by KospY, winn75 and IgorZ.

**Notice: Always Remember to install all dependencies for the mods you use!**
<br/>
<br/>
<br/>
<br/>

| Patch Table (v0.1) |

Patch Table

Please direct questions about this pull request to [534443](https://spacedock.info/profile/534443).

### CODE REVIEW

**Comment by HebaruSan** [comment]
Needs PatchManager, which is still marked as 1.3.1 only. PM probably works, but let's wait for @linuxgurugamer to update it just in case.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
PM is updated, and is showing as available in my local CKAN client, but for some reason didn't get pulled in for this build.
It is updated for 1.4.1 only, could that be the reason?

**Comment by linuxgurugamer** [comment]
Patch Manager was updated for 1.4.1, I'm not supporting 1.4.0 since it was so short.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
It appears that SpaceDock automatically truncates "1.4.0" to "1.4", so Netkan automatically transforms "1.4" to "1.4.0", even if it was originally meant as "1.4". So this author may or may not post an update for 1.4.1.

I'll see if I can figure out a pull request to fix this on the SpaceDock side...

**Comment by Olympic1** [comment]
If you want I can set the mod to 1.4.1 as I'm an admin on SpaceDock

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
It's on 1.4.1 now, but UKS isn't yet. Will check again in a while.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by Olympic1** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by Olympic1** [comment]
UKS dependencies are now on 1.4.1 but this mod also needs EPL. Author says that he is almost ready for a release.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Pull request merged**
