### PR TITLE
Delete polandball.netkan

### PR DESCRIPTION
**Pull request by SteveBenz**
Looks like a bug in the spacedock integration caused it to fail to notice the differently cased version.

### CODE REVIEW

**Comment by SteveBenz** [comment]
Looks like a bug in the spacedock integration caused it to fail to notice the differently cased version. (There's a newer version of this exact same file named with an uppercase "B" in the filename.)

**Comment by DasSkelett** [comment]
See #6877, it's a different mod actually. Since this mod here hasn't been updated in a long time, it was decided that the similar name/identifier wouldn't be a problem.

**Comment by SteveBenz** [comment]
Hm..  Well, I noticed it because I'm on a Windows machine, and Windows is a case-insensitive filesystem, so Git For Windows can't support both versions of the capitalization.

If you really think supporting both the older and the newer version of the mod is a good idea, I think the name should be split somehow.

**Comment by SteveBenz** [comment]
To be clear, this is what you see when you clone the repo on a Windows box:

E:\repos\NetKAN>git status
On branch master
Your branch is ahead of 'origin/master' by 449 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   NetKAN/PolandBall.netkan

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by DasSkelett** [comment]
I blame that oversight on the lack of Windows-using team members :P

You're right, only differencing mods with capitalization, even if all OSes would use proper case-sensitive file systems, is not best practice.
We should rename the newer one. Any suggestions?

**Comment by SteveBenz** [comment]
Not my mod - I'd be as lost as you.  But it sounds like this PR should be closed as not the right fix.

**Comment by DasSkelett** [comment]
Should be fixed now, thanks for letting us know.

**Pull request closed without merging**
