### PR TITLE
replaced dependancy on InterstellarFuelSwitch by InterstellarFuelSwitch-…

### PR DESCRIPTION
**Pull request by sswelm**
…Core

in order to prevent mod conflict, reduced dependency requirement

### CODE REVIEW

**Comment by sswelm** [comment]
As expected, Fails on CommunityTechTree because there it is not updated to KSP 1.3 yet. I think this can be ignored since CTT is just a config mod

**Comment by politas** [comment]
The min version for CTT will not work. It'll need to be 1:3.0.3

**Comment by sswelm** [comment]
ok, lets try it, but what does 1:3.0.3 mean?

**Comment by politas** [comment]
I means it has an epoch due to a historical discontinuity in version numbering systems. In this case, there was a accidental 2.4.0 that thought it came after the real 2.4 #4071 has the details.

**Pull request merged**
