### PR TITLE
Add CKAN Release for ROEngines

### PR DESCRIPTION
**Pull request by pap1723**

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
It's failing to install (and won't install for users) because RealismOverhaul conflicts with RealPlumeConfigs, which this mod provides. You'd need to either remove that conflict or remove the provides.

**Comment by pap1723** [comment]
Thank you, I have removed the conflicts and the provides in the local
.netkan file so it should all be good now.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Test script detected no changes. Was it this netkan that you updated?

**Comment by pap1723** [comment]
Sorry HebaruSan,
I made the changes to the hosted .netkan file and forgot to push them to
Github. Changes done now

**Comment by pap1723** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Looks good, thanks for the submission.

**Pull request merged**
