### PR TITLE
Add KerbalizedFlagpack

### PR DESCRIPTION
**Pull request by Dazpoet**
Fixed version of #845

### CODE REVIEW

**Comment by Dazpoet** [comment]
Works and installs fine locally for me. Are the problems Jenkins report due to the spaces in the adress?

**Comment by pjf** [comment]
Having two spec versions might have something to do with it, although that's not explicitly clear in the output from the bot...

**Comment by Dazpoet** [comment]
I knew I was tired when I wrote it... but didn't realize I was *that* tired. However it still doesn't sit well with Jenkins for some reason.

**Comment by AlexanderDzhoganov** [comment]
#rebuild

**Comment by Dazpoet** [comment]
I give up!

**Comment by hakan42** [comment]
Don't give up too early, there is still the weekend to work on this :smiling_imp:

**Comment by Dazpoet** [comment]
Now I'm confused, Jenkins explicetly failed that one repeatedly :s

**Comment by hakan42** [comment]
Yes, but it was mostly about our toolchain setup, so I just merged the PR and will see what happens when the daemon sees it. The netkan file can be fixed if and when necessary :smile:

**Pull request merged**
