### PR TITLE
Update KIS & SurfaceLights

### PR DESCRIPTION
**Pull request by ihsoft**
Both live on Guthub but release via CurseForge so, taking full control on it.

### CODE REVIEW

**Comment by ihsoft** [comment]
It looks tag `license` is required when using `#/ckan/netkan` even though the remote `.netkan` file has it. Wiki should be updated with the list of the required fields.

**Comment by plague006** [comment]
Looks good to me, merging with my thanks.

And re: updating our wiki, which page mentions metanetkans?

**Comment by ihsoft** [comment]
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ckannetkanurl

**Comment by plague006** [comment]
Ah, my confusion was because you said wiki page and that's a file. I'll poke the person who'd know best about metanetkans and see needs changing.

**Pull request merged**
