### PR TITLE
Update KerbinSide relationships

### PR DESCRIPTION
**Pull request by plague006**
@politas

### CODE REVIEW

**Comment by plague006** [comment]
e8bbc35 passes and that's the important one. I'm going to add another commit to bring KerbinSideAirRace in line with the new relationships but doing so will cause a Jenkins fail.

**Comment by politas** [comment]
Isn't that a virtual package, rather than a metapackage?

**Comment by plague006** [comment]
Yes. I probably said metapackage at some point, I misspoke.

**Comment by politas** [comment]
"provides" : [ "KerbinSide-meta" ],

So if we change that to "Kerbinside-virtual"?

**Pull request merged**
