### PR TITLE
Adding Principia.

### PR DESCRIPTION
**Pull request by zilti**

### CODE REVIEW

**Comment by politas** [comment]
Thought I'd already left this comment. This appears to be only the Linux version of Principia. Can you change the identifier, filename, name and abstract to reflect that?

**Comment by dbent** [comment]
Doesn't Prinicipia require system-wide native dependencies to be installed?

**Comment by zilti** [comment]
No, it's a universal, complete zip with everything needed to use it. I tried the package on both Windows and Linux. (There's currently no macOS build)

**Comment by politas** [comment]
Oh, great! Last time I got Principia, there were still sepaate downloads, and you had to go to the IRC channel to find the link. 

The main forum thread appears to be http://forum.kerbalspaceprogram.com/index.php?/topic/162200-wip122-principia - Can you make that the "homepage"?  Also, the latest release is 2017062403-Cauchy, so it would probably be best to use that one.

**Comment by politas** [comment]
Zilti, have you contacted the mod author(s) and asked them about listing on CKAN?

**Comment by HebaruSan** [comment]
The authors of this mod prefer not to be indexed. Closing.

https://github.com/KSP-CKAN/NetKAN/issues/6242#issuecomment-366049343

**Comment by HebaruSan** [comment]
> No, it's a universal, complete zip with everything needed to use it. I tried the package on both Windows and Linux. (There's currently no macOS build)

Just noting for posterity the proof that this is **false** in case it comes up again:

https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#its-not-starting

> #### Windows users
> If you get the message "Dependencies, namely the Microsoft Visual C++ 2015-2019 Redistributable, were not found", well, you need to install the [Microsoft Visual C++ 2015-2019 Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> 
> #### Mac users
> You need Sierra or later.
> 
> #### Linux users
> You need libc++ and libc++abi 8.

"Microsoft Visual C++ 2015-2019 Redistributable", "Sierra or later", and "libc++ and libc++abi 8" are the specific system-wide native dependencies that are required to run Principia, as noted in that mod's own documentation.

**Pull request closed without merging**
