### PR TITLE
Create ContractConfigurator-KerbinSideJobs

### PR DESCRIPTION
**Pull request by Blu3wolf**

### CODE REVIEW

**Comment by Dazpoet** [comment]
https://github.com/KSP-CKAN/NetKAN/pull/1319 lists other dependencies, which one is right?

**Comment by Blu3wolf** [comment]
If you have KerbinSide, then Kerbal Konstructs is a hard dependency.

Technically the mod will work without KerbinSide, but its pointless without it. 

If you install KerbinSide then you need Kerbal Konstructs, but that is a dependency for KerbinSide already. 

As its a mod pack, ContractConfigurator is a hard dependency.

**Comment by politas** [comment]
I'd support this dependency change.

**Comment by politas** [comment]
So we need to change the identifier to match the filename?

**Comment by politas** [comment]
I think the licence needs to be set as per #1319, though.

**Comment by Dazpoet** [comment]
Yes the identifier should match the filename and it would appear this file does not have the .netkan file-extension?

**Comment by politas** [comment]
Might be easier if I change the dependencies on my version.

**Comment by politas** [comment]
I've changed the dependencies in #1319, and I think that version is now better.

**Pull request closed without merging**
