### PR TITLE
Make KerbalField depend on the virtual BDArmory identifier

### PR DESCRIPTION
**Pull request by JonnyOThan**
I got permission from the author on the ksp forums for this

image

___

Previous time this came up: #9328

### CODE REVIEW

**Comment by HebaruSan** [comment]
> I got permission from the author on the ksp forums for this

Was it in a PM? I like to confirm things like this to be on the safe side, so I checked the thread and the author's recent activity, but I didn't find anything.

**Comment by JonnyOThan** [comment]
ah yep it was in a DM: 
image

**Comment by BingoXXXXX** [comment]
I approve

**Review by HebaruSan — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
