### PR TITLE
Update DockingCamKURS install folder

### PR DESCRIPTION
**Pull request by HebaruSan**
Used to be OLDD, now DockingCamCKURS.

ckan compat add 1.6

### CODE REVIEW

**Comment by HebaruSan** [comment]
#rebuild

**Comment by linuxgurugamer** [comment]
Oh, thank you

**Comment by linuxgurugamer** [comment]
Got a problem,  .version file say 1.6.1 is max, but CKAN says it's for 1.7.0
I verified the .version file.
Just an FYI, I will be releasing an update for 1.7.0 either later today or tomorrow

**Comment by linuxgurugamer** [comment]
See this issue: https://github.com/KSP-CKAN/NetKAN/issues/7166

**Pull request merged**
