### PR TITLE
Remove VAB folder from Fenrir

### PR DESCRIPTION
**Pull request by HebaruSan**
Author confirms that this folder is intentionally removed and will no longer be shipped:

https://forum.kerbalspaceprogram.com/index.php?/topic/166821-wip-fenrir-launcher-pack/&do=findComment&comment=3210124

### CODE REVIEW

**Comment by HebaruSan** [comment]
(Validation error fixed in https://github.com/KSP-CKAN/CKAN/pull/2173)

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Comment by politas** [comment]
Tested locally successfully

**Pull request merged**
