### PR TITLE
Updates ScanSatLite file.

### PR DESCRIPTION
**Pull request by SkyMarshal**
Which will probably fail as well since the .version file is invalid.

### CODE REVIEW

**Comment by plague006** [comment]
So this is waiting on severedsolo/ScanSatLite#3?

**Comment by SkyMarshal** [comment]
Yes, sorry.  I had to go run errands shortly after making this.

**Comment by severedsolo** [comment]
PR merged - you'll have to wait until tonight for me to update the release so the build won't fail checks any longer.

**Comment by SkyMarshal** [comment]
No worries.

**Comment by severedsolo** [comment]
#rebuild

**Pull request merged**
