### PR TITLE
Add missing CKAN badged mods from SpaceDock

### PR DESCRIPTION
**Pull request by HebaruSan**
Two adopted parts packs, some buildings, and a planet were missed by the SpaceDock add trigger. This is them.

___

ckan compat add 1.8

### CODE REVIEW

**Comment by HebaruSan** [comment]
The PR validation is broken.

**Comment by DasSkelett** [comment]
Still seems to work partially, at least:
```
Validating NetKAN/AbovetheSkySoyuzTMAandR7.netkan...
NetKAN/AbovetheSkySoyuzTMAandR7.netkan:14:4: Warning: Object contains duplicate key: u'depends'
   |  At line 14, column 4, offset 336
   |  Object started at line 1, column 0, offset 0 (AT-START)
```

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
#rebuild

**Pull request merged**
