### PR TITLE
Update ActionGroupManager.frozen

### PR DESCRIPTION
**Pull request by Real-Gecko**
Hook up to ActionGroupManager Continued from SpaceDock

### CODE REVIEW

**Comment by Real-Gecko** [comment]
Alrighty, I've contacted Alshain with PM and he granted permission to index the mod with CKAN.
screenshot_20171103_095955

**Comment by HebaruSan** [comment]
I think https://github.com/KSP-CKAN/CKAN/pull/2170 is causing errors. I'll parlay with those folks about it.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by Real-Gecko** [comment]
Yeeeeeah! Thanks :)

**Pull request merged**
