### PR TITLE
Update InterstellarFuelSwitch.netkan

### PR DESCRIPTION
**Pull request by 602p**
Set up some dependencies and links. Was asked to do this by FreeThinker on the forums.

### CODE REVIEW

**Comment by Dazpoet** [comment]
I'm very confused, does this strictly depend on CRP? I might be able to understand ModuleManager but CRP? Link to forum post and/or explanation would be highly appriciated :)

**Comment by 602p** [comment]
I'm not really sure. Talking to FreeThinker on the KSP forums, they said
>A yes, it the Community Resource Pack is a hard requirement allong with Module Manager
Which I interpreted to mean that it was a dependency (although that _is_ strange.) I'll ask again.

**Comment by Dazpoet** [comment]
On a related note please see https://github.com/KSP-CKAN/NetKAN/pull/1145 which when implemented will supercede this change but I can push any added dependencies and/or recommends/suggests to it.

**Comment by 602p** [comment]
Alright, talked to FreeThinker and they said it should be `suggest`ed.

**Comment by Dazpoet** [comment]
updated #1145 to incorporate these changes and as such I'll close this. Devs are working on a way to make packagesplitting easier which is why the older PR isn't merged yet.

**Pull request closed without merging**
