### PR TITLE
Add Community Real Agency Pack from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of h0yer, to add [Community Real Agency Pack](https://spacedock.info/mod/1543/Community%20Real%20Agency%20Pack) to CKAN.

Mod details:
    name = /mod/1543/Community%20Real%20Agency%20Pack
    author = h0yer
    abstract = CRAP is an agency framework, mostly intended for use with RealismOverhaul. 
    license = GPLv3
    Homepage = https://forum.kerbalspaceprogram.com/index.php?/topic/166314-131-community-real-agency-pack/
    description = 
# Community Real Agency Pack

_v1.0 for KSP v1.3.1_

**Intended for RealismOverhaul**

The _Community Real Agency Pack_ (short _CRAP_^^) is a collection of real world agencies and companies and serves as a manufacturer-framework for modders who make replicas, but can't really decide which manufacturer a part should get, or simply don't bother with that.

The mod started out as a small private learning project, the _"Real Agencies Collection"_, which I have now 'transcended' into some sort of extended community project, since there was 'some' interest in having such a thingy. RAC and CRAP are essentially the same thing, RAC is just for KSP 1.2.2 and CRAP for 1.3.1 and has localization...

The pack contains large 255x160 .png logos for view in mission control, as well as downscaled 64x40 ones for the vehicle assembly building's manufacturer tabs. Almost all logos were taken from wikipedia, and carefully hand-scaled and resized to fit the KSP needs.

And to round it up, it contains a neat selection of background info, in multiple languages, powered by wikipedia and the copypaste foundation, although I'm not really sure where all that info gets displayed, haven't see any of it pop up anywhere yet, hmm... *strokes beard

**(Translation/localization WIP)**

_In a few words:_
CRAP is an agency framework, mostly intended for use with RealismOverhaul.

_Furthermore:_
The _CRAP_ serves as well as reference for any modders, who make replicas, but aren't sure what exact manufacturer tag one should apply for having the parts in the proper manufacturer categories.  
The _CRAP_ heap of agencies is (hopefully) regularily updated, by... heaping up more... agencies :D , or whenever someone has the needs to add manufacturers, that our poor eyes had eluded before.

**Requirements:**
* None yet...

**Recommendations:**
* Makes not much of sense if installed on a stock "Kerbalized" game, since only very few Kerbal-modders use actual manufacturers.
* Install yourselves a fully fledged RealismOverhaul suite :)

**Installation:**
1. Standard procedures apply, first delete any old installments, if present.
2. Extract the contents of "GameData" from the downloaded archive into your ".../KSP/Gamedata/..." folder, keeping subfolder structure. Voilá.

**Support:**
For any manufacturer update requests or bug report, please don't hesitate to open an issue on GitHub or post in he forum.
If you want to participate in any way, just poke me with an ad-equate poking stick, probably the type beeing used on Soyuz keyboards, I like those a lot^^

**Credits:**
* Original Creator: Jan Hoyer (KSP-Forums/GitHub: h0yer)
* The entire RealismOverhaul team, because reasons.
* TiktaalikDreaming (KSP-Forums) for providing the "North American Rockwell Space Division" logo.
* For credits on all other logos, see "CREDITS.TXT" inside the compressed archive or view:
https://github.com/h0yer/CommunityRealAgencyPack/CREDITS.TXT

**License:**
_GPL-3.0_

Please direct questions about this pull request to [h0yer](https://spacedock.info/profile/h0yer).

### CODE REVIEW

**Comment by Olympic1** [comment]
This mod is the same as #5900 but this is made for 1.3.

@h0yer are you planning to keep both mods updating or only one of them?

**Comment by TiktaalikDreaming** [comment]
Olympic1, pretty sure he's abondoning the first, in favour of basically renaming this "Community" to suggest others could assist/contribute, see https://forum.kerbalspaceprogram.com/index.php?/topic/166314-131-community-real-agency-pack-v10/

**Comment by h0yer** [comment]
Hey guys!

I haven't noticed anything going on, sorry, I was jus informed by TiktaalikDreaming^^
Will add the CKAN to the watchlist^^

The old 1.2.2 version "Real Agency Collection" is deprecated/discontinued and has been replaced by "Community Real Agency Pack".

Sorry for casting confusion^^

**Comment by Olympic1** [comment]
No problem, will make a PR later to change this

**Pull request closed without merging**
