### PR TITLE
OPM - Remote hosting of NetKAN metadata

### PR DESCRIPTION
**Pull request by Poodmund**
Update the NetKAN metadata to point to remotely hosted NetKAN metadata.

### CODE REVIEW

**Comment by Poodmund** [comment]
We are planning to manage our own metadata going forward as we have with GPP. I am not sure if the changes made here, to the NetKAN repo data, is correct as I just copied it from the local GPP one. Please advise if necessary.

**Comment by HebaruSan** [comment]
You'll want to keep this part in your remote netkan.

```json
    "x_netkan_epoch": "2",
```

Without it, new versions will be indexed as being older than previous versions.

**Comment by Poodmund** [comment]
As so: https://github.com/Galileo88/Outer-Planets-Mod/blob/master/CKAN/OPM.netkan ?

**Comment by HebaruSan** [comment]
#rebuild

**Comment by Poodmund** [comment]
Ah I see. Thanks for the assistance and the knowledge bomb. 😄

**Pull request merged**
