### PR TITLE
Updating netKAN to cope with the new Redist scheme.

### PR DESCRIPTION
**Pull request by Lisias**

### CODE REVIEW

**Comment by Lisias** [comment]
Uh… I think I will need some assistance on this one.

TL;DR: 
```
 > git fetch --tags --progress https://github.com/KSP-CKAN/NetKAN.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/KSP-CKAN/NetKAN.git
```

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Can you please tell us what this file is for? Installing files directly in `GameData` is prone to conflicts depending on the details.

**Comment by Lisias** [comment]
Scale_Redist.dll is a interface that Add'Ons in need to get called by TweakScale on scaling events needs to import.

Until the moment, each client Add'Ons had their own copy of Scale_Redist. dll on the same folder their DLLs. But this is triggering an Add'On Binder Error fest on KSP >= 1.8 .

It was found that installing Scale_Redist.dll on GameData as 999_Scale_Redist.dll insteading of every Add'On having their own copy had solved the issue.

**Comment by HebaruSan** [comment]
Thanks!

**Pull request merged**
