### PR TITLE
Add SigmaDimensions

### PR DESCRIPTION
**Pull request by dbent**
FYI @Sigma88

`min_version` for `ModuleManager` is from [this comment](http://forum.kerbalspaceprogram.com/index.php?/topic/126548-/&page=10#comment-2402864).

@Sigma88 is there a newer minimum or a minimum required version for Kopernicus?

Since there is no KSP 1.1.x compatible version at the moment, this will currently generate the most recent version compatible with KSP 1.0.5.

Output from `ckan show` on my test KSP 1.0.5 install.
```
D:\Users\Dwayne\Projects\CKAN\NetKAN [feature/sigma_dimensions]> ckan show SigmaDimensions --ksp test-1.0.5.1028
Sigma Dimensions: A universal rescale mod

Module info:
- version:      0.4.3
- authors:      Sigma88
- status:       development
- license:      restricted

Depends:
- ModuleManager, min: 2.6.16
- Kopernicus

Provides:
- SigmaDimensions

Resources:
- homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/126548-/
- repository: https://github.com/Sigma88/Sigma-Dimensions

Filename: 62E1DDD0-SigmaDimensions-0.4.3.zip

Showing 72 installed files:
- GameData/Sigma
- GameData/Sigma/Dimensions
- GameData/Sigma/Dimensions/Configs
- GameData/Sigma/Dimensions/Configs/Bodies
- GameData/Sigma/Dimensions/Configs/Bodies/AllowUserDefined.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Bop.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Dres.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Duna.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Duna_atmo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Eeloo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Eve.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Eve_atmo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Gilly.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Ike.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Jool.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Jool_atmo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Kerbin.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Kerbin_atmo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Bop.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Dres.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Duna.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Eeloo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Eve.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Gilly.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Ike.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Jool.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Kerbin.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Laythe.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Minmus.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Moho.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Mun.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Pol.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Sun.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Tylo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/KittopiaExports/Vall.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Laythe.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Laythe_atmo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Minmus.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Moho.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Mun.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Pol.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Sun.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Sun_atmo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Tylo.cfg
- GameData/Sigma/Dimensions/Configs/Bodies/Vall.cfg
- GameData/Sigma/Dimensions/Configs/General
- GameData/Sigma/Dimensions/Configs/General/caseSensitivityFix.cfg
- GameData/Sigma/Dimensions/Configs/General/diameterFix.cfg
- GameData/Sigma/Dimensions/Configs/General/gravityFix.cfg
- GameData/Sigma/Dimensions/Configs/General/groundTextures.cfg
- GameData/Sigma/Dimensions/Configs/General/massFix.cfg
- GameData/Sigma/Dimensions/Configs/General/removeDuplicates.cfg
- GameData/Sigma/Dimensions/Configs/General/removePQSMods.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension
- GameData/Sigma/Dimensions/Configs/ReDimension/advancedSettings.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/applySettings.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/atmoScale.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/groundScatters.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/newCacheFiles.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/physicsModifier.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/rescaleSCANsat.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/resizeClouds.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/resizeKonstructs.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/resizePQSMods.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/setAsteroids.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/setDimensions.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/setKSCSwitcher.cfg
- GameData/Sigma/Dimensions/Configs/ReDimension/setPQSlevels.cfg
- GameData/Sigma/Dimensions/Configs/Sigma-Dimensions.version
- GameData/Sigma/Dimensions/README.txt
- GameData/Sigma/Dimensions/Settings.cfg
```

### CODE REVIEW

**Comment by Sigma88** [comment]
current release is for **KSP 1.0.5** and **Kopernicus 0.6.3**
I'm working on an update that will bring it up-to-speed with **KSP 1.1.2** and **Kopernicus 1.0.3**

**Comment by dbent** [comment]
@Sigma88 Thanks a lot!

I've updated the metadata with some overrides so that:

- Version **0.4.3** will depend on **ModuleManager>=2.6.19** and **Kopernicus>=0.6.3**
- Versions **>0.4.3** will depend on **ModuleManager>=2.6.23** (the version which added the **&** operator according to the changelog) and **Kopernicus>=1.0.3**.

@plague006 This should be good to go.

**Comment by plague006** [comment]
Rather than coding the depends for the next version into the override can we put them in the main body and just use an override for 0.4.3? Makes maintenance easier.

**Comment by dbent** [comment]
@plague006 Done.

**Comment by plague006** [comment]
:+1:

**Comment by Sigma88** [comment]
out of curiosity, does CKAN gather any information about downloads?
like, which planet packs are downloaded the most alongside SD and stuff like that?

**Comment by plague006** [comment]
No user tracking at the moment nor in the near future. It would be "neat" but we'd probably constantly be accused of spying on people.

**Comment by dbent** [comment]
It's been proposed as an opt-in mechanism KSP-CKAN/CKAN#1566 and I actually like the idea. It's similar to what [pkgstats](https://wiki.archlinux.org/index.php/Pkgstats) does on Arch Linux.

**Comment by Sigma88** [comment]
Honestly the moment you use an internet connection to download stuff you should expect that your download will be registered. KerbalStuff did it, spacedock does it, and github does that as well. But I know what you mean about people complaining, this choice is probably for the best.

**Pull request merged**
