### PR TITLE
Test Flight Continued

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by Olympic1** [comment]
The RO team is maintaining this, they're not so active on it but they released a beta on January 5th.
https://github.com/KSP-RO/TestFlight

**Comment by Blu3wolf** [comment]
Might it be worth adding a conflicts with for TestFlight itself if that is still going to be updated?

**Comment by linuxgurugamer** [comment]
There already is a conflicts in there for TestFlight

**Comment by Blu3wolf** [comment]
Im clearly blind! Whoops

**Pull request closed without merging**
