### PR TITLE
add CommNetAntennasExtension

### PR DESCRIPTION
**Pull request by yalov**
After passing thorough the netkan,  in CKAN - "File/install from .ckan" do nothing

### CODE REVIEW

**Comment by HebaruSan** [comment]
RemoteTechRedevAntennas is only available for 1.3.0 (because that's what's set on SpaceDock), so this mod would have that same limitation. @KSP-TaxiService, should we make that mod available in more versions?

**Comment by KSP-TaxiService** [comment]
I tried to mark the same release file on SpaceDock for both 1.3 and 1.4 and ended up in going with lowest common denominator. I guess I will have to bump version by tiny and put up for 1.4 later.

**Comment by HebaruSan** [comment]
Another option is to include a KSP-AVC .version file in the download. CKAN can consume such files to support the exact version range you wish, for example:

https://github.com/HebaruSan/Astrogator/blob/master/Astrogator.version

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
OK, I added an override to expand RemoteTechRedevAntennas's compatible game versions in #6663. We can still go the .version file route down the line, but for now this should work.

**Pull request merged**
