### PR TITLE
Add MachGauge, MeatlessIndustries, MissionBasedRD, Soylent

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Sending a commit to remove soylent (for the sake of having jenkins check the other 3 independently. Will re-add The soylent commit once jenkins clears.

**Comment by Dazpoet** [comment]
MissionBasedRD and MeatlessIndustries lack homepage entries in the generated .ckan files if you want to add those :)

**Comment by plague006** [comment]
I do.

**Comment by Dazpoet** [comment]
http://rlv.zcache.com/works_on_my_machine_classic_round_sticker-r56ce1cc314be46efbe749e9c58c761d5_v9waf_8byvr_512.jpg

**Pull request merged**
