### PR TITLE
Add Contract Pack: ScanSat Lite

### PR DESCRIPTION
**Pull request by severedsolo**

### CODE REVIEW

**Comment by Dazpoet** [comment]
You need dashes instead of spaces in the license entry.

**Comment by severedsolo** [comment]
Whoops, fixed now sorry

**Comment by severedsolo** [comment]
Just noticed there is a comma missing after scansat dependency, is that a problem?

**Comment by Dazpoet** [comment]
Since SCANsat is the last dependency listed it is not supposed to have a comma so np :)

The build fails because SCANsat isn't available for 1.0.2 yet so the bot can't find an install to satisfy all dependencies. Seems to go through the netkan check fine otherways though. I'll take another look manually and then merge if it checks out.

**Comment by severedsolo** [comment]
Weird, I'm playing on 1.0.2 and have SCANSat installed through CKAN? My mod isn't showing up (probably because of the dependency problem)

Is this something I can resolve, or do I need to take it up with DMagic?

**Comment by Dazpoet** [comment]
Hm are you running the dev build of SCANsat? What version of it does CKAN say you are using?

**Comment by severedsolo** [comment]
CKAN says v12.0 (which I believe is latest stable SCANSat)

**Comment by Dazpoet** [comment]
Oh darn I found the problem and I am afraid it is My fault. You need to change your dependency from SCANSat -> SCANsat

Had I known a stabile build was available I would have caught it sooner, sorry about that.

**Comment by severedsolo** [comment]
No problem I'll put a new PR through, cheers for your help.

**Pull request merged**
