### PR TITLE
Feature/micha maint

### LINKED ISSUE #7742: [Mod] ShipManifest (taking over maintenance)
**Discussion at first; please no changes to Netkan yet!**

Considering taking over Ship Manifest (temporarily?) as [discussed in the forum thread here](https://forum.kerbalspaceprogram.com/index.php?/topic/56643-141-ship-manifest-crew-science-resources-v-5210-17-mar-18/&do=findComment&comment=3747418). 

Wondering what the best approach is given that I **have not** been given the official go-ahead by the author @PapaJoesSoup as I haven't been able to contact him.  But since it's been quite a long time, and the last official release was for KSP1.4, I think it's valid to consider a "hostile" takeover.. ;)

Options are:

1) Create a new mod called "Ship Manifest Continued" (or similar) and mark it as replacing the original mod.

2) Take over the CKAN metadata of the existing mod and point it at my fork of the official repo instead of the current download links.

My preference would be #2 as I would hand the mod back to @PapaJoesSoup as soon as / if he returns and it would be the least disruption for users, at least via CKAN.  Not entirely sure how to handle Spacedock and Curse without his help though.

Would appreciate any recommended "Best Practices" for this situation.

Mod info
--------
* Mod name:  Ship Manifest
* Author(s): Papa_Joe, Micha
* License: CC BY-NC-SA 4.0
* Homepage: TBD (new forum thread?)
* Download: https://github.com/mwerle/ShipManifest/releases

### PR DESCRIPTION
**Pull request by mwerle**
Change maintainer for ShipManifest and ConnectedLivingSpace.

Fixes #7742 

-----

Please review changes and comment whether I've made any mistakes; I always seem to when I commit updated Netkan scripts!

### CODE REVIEW

**Comment by mwerle** [comment]
... @codepoetpbowden  just added me to the original repo for CLS. Please wait before merging as I'll revert to using the original repository for CLS.

**Comment by HebaruSan** [comment]
@mwerle do you want some help with this? If it's just a matter of reverting the changes to CLS, I can do that fairly easily.

**Comment by mwerle** [comment]
Hi @HebaruSan , thanks, but I should be ok.  I was just waiting a few days for people to try my builds via manual GitHub downloads before updating CKAN and letting it lose on the masses in case of any major issues.  I also need to put aside a few hours to update the repo and make sure everything's ok.  Then I'll update this PR.  Sorry for the delay (RL and all that...)

**Comment by mwerle** [comment]
Hmm odd, I thought I had left a comment after my last commit..  anyway, I think this can be merged now.

**Comment by HebaruSan** [comment]
Looks good, thanks for the update!

**Pull request merged**
