### PR TITLE
Create ShaymesAerospace-PSS.netkan

### PR DESCRIPTION
**Pull request by Shaymes**
fix an issue with the filename

### CODE REVIEW

**Comment by techman83** [comment]
@Shaymes I don't know what your intention was here. Closing, but feel free to comment if you have more information.

**Comment by Shaymes** [comment]
i had problems to insert the file and i want prevent double posts, the correct file is in patch 1 branch

**Comment by plague006** [comment]
I had a quick look at what you're trying to add. d6ac2fe won't work because the github repo you're referring to doesn't have any releases of the mod.

**Comment by Shaymes** [comment]
im so confused about github and the ckan manual, i have just texture files that have to add into texturereplacer and a cfg file to add in a different folder, in the manual i read i dont need a download url inside the .netkan but if i try to compile to test it it says required download missing so i  added it and it takes a lot of time to translate all the github and ckan manual stuff. i realy need a simple exlain what i have to do on my reffering site and what ckan needs

**Comment by plague006** [comment]
We can generate the .netkan file for you, but I'll need the KSP forum thread link, and the link to wherever users are supposed to download your mod.

**Comment by Shaymes** [comment]
texture replacer is not my mod and its already released, i only made textures for this mod, 

{
    "spec_version"   : 1,

    "name"           : "Portrait Stats Space Suites",
    "abstract"       : "Add Class/Level based Space Suites (Pilot, Engineer, Scientist, Tourist) for TextureReplacer - delete manual installed versions",
    "identifier"     : "ShaymesAerospace-PSS",
    "author"         : "Shaymes",
    "license"        : "MIT",
    "$kref"          : "#/ckan/github/Shaymes/KSP-Portrait-Stats-Suites",
    "download"       : "https://github.com/Shaymes/KSP-Portrait-Stats-Suites/raw/master/Archive/060.zip",
    "version"        : "0.6.0",
    "release_status" : "stable",
    "ksp_version"    : "any",
    "resources" : {
        "homepage"     : "https://github.com/Shaymes",
        "repository"   : "https://github.com/Shaymes/KSP-Portrait-Stats-Suites"
    },
    "install" : [
        {
            "file"       : "GameData/Suits",
            "install_to" : "GameData/TextureReplacer"
        },
        {
            "file"       : "GameData/ShaymesAerospace",
            "install_to" : "GameData"
        }
    ],
    "depends" : [
        { "name" : "TextureReplacer", "min_version" : "2.4.9" }
    ],
    "recommends" : [
        { "name" : "PortraitStats", "min_version" : "6.0" }
    ]
}

**Comment by plague006** [comment]
For examples of other texture packs and how to pack/host them see:

https://kerbalstuff.com/mod/767
https://kerbalstuff.com/mod/803
and
https://kerbalstuff.com/mod/1025

**Pull request closed without merging**
