### PR TITLE
Updated all my mods to GitHub and KSPAVC

### PR DESCRIPTION
**Pull request by malahx**
Hello, as KerbalStuff is now closed, all my mods can be downloaded on GitHub ;)

### CODE REVIEW

**Comment by dbent** [comment]
Hi, a few things:

- To mix the immediate break `QuickBrake.netkan` needs a comma after `$vref`. There may be other syntax errors, I haven't checked.
- We have no way of getting `name` and `abstract` properties from GitHub, so you'll probably want to set those manually.
- Since you'll be using AVC `.version` files for versioning, the version numbers will not contain a leading `v` like your mods currently have. You should add `"x_netkan_epoch": 1`, this will ensure the versions will be compared correctly.
- You can remove `x_via` properties, they're unnecessary.
- You can also remove `resources.repository`, that will be set automatically.

Since you're updating your own metadata, you may want to consider self-hosting it so you can make changes on your own. Let me know if that's something you're interested in.

Thanks!

**Comment by malahx** [comment]
Thanks for this nice review.
Can I change the autor name to malah with something like this : "author"			: [ "Malah" ], ?
And I don't know if I need to change the spec_version to an other number (many of my mods has v1 and others has v1.4 ...).

**Comment by dbent** [comment]
Yes, either `"author": "Malah"` or `"author": [ "Malah" ]` will work, if it's already present in the metadata we won't override it with the GitHub username.

See the [Spec](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md) for features particular to versions. Importantly if you're using `find` you'll need at least `v1.4`.

**Comment by dbent** [comment]
Hi, the current break is on `QuickIVA.netkan`. There is an extraneous pair of curly braces.

This:
```
"suggests": [
	{
		{ "name"		: "Toolbar" },
		{ "name"    : "RasterPropMonitor" }
	}]
```

Should be:
```
"suggests": [
		{ "name"		: "Toolbar" },
		{ "name"    : "RasterPropMonitor" }
]
```

**Comment by malahx** [comment]
Oups sorry for theses mistakes.

**Comment by dbent** [comment]
@malahx No problem, thank you for taking the time to update your metadata!

We just to address the breaks as the come in. The current break is because of the `.version` file in the `QuickBrake` archive. It's missing a comma after the `DOWNLOAD` property:

```json
{
	"NAME": "QuickBrake",
	"URL": "https://raw.githubusercontent.com/malahx/QuickBrake/master/QuickBrake.version",
	"CHANGE_LOG_URL": "https://raw.githubusercontent.com/malahx/QuickBrake/master/README.md", 
	"DOWNLOAD": "https://kerbalstuff.com/mod/764/QuickBrake"
	"VERSION":{"MAJOR":1,"MINOR":1,"PATCH":0,"BUILD":0},
    "KSP_VERSION": {
        "MAJOR": 1,
        "MINOR": 0,
        "PATCH": 5
    },
    "KSP_VERSION_MIN": {
        "MAJOR": 1,
        "MINOR": 0,
        "PATCH": 5
    },
    "KSP_VERSION_MAX": {
        "MAJOR": 1,
        "MINOR": 0,
        "PATCH": -1
    }
}
```

**Comment by dbent** [comment]
I should also note that `"v1.00"` isn't a valid spec, it's either the numeric literal `1` or `"v1.2"`, `"v1.4"`, etc.

**Comment by malahx** [comment]
I'd thought that I'd corrected this error on my .version files some month ago, my bad :'( Again thank you for all  the time you have pass with me, I think that I write json without my brain. I've corrected the spec_version, all my .version files and release all mods which has this error.

**Comment by dbent** [comment]
Cool, let's see if I #rebuild works.

**Comment by dbent** [comment]
Issue is in QuickContract's `.version` file this time, (comma needed after `DOWNLOAD`).

**Pull request closed without merging**
