### PR TITLE
Quickcursorhider

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Look for problems

### CODE REVIEW

**Comment by politas** [comment]
This got added in the earlier PR, so would need to be re-based

**Comment by linuxgurugamer** [comment]
I don't understand, sorry

**Comment by politas** [comment]
This PR is trying to add a new file that has already been created. It was included in #4408. Thus the conflict.

**Comment by linuxgurugamer** [comment]
Oh, I didn't realize that.

No need for this, the files are identical

**Pull request closed without merging**
