### PR TITLE
Add DeadSkins for AviationLights ReLit from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of StoneBlue, to add [DeadSkins for AviationLights ReLit](https://spacedock.info/mod/1472/DeadSkins%20for%20AviationLights%20ReLit) to CKAN.

Mod details:
    name = /mod/1472/DeadSkins%20for%20AviationLights%20ReLit
    author = StoneBlue
    abstract = A pack of new textures (skins!), for the AviationLights mod.
    license = https://creativecommons.org/licenses/by-nc-sa/4.0/
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/130523-100-130-deadskins-for-aviation-lights-continued-v14b-11-feb-16/
    description = These are FIVE new high-res textures (skins) that are double the resolution of the regular AviationLights.

New skins also include super handy, ultra-futuristic system for quickly finding the light you want from your undoubtedly massive collection of parts!

These are skins only; if you don't have the AviationLights mod yet, what are you waiting for?

Get it now!

##DEPENDENCIES (required mods)

   * [AviationLights](http://forum.kerbalspaceprogram.com/index.php?/topic/16801-13-aviation-lights-v314-by-moardv/)

   * [ModuleManager](http://forum.kerbalspaceprogram.com/index.php?/topic/50533-130-module-manager-281-june-29th-2017-with-n-cats-physics/)

   * And **either** [Firespitter](http://forum.kerbalspaceprogram.com/index.php?/topic/22583-firespitter-propeller-plane-and-helicopter-parts-v71-may-5th-for-ksp-10/) (need v6.3 or later) ,  **or** [Interstellar Fuel Switch](http://forum.kerbalspaceprogram.com/index.php?/topic/106243-13-interstellar-fuel-switch-ifs-261-updated-27-05-2017/)  (Both can be installed at the same time; IFS will take precedence)

 
##RECOMMENDED mod:

   * [Part Icon Fixer & Tweaks](http://forum.kerbalspaceprogram.com/index.php?/topic/91649-10x-part-icon-fixer-amp-tweaks/)   (This is what rotates the editor icons for easier visual identification between the parts)
 

##BONUS FEATURES:

   I've included two custom .cfg files:
   
* One changes the part title that is displayed in the VAB/SPH, so all 7 of the lights are grouped together in the editor. 
* The other is for use with the Part Icon Fixer & Tweaks mod, to display a larger and properly rotated part icon in the editor. 

       (If you dont want to use the functionality these .cfgs offer, just delete them from the /AviationLights folder)

##INSTALLATION:

   Just extract the ZIP and drag/drop or copy/paste the GameData folder to your KSP install folder, click "Yes" to combine with the existing /GameData folder.
   (You should now have a DeadSkins folder inside your GameData folder.)

   ** * MAKE SURE that you also have all the mod dependencies installed already, as they are NOT included with DeadSkins!! **

##LICENSE:
   CC-BY-NC-SA 4.0

##CREDITS:

   * DeadSkins for Aviation Lights Continued is an update of Deadweasel's original DeadSkins for Aviation Lights mod.
   * A BIG shout-out to Skalou, for writing the two bonus patch files for changing the displayed title, and the Part Icon patch, and especially for giving me permission to distribute them in this texture pack.
   * Also, of course, a BIG Thank You to BigNose for creating Aviation Lights in the first place!
   * Thank You to MOARdV for maintaining AviationLights during BigNose's absence.
   * Thanx to xxEvilReeperxx for the Part Icon Fixer & Tweaks mod
   * Thanx to snjo for Firespitter
   * Thanx to Sarbian for ModuleManager :D

Please direct questions about this pull request to [StoneBlue](https://spacedock.info/profile/StoneBlue).

### CODE REVIEW

**Comment by StoneBlue** [comment]
@politas I know I had originally requested to have DeadSkins removed from CKAN, but you can go ahead and approve the automatic SD request to add the new listing.
Thanx!

**Comment by politas** [comment]
@StoneBlue, what is the actual requirement that you're saying can be filled by either Firespitter or InterstellarFuelSwitch? We have both of those mods split up, with core and resources configs split into separate parts.

**Comment by StoneBlue** [comment]
Right now, DeadSkins is using EITHER Firespitter OR Interstellar Fuel
Switch as a dependency, only for texture switching. Either one can be
installed.

My next update has Interstellar Fuel Switch AND B9 Part Switch support,
using mesh switching instead of texture switching. I have not been able to
get Firespitter mesh switching working yet.
When I release the update, it will at least require EITHER Interstellar
Fuel Switch OR B9 Part Switch. Possibly Firespitter as well as, a third
option, if I can get it working.
Should I make note of this and the required dependencies on the automatic
SpaceDock PR for future releases?

Thanx
-Stone Blue

**Comment by politas** [comment]
Hi @StoneBlue, thanks for replying. This is the only PR that will be automatically generated by the SpaceDock system. Updates to mods are handled by a separate system, I have created #5928 to set things up for the current release and get things ready for your next release as much as we can. If you can contact us when you release that new version, we'll need to change the depends from DeadskinsTextureSwitch to DeadskinsMeshSwitch after you release.

**Pull request closed without merging**
