### PR TITLE
Add Fix Real Engines from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Monniasza, to add [Fix Real Engines](https://spacedock.info/mod/2416/Fix%20Real%20Engines) to CKAN.

Please direct questions about this pull request to [Monniasza](https://spacedock.info/profile/Monniasza).

Mod details:
    name = /mod/2416/Fix%20Real%20Engines
    author = Monniasza
    abstract = Fixes all Alcentar's engine mods by removing thrustCurve from them
    license = MIT
    Homepage = 
    description =
This mod fixes following mods:

- RealEngines

- LCA pack

### CODE REVIEW

**Comment by Monniasza** [comment]
Add recommended mods, both from Alcentar: RealEngines and LCA pack.

**Comment by HebaruSan** [comment]
> This mod fixes following mods:

@Monniasza what does it fix about them?

**Comment by HebaruSan** [comment]
Also, these mods are both licensed under GPL-2.0. Have you considered adopting them rather than releasing a separate mod to "fix" them? Formal adoption would be significantly less awkward in many ways.

**Comment by Monniasza** [comment]
> Also, these mods are both licensed under GPL-2.0. Have you considered adopting them rather than releasing a separate mod to "fix" them? Formal adoption would be significantly less awkward in many ways.

I want to adopt mods and fix them.

**Comment by HebaruSan** [comment]
> @Monniasza what does it fix about them?

No answer to this; closing.

**Pull request closed without merging**
