### PR TITLE
Add RealisticRemodel1x

### PR DESCRIPTION
**Pull request by plague006**
Will fail on dependency for `SigmaDimensions`

### CODE REVIEW

**Comment by plague006** [comment]
Local output

````
|   ModuleManager.2.6.24.dll
|   
+---Kopernicus
|   +---Config
|   |       System.cfg
|   |       
|   \---Plugins
|           Kopernicus.Components.dll
|           Kopernicus.dll
|           Kopernicus.OnDemand.dll
|           
+---RealisticRemodel-1x
|   |   SolarSystem.cfg
|   |   
|   \---Compatibility
|       +---OPM
|       |       OPMKopernicus.cfg
|       |       
|       +---Sigma Binary
|       |       Pallo-Chardy.cfg
|       |       
|       \---Sigma Dimensions
|               ProxiAndDeedi.cfg
|               
\---Sigma
    \---Binary
        |   Sigma-Binary.version
        |   
        +---Configs
        |       checkMaxDistance.cfg
        |       generateBarycenters.cfg
        |       generateOrbits.cfg
        |       removeContracts.cfg
        |       
        \---Plugins
                SigmaBinary.dll
                

````

**Comment by politas** [comment]
Needs a dependency on ModuleManager, I think. A .cfg file that starts with this:

    @Kopernicus:BEFORE[SigmaBinary]:NEEDS[!OPM]

looks like a MM script to me. The local output matches up with the included files, as far as I can see.

**Comment by plague006** [comment]
MM dependency added.

**Comment by politas** [comment]
SigmaDimensions should be on KSP 1.1.2 pretty soon. I'm going to merge this so that when @Sigma88 releases, this will appear immediately. Like magic!

**Comment by Sigma88** [comment]
hi guys, I'm waiting for a licensing issue to be resolved before releasing SigmaDimensions for 1.1.2
I expected it to be out yesterday

**Comment by plague006** [comment]
Thanks for the heads up.

**Pull request merged**
