### PR TITLE
Add Stock Visual Enhancements from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Nhawks17, to add [Stock Visual Enhancements](https://kerbalstuff.com/mod/1263/Stock%20Visual%20Enhancements) to CKAN.

Please direct questions about this pull request to [Nhawks17](https://kerbalstuff.com/profile/Nhawks17).

### CODE REVIEW

**Comment by Olympic1** [comment]
This mod requires EVE, which requires #2553 to be merged first. It also recommends Scatterer for atmospheric effects and Kopernicus for Jool's rings.

There are two downloads available on the [thread](http://forum.kerbalspaceprogram.com/threads/137223) and [GitHub](https://github.com/Nhawks1717/StockVisualEnhancements/releases):
* `SVE Overhaul` - Which requires the development version of EVE.
* `SVE Release` - Which requires the released version of EVE.

Both downloads, on GitHub, have 4 seperate `.zip` files each for low, medium, high and ultra resolutions. The KerbalStuff page only includes the `SVE Release` with medium resolution textures.

@Nhawks1717, is this correct? More info is helpfull.

**Comment by Nhawks1717** [comment]
Yes this is correct. The SVE Overhaul version does not need to be added to CKAN, only the release version. If possible It'd be awesome to have all of the resolutions that are on GitHub to be added to CKAN. I didn't see a way to add multiple zips on Kerbal Stuff :) If you need anymore information just let me know.

**Comment by Olympic1** [comment]
Adding all the resolutions will be possible. The same method will be used as we use for installing RSS Textures.

**Comment by Nhawks1717** [comment]
Awesome! Sounds good to me then :D

**Pull request closed without merging**
