### PR TITLE
Add Kerbodyne Plus 0.1 Alpha from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
# Author needs to change install directory
This pull request was automatically generated by Kerbal Stuff on behalf of BonusEventus, to add [Kerbodyne Plus 0.1 Alpha](https://kerbalstuff.com/mod/906/Kerbodyne%20Plus%200.1%20Alpha) to CKAN.

Please direct questions about this pull request to [BonusEventus](https://kerbalstuff.com/profile/BonusEventus).

## TODO
- [ ] `license` should be CC-BY-NC-SA-4.0
- [ ] `__MACOSX` directory needs to be filtered
- [ ] `.DS_Store` files needs to be filtered
- [ ] Install location needs to be decided

### CODE REVIEW

**Comment by plague006** [comment]
Read the forum thread, they *do* plan on changing the folder name/structure. I informed them that as soon as the folder name is finalized, the mod can easily be added to CKAN.

**Comment by pjf** [comment]
I'm burning through PRs as best I can today. It looks like we can have this installed to `GameData/Custom` with the current configuration. Working on a file now. :)

**Comment by pjf** [comment]
Have a file that looks good:

```
Showing 68 installed files:
- GameData/Custom
- GameData/Custom/license.txt
- GameData/Custom/Parts
- GameData/Custom/Parts/booster
- GameData/Custom/Parts/booster/booster.cfg
- GameData/Custom/Parts/booster/booster.mu
- GameData/Custom/Parts/booster/booster.png
- GameData/Custom/Parts/decoupler
- GameData/Custom/Parts/decoupler/decoupler.cfg
- GameData/Custom/Parts/decoupler/decoupler.mu
- GameData/Custom/Parts/decoupler/decoupler.png
- GameData/Custom/Parts/extremeDockingPort
- GameData/Custom/Parts/extremeDockingPort/extremeDockingPort.cfg
- GameData/Custom/Parts/extremeDockingPort/extremeDockingPort2_diff.png
- GameData/Custom/Parts/extremeDockingPort/extremeDockingPort_1m.mu
- GameData/Custom/Parts/extremeDockingPort/extremeDockingPort_2m.cfg
- GameData/Custom/Parts/extremeDockingPort/extremeDockingPort_3m.cfg
- GameData/Custom/Parts/H90
- GameData/Custom/Parts/H90/H80.cfg
- GameData/Custom/Parts/H90/H80.mu
- GameData/Custom/Parts/H90/H90.cfg
- GameData/Custom/Parts/H90/H90.mu
- GameData/Custom/Parts/H90/hardPoint.png
- GameData/Custom/Parts/k303
- GameData/Custom/Parts/k303/16m_375Tank_ao.png
- GameData/Custom/Parts/k303/k303_16_375.cfg
- GameData/Custom/Parts/k303/k303_16_375.mu
- GameData/Custom/Parts/modularHangar
- GameData/Custom/Parts/modularHangar/converter.cfg
- GameData/Custom/Parts/modularHangar/converter.mu
- GameData/Custom/Parts/modularHangar/converter.png
- GameData/Custom/Parts/modularHangar/converterEmissive.png
- GameData/Custom/Parts/modularHangar/faceplate.cfg
- GameData/Custom/Parts/modularHangar/faceplate.mu
- GameData/Custom/Parts/modularHangar/faceplate.png
- GameData/Custom/Parts/modularHangar/faceplateEmissive.png
- GameData/Custom/Parts/modularHangar/modularHangar.cfg
- GameData/Custom/Parts/modularHangar/modularHangar.mu
- GameData/Custom/Parts/modularHangar/modularHangarCap.cfg
- GameData/Custom/Parts/modularHangar/modularHangarCap.mu
- GameData/Custom/Parts/modularHangar/modularHangarDiff.png
- GameData/Custom/Parts/modularHangar/modularHangarEmissive.png
- GameData/Custom/Parts/modularHangar/modularHangarHollow.cfg
- GameData/Custom/Parts/modularHangar/modularHangarHollow.mu
- GameData/Custom/Parts/modularHangar/modularHangarHollow2.cfg
- GameData/Custom/Parts/modularHangar/modularHangarHollow2.mu
- GameData/Custom/Parts/modularHangar/moduleHangarHollow.mu
- GameData/Custom/Parts/modularHangar/serviceModule_emissive.png
- GameData/Custom/Parts/modularHangar/sideTank.cfg
- GameData/Custom/Parts/modularHangar/sideTank.mu
- GameData/Custom/Parts/modularHangar/sideTank.png
- GameData/Custom/Parts/modularHangar/T303.cfg
- GameData/Custom/Parts/modularHangar/T303.mu
- GameData/Custom/Parts/modularHangar/triTruss.png
- GameData/Custom/Parts/plasmaThruster
- GameData/Custom/Parts/plasmaThruster/plasmaThruster.cfg
- GameData/Custom/Parts/plasmaThruster/plasmaThruster.mu
- GameData/Custom/Parts/plasmaThruster/plasmaThruster.png
- GameData/Custom/Parts/plasmaThruster/plasmaThrusterLuminous.png
- GameData/Custom/Parts/QuadAdapter
- GameData/Custom/Parts/QuadAdapter/3_75_2_5_quadAdapter.cfg
- GameData/Custom/Parts/QuadAdapter/3_75_2_5_quadAdapter.mu
- GameData/Custom/Parts/QuadAdapter/quad_adapter.png
- GameData/Custom/readme.txt
- GameData/Custom/Sounds
- GameData/Custom/Sounds/sound_large_blast.wav
- GameData/Custom/Sounds/sound_large_booster-old1.wav
- GameData/Custom/Sounds/sound_large_booster.wav
```

PR coming in soon.

**Comment by pjf** [comment]
Bam! #2422 supersedes this now. :)

**Pull request closed without merging**
