### PR TITLE
Add Lights Out from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of RealGecko, to add [Lights Out](https://spacedock.info/mod/1006/Lights%20Out) to CKAN.

Mod details:
    name = /mod/1006/Lights%20Out
    author = RealGecko
    abstract = Add day and night modes to the VAB and SPH! Turn off the lights in the editors! Works at all upgrade levels!
    license = MIT
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/102558-105-lightsout-v015-daynight-mode-in-vabsph/
    description = Version 1.2 of [nodrog6](http://spacedock.info/profile/nodrog6) mod with [Fwiffo](http://forum.kerbalspaceprogram.com/index.php?/profile/148084-fwiffo/) additions.

Please direct questions about this pull request to [RealGecko](https://spacedock.info/profile/RealGecko).

### CODE REVIEW

**Comment by Real-Gecko** [comment]
I don't understand why checks fail.

**Comment by Olympic1** [comment]
'LightsOut' matches an existing frozen identifier: NetKAN/LightsOut.frozen

**Comment by Olympic1** [comment]
merging

**Comment by Real-Gecko** [comment]
Nice :)

**Pull request merged**
