### PR TITLE
Fix JPLRepo mods - AmpYear DeepFreeze TarsierSpaceTech

### PR DESCRIPTION
**Pull request by JPLRepo**

### CODE REVIEW

**Comment by Dazpoet** [comment]
#rebuild

**Comment by JPLRepo** [comment]
I don't understand? Have I done something wrong?
Why has this failed?

I keep getting badgered by users wanting me to add support for this CKAN but this is the second time I have attempted to follow the instructions only to have some issue?

**Comment by Dazpoet** [comment]
It seems our bot is running into some issues with an inconsistency not in your mods. We'll have to check this one out manually.

**Comment by JPLRepo** [comment]
Ok that's fine. As long as it isn't something I am doing wrong.
Thanks.

**Comment by Dazpoet** [comment]
Haven't had the time to check this yet, hoping to get around to it soon enough.

**Pull request merged**
