### PR TITLE
Update SimpleConstruction.netkan

### PR DESCRIPTION
**Pull request by Real-Gecko**
- Updated license
- Removed `x_netkan_force_v` to avoid odd version numbering
- Removed installation directives.

### CODE REVIEW

**Comment by Real-Gecko** [comment]
Connected with https://github.com/KSP-CKAN/CKAN-meta/pull/1238

**Comment by Dazpoet** [comment]
Does the client know what to do nowadays when we flat out remove a lot of metadata like in https://github.com/KSP-CKAN/CKAN-meta/pull/1238 ? I recall it being an issue but I'm not sure how it's now. Another solution could be the addition of an [epoch](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#epoch) using the [x_netkan_epoch](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#x_netkan_epoch)

**Comment by Real-Gecko** [comment]
So, if I make `"epoch": 1` that will solve current version numbering problem and there will be no need for https://github.com/KSP-CKAN/CKAN-meta/pull/1238?

**Comment by politas** [comment]
Yes, that's correct. Deleting metadata from the repository doesn't update the current installed version metadata, so any users who have say "v3.4" installed will never see a "3.5" release as an upgrade, even if the repository now contains only "3.3", "3.4", "3.5". Otherwise, users would not be able to usefully install from a .ckan file.

Changing the epoch is the right way to reset the versions if you really feel it is necessary to not have "v" on the CKAN version numbers.

**Comment by Real-Gecko** [comment]
Did that.
Prior to version 3.1 version numbering [was ok](http://spacedock.info/mod/59/SimpleConstruction#changelog), like `2.2`, `3.0`, but starting from version 3.1 MatterBeam started to add something like this: `Version_3.1`, reason is unknown to me, but it now caused problems with new version. I have `3.4.1` released already, but client still thinks that `Version_3.3` is major:
screenshot_20161201_024836

**Comment by Real-Gecko** [comment]
So?

**Comment by Real-Gecko** [comment]
So, I think I found a better solution by adding "x_netkan_version_edit", but now build fails with error
`CKAN.FileNotFoundKraken: Trying to install SimpleConstruction vVersion_3.3, but it's not downloaded or download is corrupted` as it tries to get deleted version from Spacedock.
But I also noticed that install section is like this
```
About to install...

 * SimpleConstruction vVersion_3.3
 * Module Manager 2.7.5
 * Interstellar Fuel Switch Core 2.2.9
 * TweakScale - Rescale Everything! v2.3.2
```
Why does it tries to install TweakScale?

**Comment by politas** [comment]
Versions are now 404, so...

**Comment by Real-Gecko** [comment]
Thanks!

**Comment by politas** [comment]
Ah, damn. Thought this was the other one.

**Comment by Real-Gecko** [comment]
Emm, version 3.4.1 is not doubled in CKAN-meta:
```
 		SimpleConstruction/SimpleConstruction-3.4.1.ckan
		SimpleConstruction/SimpleConstruction-v3.4.1.ckan
```

**Comment by politas** [comment]
Yeah, sorry, I really didn't mean to merge this change. We need an epoch or we can't ditch the "v"

**Pull request merged**
