### PR TITLE
Update SimpleConstruction.netkan

### PR DESCRIPTION
**Pull request by zer0Kerbal**
I think I left all the 'auto' fields alone.

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
okay, what I'd do wrong this time. 🐙

**Comment by zer0Kerbal** [comment]
darn extra spaces... thank you.

**Comment by HebaruSan** [comment]
Thanks for the update! Appreciate you saving us the work of looking up all this info.

**Comment by zer0Kerbal** [comment]
thank you for doing all the work!

**Pull request merged**
