### PR TITLE
SpaceY-Expanded: Update for spacedock

### PR DESCRIPTION
**Pull request by NecroBones**

### CODE REVIEW

**Comment by Olympic1** [comment]
I found a `1.1.5` version for the mod in CKAN-meta

Failed because `couldn't download or download is corrupted`

**Comment by Olympic1** [comment]
@NecroBones, I found a `1.1.5` version for the mod in CKAN-meta

After investigating I noticed that you called the latest version `1.1.4` while you mention `1.1.5` in the changelog. The `.zip` is also called `1.1.4` but includes files from `1.1.5`.

**Comment by NecroBones** [comment]
Yes, I think I probably typed it wrong in the spacedock version field. Spacedock (like Kerbalstuff) renames based on the provided version. I'll reupload and clear it up.

**Comment by NecroBones** [comment]
@Olympic1 Yep, I had simply uploaded 1.1.4 as 1.1.5. I've corrected it on Spacedock.

**Comment by Olympic1** [comment]
Thanks. To fix this and your other PR's, you have to rebase because we added the`.kerbalstuff` extension to all mods that were on KS.

**Comment by NecroBones** [comment]
Not sure I follow. I see that the filename extensions were changed. Does that mean I need to scrap this pull request and re-do it?

**Comment by Olympic1** [comment]
yes

**Comment by plague006** [comment]
Other than the conflict, is this ready for merge @Olympic1?

**Comment by Olympic1** [comment]
yes

**Comment by NecroBones** [comment]
OK, still learning my way around GitHub. :) I'm forgetting that I have an actual branch. :) Thanks guys!

**Comment by plague006** [comment]
@NecroBones No worries, I'm having.. "fun"? Trying to figure out how to solve merge conflicts. :D

**Pull request merged**
