### PR TITLE
Add Corvus -1.25m Two Kerbal Pod from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of OrionKermin, to add [Corvus -1.25m Two Kerbal Pod](https://kerbalstuff.com/mod/837/Corvus%20-1.25m%20Two%20Kerbal%20Pod) to CKAN.

Please direct questions about this pull request to [OrionKermin](https://kerbalstuff.com/profile/OrionKermin).

### CODE REVIEW

**Comment by mgsdk** [comment]
Also, the homepage is not listed directly on KS in the metadata, but in the description instead. http://forum.kerbalspaceprogram.com/threads/121062

**Comment by politas** [comment]
I'm not sure how to handle either the licence or the install for this one, so I'll leave it for more experienced NetKANers.

**Comment by Dazpoet** [comment]
License should indeed be "restricted" and I'm not sure how we should resolve the HGR problem. It has been requested that we add it [here](https://github.com/KSP-CKAN/NetKAN/issues/1261) so I guess the correct course of action would be to add HGR before this mod is added and then set it as a dependency for this.

Adding a blocked-on-other for now until the depedency can be fulfilled.

**Comment by politas** [comment]
It doesn't really need the whole of HGR, though. The reason HGR is held up doesn't apply to the limited parts this mod wants to use.

**Comment by politas** [comment]
Could we make a "provides/conflicts" pack that can be also provided by full HGR when it is sorted out?

**Comment by Dazpoet** [comment]
We could have but I much prefer https://github.com/KSP-CKAN/CKAN-meta/pull/540 :)

**Pull request closed without merging**
