### PR TITLE
Add Apollo OLD from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of dibella55, to add [Apollo OLD](https://kerbalstuff.com/mod/1115/Apollo%20OLD) to CKAN.

Please direct questions about this pull request to [dibella55](https://kerbalstuff.com/profile/dibella55).

### CODE REVIEW

**Comment by plague006** [comment]
Another broken mod. Followed the [link](http://forum.kerbalspaceprogram.com/threads/70557-APOLLO-%28SATURN-V-with-F1-J2-APOLLO-CSM-LEM-LLRV%29-by-OLDD-%28v-1-4-09-05-14%29) on the KS page description and according to that thread the mod doesn't work under 1.0.

**Comment by Dazpoet** [comment]
Does it work for earlier versions of KSP? If so we might be able to hardcode it to those versions?

**Comment by plague006** [comment]
It probably does work with earlier versions, but I don't have old versions of the game. If you choose to index it, I would suggest indexing directly via the mod author's links and not this KerbalStuff re-upload.

**Comment by Dazpoet** [comment]
Hm I don't have any old versions to test with either so I label this as needs looking into then :)

**Comment by plague006** [comment]
Closing this due to age. It seems nobody has a version with which to test if this mod runs. Can be re-opened if someone looks into it.

**Pull request closed without merging**
