### PR TITLE
Fix StockPlus

### PR DESCRIPTION
**Pull request by Olympic1**
Search for the `.zip` file.

Testing locally installs the required file

### CODE REVIEW

**Comment by techman83** [comment]
LGTM! Merging with thanks!

**Comment by plague006** [comment]
Still fails. @techman83 can you have a look into what's going wrong?

**Comment by Olympic1** [comment]
It only fails for netkan-bot, because locally they download it correctly.

**Comment by plague006** [comment]
Yes. That's been the case for weeks.

**Comment by techman83** [comment]
O.o - Ran it by hand with the NetKAN user + netkan.exe that the bot uses (which is updated automatically) and it worked fine... It's just in the process of doing it's latest run, will have a look afterwards. You've all been doing amazing as those are the last 2 showing errors in the logs! :D

**Comment by techman83** [comment]
Ok Fixed. The Download URL hadn't changed so the cached download hadn't been replaced. Which was different to whatever it refers to now. KSP-CKAN/NetKAN-bot#16 will help deal with this.

**Pull request merged**
