### PR TITLE
Add missing dependency for Mk3HypersonicSystems

### PR DESCRIPTION
**Pull request by plague006**

### CODE REVIEW

**Comment by plague006** [comment]
Again would appreciate an after-the-fact review.

**Comment by politas** [comment]
There's a new thread for it that should replace the homepage: http://forum.kerbalspaceprogram.com/index.php?/topic/137782-11-mk3-hypersonic-systems-release

**Comment by politas** [comment]
Also, CrossFeedEnabler is obsolete, and the mod author should be using the stock methods for enabling crossfeed.

**Comment by plague006** [comment]
> new thread

Done in https://github.com/KSP-CKAN/NetKAN/commit/3d7b2b3247a3ac2fc86a8ab9bbc539c30fc9abf1

> CrossFeedEnabler is obsolete

Correct but I'm not sure why you're saying this.

**Comment by politas** [comment]
>> CrossFeedEnabler is obsolete

>Correct but I'm not sure why you're saying this.

Neither am I, now.

**Pull request merged**
