### PR TITLE
Update asset_match for InfernalRobotics

### PR DESCRIPTION
**Pull request by plague006**
That last asset_match I wrote was true facepalm. :(

### CODE REVIEW

**Comment by plague006** [comment]
As this is a highly sought after mod and this is a very small change, merging.

**Comment by politas** [comment]
I would probably go with `^IR.*Core\\.zip` to ensure that it starts with "IR", but I enjoy complex regexps.

**Comment by plague006** [comment]
"IR" could so easily change to "InfernalRobotics" is the reason I balked at it.

**Comment by politas** [comment]
Ok, then `^I.*Core\\.zip`

**Pull request merged**
