### PR TITLE
Add PhotoRealisticVisualEnhancement

### PR DESCRIPTION
**Pull request by HebaruSan**
See #9014, the author @SpaceODY requested this mod to be added, then later closed the request with plans to set things up differently.

https://github.com/SpaceODY/PRVE

### CODE REVIEW

**Comment by HebaruSan** [comment]
- [ ] Probably needs to `provides`/`conflicts` some of the virtual config modules
- [ ] The repo says this is derived from 6 prior mods, so we should check them to make sure the license is OK
- [ ] The Scatterer dependency should be versioned

**Comment by HebaruSan** [comment]
Hmm, I'm guessing it's bad to mix and match versions here:

```
   * scatterer 3:v0.0772 (spacedock.info, 51.6 MiB)
   * Scatterer Default Config 3:v0.0831 (cached)
```

**Comment by SpaceODY** [comment]
I just updated the mod to better support ckan. The base mod download hasn't changed but the 64k addon has. The configs now overwrite other files via module manager. There is a separate gamedata folder for this addon labeled "PRVE-64k" now.

As for the scatterer v0.08 configs leave them off of ckan for now. If people wish to have them they will need to manually download it.

**Comment by HebaruSan** [comment]
All the licenses that were easy to check, check out fine. The situation with KSRSS is painfully complicated, so we'll let them worry about checking that everyone's following all the rules and complain if they find problems. :relieved:

**Comment by SpaceODY** [comment]
Alright, thank you for the help!

**Comment by HebaruSan** [comment]
> Also, whenever I release a new version, how do I go about updating it on ckan?

CKAN will do that for you automagically when you upload a new release to GitHub (within 30 minutes or so). If you want to make changes to the compatibility or dependencies, you can either try editing the netkans yourself in a pull request, or describe the changes in a new issue like you did in #9014.

**Pull request merged**
