### PR TITLE
Update WildBlue-PlayMode-CRP.netkan

### PR DESCRIPTION
**Pull request by ProgrammerFailure**
The latest update of this mod includes a new omnistorage.txt. This adds that to install instructions.

### CODE REVIEW

**Comment by ProgrammerFailure** [comment]
BTW, with @Angel-125's latest release of wildbluetools, someone should take a look at the metadata for all the playmodes. 

Any files added or deleted will likely require editing the netkan.

**Comment by HebaruSan** [comment]
Thanks for pointing this out!

> BTW, with @Angel-125's latest release of wildbluetools, someone should take a look at the metadata for all the playmodes.
> 
> Any files added or deleted will likely require editing the netkan.

Yup, we know. That's what these are about:

- https://github.com/KSP-CKAN/NetKAN/blob/b8f86f078967975f50ebff091ecc14575267c132/NetKAN/WildBlue-PlayMode-CRP.netkan#L10-L11
- KSP-CKAN/CKAN-meta#3258
- KSP-CKAN/CKAN-meta#3259
- KSP-CKAN/CKAN-meta#3260
- KSP-CKAN/CKAN-meta#3261
- KSP-CKAN/CKAN-meta#3262
- KSP-CKAN/CKAN-meta#3263
- KSP-CKAN/CKAN-meta#3264
- KSP-CKAN/CKAN-meta#3265
- KSP-CKAN/CKAN-meta#3266
- KSP-CKAN/CKAN-meta#3267
- KSP-CKAN/CKAN-meta#3268
- KSP-CKAN/CKAN-meta#3269
- KSP-CKAN/CKAN-meta#3270
- KSP-CKAN/CKAN-meta#3271
- KSP-CKAN/CKAN-meta#3272

Don't worry, this change would have been manually reviewed.

**Comment by ProgrammerFailure** [comment]
Oh, didn't realize it was automated. So presumably my change wasn't needed? Will close soon

**Review by HebaruSan — APPROVED** [review]
Let's go with this edit.

There's an automated system to trigger manual reviews, but we'd still have to make a change like this one way or another, and this looks good. Thanks for the update.

**Comment by ProgrammerFailure** [comment]
@HebaruSan 
Just noting here that I think all the netkans for various WBI playmodes are correct. I couldn't find any issues with any of them.

**Pull request merged**
