### PR TITLE
Add Stockalike Mining Extension from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Suicidalinsanity, to add [Stockalike Mining Extension](https://kerbalstuff.com/mod/1415/Stockalike%20Mining%20Extension) to CKAN.

Please direct questions about this pull request to [Suicidalinsanity](https://kerbalstuff.com/profile/Suicidalinsanity).

### CODE REVIEW

**Comment by politas** [comment]
Mixes up folders with Mk2Expansion in a way that's likely to cause problems.

**Comment by plague006** [comment]
Currently this mod adds a resources folder not present in mk2exp. and wants to replace the agencies folder (which are identical in both mods). If the mod author plans on adding resources to mk2exp. or plans on changing the agencies between both mods, there should be no issues.


MD5 checksum comparison:
````
21 files in digest file. 18 errors.

OK	MD5	Agencies\Agents.cfg
OK	MD5	Agencies\IA.png
OK	MD5	Agencies\IA_scaled.png
FAIL	MD5	Agencies\Thumbs.db
File does not exist: Parts\Resource\Generator\fuellcell.dds
File does not exist: Parts\Resource\Generator\mk2FuselageShort.dds
File does not exist: Parts\Resource\Generator\Model.mu
File does not exist: Parts\Resource\Generator\part.cfg
File does not exist: Parts\Resource\ISRUDrill\mk2FuselageShort.dds
File does not exist: Parts\Resource\ISRUDrill\Model.mu
File does not exist: Parts\Resource\ISRUDrill\RadialDrill.cfg
File does not exist: Parts\Resource\ISRUDrill\TriBitDrill.dds
File does not exist: Parts\Resource\OreTank\ksp_l_resourceContainer_diff.dds
File does not exist: Parts\Resource\OreTank\mk2FuselageShort.dds
File does not exist: Parts\Resource\OreTank\Model.mu
File does not exist: Parts\Resource\OreTank\part.cfg
File does not exist: Parts\Resource\Refinery\ISRU.cfg
File does not exist: Parts\Resource\Refinery\ksp_s_processorSmall_diff.dds
File does not exist: Parts\Resource\Refinery\mk2FuselageShort.dds
File does not exist: Parts\Resource\Refinery\Model.mu
File does not exist: Parts\Resource\Refinery\Processor_Large.dds
````

**Comment by politas** [comment]
If we split the Agencies into a separate mod that they both have a dependency on, and filter out the Agencies from both mods, it should work fine.

**Comment by plague006** [comment]
Closing for #3052

**Pull request closed without merging**
