### PR TITLE
Add "config" to RSE-default display name

### PR DESCRIPTION
**Pull request by JonnyOThan**
There's some confusion about what this module is and whether it's necessary, this might help

### CODE REVIEW

**Comment by HebaruSan** [comment]
That was actually specifically requested by the author in #9044, unless there was some misunderstanding there, which is very possible.

**Comment by JonnyOThan** [comment]
As always thanks for the background!  I think your take is correct.  @ensou4 any thoughts here?  This doesn't come up *that* often but I just saw someone on discord that was confused about what to install.

**Comment by HebaruSan** [comment]
Let's leave this alone for now until we can confirm it wouldn't miff the author.

**Comment by ensou04** [comment]
> As always thanks for the background! I think your take is correct. @ensou04 any thoughts here? This doesn't come up _that_ often but I just saw someone on discord that was confused about what to install.

[Rocket Sound Enhancement](https://github.com/ensou04/RocketSoundEnhancement) the Plugin is the brains behind the mod, it doesn't have any library of sounds or configs. Can be installed alone and it'll provide sound muffling and other basic atmospheric sound filtering.

[Rocket Sound Enhancement - Default](https://github.com/ensou04/RocketSoundEnhancementDefault) is the library of sounds and configs that replaces the stock and supported mod sound effects plus additional atmospheric effects. It requires the plugin to function. 

Separated them because they're technically two different mods and had different development cycles, didn't want to constantly be uploading a large library of files every time we updated the plugin.

**Pull request closed without merging**
