### PR TITLE
Update CivilianPopulation.netkan

### PR DESCRIPTION
**Pull request by rabidninjawombat**
hopefully i've formatted this correctly(feel free to double check it) . But i am attempting to update and list Civilian Population on CKAN (ive recently taken over development from the previous dev MichaelHester07)  Pretty sure its not actively listed because of the old file having a dependency on Regolith which is defunct.

(its currently downloadable via Kerbalstuff, but I know the info in the NetKan is out of date)

Thanks for any help :)

### CODE REVIEW

**Comment by Dazpoet** [comment]
The last comma on line 16 isn't needed and both [ExtraplanetaryLaunchpads](https://github.com/KSP-CKAN/CKAN-meta/blob/master/ExtraPlanetaryLaunchpads/Extraplanetary-Launchpads-5.1.94.ckan) and [Hangar Extender](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/HangarExtender.netkan) are available in CKAN :)

**Comment by rabidninjawombat** [comment]
Awesome, for some reason i couldnt fine them earlier.  Feel free to add them to the suggestions (or if you need me to i can edit the pull request.

**Comment by Dazpoet** [comment]
Line 16 needs the finishing comma removed and lines 19 and 20 need the same kind of commas added :) you can try running your file through jsonlint.com to check for correctness if you want.

**Comment by rabidninjawombat** [comment]
Fixed and validated... sorry bout the issues :)

**Comment by Dazpoet** [comment]
fails because it builds a version that already exists in CKAN-meta. I'm merging this which will push the needed changes to that repository in a few hours (<6) and then everything should be fine and dandy.

**Comment by rabidninjawombat** [comment]
Thank you sir, exactly what i was looking for.

**Pull request merged**
