### PR TITLE
New entry for LaserDist mod I just released

### PR DESCRIPTION
**Pull request by Dunbaratu**
I just released LaserDist on spacedock and github (soon to be Curse also once I finish submitting this PR for NETKAN).  This is the new netkan entry for it.

### CODE REVIEW

**Comment by politas** [comment]
Could you make the homepage link go to your forum thread, instead? The github $kref will add a link to your repository automatically.
Also, I note you have an AVC .version file. You could use a $vref to automatically keep the KSP version information updated.
  
    "$vref": "#/ckan/ksp-avc",

**Comment by Dunbaratu** [comment]
I've edited the PR with the requested changes. (but I really don't see the forum post as being the mod's home page.  To me the github page is more "homepage like" than the forum post.

**Comment by Cphoenix** [comment]
When the NetKAN bot goes to your GitHub repo to get more metadata, it'll add a link to the repository (it goes in resources->repository). So users will see both a link to the forum page **and** the GitHub repo in CKAN.

**Comment by Cphoenix** [comment]
It is worth noting that this way, users will see both links in the CKAN application.

**Comment by politas** [comment]
Thanks for the update. This looks great. Merging now!

**Pull request merged**
