### PR TITLE
RocketSoundenhancement

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
@HebaruSan Can you please check these.  There are two different zip files, in different releases in the github repo.  Not sure how to fix

**Comment by linuxgurugamer** [comment]
also, the failure is unknown to  me

**Comment by HebaruSan** [comment]
The failure is this.

```
Installing mod "RocketSoundEnhancement-defaultConfigs 0.5.1"
Installing mod "RocketSoundEnhancement 0.5.1"
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/RocketSoundEnhancement/Plugins/LICENSE.txt
Installing Mod : RocketSoundEnhancement 0.5.1
Owning Mod     : RocketSoundEnhancement-defaultConfigs
CKAN Version   : v1.29.1

Your GameData has been returned to its original state.

Build step 'Execute shell' marked build as failure
```

**Comment by HebaruSan** [comment]
@linuxgurugamer added some `asset_match` sections to the krefs, seems to have worked. Don't worry about the Java exceptions, Jenkins is on the fritz and pending replacement.

- https://ci.ksp-ckan.space/job/NetKAN/10242/console

Both modules have the same `name` now, should override it for the configs:

```
About to install...

 * Rocket Sound Enhancement 0.5.0 (cached)
 * Rocket Sound Enhancement 0.5.1 (cached)
 * Module Manager 4.1.4 (cached)
```

**Pull request merged**
