### PR TITLE
Add FuelSwitch to every tank from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of micha030201, to add [FuelSwitch to every tank](https://kerbalstuff.com/mod/861/FuelSwitch%20to%20every%20tank) to CKAN.

Please direct questions about this pull request to [micha030201](https://kerbalstuff.com/profile/micha030201).

### CODE REVIEW

**Comment by plague006** [comment]
I jumped into this one thinking it would be a standard one, it's not. I think this mod needs to be split into 2 (default and thermal paint versions) packages on our end. In addition, Thermal Paint mod (http://forum.kerbalspaceprogram.com/threads/123279) will likely need to be added to make things coherent.

**Comment by Dazpoet** [comment]
I wonder if this collides with StockFuelSwitch which I gather does much the same thing? Marking this as a "needs looking into" since I'm not sure how to handle it.

And yes, thermal paint will probably have to be added, although it's only available on curse so it'll have to go into CKAN-meta.

**Comment by plague006** [comment]
If someone else could try this mod.. I couldn't see any effect from it being installed. I tried StockFuelSwitch and that had the expected outcome (tweakable on fuel tanks in the VAB).

**Comment by plague006** [comment]
Daz pointed out why the mod wasn't working (missing bracket in the mod itself).

**Pull request closed without merging**
