### PR TITLE
Update SmartParts.netkan

### PR DESCRIPTION
**Pull request by SirDiazo**
I am taking over this mod, at least temporarily, so it has to point to my GitHub to pickup the new releases.

### CODE REVIEW

**Comment by Dazpoet** [comment]
I see a file named KISConfig.cfg, does that require ModuleManager and should this mod then depend on it?

**Comment by SirDiazo** [comment]
No.

KISConfig.cfg is an optional file for inter-operability with Kerbal Inventory System. Smart Parts does not require Module Manager.

**Comment by SirDiazo** [comment]
Just poking this.

I posted in my forum thread that I had updated CKAN, but until this is merged that isn't true.

**Comment by Dazpoet** [comment]
Sorry for being slow but our NetKAN manager (me) is currently in the process of moving so I'm doing these things on a laptop, over 3G, in the forest :p

**Pull request merged**
