### PR TITLE
Added at request of author

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by plague006** [comment]
You can omit `author` `name` and `abstract` for KerbalStuff netkans. Netkan.exe will insert all that information from the KerbalStuff page. The benefit to not hardcoding them is if the author updates the info it'll be reflected in CKAN.

**Comment by linuxgurugamer** [comment]
Thanks, I updated both kal9000 and origameFoldableAssets


JBB

**Comment by plague006** [comment]
Your commit comment says you removed the `name`s, but that's not the case.

**Comment by linuxgurugamer** [comment]
Thanks, i missed that one.

Fixed and committed

**Comment by plague006** [comment]
Each pass local. Merging with my thanks.

**Pull request merged**
