### PR TITLE
Spacedocking KerbalKonstructs

### PR DESCRIPTION
**Pull request by politas**

### CODE REVIEW

**Comment by Olympic1** [comment]
You can use a `"$vref": "#/ckan/ksp-avc",` so you can comment it out

and also add `"license": [ "MIT", "BSD-3-clause" ],` before `"x_netkan_license_ok" : true,`

**Comment by politas** [comment]
Neither of those changes avoids the "Exception has been thrown by the target of an invocation" error I keep getting. I am at a loss to explain what is wrong.

**Comment by politas** [comment]
Neither of those changes avoids the "Exception has been thrown by the target of an invocation" error I keep getting. I am at a loss to explain what is wrong.

**Comment by Dazpoet** [comment]
Try removing the x_netkan_license_ok thing and change the license to just be BSD-3-clause. That'll bring us down to a bare minimum while we maintain only the strictest license.

**Comment by politas** [comment]
Exception has been thrown by the target of an invocation.

**Comment by Dazpoet** [comment]
Ok so tried stripping away anything not needed and ended up with:

```
{
  	"spec_version" : "v1.4",
  	"identifier"   : "KerbalKonstructs",
 	"$kref"        : "#/ckan/spacedock/124",
    "licence"      : "BSD-3-clause"
 }
 ```
Which I then ran through NetKAN.exe and it does seem to properly generate the file and then crash horribly as can be seen from this debug output:

```
748 [1] DEBUG CKAN.NetKAN.Transformers.PropertySortTransformer (null) - Transformed metadata:
{
  "spec_version": "v1.4",
  "identifier": "KerbalKonstructs",
  "name": "Kerbal Konstructs",
  "abstract": "Create new bases and launchsites in KSP",
  "author": "AlphaAsh",
  "license": "BSD",
  "resources": {
    "spacedock": "https://spacedock.info/mod/124/Kerbal%20Konstructs",
    "x_screenshot": "https://spacedock.info/content/AlphaAsh_462/Kerbal_Konstructs/Kerbal_Konstructs-1455806350.350444.jpg"
  },
  "version": "0.9.5.1",
  "ksp_version": "1.0.5",
  "download": "https://spacedock.info/mod/124/Kerbal%20Konstructs/download/0.9.5.1",
  "download_size": 6469820,
  "licence": "BSD-3-clause",
  "x_generated_by": "netkan"
}
755 [1] INFO CKAN.NetKAN.Program (null) - Finished transformation
758 [1] DEBUG CKAN.CkanModule (null) - Inflating comparator object
808 [1] DEBUG CKAN.CkanModule (null) - Building CkanModule
810 [1] DEBUG CKAN.CkanModule (null) - In-client JSON schema validation unimplemented.
837 [1] FATAL CKAN.NetKAN.Program (null) - Exception has been thrown by the target of an invocation.
840 [1] FATAL CKAN.NetKAN.Program (null) -    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at CKAN.JsonSimpleStringConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at CKAN.JsonSingleOrArrayConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at CKAN.CkanModule..ctor(String json, IGameComparator comparator)
   at CKAN.CkanModule.FromJson(String json)
   at CKAN.NetKAN.Validators.CkanValidator.Validate(Metadata metadata)
   at CKAN.NetKAN.Program.Main(String[] args)
```

I guess we'll ping @dbent who's the current master of NetKAN to see if he can make any sense from the above, I sure can't because it just looks like random words mashed together to me <.<

**Comment by Dazpoet** [comment]
And just now I saw it... `license` is misspelled xD

**Comment by dbent** [comment]
Aye, that's not a particularly helpful exception though, I'll see if I can make it better.

**Comment by politas** [comment]
Oh, you Americans and your silly spellings! Quite licentious!

**Comment by Olympic1** [comment]
Didn't see that typo either, merging with my thanks

**Comment by politas** [comment]
It's not a typo, it's the correct spelling of the word.

**Comment by plague006** [comment]
> It's not a typo, it's the correct spelling of the word.

If you were writing prose, sure.

**Comment by Olympic1** [comment]
Here we write `licence` with a `c`

**Comment by politas** [comment]
A licence is a thing that licenses you to do something.

**Pull request merged**
