### PR TITLE
SXT -> github

### PR DESCRIPTION
**Pull request by ChucklesTheBeard**

### CODE REVIEW

**Comment by plague006** [comment]
`description` should be `abstract`

**Comment by ChucklesTheBeard** [comment]
:heavy_check_mark:

**Comment by ChucklesTheBeard** [comment]
:white_check_mark:

**Comment by plague006** [comment]
This will need an install stanza to filter `Thumbs.db`

**Comment by plague006** [comment]
spec_version `v1.4` or higher required for install with 'find'

**Comment by plague006** [comment]
You only need 1.4. We try to keep it to the lowest spec_ver for greater compatibility but this isn't a big enough difference that I'll push the issue. Sorry to anyone who hasn't updated since Jun 30, you lose on this one. :D 

Merging with my thanks.

**Comment by NathanKell** [comment]
@Signatum I recally you generally prefer to use Github for in-process things and KS (now, presumably, space dock) for "ready for the world" releases. Once you're set up on spacedock, this can of course be switched back.

**Pull request merged**
