### PR TITLE
add Water Launch Sites

### PR DESCRIPTION
**Pull request by yalov**

### CODE REVIEW

**Comment by DasSkelett** [comment]
I don't think we can pull the license from github.

**Comment by yalov** [comment]
Changes since 1.25.4

Features
[Netkan] Get license from GitHub (#2663 by: HebaruSan; reviewed: politas)

**Comment by DasSkelett** [comment]
That's a good point...

**Comment by yalov** [comment]
does patches updates spec_version? or I need 
    "spec_version" : "v1.26"

**Comment by DasSkelett** [comment]
You need v1.26

**Comment by yalov** [comment]
:confused:

**Comment by DasSkelett** [comment]
#rebuild

**Comment by DasSkelett** [comment]
Is the `x_netkan_license_ok` flag needed @HebaruSan ?

**Comment by HebaruSan** [comment]
Happy to see KSP-CKAN/CKAN#2663 getting some use!

`x_netkan_license_ok` apparently just bypasses that error in the validation script, and has no effect otherwise. I couldn't find documentation on why it was thought to be needed in the first place.

In any case, thanks for the submission!

**Pull request merged**
