### PR TITLE
Community Part Titles, separating Extras

### PR DESCRIPTION
**Pull request by yalov**
does it ok?

### CODE REVIEW

**Comment by HebaruSan** [comment]
Would a user ever want to install `CommunityPartsTitlesExtrasNoCCKDup` without the other two?

**Comment by yalov** [comment]
yes I had had this patch before started to make CPT

**Comment by yalov** [comment]
Fore example: https://forum.kerbalspaceprogram.com/index.php?/topic/149840-discussion-community-category-kit/&do=findComment&comment=2954690

**Comment by HebaruSan** [comment]
OK, that makes sense...

**Comment by yalov** [comment]
Does bot run once per day?

**Comment by DasSkelett** [comment]
It *should* run about once every 2-3 hours now, but the new bot isn't running perfectly yet and the outage of Spacedock messed it up somehow.

**Comment by techman83** [comment]
Well the old bot would have had the same problem with the spacedock outage :wink:  - But the inflator seems to have gotten stuck, so I've given it a kick.

**Pull request merged**
