### PR TITLE
Add HGR inline chutes without decoupler from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Monniasza, to add [HGR inline chutes without decoupler](https://spacedock.info/mod/2389/HGR%20inline%20chutes%20without%20decoupler) to CKAN.

Please direct questions about this pull request to [Monniasza](https://spacedock.info/profile/Monniasza).

Mod details:
    name = /mod/2389/HGR%20inline%20chutes%20without%20decoupler
    author = Monniasza
    abstract = The mod adds versions of HGR inline chutes without decouplers.
    license = MIT
    Homepage = 
    description =
The mod adds two derivative parachutes for Home Grown Rocket Parts:
HGR MK.18 Inline Chute without decoupler
LOM-7 Inline Chute without decoupler

### CODE REVIEW

**Comment by Monniasza** [comment]
The mod requires HGR 1.875m Parts to work correctly

**Comment by HebaruSan** [comment]
@Monniasza  OK, where is that mod?

**Comment by HebaruSan** [comment]
HGR got adopted, but the new maintainer does not want to be indexed in CKAN:

- https://forum.kerbalspaceprogram.com/index.php?/topic/131556-16-19-hgr-community-fixes-home-grown-fixes-for-home-grown-rockets-v170-02019-nov-12/&do=findComment&comment=3441759
- https://forum.kerbalspaceprogram.com/index.php?/topic/131556-16-19-hgr-community-fixes-home-grown-fixes-for-home-grown-rockets-v170-02019-nov-12/&do=findComment&comment=3441844

**Comment by HebaruSan** [comment]
Re-opening temporarily because I want to look at the script validation UI...

**Pull request closed without merging**
