### PR TITLE
Add VersatileToolboxSystem

### PR DESCRIPTION
**Pull request by plague006**
Closes https://github.com/KSP-CKAN/NetKAN/pull/3217

### CODE REVIEW

**Comment by plague006** [comment]
Really unsure if I should include any USI mods.

**Comment by politas** [comment]
"For compatibility with USI resources, you must install USI Life Support and mods that enable USI fuels(Karbonite)." Not sure what the mod does other than adding USI support. Maybe depends on USI-LS and Recommends Karbonite?
Also "This mod requires Kerbal Inventory System for full functionality"

**Comment by Olympic1** [comment]
> This mod requires Kerbal Inventory System if you want to enable all of the features it was built for:

I should set a `depends` on `USI-LS` (to use all containers) and `KIS` (to use the racks and move parts around) to make this mod fully functional, and set a `recommends` on `Karbonite`.

**Comment by plague006** [comment]
Looking at the SD page alone I'd be inclined to agree we should add more than just KIS as a `depends`. However, if you take a look at the [ksp forum page](http://forum.kerbalspaceprogram.com/index.php?/topic/70312-105-versatile-toolbox-system-added-usi-support/) the overall tone changes. Instead of the mod being named `Versatile Toolbox System: USI Pack` which implies USI is integral, it's now just `[1.0.5] Versatile Toolbox System (Added USI Support)` which is clearly its own mod that happens to support USI and to support USI, it needs specific mods installed.

Further from the forum page:

>Release 3 adds fuel cell parts and support for USI Life Support Resources

This mod is definitely its own thing with or without USI.

**Comment by plague006** [comment]
As a compromise, how about leaving the relationships but hardcoding the `abstract` to include: `For compatibility with USI resources, you must install USI Life Support and mods that enable USI fuels(Karbonite).`

**Comment by Olympic1** [comment]
Then just `recommends` or `suggests` `USI-LS` and `Karbonite`.

**Comment by Olympic1** [comment]
Merging with my thanks

**Pull request merged**
