### PR TITLE
Change RSSTextures to recommends

### PR DESCRIPTION
**Pull request by plague006**
Once this is merged #2950 can be re-examined.

### CODE REVIEW

**Comment by politas** [comment]
Oh, hang on. This is the wrong way around. RO needs RSSTextures, but RSSTextures doesn't need RO

**Comment by plague006** [comment]
Quite right, I'll revert this and open a new PR.

**Comment by plague006** [comment]
Erm wait.. RSSTextures already don't depend on RSS.

**Comment by plague006** [comment]
So in fact there was no change required whatsoever?

**Comment by politas** [comment]
Does RSSTextures depend on Realism Overhaul?

**Comment by plague006** [comment]
Nah, the files haven't been touched in 8 months.

**Pull request merged**
