### PR TITLE
KerbalRotorExpansion

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
closes #4307

**Comment by politas** [comment]
License should be "CC-NC-SA-4.0" - Looks like the author updated it after the original upload.

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by politas** [comment]
#rebuild

**Comment by politas** [comment]
LGTM. Merging with thanks!

**Pull request merged**
