### PR TITLE
Add SigmaBinary-core and SigmaBinary-DunaIke

### PR DESCRIPTION
**Pull request by plague006**
Paging @Sigma88 for input.

`SigmaBinary-core` installs the `GameData` contents and has an abstract which informs users that this mod on its own won't create binary systems.

`SigmaBinary-DunaIke` installs the Duna + Ike binary system to `GameData/Sigma/BinaryExpansion` (would like to know if you prefer a different destination)

In using `SigmaBinary-core` as the idenfitier (seen only to CKAN's code) it would allow for easy creation of an eventual `SigmaBinary` install which includes the core and the default binaries, or can easily accept binaries from other sources. Currently the mod's name (visible to users) is `Sigma Binary` to help people find it and to provide simplicity until such a time as a full `SigmaBinary` install exists.

A question though, do .cfgs like `DunaIke.cfg` conflict with others or can multiple .cfgs be included to create multiple binary systems?

Closes #1890

### CODE REVIEW

**Comment by Sigma88** [comment]
hi plague
first, you're awesome. I thought I had to explain how to patch this but I've seen you have already done more than I was hoping for :D 

as for your questions:

Dunaike.cfg can go anywhere. the folder you chose is more than fine

the mod is designed to work with as many binary systems you can imagine.

It's still a work in progress, so some bug may occur. But as far as I know there shouldn't be any problems.

It's also possible to "nest" a binary system inside another as long as who changes the template knows what he's doing :)

if you have any more questions feel free to ask :)

**Comment by plague006** [comment]
Nope that's perfect, thanks. =)

**Comment by plague006** [comment]
Erroneous Jenkins, passes local. Merging.

**Comment by techman83** [comment]
Refer KSP-CKAN/CKAN#1273

**Comment by Sigma88** [comment]
@plague006  hi there, I'm seeing weird download spikes on kerbalstuff

just after OPM updated their mod I've got a bunch of download of old versions of all my mods
#1309  #1605  #1609  
is it possible that CKAN is making people download old versions of my mods?

should I do something for CKAN every time I release a new patch?

**Comment by plague006** [comment]
I don't have access to my full setup, but looking at the modlist for CKAN I see sigma Binary at 1.0.1, Expansion+OPM at 0.8.0 and Signma RemoteTech at 0.4.5.

I also did a quick web search of the ckan-meta repo and nothing seems to depend on any of your mods (and by extension none of them depend on an old version of your mod).

I don't *think* this is coming from us. Maybe a youtuber or someone/something featured your mod(s) with old links?

Last thought, if it's versions that are compatible with 1.0.2 that might be a factor.

**Comment by Sigma88** [comment]
seems kinda weird to get thousands of download all in the same day, even more strange since that spike accounted for 50% of my total downloads :)

nobody cares about my mods and suddently a bunch of bots feel the need to download crappy old versions? sounds funny :D

thank you for taking the time anyway, happy to hear it's not a CKAN issue :)

**Comment by Sigma88** [comment]
sorry to bother you again

Yesterday I moved the download mirror from KerbalStuff to GitHub and completely forgot about CKAN

I'm going to add a pull request to account for the changes.

If I mess something up please let me know :)

**Pull request merged**
