### PR TITLE
First release for EVA Handrails Pack Continued

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Released on Friday

### CODE REVIEW

**Comment by dbent** [comment]
Sorry for not getting to this earlier. Couple of things:

- If the original mod has been abandoned for good and you're taking over active maintership we can just update the existing [`.netkan`](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/NebulaEVAHandrails.netkan). That way anyone with the original mod will get your version on upgrade.
- If you *don't* want to replace the original, then a `conflicts` relationship should be added.
- The `ModuleManager` assembly should be filtered, although you may just want to change the packaging since `ModuleManager` assemblies are usually distributed directly under `GameData` not within mod-specific subdirectories. The filter clause would look like:

  ```json
    "install": [
        {
            "file"       : "NEBULA",
            "install_to" : "GameData",
            "filter_regexp": "ModuleManager.+\\.dll"
        }
    ]
  ```

**Comment by linuxgurugamer** [comment]
Hi,

I would rather NOT replace the old one, just in case he comes back.

I created one already, EVAHandrailsContinued.netkan, can you update it 
for me?

Thanks


JBB

**Comment by dbent** [comment]
Implemented in #1645.

**Comment by linuxgurugamer** [comment]
Thank you


JBB

**Pull request closed without merging**
