### PR TITLE
Create Mk1RocketFuelFuselage.netkan

### PR DESCRIPTION
**Pull request by politas**
Fix #2851

### CODE REVIEW

**Comment by plague006** [comment]
Please filter the source.

**Comment by politas** [comment]
Source code and license filtered.

**Comment by plague006** [comment]
Please don't filter the license, many licenses require the distribution of the license itself with the mod and it's best not to start down that road.

**Comment by politas** [comment]
Should have stopped when I had it right :)

**Comment by plague006** [comment]
Merging with my thanks.

**Pull request merged**
