### PR TITLE
Add Harder Solar System netkan files

### PR DESCRIPTION
**Pull request by stevehead**
Each netkan file is for a different scaled solar system.

### CODE REVIEW

**Comment by plague006** [comment]
For each of the .netkans you can use `"provides": "HarderSolarSystem"` and "conflicts: HarderSolarSystem" which will ensure users can only install one at a time while keeping the metadata easier to read.

**Comment by plague006** [comment]
None of the netkans contain install stanzas which means CKAN doesn't know how to install them. `HarderSolarSystem-1x.netkan` will require:
````
"install": [
        {
            "find"       : "1x/GameData/HarderSolarSystem-1x",
            "install_to" : "GameData"
        }
    ]
````

There's also no `cache` folder in `1x/GameData/HarderSolarSystem-1x`.

**Comment by stevehead** [comment]
Thanks, I'll make the changes. I tested each individually using the netkan.exe and then installing with ckan file generated, and they all worked fine. It was my understanding that CKAN by default finds the first top-level directory with the identifier. I'll put them in for clarification. Also, HarderSolarSystem-1x does not have a cache folder since it is using the stock scales.

**Comment by Olympic1** [comment]
Change `"spec_version": 1` to `"spec_version": "v1.4"` because yuo're using the `find` command

**Comment by stevehead** [comment]
Thanks guys. Hopefully, I got it this time.

**Comment by plague006** [comment]
>It was my understanding that CKAN by default finds the first top-most directory with the identifier.

That's the case, I just wanted it explicitly defined to make it a little clearer when reading the metadata.

>Also, HarderSolarSystem-1x does not have a cache folder for Kopernicus textures since it is using the stock scale.

That's my mistake then, Kopernicus-dependent mods aren't my strong suit and it jumped out at me as being inconsistent with the others.

This gets a :+1: from me and I'll leave the last call to @Olympic1.

One last note, as it stands each .netkan will have to be updated manually with new KSP releases to mark them as compatible. If you want to automate that, you could use .version files (identical copies of `HarderSolarSystem.version` in each version's folder for example) to define KSP version compatibility. Just a suggestion you can take or leave.

**Comment by stevehead** [comment]
Hmm... good call. I'm going to be working all day, but I can add the .version file after I get home later.

**Comment by Olympic1** [comment]
> Hmm... good call. I'm going to be working all day, but I can add the .version file after I get home later.

If you made the .version files and included them into the download (you'll need to make a new release with the files), you'll need to add `"$vref" : "#/ckan/ksp-avc",` into the .netkan files.

**Comment by stevehead** [comment]
Alright, thanks for the help. I'll get it done this evening. I would have gone with KerbalStuff to make things easier, but the nature of how I'm releasing this is a quite unique.

**Comment by stevehead** [comment]
The .version files are included in a new release on GitHub

**Comment by Olympic1** [comment]
Merging with great thanks.

**Pull request merged**
