### PR TITLE
Add Giving Aircraft a Purpose (GAP)

### PR DESCRIPTION
**Pull request by inigmatus**
ready for submission to CKAN!

### CODE REVIEW

**Comment by inigmatus** [comment]
I've got fans chomping at the bit to get this from CKAN. not sure on ETA, but figured I'd ping whoever monitors this with this note. :)

**Comment by plague006** [comment]
For the sake of easier management, all contract packs use a standard identifier of `ContractConfigurator-<PackName>`. Since this is merged, can't do much about it now though.

**Comment by inigmatus** [comment]
Should i change it?

**Comment by plague006** [comment]
Unfortunately at this point it can't be changed without causing issues to users of the mod. This should have been caught in the review, but these things are sometimes missed.

**Comment by inigmatus** [comment]
It's early enough now.it just became available tonight. Can this pull request be reverted?

**Comment by inigmatus** [comment]
I don't mind if this gets reverted away this point with the correct name put back in.

**Comment by inigmatus** [comment]
I created a new pull request to do this: https://github.com/KSP-CKAN/NetKAN/pull/2908

**Pull request merged**
