### PR TITLE
Create AsphaltTilesWelded.netkan

### PR DESCRIPTION
**Pull request by enceos**

### CODE REVIEW

**Comment by politas** [comment]
You state in the description on Spacedock that "welded parts are mod independable." If that is the case, using "recommends" instead of "depends" would be better.

**Comment by politas** [comment]
Also, to use a "find" install directive, you'll need to bump spec_version up to "v1.4".

**Comment by enceos** [comment]
I meant they are independable from the welding mod.

**Comment by enceos** [comment]
Should look good now. I'll change the description on SpaceDock to be more clear.

**Comment by politas** [comment]
OK. Just need to bump spec_version, and it should be fine, then.

**Comment by enceos** [comment]
I changed the "find" to "file"

**Comment by politas** [comment]
Yep. Dependency failure this time

**Comment by enceos** [comment]
It didn't find the AsphaltTiles in the database?

**Comment by politas** [comment]
It's looking for .ckan files, I think. The robot should make one soon.

**Comment by enceos** [comment]
I learned much about CKAN today )

**Comment by politas** [comment]
There's a fair bit to learn. I've been finding different ways to go wrong pretty solidly for the last four months!

**Comment by enceos** [comment]
I think "Adding a Modto CKAN" page needs a link to https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md
Under the "Special Installations" section. If I saw that I woudn't make that many mistakes.

**Comment by politas** [comment]
Feel free to make that addition where you think it would make the most sense. Those pages are using Wiki rules; Be Bold!

**Comment by politas** [comment]
Merged with thanks!

**Pull request merged**
