### PR TITLE
Void

### PR DESCRIPTION
**Pull request by linuxgurugamer**

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
#rebuild

**Comment by HebaruSan** [comment]
It's trying to install it on 1.4.3 for some reason, even though the file says 1.4.2. I'll take a look...

**Comment by linuxgurugamer** [comment]
Could this be because Spacedock is not yet updated for 1.4.3, which just dropped?

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
No, it's because the test script wasn't getting the game versions correctly. Should be fixed now.

The [version you just committed](https://github.com/KSP-CKAN/CKAN-meta/commit/7183fd6be46a6611d78a20d4bb5950830adc6109) has no game version constraints at all.

**Comment by linuxgurugamer** [comment]
Oh, I just changed the script to pull from Github instead of Spacedock
Good to know it's fixed

**Comment by HebaruSan** [comment]
Right, SpaceDock knows about KSP versions inherently and GitHub doesn't, so .version files are needed for GitHub.

**Comment by HebaruSan** [comment]
Oh, when I said "script" I meant the stuff that drives the build tests for pull requests, changed recently in KSP-CKAN/xKAN-meta_testing#39. The mod's metadata was fine.

**Pull request merged**
