### PR TITLE
Add ROCapsules and ROTanks to NetKan

### PR DESCRIPTION
**Pull request by pap1723**

### CODE REVIEW

**Comment by HebaruSan** [comment]
```
1961 [1] WARN CKAN.NetKAN.Transformers.GithubTransformer (null) - No releases found for KSP-RO/ROCapsules
2033 [1] FATAL CKAN.NetKAN.Program (null) - ROCapsules missing required field download
```

**Comment by pap1723** [comment]
Should be working correctly now.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Yup, looks good.

**Comment by HebaruSan** [comment]
... and the last thing I wanted to check: Yes, there is a precedent for a mod named "ROSomething", instead of "RealismOverhaulSomething", so we won't be creating any confusion on that score here:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ROEngines.netkan

**Pull request merged**
