### PR TITLE
Add Sigma Stock Recolor from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Sigma88, to add [Sigma Stock Recolor](https://kerbalstuff.com/mod/1067/Sigma%20Stock%20Recolor) to CKAN.

Please direct questions about this pull request to [Sigma88](https://kerbalstuff.com/profile/Sigma88).

### CODE REVIEW

**Comment by Sigma88** [comment]
If anyone wants to add this, feel free to ask me anything you might need.

as always, thank you for your time

**Comment by plague006** [comment]
Does this require ModuleManager or does it run out of the box?

**Comment by Sigma88** [comment]
it requires module manager (that's the only requirement)

supports:
Planetshine
DistantObjectEnhancement
EnvironmentalVisualEnhancements (and derivatives)
KSP-AVC
OPM
and this is it, I think...

**Comment by plague006** [comment]
:+1:

**Comment by plague006** [comment]
To be clear, I'm not ignoring your list of supported mods, we just don't have a real definition for the `supports` relationship.

**Comment by Sigma88** [comment]
oh, don't worry!

I can always make a pull request myself adding the various mod as a "compatibility"
For now what you have done is more than enough

I always wanted to add the various compatibilities and reccomends even on my other mods, but I always end up procrastinating.

Thank you for your work :+1:

**Comment by plague006** [comment]
Mods are assumed to be compatible unless there's a `conflicts` relationship. But if you want to `suggest` or `recommend` mods to accompany yours I'd be happy to add them.

**Pull request closed without merging**
