### PR TITLE
AKR moved to github

### PR DESCRIPTION
**Pull request by Olympic1**
Jenkins will fail as there is no `.zip` file included into the release

### CODE REVIEW

**Comment by plague006** [comment]
Will the author eventually add .zips to the release?

**Comment by Olympic1** [comment]
I asked him to include one in the current release and future ones.

Wouldn't it be possible to extract the source form a release (zipball/tarball) ?

**Comment by plague006** [comment]
Not currently, not as far as I know.

**Comment by plague006** [comment]
Rebuild as there's now a release.

**Comment by plague006** [comment]
I took a cursory look in the .zip listed in the release and couldn't find flags anywhere, thus the Jenkins fail.

**Comment by Olympic1** [comment]
@plague006 I froze the file till the flags are added back into the download

**Pull request merged**
