### PR TITLE
Added metadata for GroundConstruction-Core package.

### PR DESCRIPTION
**Pull request by allista**

### CODE REVIEW

**Comment by allista** [comment]
Need to run the build again: I send PR before the archive have uploaded to SpaceDock.

**Comment by allista** [comment]
I rephrase: how can I re-launch the checks if I have nothing to add in terms of commits?

**Comment by fat-lobyte** [comment]
@allista Silly idea, but could you maybe add a ... "fix whitespace" commit in some file?

Also, are you sure that the missing SpaceDock file was the reason for the [build failure](https://ci.ksp-ckan.org/job/NetKAN/5279/console)? The log says:

    6130 [1] FATAL CKAN.NetKAN.Program (null) - No files found in GameData/GroundConstruction/Parts/DIYKit to install!

**Comment by allista** [comment]
Yep, will do that.

Positive. The structure of the archive was changed in that way in the last version (which has failed to upload at first yesterday).

**Comment by fat-lobyte** [comment]
I see. Well, since you uploaded new commits and the checks failed anyway, it seems that you would theoretically have to create a new pull request to get green checkmarks.

Does it matter though? Is there an auto-merge feature? I think a friendly human should be able to merge it anyway.

**Comment by allista** [comment]
Just in case, pinging to let you know that everything is OK and ready to be merged.

**Comment by linuxgurugamer** [comment]
@allista to force a rebuild, use #rebuild (and this comment may do it as well)
i'll take a look and merge if it's good

**Comment by allista** [comment]
@linuxgurugamer thanks for the info!

**Comment by ahmedcharles** [comment]
Has this propagated to the CKAN index correctly? GroundConstruction-Core is still not showing up in my index.

**Comment by allista** [comment]
It has not. The netkan issue about this is here:
https://github.com/KSP-CKAN/NetKAN/issues/5289

**Pull request merged**
