### PR TITLE
Add Solaris Hypernautics from Kerbal Stuff

### PR DESCRIPTION
**Pull request by KerbalStuffBot**
This pull request was automatically generated by Kerbal Stuff on behalf of Railgun88, to add [Solaris Hypernautics](https://kerbalstuff.com/mod/900/Solaris%20Hypernautics) to CKAN.

Please direct questions about this pull request to [Railgun88](https://kerbalstuff.com/profile/Railgun88).

### CODE REVIEW

**Comment by Dazpoet** [comment]
Version number is part of foldername.

**Comment by RichardLake** [comment]
Also needs thumbs.db filtered.

**Comment by plague006** [comment]
Left comment in the mod's thread (http://forum.kerbalspaceprogram.com/threads/125482) advising the author of what's required for CKAN indexing.

**Comment by Carbonjvd** [comment]
I modified the folder name to name longer include the version number in the latest mod update. Now it should fine to integrate. Thanks for letting me know, CKAN's been on the backburner for a bit now.

**Pull request closed without merging**
