### PR TITLE
Update SigmaModExpansions.netkan

### PR DESCRIPTION
**Pull request by Sigma88**
changing dependencies

### CODE REVIEW

**Comment by dbent** [comment]
Need to remove the comma at the end of `{ "name": "ModuleManager" },`.

**Comment by dbent** [comment]
#rebuild

**Comment by dbent** [comment]
Changes should appear in the next run of the bot which is in about an hour and a half.

**Comment by Sigma88** [comment]
@dbent nice thanks, so now If I want to add stuff like "supports" and other stuff I can just do this. but someone with writing permission will always have to check it before it will be applied right?

**Comment by dbent** [comment]
Yep.

**Comment by Sigma88** [comment]
@dbent perfect, thanks for the help. now I just need to decide how many parameters to add... I'm looking at the OPM file and it's huge :D

**Pull request merged**
