### PR TITLE
Add new plugin : KspBugReport

### PR DESCRIPTION
**Pull request by gotmachine**
Bug reporting plugin, homepage : https://github.com/KSPModdingLibs/KSPBugReport

### CODE REVIEW

**Comment by HebaruSan** [comment]
@DasSkelett, thoughts on including `CKAN/registry.json` in these archives?

**Comment by DasSkelett** [comment]
I doubt any mod author (that isn't on the CKAN team ;-) has ever asked for and looked at the registry.json, but why not, maybe some are going to start doing this when it already comes with the bug report. And it might come in handy if someone uses it to report bugs to us.

**Comment by HebaruSan** [comment]
Well the idea would be to capture the user's mod list. For which it would probably be much better to include the newest file in the `<KSP>/CKAN/history` folder. A few kilobytes instead of 20+ MB.

**Comment by DasSkelett** [comment]
The full list of installed mods it already in `KSP.log`, but it would add the information of which got installed through CKAN and which were done manually. And I agree if it's just for that, the `installed-*.ckan` files would be smaller.

**Comment by HebaruSan** [comment]
Thanks for the submission, and good luck with this one. We might stop by later to submit some CKAN-related enhancements!

**Pull request merged**
