### PR TITLE
Add .netkan for AGroupOnStage

### PR DESCRIPTION
**Pull request by iPeer**
Was requested by a few users, so I figured I might as well. Tests came back A-OK.

### CODE REVIEW

**Comment by Dazpoet** [comment]
The bot returns an error like

```
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "\x{feff}{\n\t"spec_v...") at /usr/share/perl5/JSON/Any.pm line 407, <$fh> chunk 1.
```

I'm going to throw a guess that you have a space before the first character? Try removing that.

**Comment by iPeer** [comment]
Should be fixed.

**Comment by Dazpoet** [comment]
Seems to have fixed that error. Now it fails because your recommends is incorrectly formated. You need the identifier rather than the name. Iirc the identifier is AGExt

**Comment by iPeer** [comment]
Fixed.

**Comment by Dazpoet** [comment]
Looking good, thanks :)

**Pull request merged**
