### PR TITLE
Add Orbit Portal Technology [OPT] Spaceplane Parts from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of moobien, to add [Orbit Portal Technology [OPT] Spaceplane Parts](https://spacedock.info/mod/711/Orbit%20Portal%20Technology%20%5BOPT%5D%20Spaceplane%20Parts) to CKAN.

Mod details:
    name = /mod/711/Orbit%20Portal%20Technology%20%5BOPT%5D%20Spaceplane%20Parts
    author = moobien
    abstract = Orbit Portal Technology [OPT] is a Research and Development company dedicated to space plane and trans-atmospheric propulsion technology
    license = Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
    Homepage = http://forum.kerbalspaceprogram.com/index.php?/topic/87956-105wip-opt-space-plane-v18-test-release-available-08012016/#comment-1476665
    description = Orbit Portal Technology [OPT] is a Research and Development company dedicated to space plane and trans-atmospheric propulsion technology. This mod Was created by **K.Yeon** and he has given** Winchester** and myself to maintain the mod until his return in september.

*Mod requires Firespitter and is included.

[[http://imgur.com/a/wBynS]]

**Planned Changes/Updates**

* Change PNG textures to DDS
* Re-Organise Folder Structure
* Double check IFS and CLS patches for all parts.
* Rename all parts to add 'OPT' to the begining for mod compatabilities
* Add real fuels MM patches.
* Add Normal maps to parts.
* Remodel/Retexture J SAS Module.
* Get ARIE Nacelle and KY Nacelle functioning.
* Add descriptions to parts.

##Special Thanks:

**Stone Blue** - For his help with the model side of things.
**Nils277** - for his help on the CLS patch
**Winchester** - for his work in compiling the multiple versions I found.
**AccidentalDisassembly** - for his patching/editing to help clean the mod up
**K.Yeon** - Without you this mod would not exist, thank you for letting us maintain it while you are away.

Please direct questions about this pull request to [moobien](https://spacedock.info/profile/moobien).

### CODE REVIEW

**Comment by Cphoenix** [comment]
This is probably a bad idea given that [the next update will break everyone's ships](http://forum.kerbalspaceprogram.com/index.php?/topic/87956-105wip-opt-space-plane-v18-test-release-available-08012016/&do=findComment&comment=2621649).

**Comment by politas** [comment]
True, but that will be some time off. If we didn't add mods because a future version will break compatibility, we'd be artificially preventing a lot of mods from being indexed.

**Comment by politas** [comment]
Note that we have OPTSpacePlaneParts already assigned as the identifier for this. The .frozen file needs to be removed.

**Comment by politas** [comment]
stali79:  Once i complete the rebuild of the mod i will put it on ckan but that wont be for a month or two.

Closing PR

**Pull request closed without merging**
