### PR TITLE
Split Filter Extensions

### PR DESCRIPTION
**Pull request by Crzyrndm**
New release package will have the configuration files shifted to "000_FilterExtensions Configs" and installed separately

Release has now been made

### CODE REVIEW

**Comment by Dazpoet** [comment]
Based on the .zip file it seems that https://github.com/KSP-CKAN/NetKAN/pull/1394/files#diff-b550b9beec2705b4862ddc25cdb3ffb6R15 should be pointing to `GameData/000_FilterExtensions/Configs`. If this folder will move in the future you might just issue a `find` keyword instead and change the install stanza to

```
"install" : [ { "find" : "Configs",
"install_to" : "GameData/000_FilterExtensions" } ]
```

This would find the first, topmost in the folderstructure, folder named Configs in the .zip file and then install it inside the folder `000_FilterExtensions` in the `GameData` directory.

**Comment by Crzyrndm** [comment]
The .zip is this one here:
https://github.com/Crzyrndm/FilterExtension/releases/tag/2.1.4

**Comment by Dazpoet** [comment]
#rebuild then and see if that solves it

**Comment by Dazpoet** [comment]
My mistake it seems, sorry for the confusion.

**Pull request merged**
