### PR TITLE
Create BladeTweaks.netkan

### PR DESCRIPTION
**Pull request by blade1981m**

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks for the contribution!

The MechJeb.cfg and Squad.cfg files both set bulkheadProfiles for mk2DockingPort, to different values. Is that intentional?

**Comment by blade1981m** [comment]
No, that is not. Not sure how I managed that. I will make a change here real quick. Thanks for catching that.

**Comment by blade1981m** [comment]
Ok, github repo is updated but there are no changes to the netkan file. Do I need to do anything else regarding this pull request?

**Comment by HebaruSan** [comment]
Nope, you're all set. Thanks again for submitting this!

**Pull request merged**
