### PR TITLE
Create DockRotate.netkan

### PR DESCRIPTION
**Pull request by peteletroll**
New mod - depends on ModuleManager, which is included in the release .zip

### CODE REVIEW

**Comment by HebaruSan** [comment]
This will install two copies of Module Manager, one via the dependency, and one from your ZIP. We try to avoid installing bundled dependencies. Any chance you could move ModuleManager.3.0.1.dll into the parent directory, so it would still be there for manual installers but ignored for CKAN?

**Comment by peteletroll** [comment]
Yes, no problem. It has to be in GameData, right?

**Comment by HebaruSan** [comment]
Yes, that's my understanding. Thanks!

**Comment by peteletroll** [comment]
New version released.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by HebaruSan** [comment]
Looks good. Thanks for the submission!

**Pull request merged**
