### PR TITLE
Rename EVE stock configs to reduce user confusion

### PR DESCRIPTION
**Pull request by JonnyOThan**

### CODE REVIEW

**Review by HebaruSan — CHANGES_REQUESTED** [review]
This is changing a string that explains what the module is to one that is opaque and doesn't mean anything to the user. I'm not seeing why we'd do this.

**Comment by JonnyOThan** [comment]
Another example:

IMG_7684

**Comment by HebaruSan** [comment]
Interesting, that user found the current name clear once they read the whole thing.

**Comment by HebaruSan** [comment]
@JonnyOThan, what if we just shorten "Environmental Visual Enhancements" to "EVE" so the rest can be seen more easily?

EVE - Stock Planet Config files

**Comment by JonnyOThan** [comment]
> what if we just shorten "Environmental Visual Enhancements" to "EVE" so the rest can be seen more easily?

Would certainly help I think

**Review by HebaruSan — APPROVED** [review]
Alright, let's try this.

**Comment by JonnyOThan** [comment]
How about adding "aka BoulderCo" or something in the abstract?  In any case this is certainly an improvement.

**Pull request merged**
