### PR TITLE
add ksp-avc for GPP

### PR DESCRIPTION
**Pull request by Galileo88**

### CODE REVIEW

**Comment by Olympic1** [comment]
If you're gonna use `vref` you should delete `ksp-version` and `version` in the netkan

**Comment by Galileo88** [comment]
Ok new PR on the way

**Comment by Galileo88** [comment]
Removing those seems to make it fail?

**Comment by Galileo88** [comment]
Ahh dont worry about it. Ill just update it manually each time. Not a big deal.

**Pull request closed without merging**
