### PR TITLE
Netkan file for Star-Trek Style Engines for KSPI

### PR DESCRIPTION
**Pull request by ABZB**
correct repository now

### CODE REVIEW

**Comment by Dazpoet** [comment]
This is indeed the correct repository but you are still not adressing the original problem from https://github.com/KSP-CKAN/NetKAN/pull/831, namely that we do not currently index KSPI-Extended which is listed as a dependency for this mod.

To get the file working you need to:
- remove the `sss` in the install stanza.
- change the `"x_netkan_license_ok": true` to `"license" : "CC-BY-NC-SA-4.0",`

To get the PR merged you need to:
- filter uneccessary files such as the temp .xslx file and preferably the 88x31.png
- Add dependencies

The last stage is why this mod isn't already added since we do not index, nor can index KSPI-Extended at this time.

**Comment by ABZB** [comment]
Thank you!
 I had misunderstood the function of the dependency list then - I thought
that was for CKAN's internal dependency checking. Or do you mean that even
once I add the dependency, this will not be added until KSPI-Extended is
indexed (Freethinker told me he will take care of that once he has fixed
the various bugs still currently present to his satisfaction)?

**Comment by Dazpoet** [comment]
The dependency listing is used for CKAN to tell us which mods are required for this mod to work properly.

E.g. [NearFutureConstruction](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/NearFutureConstruction.netkan) depends on `InterstellarFuelSwitch` and `CommunityResourcePack` which means those dependencies _must_ be fulfilled for the version of the game which the installation is attempted on.

When dependencies are fulfilled CKAN will install the mod and it's dependencies together, ergo a mod with unfillfilled dependencies will not be installed even if it is marked as compatible with a given version of KSP. A current example is [MKS](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/UKS.netkan) which is available for new versions of KSP but does not have the dependecy for an up to date FirespitterCore fulfilled and henceforth is not listed in CKAN for 1.0.x versions of the game.

Your mod depends on KSPI-Extended and since we currently don't have that indexed, due to lack of a standalone binary which does not require overwriting of KSPInterstellar files, your mods dependencies by definition cannot be fulfilled at this time.

I'm looking into the KSPI-E thread from time to time checking if the future full release is out yet but so far it isn't.

**Comment by Dazpoet** [comment]
Seems we'll be able to add this soon :) https://github.com/KSP-CKAN/NetKAN/pull/1316

**Pull request closed without merging**
