### PR TITLE
Headlines compatibility and relationships

### LINKED ISSUE #8771: Add Headlines
```yaml
spec_version: v1.16
identifier: Headlines
license: CC-BY-NC-4.0
$kref: '#/ckan/github/bongotastic/Headlines'
resources:
  license: https://github.com/bongotastic/Headlines/blob/master/LICENSE.md
  manual: https://github.com/bongotastic/Headlines/wiki
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/204561-*
ksp_version_min: '1.8'
ksp_version_max: 1.10.1
depends:
  - name: RP-0
  - name: KerbalRenamer
    min_version: '1.5'
  - name: KerbalAlarmClock
x_via: Generated by Metadata Webtool

```

### PR DESCRIPTION
**Pull request by HebaruSan**
See #8771, the author requests:

- Min compat of 1.8
- Two new depends

Closes #8771.

### CODE REVIEW

**Comment by bongotastic** [comment]
@HebaruSan 
Oddly, CKAN hasn't detected a new release made a bit over 12h ago. I wonder is something was lost in the update.

**Comment by HebaruSan** [comment]
The GitHub API is sorting that release in a weird order:

https://api.github.com/repos/bongotastic/Headlines/releases

So far I don't understand why it's doing that.

**Comment by bongotastic** [comment]
Maybe I have an explanation. The release picked up is a hotfix created after I began a draft release (to write the changelog). Let me re release and see.

**Comment by bongotastic** [comment]
Done, let's see if this fixes the issue in a few hours.

**Comment by HebaruSan** [comment]
So far so good, v0.5.0.1-beta is sorting to the top of the API:

https://api.github.com/repos/bongotastic/Headlines/releases

Should be picked up within 30 minutes...

**Comment by bongotastic** [comment]
Thanks, sorting seems to be by when the draft release was created. Easy to avoid in the future.

**Pull request merged**
