### PR TITLE
Create TACLS-Declutter.netkan

### PR DESCRIPTION
**Pull request by TheFarix**
After much trial an error, I think I finally figured out how to create a proper netkan file.

### CODE REVIEW

**Comment by pjf** [comment]
@TheFarix : You rock. Does the following look correct to you?

```
TAC Life Support Declutter Revised: Reduces 30 TAC Life Support parts down to 6, or even 2 if using TweekScale.

Module info:
- version:	0.1.2
- authors:	Farix
- status:	stable
- license:	MIT

Depends:
- TACLS
- InterstellarFuelSwitch-Core
- ModuleManager

Provides:
- TACLS-Declutter

Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/40667?p=2001257&viewfull=1#post2001257
- kerbalstuff: https://kerbalstuff.com/mod/1216/TAC%20Life%20Support%20Declutter%20Revised
- repository: https://github.com/TheFarix/TACLS-Declutter-Revised/

Filename: DAC577AA-TACLS-Declutter-0.1.2.zip

Showing 3 installed files:
- GameData/TACLS-Declutter
- GameData/TACLS-Declutter/TACLS-Declutter.cfg
- GameData/TACLS-Declutter/TACLS-Declutter.version
```

Most importantly, this is really a single `.cfg` file, along with the `.version`?

If so, this looks good to me. :)

**Comment by TheFarix** [comment]
Yes, just the .cfg and .version files. I wasn't sure if I set up the dependencies correctly

**Comment by pjf** [comment]
@TheFarix : The deps look good to me! We will always be insisting on `IntersetellarFuelSwitch-Core` (I note the KS page says one can use the Firespitter core instead), but I trust that's not a big problem. :)

**Comment by TheFarix** [comment]
Nope, I've tested it and it works with both, but will prefer Intersetellar Fuel Switch if it is available.

**Comment by pjf** [comment]
Excellent! Merging with great thanks!

**Pull request merged**
