### PR TITLE
Add EasyBoard from SpaceDock

### PR DESCRIPTION
**Pull request by Space-Duck**
This pull request was automatically generated by SpaceDock on behalf of Dizor, to add [EasyBoard](https://spacedock.info/mod/655/EasyBoard) to CKAN.

Mod details:
    name = /mod/655/EasyBoard
    author = Dizor
    abstract = EasyBoard is a KSP mod that simplifies boarding a vessel for kerbals. With this mod board key "B" works as a toggle. When "B" pressed in EVA your kerbal will wait until you take him to any crew cabin or command seat. Once airlock or command seat reached your kerbal will automatically go in.
    license = GPLv3
    Homepage = https://github.com/IDizor/EasyBoard/releases/
    description = This is your mod listing! You can edit it as much as you like before you make it public.

To edit **this** text, you can click on the "**Edit this Mod**" button up there.

By the way, you have a lot of flexibility here. You can embed YouTube videos or screenshots. Be creative.

You can check out the SpaceDock [markdown documentation](/markdown) for tips.

Thanks for hosting your mod on SpaceDock!

Please direct questions about this pull request to [Dizor](https://spacedock.info/profile/Dizor).

### CODE REVIEW

**Comment by plague006** [comment]
Sounds handy. I want this.

**Comment by politas** [comment]
Ooh, I never knew I wanted this until now!

**Comment by politas** [comment]
Should be good to go, now.

**Comment by plague006** [comment]
Easyboard, welcome to my KSP install. :D

**Pull request merged**
