### PR TITLE
Override StageRecovery KSP versions

### PR DESCRIPTION
**Pull request by dbent**

### CODE REVIEW

**Comment by pjf** [comment]
Oh noes! What was wrong with StageRecovery's AVC file? (Or doesn't it have one?)

**Comment by pjf** [comment]
KSP-CKAN/CKAN#1199 may be relevant here if it's got a broken file.

**Comment by dbent** [comment]
It's pegged at KSP 1.0.2, whereas KS metadata is up to date.

**Comment by pjf** [comment]
Rather than removing the AVC line, can we do a single-version override (assuming the next release contains accurate AVC info)?

(Assuming KSP-CKAN/CKAN#1197 is good to go.)   :)

**Comment by pjf** [comment]
Look at me shamelessly trying to get my patches merged. ;)

**Comment by dbent** [comment]
Ha, I'll take a look at the PR now.

**Comment by pjf** [comment]
@magico13, we're marking the current release of your software as 1.0.2-1.0.4 compatible. If we're wrong about this, then holy smokes please let us know! :)

**Comment by dbent** [comment]
@SkyMarshal linked to this [post](http://forum.kerbalspaceprogram.com/threads/86677?p=2043068&viewfull=1#post2043068) in the original issue.

**Comment by magico13** [comment]
> @magico13, we're marking the current release of your software as 1.0.2-1.0.4 compatible. If we're wrong about this, then holy smokes please let us know! :)

Thank you guys! SR didn't need an update for 1.0.4 and I just got around to indicating that on KS today after noticing it wasn't in CKAN anymore (since CKAN assumed it wasn't working with 1.0.4 since everything was telling it that ;) )

I've got the remote AVC file updated, but I don't see a reason to push a new download that has zero changes other than changing a 2 to a 4. KCT might have the same issue, btw.

**Comment by pjf** [comment]
@magico13: Aye aye, we're on it! We've been unprepared for Squad making KSP releases that *haven't* totally broken all the things, and so we're working new metadata magic to bring everything up to date without requiring mod authors to recompile or re-release.

[This group of issues](https://github.com/KSP-CKAN/CKAN/milestones/Fuzzy%20versioning) is where a lot of the action is, but you don't need to do anything but continue to be awesome. :)

**Comment by magico13** [comment]
I just read your post on the forum about 1.0.4. Might suggest taking a bit of time tomorrow during the sprint to figure some stuff out for small updates, to save headaches in the future (I'm expecting 1.1 will probably have a 1.1.1) ;)

**Comment by pjf** [comment]
> Might suggest taking a bit of time tomorrow during the sprint to figure some stuff out for small updates.

@magico13 : That's been my entire week! :D (Also the sprint is almost over, as I'm on Australian time!)

KSP-CKAN/CKAN#1173 is where the core of the discussion is happening, the results of which should give us much of the architecture we need. :)

**Pull request merged**
