### PR TITLE
Create UnmannedBeforeMannedChallenge.netkan

### PR DESCRIPTION
**Pull request by Y3mo**
Another mini mod with self-administered netkan.

Thank you very much,
Y3mo

### CODE REVIEW

**Comment by Y3mo** [comment]
Ok, I give up, no idea whats wrong with it.

**Comment by Dazpoet** [comment]
I think Jenkins might be doing a dumdum but let's ask @techman83 to be sure

**Comment by politas** [comment]
`Extracted 1.99.99 as KSP version.
Overriding '1.99.99' with '1.2.1'
Creating a dummy KSP '1.2.1' install`

I think that's an issue with our build script

**Comment by politas** [comment]
#rebuild

**Comment by techman83** [comment]
The build script should probably favor the ksp_version_min if present over the ksp_version_max.

It was indeed not available for 1.2.1 :-)
```
"ksp_version_max": "1.99.99",
"ksp_version_min": "1.2.2",
```

**Pull request merged**
