### PR TITLE
add RadarAltitude to CKAN

### PR DESCRIPTION
**Pull request by yalov**
@Marginal, Could you add .version file to your archive/repo ? 
Example: [SpeedUnitAnnex.version](https://github.com/yalov/SpeedUnitAnnex/blob/master/SpeedUnitAnnex.version)

### CODE REVIEW

**Comment by Marginal** [comment]
Have added a .version file in https://github.com/Marginal/RadarAltitude/commit/86f5e43a059e986418892b959a53452fbf0a4ed6.

**Comment by yalov** [comment]
I am not familiar with ckan curseforge api ... 
@HebaruSan

**Comment by HebaruSan** [comment]
The .version file needs to be inside the download. Once that's done, replace ksp_version with:

```json
    "$vref": "#/ckan/ksp-avc",
```

**Comment by Marginal** [comment]
Sorry, I had misunderstood the purpose of the URL field. Corrected in 
https://github.com/Marginal/RadarAltitude/commit/ae411ae140452f75776fe9bafc55243584fa6160

**Comment by Marginal** [comment]
Released [new version](
https://github.com/Marginal/RadarAltitude/releases/latest) with .version file included.

**Comment by HebaruSan** [comment]
Thanks for the changes @Marginal, and thanks for the metadata @yalov!

**Pull request merged**
