### PR TITLE
Added peadar1987's KPseudonym config pack international

### PR DESCRIPTION
**Pull request by TeddyDD**
Just one version for now. Working on the rest, but this can be merged, I'll open PR when the time comes
related to #579

### CODE REVIEW

**Comment by hakan42** [comment]
Could we have a slightly shorter identifer? something like "KPseudonym-ConfigPack-International" ? This would match much better with the core addon.

And the "peadar1987" could be added as author.

**Comment by TeddyDD** [comment]
Why not but now it's too late I suppose?

**Comment by TeddyDD** [comment]
Here you are :)

**Comment by hakan42** [comment]
I know you are going to hate me but the filename of the netkan and the identifier have to be identical :smiling_imp:

I will merge this now and rename the file later on. 

Thank you for your contribution :smile:

**Comment by TeddyDD** [comment]
Of course I know. And they are: https://github.com/TeddyDD/NetKAN/commit/17a690b30f2d00e63a8e45d4b1e7875b98f1fad1 (or I'm too dumb for magic of git)

**Comment by hakan42** [comment]
Nah, I'm too dumb to read pull requests on my mobile :blush:

**Pull request merged**
