### PR TITLE
Update CivilianPopulation.netkan

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Updated download location

### CODE REVIEW

**Comment by HebaruSan** [comment]
Wrong mod.
https://spacedock.info/mod/2228

**Comment by linuxgurugamer** [comment]
Thank you, I was about to make the change when you got it fixed

**Comment by HebaruSan** [comment]
The validation is still running. In the future please don't merge till it's done, in case there's a problem.

**Comment by linuxgurugamer** [comment]
Sure, it showed completed on my screen, which is why I merged.  I've seen this occasionally with github, I'll keep it in mind for the future

**Pull request merged**
