### PR TITLE
Add Vaporo's Blue Galaxy Skybox (fixed KerbalStuffBot submission) 

### PR DESCRIPTION
**Pull request by politas**
Closes #2938

### CODE REVIEW

**Comment by politas** [comment]
Turns out the EnvMap is no longer used, so no requirement for the second option.

**Comment by Olympic1** [comment]
Requires `TextureReplacer`

**Comment by plague006** [comment]
A thought on the whole conflicting with other skyboxes thing, do Kopernicus-based mods usually change the Kerbin skybox? (the ones that change the planet Kerbin anyways) and if they do, we can probably cover our bases by conflicting Kopernicus.

**Comment by Olympic1** [comment]
Kopernicus can't change the skybox

**Comment by politas** [comment]
Yes, I ran a few searches looking for skybox-related metadata before I submitted. I think we're good to go.

**Pull request merged**
